### ISSUE TITLE
php artisan horizon:validate

### ISSUE THREAD

**Issue by dillingham** [laravel/horizon#1000]
There have been tips on how to not misconfigure horizon in themsaid's book and a few times on twitter.

I think it would be pretty awesome if there was a command that reads the config and outputs warnings.

Example tip: https://twitter.com/themsaid/status/1371474388718063616

Could be awesome if the exit code stopped CI / deployments

**Comment by driesvints** [comment]
We've actually begon to implement exception throwing when misconfiguration happened which is a more explicit way of informing devs that something is misconfigured. It's probably best that we continue doing that if anything else pops up.

We've implemented the following PR for the tweet you mention: https://github.com/laravel/horizon/pull/988

**Comment by driesvints** [comment]
Just saw you commented on that. We're not pursuing a validate command at this moment, sorry.

**Comment by dillingham** [comment]
@driesvints thank you for the details. I think those exceptions are great
I just wanted to put it on your radar cause I think its kind of a cool idea.

**Comment by driesvints** [comment]
@dillingham if you find any more use cases for misconfiguration definitely let us know or send in a PR to handle those. That way we can prevent people from misconfiguring their Horizon setups.
