### ISSUE TITLE
Gate set auth model as 2nd arg for auth callback when using custom guard 

### ISSUE THREAD

**Issue by myckhel** [laravel/horizon#1001]
- Horizon Version: ^5.7
- Laravel Version: ^8.18
- PHP Version: ^8.0
- Redis Driver & Version: predis/phpredis ^1.1

### Description:
**When i tried to use a custom guard for my authorisation logic then i was able to access the authenticated object from the 2nd callback argument instead of the first argument.**

### Steps To Reproduce:
```php
namespace App\Providers;

class HorizonServiceProvider extends HorizonApplicationServiceProvider
{
...
  protected function authorization()
    {
        $this->gate();

        Horizon::auth(function ($request) {
            return app()->environment('local') ||
                   Gate::check('viewHorizon', [$request->user('web:admin')]);
                  // used custom guard
        });
    }
  
  protected function gate()
    {
        Gate::define(
          'viewHorizon',
          fn ($user = null, $admin = null) =>
          // 2nd arg = $admin has the authenticated object
          // # unexpected behaviour
            ($admin ? $admin::class : null) == Admin::class
        );
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by myckhel** [comment]
This is actually so annoying.

You cant just keep closing issues like this without any sign of help.

**Comment by driesvints** [comment]
I'm sorry @myckhel but this isn't a support channel. Please try one of the support channels above. There's lots of people who can help you out there. If you can confirm you're experiencing a bug feel free to report back.

**Comment by myckhel** [comment]
Thank you for your reply.
