### ISSUE TITLE
Using setlocale causes the dashboard to not show any processed jobs

### ISSUE THREAD

**Issue by codebros-nl** [laravel/horizon#1003]
- Horizon Version: 5.7.4
- Laravel Version: 8.35.1
- PHP Version: 7.3.27
- Redis Driver & Version: predis/phpredis 6.0.6
- Database Driver & Version: MySQL 5.7.33

### Description:
When setting a `setlocale()` in my `AppServiceProvider.php` Horizon doesn't show any processed jobs on the dashboard. My fix for now was to add a conditional check if the app was not running in the console.

### Steps To Reproduce:

- Add `setlocale(LC_ALL, 'nl_NL.utf-8')` to `AppServiceProvider.php` inside the boot method.

**Comment by driesvints** [comment]
Can't reproduce this. Horizon continues to work fine for me with this in the AppServiceProvider.php

**Comment by Jon78** [comment]
@codebros-nl thanks for the pointer! This has been bugging us for years. We've also fixed this issue by adding `if (! $this->app->runningInConsole()) { // }` (as suggested in https://laracasts.com/discuss/channels/laravel/horizon-on-production-show-no-jobs-at-all-on-all-three-menus)

**Comment by Jon78** [comment]
Could this be the cause? https://github.com/laravel/horizon/issues/788#issuecomment-601255010

**Comment by Jon78** [comment]
https://github.com/phpredis/phpredis/issues/1893

**Comment by Jon78** [comment]
Ah, because the problem you're describing sounded similar to mine and your screenshots are in German :smiley: Maybe your server config sets a non-English locale then? I would investigate what gets passed to Redis to see if floats are properly formatted as per https://github.com/laravel/horizon/issues/788#issuecomment-601255010
