### ISSUE TITLE
ERROR: array_values() expects parameter 1 to be array, bool given {"exception":"[object] (ErrorException(code: 0): array_values() expects parameter 1 to be array, bool given at /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php:80)

### ISSUE THREAD

**Issue by KristenKatona** [laravel/horizon#1004]
- Horizon Version: 5.7.4
- Laravel Version: 8.35.1
- PHP Version: 7.3
- Redis Driver & Version: predis 1.1.6
- Database Driver & Version: doctrine/dbal 3.0.0

### Description:
Upon starting up Laravel with Horizon, I get the following error:
```array_values() expects parameter 1 to be array, bool given {"exception":"[object] (ErrorException(code: 0): array_values() expects parameter 1 to be array, bool given at /app/vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php:80)```

This prevents Horizon from starting.

### Steps To Reproduce:
Start up laravel with horizon

**Comment by driesvints** [comment]
Works fine for me.

**Comment by xwiz** [comment]
This is a naughty problem, briefly happened and corrected itself, might be from some sort of config reading issue.

**Comment by egorsmkv** [comment]
I get this error on server restart
