### ISSUE TITLE
Batches with failed jobs are reported as finished

### ISSUE THREAD

**Issue by sebdesign** [laravel/horizon#1005]
- Horizon Version: 5.7.3
- Laravel Version: 8.43.0
- PHP Version: 7.4.16
- Redis Driver & Version: predis/phpredis 1.1.6
- Database Driver & Version: MySQL 5.7.33

### Description:

According to this issue: https://github.com/laravel/framework/issues/36864, batches which have failed jobs are reported as `Finished`. The correct behavior is that only batches without failed jobs have the `finished_at` timestamp, so they should display the `Failures` badge and not the `Finished` badge.

The reason this is happening is primarily a rounding error. The Batch::progress() method is not very accurate, because it rounds the number of processed jobs divided by the number of total jobs.

E.g. for a total of 1000 jobs where 1 failed, that calculates round(((1000 - 1) / 1000)) * 100) which returns 100.
But for 100 total jobs that would return 99.

In the `screen/batches/preview.vue` component, the `Failures` is displayed only if the progress is < 100, and the `Finished` badge only when progress is 100. Also the `Pending` badge is not correct because it assumes a batch has pending jobs without failed jobs, which is not the case for batches dispatched using `allowFailures()`.

### Steps To Reproduce:
```php
class Success {
    use Illuminate\Bus\Batchable;

    public function handle () {
        //
    }
}

class Failure {
    use Illuminate\Bus\Batchable;

    public function handle () {
        abort(500);
    }
}

$batch = Bus::batch(collect()
    ->times(999, fn () => new Success())
    ->add(new Failure())
)->name('99.9% success')->allowFailures()->dispatch();

// After the batch has been "processed"

$batch->totalJobs; // 1000
$batch->pendingJobs; // 1
$batch->failedJobs; // 1
$batch->processedJobs(); // 999
$batch->progress(); // 100
$batch->finished(); // false
$batch->cancelled(); // false
```

**Comment by themsaid** [comment]
Thanks. Noticed it's a large batch so completion percentage was 100%. Fixed this in https://github.com/laravel/horizon/commit/58b71c188cdbc3dc07ff0ab22861641200334b25
