### ISSUE TITLE
Pending jobs & Completed jobs not showing

### ISSUE THREAD

**Issue by osama-klabs** [laravel/horizon#1006]
- Horizon Version: 5.7.3
- Laravel Version: 8.34.0
- PHP Version: 7.4.16
- Redis Driver & Version: predis1.1.6

### Description:
Pending jobs & completed jobs not showing. see images
![Screenshot 2021-04-05 at 8 21 52 PM](https://user-images.githubusercontent.com/52484225/113590822-910a8a00-964c-11eb-8150-712bea862e28.png)
![Screenshot 2021-04-05 at 8 22 13 PM](https://user-images.githubusercontent.com/52484225/113590853-9ec00f80-964c-11eb-9009-672d9f728dfc.png)

**Comment by driesvints** [comment]
What Redis driver are you using? Predis or phpredis?

**Comment by osama-klabs** [comment]
@driesvints  predis

**Comment by driesvints** [comment]
I tried this a bit earlier and all worked fine for me. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by Jon78** [comment]
See #1003 for a possible solution (also phpredis is recommended over predis, see https://laravel.com/docs/8.x/redis)

**Comment by xicond** [comment]
happen on me on v4.3.5
I downgraded it to v4.2.1 and `php artisan view:clear` for workaround

**Comment by xicond** [comment]
In my case, it cause by I'm using cdn on assets, is there any way to workaround ?
It has been working on v3.7.2, but not on v4.x.x after I upgraded to laravel v7

**Comment by xicond** [comment]
I worked around it by override layout.blade without `asset()` for js
