### ISSUE TITLE
Vue is not properly render the dashboard page

### ISSUE THREAD

**Issue by rick20** [laravel/horizon#1008]
- Horizon Version: 5.7.5
- Laravel Version: 8.35.1
- PHP Version: 7.4

### Description:
Vue seems improperly rendering the dashboard and only showing a blank page:
I can see the view successfully rendering the page.
Routes respect the ```path``` in config file.
Unauthenticated request correctly showing 403.
All css and js loaded properly.
No js error on chrome devtools.
Config, cache and views are cleared via artisan and php-fpm restarted everytime I visit the dashboard.

But the dashboard keeps showing a blank page.

When a v-cloak removed, the page showing the title and menu for a split of second, but then it's immediately removed from the DOM.

Here's how it appears without v-cloak before it disappear.

<img width="1261" alt="Screen Shot 2021-04-07 at 17 09 31" src="https://user-images.githubusercontent.com/1517180/113853910-70ffd580-97c8-11eb-98ba-a8766344b6f6.png">

**Comment by driesvints** [comment]
Works fine for me. Make sure you re-publish your assets when updating: https://laravel.com/docs/8.x/horizon#upgrading-horizon

**Comment by rick20** [comment]
For those who are like me in which have strict security policy, please make sure to add ```‘unsafe-eval’``` to your ```Content-Security-Policy``` header so that vue can run properly. The errors are suppressed under production build.
