### ISSUE TITLE
what is this wip auto-commit / deploy command Taylor used in his Laracon keynotes?

### ISSUE THREAD

**Issue by vesper8** [laravel/horizon#101]
I know this is not specifically related to Horizon but he used it a few times during the video. Is it just a custom alias for an auto-git-commit ?

I also like the command he used to deploy to the cloud

Are these Envoyer-related? Is there somewhere where those most excellent shortcuts are shared? Would love to become more productive and use these myself!

**Comment by themsaid** [comment]
sorry man, not the right place for this :)
