### ISSUE TITLE
delete horizon key running on the wrong connection

### ISSUE THREAD

**Issue by fluxoti** [laravel/horizon#1013]
- Horizon Version: 3.7.1
- Laravel Version: 6.2
- PHP Version: 7.4
- Redis Driver & Version: phpredis 5.3.0
- Database Driver & Version:

### Description:

I have two connections to the redis in my application the default and the horizon, using the redis monitor I verified that the `"DEL" "horizon:*` is running on the redis default, and the others horizon commands is running in the correct connection.

```
root@redis-default:/data# redis-cli monitor
1619445826.912350 [0 10.8.72.138:59282] "DEL" "horizon:16906112"
1619445826.912360 [0 10.8.85.96:45044] "DEL" "horizon:16906275"
1619445826.917071 [0 10.8.54.79:55416] "DEL" "horizon:16906109"
1619445826.924247 [0 10.8.72.138:59010] "DEL" "horizon:16906117"
1619445826.926253 [0 10.8.54.79:55826] "DEL" "horizon:16906103"
1619445826.928338 [0 10.8.54.79:55500] "DEL" "horizon:16906120"


root@redis-horizon:/data# redis-cli monitor
1619445959.239873 [0 lua] "hmget" "horizon:job:App\\System\\Jobs\\Dial" "throughput" "runtime"
1619445959.239887 [0 lua] "hmset" "horizon:job:App\\System\\Jobs\\Dial" "throughput" "42806" "runtime" "176.76829393075687"
1619445959.240019 [0 10.8.72.138:47042] "HMSET" "horizon:16974515" "status" "completed" "completed_at" "1619445959.2395"
1619445959.240075 [0 10.8.72.138:47042] "EXPIREAT" "horizon:16974515" "1619446019"
1619445959.240172 [0 10.8.54.79:56028] "INCR" "horizon:job_id"
```

### Steps To Reproduce:

create two connections to the redis and change the horizon to use one of the two and check the DEL commands running on the other connection.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
