### ISSUE TITLE
[Bug] completed job stay in pending

### ISSUE THREAD

**Issue by neoteknic** [laravel/horizon#1015]
- Horizon Version: 5.7.6
- Laravel Version: 8.40.0
- PHP Version: 8.0.3
- Redis Driver & Version: phpredis 5.3.4
- Database Driver & Version: mariadb 10.5.9

### Description:
Bug, job stay in pending after complete, it is both in complete and pending : 
![image](https://user-images.githubusercontent.com/1809652/116700889-98148600-a9c7-11eb-8bc6-83ac47024b1a.png)

![image](https://user-images.githubusercontent.com/1809652/116700951-a367b180-a9c7-11eb-955a-f19449a816b1.png)

### Steps To Reproduce:
dont know how to reproduce, happen randomly

**Comment by driesvints** [comment]
If there's nothing to reproduce it's going to be hard for us to figure this out. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by sergey-solo** [comment]
Same here. Same versions for horizon and laravel.

**Comment by lucaspanik** [comment]
@neoteknic  and @sergey-solo 

Same in:
- https://github.com/laravel/horizon/issues/1034
- https://github.com/laravel/horizon/issues/1060
