### ISSUE TITLE
Memory exhausted when queue payload has too much data

### ISSUE THREAD

**Issue by l3lackheart** [laravel/horizon#1019]
- "laravel/horizon": "^5.7",
- "laravel/framework": "^8.0"
- "php": "^7.4.16",

### Description

When I try export large dataset using [Laravel Excel](https://docs.laravel-excel.com/3.1/exports/queued.html), I chunked it into 1k rows per queue. Horizon tried to store log data of every previous chunked data. I want to have a way to disable log for this case, or at least disable chained data (see image)

![image](https://user-images.githubusercontent.com/25253808/118114819-4e3d8e00-b412-11eb-81eb-b338390ac545.png)

**Comment by driesvints** [comment]
Use a different strategy for chunking the data. This isn't a Horizon issue, sorry.
