### ISSUE TITLE
Zero queue processes for queues at load with processes available to balance

### ISSUE THREAD

**Issue by murphatron** [laravel/horizon#1020]
- Horizon Version: 5.7.6
- Laravel Version: 8.41.0
- PHP Version: 7.4.15
- Redis Driver & Version: predis/phpredis N/A
- Database Driver & Version:

### Description:
To preface, I'm not seeking assistance with troubleshooting. My intention is to describe my experience to hopefully lead to some improvements either within Horizon proper or the documentation used by other developers.

I believe there may some muddled context of the `minProcesses` configuration in Horizon. I'm experiencing weird balancing issues where processes for a given queue falls to zero, even with a `minProcesses` set. I was able to correct my issue partly by modifying my configuration. After delving into the Horizon code to understand why my change may have alleviated the issue, I arrived at the aforementioned conclusion. 

In the docs, the only line I see describing `minProcesses` and `maxProcesses` is the following:
>When using the auto strategy, you may define the minProcesses and maxProcesses configuration options to control the minimum and the maximum number of worker processes Horizon should scale up and down to:

Checking SupervisorOptions.php and the phpdocs for these options, they read as:
```php
    /**
     * The maximum number of total processes to start when auto-scaling.
     *
     * @var int
     */
    public $maxProcesses = 1;

    /**
     * The minimum number of processes to assign per working when auto-scaling.
     *
     * @var int
     */
    public $minProcesses = 1;
```

Already between these two descriptions seems to imply different contexts of the `minProcesses` option. The Laravel documentation seems to imply `minProcesses` applies as a total sum minimum of processes across all queues. Where the phpdocs imply that the `minProcesses` configuration is on a queue (per working?) basis. At the very least, it seems that the Laravel docs are unclear and at most, at odds with the actual configuration intention.

### Steps To Reproduce:

Working with this configuration:
```php
    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis-sentinel',
            'queue' => ['critical', 'major','default', 'minor', 'trivial'],
            'balance' => 'auto',
            'minProcesses' => 1,
            'memory' => 128,
            'tries' => 1,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'prod' => [
            'supervisor-1' => [
                'maxProcesses' => 10,
                'minProcesses' => 5,
                'balanceMaxShift' => 3,
                'balanceCooldown' => 3,
            ],
        ],
    ],
```

When I start horizon, I begin with the 5 queues above with 2 processes each. Lower than the configured `minProcesses` of 5. At 2 processes per queue, that would be 10 processes total, equal to the configured `maxProcesses`.

As jobs build in up across queues, a condition can occur where rebalancing ramps the processes per queue up to 5 (which matches my `minProcesses` configuration... may be a coincidence though) each for some, with others falling to 0 processes. A specific occurrence had my critical, major, minor, and trivial queues increased from 2 to 5, and dropping my `default` queue to 0 with 300 jobs in queue not being processed in `default` and the queued jobs in the other queues fell to 0 but rebalancing didn't bring these processes down from 5.

Once `default` fell to zero, restarting Horizon had little affect. The app would start the supervisor with 2 processes per queue, rebalancing would quickly follow, dropping the process count to 0 for default (with 300+ jobs still in this queue) and raising the process count in the other queues to 5 even though there were no jobs in those queues.

After changing `minProcesses` to 1 in my configuration and restarting Horizon, this allowed all queues to start with 1 process each, the `default` queue increased processes (to 6) as expected to work through the jobs until all where processed and the queue size fell back to 0.

What I suspect is happening is since my total queue count * `minProcesses` is higher than `maxProcesses`, an unexpected condition is occurring in AutoScaler causing queues that aren't at load to scale up, and others to scale down to 0.

There's a lot here. My apologies if this is unclear. If you have any questions, let me know and I'll do my best to answer them.

**Comment by driesvints** [comment]
Sorry, this is a lot to take in. I understand from the above that this is simple because of inconsistency with the docs and the php docs? In that case we'd appreciate PR's to either the docs or to Horizon to improve these. I personally don't see a problem with the current wording, sorry.

As for the second part of your post we cannot help you out through the issue tracker here. I suggest you try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
