### ISSUE TITLE
Redis sentinel configuration

### ISSUE THREAD

**Issue by alsma** [laravel/horizon#1021]
- Laravel Version: 8.40.0
- Laravel Horizon Version: 5.7.6
- PHP Version: 8.0.3
- Redis driver: predis 1.1.7
- Database Driver & Version: 5.7.33-36 Percona Server

### Description:
As it's mentioned in docs Laravel supports redis cluster, but in fact there are several issues with it.
First of all it's missing confiugration examples in Laravel doc, I've spent some time to debug expected configuration format.
Another one is that Horizon currently breaks cluster configuration by running following [code](https://github.com/laravel/horizon/blob/5.x/src/Horizon.php#L100).  Even more it copies configuration of the specified connection to new one called `horizon` which won't work as well.

For instance we have default database config:
```php
return [
 'redis' => [
        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_',
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],
    ],
];
```
Now we want to use redis sentinel. We update config to following:
```php
return [
    'redis' => [
        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_',
        ],

        'clusters' => [
            'default' => [
                [
                    'url' => env('REDIS_URL'),
                    'host' => env('REDIS_HOST', '127.0.0.1'),
                    'password' => env('REDIS_PASSWORD'),
                    'port' => env('REDIS_PORT', 6379),
                ],

                'options' => [
                    'replication' => 'sentinel',
                    'service' => 'mymaster',
                    'parameters' => [
                        'database' => env('REDIS_DB', 0),
                    ]
                ],
            ],
        ],
    ],
];
```

Then running following code will throw error

```php
dd(\Illuminate\Support\Facades\Redis::get('test'));

  `SELECT` failed: ERR unknown command `SELECT`, with args beginning with: `0`,  [tcp://redis-sentinel:26379]
```
Without Horizon it works as expected.

**Comment by alsma** [comment]
If someone need workaround we can use default config and register new driver type.
```
.env
REDIS_CLIENT=predis-sentinel
```

```php
    public function register(): void
    {
        $this->app->resolving('redis', function (RedisManager $redisManager) {
            $redisManager->extend('predis-sentinel', function () {
                return new class extends PredisConnector {
                    public function connect(array $config, array $options)
                    {
                        $parameters = array_only($config, ['database', 'password']);
                        $config = array_except($config, ['database', 'password']);

                        $options = array_merge(
                            ['replication' => 'sentinel'],
                            array_except($options, 'sentinel'),
                            $options['sentinel'],
                            compact('parameters')
                        );

                        $connection = parent::connect([$config], $options);
                        $connection->client()->getConnection()->setUpdateSentinels(true);

                        return $connection;
                    }
                };
            });
        });
     }
```

**Comment by driesvints** [comment]
I think it's best that you send PRs to the docs and Horizon if you believe some things can be improved here 👍

**Comment by halaei** [comment]
@alsma Does this note from docs help?

> https://laravel.com/docs/8.x/queues#redis
If your Redis queue connection uses a Redis Cluster, your queue names must contain a key hash tag. This is required in order to ensure all of the Redis keys for a given queue are placed into the same hash slot:
```php
'redis' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => '{default}',
    'retry_after' => 90,
],
```
So each Laravel queue doesn't really support distribution across multiple Redis instances in a cluster. The key hash tag is a way to disable distribution for queues.

@driesvints do you know if horizon supports cluster distribution? If it doesn't I guess @alsma has to use the same key has tag in `config('horizon.prefix')` as well.

**Comment by driesvints** [comment]
I don't, no

**Comment by miaotiao** [comment]
@driesvints  So far,horizon still doesn't support  cluster distribution. So we has to use the same key hash tag in `config('horizon.prefix')` as well.
