### ISSUE TITLE
Auto Load Entries Not Working

### ISSUE THREAD

**Issue by jatinthapar1910** [laravel/horizon#1024]
- Horizon Version: 5.7
- Laravel Version: 8.12
- PHP Version: 8.0.3
- Redis Driver & Version: predis 1.1
- Database Driver & Version: Postgres 12.3

### Description:
Auto Load Entries in Laravel Horizon is not auto-loading the jobs. Rather Load New Entries is appearing every time.

### Steps To Reproduce:
I am not sure the exact steps to reproduce but I tried with a new Laravel Setup with nothing except Laravel Framework (with dependencies) and Laravel Horizon.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Cannonb4ll** [comment]
Having the same issue since the latest version. I think it has to do with this PR that moved contents: #1022

**Comment by driesvints** [comment]
I'm gonna revert that PR, thanks.

**Comment by jatinthapar1910** [comment]
This solves the issue, thanks @driesvints.
