### ISSUE TITLE
Blank Horizon Dashboard

### ISSUE THREAD

**Issue by Jurero123** [laravel/horizon#1027]
- Horizon Version: 5.7
- Laravel Version: 8.40
- PHP Version: 8.0
- Redis Driver & Version: predis/phpredis 5.0.9
- Database Driver & Version: MySQL 8

### Description:
When trying to open /horizon/dashboard, I can only see a blank page (with horizon BG color). There are no console errors, but when inspecting the source, I can see the following attribute on the #horizon div. Attaching screenshot.
![2021-05-28_08-06](https://user-images.githubusercontent.com/9927764/119938223-5c4fea80-bf8c-11eb-8527-6755dfafb483.png)

Non Horizon routes are working fine. Application is not in the maintenance mode.

### Steps To Reproduce:
Not really sure when or how this happened as it was working fine a few days ago.

**Comment by Jurero123** [comment]
I just updated Horizon to v5.7.8 (2021-05-27) and published assets and it is working again. Closing the issue.

**Comment by code2prog** [comment]
Something is wrong. Empty dashboard in version 5.7.8. Updating or publishing assets does not help and only after moving back to 5.7.7 and publishing assets again the dashboard displays correctly
