### ISSUE TITLE
SMTP Mail Issue

### ISSUE THREAD

**Issue by karthickraja05** [laravel/horizon#1032]
- Horizon Version: 4.3.5
- Laravel Version: 7.0
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version:

### Description:

Hi,

I am using this package for sent mails to many users. (SMTP gmail)
I sent around 300 mails. 
Config/horizon.php

```
'local' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'auto',
                'processes' => 10,
                'tries' => 1,
                'nice' => 0,
            ],
        ],
```

Initially mail sent successfully after some time processing most of mail not sent.

But in normal queue method all mails sent successfully, (Only time takes long).

Any one faced like that of issue. or do you know what mistake i did.
Guide to me

Thanks Advance.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
