### ISSUE TITLE
Publish Nginx

### ISSUE THREAD

**Issue by antoniovalenzuela** [laravel/horizon#1033]
Hi, it's possible publish horizon in location Nginx?

I can use anothers routes with this configuration, but horizon shows many errors in URL paths (vendor, css, js).

	location ^~ /path {
		alias /var/www/html/store/public;
		try_files $uri $uri/ @store;

		location ~ \.php {
			include fastcgi.conf;
			fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
			fastcgi_intercept_errors on;
			include /etc/nginx/fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $request_filename;
		}
	}

	location @store{
		rewrite /store/(.*)$ /store/index.php last;
	}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
