### ISSUE TITLE
Complete jobs not leaving the pending queue

### ISSUE THREAD

**Issue by lucaspanik** [laravel/horizon#1034]
- Horizon Version: 5.7.9
- Laravel Version: 8.27.0
- PHP Version: 7.4.9
- Redis Driver & Version: predis/phpredis 5.2.1
- Database Driver & Version: mysqlnd 7.4.9

### Description:
First of all, I apologize if I'm posting in the wrong place, but I searched the other communication channels and didn't find anything related to this problem.

For some reason, some jobs that run very fast are not coming out of the pending queue even though they are given a completion date.

This bug happens sporadically and randomly, it is not a specific job, nor a specific process, it just happens with jobs that run very fast, or with jobs that, due to some condition, do not need to perform any action in the code, marking the job as complete in it second that the job starts processing.

My environment is currently an AWS EC2 with AWS Redis.

In the case of the prints below, the notification arrived successfully for the user, however, for some reason, the job was left in the pending queue, overcrowding the queue with unreal information, since they are already complete.

### Steps To Reproduce:

1. Create a job that has nothing in the handle method

### Prints of completed jobs being in the pending queue
![BroadcastNotificationCreated still in pending queu](https://user-images.githubusercontent.com/7035554/121985129-8a924000-cd6a-11eb-8a99-0a114f15c430.png)

![Completed at equal to Pushed At date](https://user-images.githubusercontent.com/7035554/121985174-a0076a00-cd6a-11eb-8fb0-538838e75374.png)

**Comment by lucaspanik** [comment]
![ADD sleep(3)](https://user-images.githubusercontent.com/7035554/121988525-dba53280-cd70-11eb-9fe5-afe481541879.png)

Apparently putting a sleep(3) makes the job leave the pending queue and go to the completion queue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lucaspanik** [comment]
Hi @driesvints , thanks for replying.

I reported it as a bug because it is an event of the framework itself, where I don't have access to this job's settings.

`Illuminate\Notifications\Event\BroadcastNotificationCreated`

But if the case is really a support issue, I will open it in the channels informed by you.

Thanks.

**Comment by LocalHeroPro** [comment]
I noticed similar bug.
Jobs aren't decreased to 0 - right now I have > 100 jobs - even after clearing queue, pending jobs tab is empty.

**Comment by LocalHeroPro** [comment]
And jobs are still running. Even when i have clear `pending jobs` tab. It's bug, because I can't clear in normal way jobs.

**Comment by kolinko-ant** [comment]
We also see the same issue! 1 out of 1000 jobs stays at pending tab although it says
ID
cc44ad25-b558-4e65-a105-489f4ab48816
Queue
process_statistics
Pushed At
2021-07-02 22:03:00
Completed At
2021-07-02 22:03:00

**Comment by lucaspanik** [comment]
> We also see the same issue! 1 out of 1000 jobs stays at pending tab although it says
> ID
> cc44ad25-b558-4e65-a105-489f4ab48816
> Queue
> process_statistics
> Pushed At
> 2021-07-02 22:03:00
> Completed At
> 2021-07-02 22:03:00
> 
> I am just curious will this issue be checked? Because now it's closed, so not sure if somebody is aware of this issue.

Good to know it's not just happening to me, turning this into a bug if I'm right.

if possible, send a print to demonstrate this case as well.

**Comment by lucaspanik** [comment]
@driesvints  I've updated all possible packages to the latest versions and I still have the problem. But now I'm bringing more information to detect the problem.

- Horizon Version: 5.7.9
- Laravel Version: 8.48.1
- PHP Version: 7.4.9
- Redis Driver & Version: phpredis 5.2.1
- Database Driver & Version: mysqlnd 7.4.9

---
![image](https://user-images.githubusercontent.com/7035554/125865187-25364633-c9a4-4daa-bbcb-3052eb9c48df.png)

---
```bash 
composer show | grep 'laravel/horizon' 
laravel/horizon                    v5.7.9            Dashboard and code-driven configuration for Laravel queues.
```
---

```bash 
composer show | grep 'laravel/framework' 
laravel/framework                  v8.48.1           The Laravel Framework. 
```

---

![image](https://user-images.githubusercontent.com/7035554/125859639-5151ccac-c8bb-48f1-af9f-822f86426bda.png)

---

![image](https://user-images.githubusercontent.com/7035554/125859772-2b15acda-90c9-45e7-a674-a792ea619a2e.png)

---

![image](https://user-images.githubusercontent.com/7035554/125860236-fee7846d-b721-47b9-b557-570621a1fcdc.png)

---

AWS - ElastiCache

![image](https://user-images.githubusercontent.com/7035554/125860659-d3183741-4d82-44cb-98b2-6c3d9fbd3872.png)

Redis version:
![image](https://user-images.githubusercontent.com/7035554/125860910-f81ea4e4-a5e2-4811-a0b7-8059839a2212.png)

---

```bash 
supervisord -v 
4.2.2
```

```conf
[program:horizon]
process_name=%(program_name)s
command=php /home/ec2-user/laravel/artisan horizon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0 
stopwaitsecs=660 ; 11 min
```

> You should ensure that the value of stopwaitsecs is greater than the number of seconds consumed by your longest running job. Otherwise, Supervisor may kill the job before it is finished processing.
>
> [Supervisor Configuration (stopwaitsecs config)](https://laravel.com/docs/8.x/horizon#supervisor-configuration)

My longest job is 10 minutes.

---

My server responsible for running the jobs is an AWS [m5.2xlarge](https://aws.amazon.com/ec2/instance-types/m5/) with all packages and programs updated.

--

Using Redis Desktop Manager to get more information I noticed that the job is actually pending:

![image](https://user-images.githubusercontent.com/7035554/125865924-c9363e39-dcc0-4e13-abab-a8dc7c24e1a2.png)

You can see that the dates are exactly the same but the status is still pending.

![image](https://user-images.githubusercontent.com/7035554/125866362-6941cd5f-83a7-4f4b-a8f5-2773c61e4a16.png)

-- 

Well, I think I'm trying my best to understand the problem, and offering as much data as possible to get some help.

But I confess to not knowing where else to look for more information. =/

**Comment by erickneverson** [comment]
> ![ADD sleep(3)](https://user-images.githubusercontent.com/7035554/121988525-dba53280-cd70-11eb-9fe5-afe481541879.png)
> 
> Apparently putting a `sleep(3)` in jobs that I have access makes the job leave the "Pending Jobs" and go to the "Completed Jobs".

I'm currently in the middle of testing this out as I'm also facing this issue now suddenly after using horizon for months. Just curious what your experience was trying other sleep values (1 second?).  Hope this issue gets resolved soon.

**Comment by lucaspanik** [comment]
> @lucaspanik did you ever find a solution to this that didn't require you to sleep for every job? If not, would you be willing to share your timeout and retry_after values?

@rforced  Unfortunately, I didn't find any solution for this, I'm still using sleep in my own jobs.

However, as you can see above the prints, I'm having a problem with a job from Laravel itself, `BroadcastNotificationCreated`, where I don't have direct control over retry and timeout.

**Comment by hsndev18** [comment]
Still I have same issue 

```
ID              ba1e7588-db18-4b33-9d57-8dc0c083f8b9
Queue           send-custom-emails
Pushed          2024-06-29 00:33:04
Completed       -
```

and it's stuck on pending status !

how to solve it ?

**Comment by thaifanisalla** [comment]
Having same issue (stuck on pending even with delay(1 second), and it happens randomly for some jobs.
PHP: 8.3
Laravel: 10.48.29
Horizon :5.33.5

<img width="900" height="261" alt="Image" src="https://github.com/user-attachments/assets/85bc575e-62dc-49cf-ba5b-f9e7f9fc142e" />
