### ISSUE TITLE
Pending & completed list empty while workload count is correct

### ISSUE THREAD

**Issue by mrmonat** [laravel/horizon#1035]
- Horizon Version: v5.7.8
- Laravel Version: 8.37.0
- PHP Version: 8.0.7
- Redis Driver & Version: phpredis 5.3.4
- Database Driver & Version: Redis (v5.0.3) / MySQL (v15.1 Maria DB)

### Description:

Pending / completed jobs don't show up in the list view. The counting of pending jobs does work on the dashboard. All jobs finish execution without problems / failures but are not visible in the pending / completed list view. Each Job only takes a few seconds so "Horizon Trimming" should not be the problem. Interestingly all jobs are visible in Telescope while pending and when completed.

**Dashboard Workload**
![Bildschirmfoto 2021-06-15 um 10 21 59](https://user-images.githubusercontent.com/17597850/122019777-6f541e80-cdc4-11eb-851d-a5d8b7d05d5c.png)

**Workload JSON Response**
![Bildschirmfoto 2021-06-15 um 10 23 13](https://user-images.githubusercontent.com/17597850/122019837-7ed36780-cdc4-11eb-90e5-3a8c9867f33b.png)

**Pending List View**
![Bildschirmfoto 2021-06-15 um 10 22 14](https://user-images.githubusercontent.com/17597850/122019804-75e29600-cdc4-11eb-962f-25081fdaad3e.png)

**Pending JSON Response**
![Bildschirmfoto 2021-06-15 um 10 23 21](https://user-images.githubusercontent.com/17597850/122019935-97dc1880-cdc4-11eb-9861-ad92702c6364.png)

### Steps To Reproduce:

Inside a dispatched Job a new Job Batch is created:
```php
$batch = Bus::batch([])->dispatch();

$jobs = $this->getJobs(); // Returns Array of Dispatchable, Batchable Jobs

$batch->add($jobs);

```

Horizon Config (Trim):
```php
'trim' => [
        'recent' => 60,
        'pending' => 60,
        'completed' => 60,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
],
```

**Comment by driesvints** [comment]
I'm not sure what the problem here is. The jobs are handled almost immediately like you say so they shouldn't be showing up in pending?

**Comment by mrmonat** [comment]
The problem is not only happening in the pending list but also the completed list is empty as well as the "completed" JSON response.

**Comment by driesvints** [comment]
There's really very few info here to debug all this. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Jon78** [comment]
Could it be you're using setlocale? See https://github.com/laravel/horizon/issues/1003

**Comment by mrmonat** [comment]
@Jon78 no I don't set setlocale. I left everything related to localization on default. There seems to be a problem with the redis "zsets" "failed_jobs", "completed_jobs" and "pending_jobs" because they are always empty / don't get created...

**Comment by Jon78** [comment]
> @Jon78 no I don't set setlocale. I left everything related to localization on default. There seems to be a problem with the redis "zsets" "failed_jobs", "completed_jobs" and "pending_jobs" because they are always empty / don't get created...

Ah, because the problem you're describing sounded similar to mine and your screenshots are in German :smiley: Maybe your server config sets a non-English locale then? I would investigate what gets passed to Redis to see if floats are properly formatted as per https://github.com/laravel/horizon/issues/788#issuecomment-601255010

**Comment by mrmonat** [comment]
@Jon78 You were quite right...

For everyone having the same issue in the future:

The Server had a default Language of `de_DE.UTF-8`. This caused Problems in Laravels `RedisJobRepository` because the microtime passed to the Redis `ZADD` method was formatted like `1234556,12345` instead of `1234556.12345`. Because of that, not a single job got added to the sets `failed_jobs`, `completed_jobs`, `pending_jobs`.

The solution is to set the Locale in AppServiceProvider:
```php
setlocale(LC_ALL, 'en_US.UTF-8');
```

**Comment by Jon78** [comment]
@driesvints this keeps popping up. Will you accept a PR to permanently fix it?

**Comment by driesvints** [comment]
@Jon78 think previous attempts got shot down. You're always free to give it another go but it seems to be a tough nut to crack.
