### ISSUE TITLE
Add ability immediately run 'delayed' jobs.

### ISSUE THREAD

**Issue by hailwood** [laravel/horizon#1036]
Similar to how we can retry a failed job, it would be useful to be able to immediately execute a pending job.

Useful in edge cases where for example a welcome email might be sent after four hours, but you want to send it to the client immediately for various reasons - manually sending the email would be an issue as they'd then receive the welcome email twice unless you'd built in a 'welcome_email_sent' column. 

Or as another example we interact with some AWS services where things are not instant (e.g. cloudfront provisioning) so we queue a delayed job which is set for the maximum time we know the task to take on AWS. Sometimes this completes a lot faster and it would be useful to be able to manually execute the next step instead of waiting.

**Comment by driesvints** [comment]
I definitely see that being useful myself. Feel free to attempt a PR for Taylor to review 👍

**Comment by omitobi** [comment]
I really needed this functionality myself.

**Comment by laravel-o11y** [comment]
https://github.com/boring-o11y/horizon-delayed-jobs adds a new screen with the delayed jobs and a function to immediately execute the job
