### ISSUE TITLE
Can a single url horizon monitor all laravel apps queue

### ISSUE THREAD

**Issue by Daniel-Lau-Malaysia** [laravel/horizon#1038]
I have installed 4 laravel/lumens application on a single server. Current to view the progress of the jobs in each laravel/lumens app , I need to monitor it on all 4 browser tabs. What I want to do is a single url horizon ( ie single browser  tab ) that can view the progress of all four laravel/lumens app jobs including failed jobs and also restarting failed job. Is this possible to do ?  If can please guide me to solve this problem. I am currently using php artisan serve on all 4 apps and Laravel 8 version.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Daniel-Lau-Malaysia** [comment]
Thanks First time using
