### ISSUE TITLE
Support env for the worker command

### ISSUE THREAD

**Issue by ahmedash95** [laravel/horizon#1039]
Hello,

The problem is that I use [DataDog APM](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers) to monitor my application performance. and because Horizon runs  multiple workers itself `php artisan horizon:work` there is no way to add DD env vars to that cli command to be like 
```bash
DD_TRACE_CLI_ENABLED=true DD_SERVICE='my_app_horizon_worker' DD_ENV='production' DD_VERSION='6.60.60' php artisan horizon:work
```

a small experiment I did was to change [WorkerCommandString.php#L24](https://github.com/laravel/horizon/blob/5.x/src/WorkerCommandString.php#L24) to be like below and `horizon.worker_env` is a string of env vars like `name=horiozn_app version=1.5.0` but I wish if Horizon would be able to support that instead of doing fork and keep maintaining it to get the last updates from original repository.
```php
return sprintf(
            "%s %s {$options->connection} %s",
            config('horizon.worker_env', ''),
            $command,
            static::toOptionsString($options)
        );
```

also I can help with a PR if you just approve that concept

**Comment by driesvints** [comment]
We don't have any plans for this atm, sorry.
