### ISSUE TITLE
horizon:clear command blocks the Redis server.

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#1044]
- Horizon Version: 5.7.9
- Laravel Version: 8.50.0
- PHP Version: 7.4.21
- Redis Driver & Version: any
- Database Driver & Version:

### Description:
Redis is "almost" single-threaded. It means when one command is being executed, the other commands have to wait. It is not a problem in general. But we must avoid slow commands whenever possible. The current implementation of `RedisJobRepository::purge()` runs a single slow LUA scripts that iterates over all the recent jobs, the processed jobs in the past 1 hour by default, which can be thousands or millions of jobs depending on the workload.
 
I recommend to perform one step of iteration inside the LUA script to remove just 1000 jobs, and move the iteration logic to PHP to prevent blocking.

**Comment by driesvints** [comment]
Feel free to attempt a PR. Thanks
