### ISSUE TITLE
hello,I found a problem on the display page

### ISSUE THREAD

**Issue by thefireb** [laravel/horizon#1047]
![image](https://user-images.githubusercontent.com/25997235/128489154-2c9bbe4c-0eb3-4da9-94b7-ae5dff6c47f0.png)
my horizon version is ~3.0 and my laravel framework version is v6.2.0
![image](https://user-images.githubusercontent.com/25997235/128489337-b0a53d7c-7ca8-45d2-978a-7dba201bb301.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
