### ISSUE TITLE
hello,in laravel8 I also find the display page's problem

### ISSUE THREAD

**Issue by thefireb** [laravel/horizon#1048]
![image](https://user-images.githubusercontent.com/25997235/128652555-4913bfe9-0234-4681-ac7c-c7b94d0a1509.png)
my horizon version is v5.7 and my laravel framework version is v8.4.0 and I run it in homestead on windows 10
![image](https://user-images.githubusercontent.com/25997235/128652607-7b62ea30-d5c4-4fed-90e6-3476cb826cfa.png)
I dont now what problem in it, i feel it like my before's problem, but i cant find the problem

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by halaei** [comment]
Hello @thefireb  I just want to mention you are using Horizon on a database queue. But Horizon only supports Redis. Hence the error `undefined method DatabaseQueue::readyNow()`.

**Comment by thefireb** [comment]
@halaei thinks you very much
