### ISSUE TITLE
expireat usage

### ISSUE THREAD

**Issue by hairmenu** [laravel/horizon#1049]
Hi

First, tx for the package it looks very useful. 
However, i would like to share something. It is not exactly a bug, but since it may become a deal breaker to me i share it.
When i unittest my app, since i installed Horizon i got an error when it comes to send queued emails.

vendor/laravel/horizon/src/Repositories/RedisJobRepository.php:337
At this line, Horizon use the Redis command "expireat" which is legit but 2 things
-> i cannot find any redis mock package covering this redis function :-(, `expire` function is covered...
-> I thought Horizon was a monitoring tool, so why it is interfering in my unit test?

Regards

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
