### ISSUE TITLE
Show paused supervisors on dashboard

### ISSUE THREAD

**Issue by hylke94** [laravel/horizon#1051]
We already have a main status in the top right corner. We can also see a pause icon if a whole master is paused. Excellent!

But can we also get a little pause icon if a single supervisor is paused? The AJAX call already returns the status of the supervisor (see screenshot), but nothing is done with it. Would be much appreciated :smile:.

![image](https://user-images.githubusercontent.com/1220076/129007558-9cb09b9b-b5f2-439f-94a3-e7516374366e.png)

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍

**Comment by hylke94** [comment]
> Feel free to attempt a PR

Any change of a new release? :see_no_evil:

**Comment by driesvints** [comment]
@hylke94 releases are done on Tuesday's so that's today.

**Comment by hylke94** [comment]
Aah, nice. Didn't know that... I'll wait a bit longer ;)
