### ISSUE TITLE
Memory footprint displayed for each job

### ISSUE THREAD

**Issue by tentacode** [laravel/horizon#1053]
Hello there 👋

I wondered if there is a way to add the memory footprint of a job in addition to the time, I haven't seen it in the documentation, maybe it's a ghost feature?

If it's not yet implemented is this something you would like to see in Horizon too? Could you give me some inputs on how to do it so I can submit a PR if interested?

Keep up the awesome work 💪

**Comment by driesvints** [comment]
Heya. We're not planning to add this ourselves but you're always free to attempt a PR. Thanks
