### ISSUE TITLE
Error after upgrading to Horizon 5.6.4

### ISSUE THREAD

**Issue by ocind** [laravel/horizon#1055]
- Horizon Version: 5.6.4
- Laravel Version: 8.15.0
- PHP Version: 7.4.16
- Redis Driver & Version: phpredis 1.1.6
- Database Driver & Version:

### Description & Steps To Reproduce:
We are currently using Horizon 5.4.0

When upgrading to Horizon 5.6.4 we are getting this error 
```
PHP Error:  __clone method called on non-object in /var/www/<project-name>/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php on line 94
```
while submitting a new notification job.
Downgrading back to 5.4.0 solves the issue.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
