### ISSUE TITLE
Possibility to define max processed per queue

### ISSUE THREAD

**Issue by kgiedrius** [laravel/horizon#1058]
In "auto" balance mode now it is not possible to define max processes per queue, only min processes per queue and total processes (maxProcesses) for all queues.

Current configuration:
      'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['Q2', 'Q3', 'Q4', 'Q5', 'Q7', 'Q8', 'Q10', 'Q14', 'Q11', 'Q13'],
            'balance' => 'auto',
            'minProcesses' => 1,
            'maxProcesses' => 22,
            'memory' => 512,
            'tries' => 2,
            'nice' => 0,
        ]

Suggest:
      'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['Q2', 'Q3', 'Q4', 'Q5', 'Q7', 'Q8', 'Q10', 'Q14', 'Q11', 'Q13'],
            'balance' => 'auto',
            'minProcessesPerQueue' => 1,
            'maxProcessesPerQueue' => 5,
            'maxProcesses' => 50,
            'memory' => 512,
            'tries' => 2,
            'nice' => 0,
        ]

**Comment by driesvints** [comment]
Feel free to propose something through a PR 👍
