### ISSUE TITLE
Separate cache clear from laravel cache clear

### ISSUE THREAD

**Issue by kgiedrius** [laravel/horizon#1059]
When all cache drivers are "redis" Laravel cache:clear clears everything from queue which is not very good approach

CACHE_DRIVER=redis
CACHE_PREFIX=project_prefix
SESSION_DRIVER=redis
QUEUE_DRIVER=redis

**Comment by driesvints** [comment]
The Redis cache and persistent connections are on separate databases by default: 

https://github.com/laravel/laravel/blob/8.x/config/database.php#L142
https://github.com/laravel/laravel/blob/8.x/config/cache.php#L78
