### ISSUE TITLE
The job is completing but still shows as pending.

### ISSUE THREAD

**Issue by polatdev** [laravel/horizon#1060]
- Horizon Version: 5.7
- Laravel Version: 8.40
- PHP Version: 8.0.9
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: MongoDB 5

### Description:
The job is completing but still shows as pending.

### Steps To Reproduce:

Hello, I am running concurrent queues in RabbitMQ using horizon.
For example, when I want to terminate the queue anywhere in the queue, I stop the whole process with 'exit' or 'die'. But it still shows up as pending in horizon. How can I manually stop operations?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lucaspanik** [comment]
@polatdev I have the same problem... I don't think anyone knows why https://github.com/laravel/horizon/issues/1034
