### ISSUE TITLE
laravel/horizon v5.6.4 requires ext-pcntl

### ISSUE THREAD

**Issue by Nimaw** [laravel/horizon#1061]
- Horizon Version: ^5.2
- Laravel Version: 7 | 8
- PHP Version: 8.0.9
- Database Driver & Version: MySql : 10.4.20

### Description:
I want to use Laravel Horizon in a project.
When i running `composer install`  returns an error about larave/horizon.
Error :
`- laravel/horizon v5.6.4 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.`

According to my searches, the `pcntl` extention cannot be used in Windows.

Repository i cloned and want to use : https://github.com/spatie/larabank-aggregates

**Comment by driesvints** [comment]
We don't support windows.

**Comment by mealinux** [comment]
> We don't support windows.

there is same case on linux?
