### ISSUE TITLE
Incomplete execution of jobs after horizon:terminate command

### ISSUE THREAD

**Issue by Mnikoei** [laravel/horizon#1066]
Horizon Version: 5.7.12
Laravel Version: 8.41.0
PHP Version: 8.0.8
Redis Driver & Version: predis: 1.1.7
Database Driver & Version: MySQL 8.0

### Description:

When horizon:terminate command is used this job gives unexpected results:

```
public function handle()‍‍‍
 {
        sleep(50);
        info('X');
        sleep(50);
        info('Y');
 }
```

after running command before ending first 50 seconds, it executes info('X') instantly then after 50 seconds executes info('Y').
i didn't look for how this happens in horizon codes but it's noted in docs that any jobs that are currently being processed by will be completed and then Horizon will stop executing but that doesn't happen here.

**Comment by halaei** [comment]
Maybe the job reaches timeout. The default timeout is probably 60 seconds. Does it print 'Y' if you don't terminate horizon?

**Comment by driesvints** [comment]
> after running command before ending first 50 seconds, it executes info('X') instantly then after 50 seconds executes info('Y').

That seems the logic result of the code in the snippet?

**Comment by halaei** [comment]
Interrupts causes sleep function to immediately return with a non-zero value. Running horizon:terminate sends a signal to the workers. Therefore info('X') is executed instantly.
