### ISSUE TITLE
Call redis.replicate_commands()

### ISSUE THREAD

**Issue by davidvandertuijn** [laravel/horizon#1068]
- Horizon Version: 5.7
- Laravel Version: 8.40
- PHP Version: 7.4.22
- Redis Driver & Version: predis/phpredis 3.2.12 & predis 1.1
- Database Driver & Version:

### Description:

`ERR Error running script (call to f_281c23c60c642d42fdedcc1acc8adc7317dd75a5): @user_script:18: @user_script: 18: Write commands not allowed after non deterministic commands. Call redis.replicate_commands() at the start of your script in order to switch to single commands replication mode.`

[Replicating commands instead of scripts](https://redis.io/commands/EVAL#replicating-commands-instead-of-scripts)
Howto call redis.replicate_commands() ?

### Steps To Reproduce:

`php artisan horizon:clear --queue=supplier_feeds_queue`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by logan-jobzmall** [comment]
I am having this issue as well - only against Elasticache however, local is fine -  @davidvandertuijn @driesvints  - was there any resolution to this?

**Comment by markieo1** [comment]
This is still an issue. I have created an PR to fix it.
