### ISSUE TITLE
If displayName return a different name for all jobs it create too much record in redis

### ISSUE THREAD

**Issue by neodc** [laravel/horizon#1070]
- Horizon Version: 5.6.6
- Laravel Version: 8.27.0
- PHP Version: 7.3

### Description:

In one of our job we implemented displayName() to add some information after the class name, in that information is the id of the model process by the job so that we can trace what happened in our log, that means that the displayName() return is (almost, not in case of retry) always unique.

I see that in Horizon the displayName() is used as a key for some metrics and so it create a lot of record where it expect to create only one by job class.

### Steps To Reproduce:

1. Create a Queueable with displayName() overwritten so that it's unique, for example:
```
public function displayName(): string
{
	return get_class($this) . ' ' . $this->custom_id;
}
```
2. Start a lot of instance of this job with different custom_id
3. The redis db start to fill up from all the different record created for metrics and `horizon:snapshot` start to take a lot of time to process everything

**Comment by driesvints** [comment]
Heya, yes this is the intended behavior. The `displayName` method is meant to retrieve the class name. We don't document this anywhere that you can overwrite this. It's purely a mechanism for internal purposes. If you need to add a custom display name I suggest you add that through the job payload.
