### ISSUE TITLE
Some batch jobs fail (MaxAttemptsExceededException) but actually it does not.

### ISSUE THREAD

**Issue by RomanSarvarov** [laravel/horizon#1071]
- Horizon Version: 5.7.12
- Laravel Version: 8.61.0
- PHP Version: 8.0
- Redis Driver & Version: predis/phpredis 1.1.2
- Database Driver & Version:  10.3.31-MariaDB-0ubuntu0.20.04.1-log Ubuntu 20.04
- horizon.php:
```
'supervisor-2' => [
    'connection' => 'redis',
    'queue' => ['scrape'],
    'balance' => 'auto',
    'minProcesses' => 1,
    'maxProcesses' => 2,
    'memory' => 128,
    'tries' => 1,
    'retry_after' => 60 * 60,
    'timeout' => 55 * 60,
    'nice' => 10,
],
```
- exception:
`Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\Scrape\Donstroy\DonstroyImportFlatsJob has been attempted too many times or run too long. The job may have previously timed out. in /var/www/kotlovan.io/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:750`

### Description:
I run a batch of jobs every hour via cron.
Sometimes my jobs are fail in Horizon, but actually they are reach the end of handle() function and work fine.
In handle function of jobs there is not any bad terminations like exit or die.
If I retry job manually it never fails.
Runtime of these failed jobs is always 0.01 sec, but actually it runs for a few minutes untill reach end of job's handle function.
![Screenshot_2](https://user-images.githubusercontent.com/27378369/134207770-df8e3d05-1c37-48c1-9ce0-6d77b89f6239.jpg)

**Comment by RomanSarvarov** [comment]
I changed maxProcesses => 2 to maxProcesses => 1 and exception is not throwing, as I see.
Why?

**Comment by henze-housepedia** [comment]
I have had the same problem: This happens only when you set the balance strategy to auto. I think it has something to do with the way horizon assigns processes. As if it kills off a worker during processing to assign it to a queue needs more workers.

Try setting it to simple or false.
