### ISSUE TITLE
Some batches does not have "finished" badge when actually finished, have "-1" pending jobs and Completion > 100%

### ISSUE THREAD

**Issue by RomanSarvarov** [laravel/horizon#1073]
Horizon Version: 5.7.12
Laravel Version: 8.61.0
PHP Version: 8.0
Redis Driver & Version: predis/phpredis 1.1.2
Database Driver & Version: 10.3.31-MariaDB-0ubuntu0.20.04.1-log Ubuntu 20.04
horizon.php:
```
'supervisor-2' => [
    'connection' => 'redis',
    'queue' => ['scrape'],
    'balance' => 'auto',
    'minProcesses' => 1,
    'maxProcesses' => 2,
    'memory' => 128,
    'tries' => 1,
    'retry_after' => 60 * 60,
    'timeout' => 55 * 60,
    'nice' => 10,
],
```
### Description:
I have long running batches of jobs (15+ min).
Sometimes this happens:
![Screenshot_3](https://user-images.githubusercontent.com/27378369/134371285-83e22664-3572-4c6d-ad04-42a42256174d.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/27378369/134371507-9886546c-e23f-45ce-b385-a1f28f3e57bb.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/27378369/134398447-b4663269-c73e-47c9-bff0-f06abc9a397c.jpg)

But it actually finished succesfully.
By the way there should be 18 completed Jobs, not 19.

**Comment by ehben83** [comment]
@RomanSarvarov I have the same problem. Do you know what causes this ?

**Comment by RomanSarvarov** [comment]
> 

As I remember I fixed that by increasing the process count.

**Comment by ehben83** [comment]
@RomanSarvarov Thank you for your fast reply. 

I'm not sure I understand of which specific parameter you talk about ?

**Comment by RomanSarvarov** [comment]
> @RomanSarvarov Thank you for your fast reply.
> 
> I'm not sure I understand of which specific parameter you talk about ?

maxProcesses

Btw do you have any job that add more jobs in batch?

**Comment by ehben83** [comment]
Yes - totally ! I have jobs being added to the batch.
