### ISSUE TITLE
MaxAttemptsExceededException when balance strategy set to auto.

### ISSUE THREAD

**Issue by henze-housepedia** [laravel/horizon#1075]
- Horizon Version: 5.7.13
- Laravel Version: 8.61.0
- PHP Version:8.0.10
- Redis Driver & Version: predis 1.17 (redis version 6.2.5)
- Database Driver & Version: mysqlnd 8.0.10

### Description:
I have a supervisor that supervises multiple queues and a minimum of 2 and a maximum of 30 workers. When I set the balance strategy to auto, I receive MaxAttemptsExceededException, But do I change the strategy to false or simple, I do not.

### Steps To Reproduce:
- set up a supervisor with 2 queues, with 2 or more workers.
- set tries to 1
- retry_after to 65
- timeout to 60 (as per the docs)
- set the balance to 'auto'
- create a simple job (just let it 'sleep' a few seconds in the handle)
- start horizon
- dispatch many jobs randomly to both queues.

**Comment by RomanSarvarov** [comment]
I have the same problem.
Can you share their runtime? I have 0.01 runtime always.

**Comment by henze-housepedia** [comment]
That's because The job seems to be killed without removing it from the queue. The job get's processed again and immediately marked as failed because the max attempts was exceeded (hence this error).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ankurk91** [comment]
I removed `WithoutOverlapping` middleware from my jobs and the issue is fixed for me now.

I was having many job failed with 0.00 runtime daily.
