### ISSUE TITLE
See worker name on job detail when finished or failed

### ISSUE THREAD

**Issue by glamorous** [laravel/horizon#1079]
I want to create a PR to see the worker name on the job details page especially when a job has failed. This can/will be very useful if jobs only seems to fail on a particular server. This information on the ui would help to identify such kind of problems.

The only thing that is "holding" me back to create a PR is that I didn't find a way to pass the worker name to the job. I don't believe that is passed already or available in the job details.

If someone from the community can point me in the right direction, I can look into it again to create a proposal.

**Comment by driesvints** [comment]
Hey @glamorous. This is best asked on a support channel. If you do end up finding a way feel free to send in a PR! Thanks
