### ISSUE TITLE
Order snapshots by score

### ISSUE THREAD

**Issue by KristofMorva** [laravel/horizon#108]
Metric Jobs and Queues return an `array_flip(): Can only flip STRING and INTEGER values!` error for `src/Repositories/RedisMetricsRepository.php` on line `234`. If I see it right, the problem is, scores are stored as floats, not as integers, and floats cannot be array keys. Sadly I'm not an expert in Redis (not even a beginner yet sadly), so at this point I can't propose a PR (but I guess either we should have integer scores, we should cast them before flipping, or we shouldn't flip).

By the way I'm on PHP 7.1, with Horizon 1.0.0 and Laravel 5.5.

**Comment by themsaid** [comment]
> scores are stored as floats

They're not, scores are a Unix timestamp representation.

**Comment by themsaid** [comment]
What redis client are you using?

**Comment by KristofMorva** [comment]
@themsaid yes they are timestamps, but according to `var_dump`, they are floats. I'm using PHPRedis (the PHP extension) in the project.

I have found an issue, which may be related (https://github.com/phpredis/phpredis/issues/1189):
> The scores in a Redis zset are stored internally as double precision floating point numbers, and are returned to phpredis in string representation which phpredis treats as a float.

**Comment by tillkruss** [comment]
I'm seeing the same error using PhpRedis.

```
array_flip(): Can only flip STRING and INTEGER values!
```

**Comment by themsaid** [comment]
Check https://github.com/laravel/horizon/pull/147
