### ISSUE TITLE
ForgetFailedCommand should have used uuid instead of id when forgetting a failed job

### ISSUE THREAD

**Issue by ocind** [laravel/horizon#1080]
- Horizon Version: 5.7.13
- Laravel Version: 8.6.2
- PHP Version: 7.4.23

### Description:
ForgetFailedCommand uses Job ID to be removed from horizon redis. However, when storing a failed job unto Redis, Horizon always uses UUID instead of ID. This causes the job to be successfully removed from the failed_job database table but not removed from Horizon.

To fix this, ForgetFailedCommand must be updated to remove the failed job from Redis using job UUID as key instead of job ID

### Steps To Reproduce:
1) Create a job which always fail
2) Trigger a job
3) Notice that a new entry is created in the failed_jobs table
4) Try "forgetting" that failed job by running `php artisan horizon:forget <job-id>` as explained in the [docs](https://laravel.com/docs/8.x/horizon#deleting-failed-jobs)
5) Job would be removed from failed_jobs database but running `HGETALL 'horizon:<job-uuid>' against redis shows that the job still remain in Redis.

**Comment by driesvints** [comment]
Thanks, let's see how your PR goes.
