### ISSUE TITLE
Horizon config will overwrite custom option of database config.

### ISSUE THREAD

**Issue by fish8536** [laravel/horizon#1087]
- Horizon Version: v5.7.6
- Laravel Version: v8.40.0
- PHP Version: 7.3.21
- Redis Driver & Version: predis/phpredis 5.2.2
- Database Driver & Version: mysql 5.7

### Description:

When we used redis and redis cluster, then set custom password in array `options` into Laravel config.
There is the problem that Laravel horizon will overwrite the config `options` when it set own prefix in options.

[laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php](https://github.com/laravel/framework/blob/e38ae60c197e01b300981932758b077bdab12946/src/Illuminate/Redis/Connectors/PhpRedisConnector.php#L28)
https://github.com/laravel/horizon/blob/640df7c65c464f83cda66781636d816a0992b0b1/src/Horizon.php#L107

### Steps To Reproduce:
Here is my config.

/config/database.php
```
'redis' => [
    'client' => 'phpredis',

    'Horizon' => [
        'host' => env('REDIS_HORIZON_HOST', '127.0.0.1'),
        'port' => env('REDIS_HORIZON_PORT', 6379),
        'database' => 1,
        'options' => [
            'password' => env('REDIS_HORIZON_PASSWORD', null),
        ],
    ],

    'options' => [
        'cluster' => 'redis',
        'password' => env('REDIS_CLUSTER_PASSWORD', null),
        'failover' => \RedisCluster::FAILOVER_DISTRIBUTE_SLAVES,
    ],

    'clusters' => [
        'hex_cluster' => [
            [
                'host' => env('REDIS_CLUSTER_HOST', '127.0.0.1'),
                'port' => env('REDIS_CLUSTER_PORT', 6379),
            ],
        ],
    ],
]
```

**Comment by mfn** [comment]
Indeed, because both are on the top level, it will overwrite them:
```
php -r 'var_dump(array_merge(["options"=>["password"=>"yolo"]], ["options" => ["prefix" => "horizon:"]]));'
array(1) {
  ["options"]=>
  array(1) {
    ["prefix"]=>
    string(8) "horizon:"
  }
}
```
The fix might be to use `array_merge_recursive`, see this:
```
php -r 'var_dump(array_merge_recursive(["options"=>["password"=>"yolo"]], ["options" => ["prefix" => "horizon:"]]));'
array(1) {
  ["options"]=>
  array(2) {
    ["password"]=>
    string(4) "yolo"
    ["prefix"]=>
    string(8) "horizon:"
  }
}
```

**Comment by fish8536** [comment]
I tried to use the way you provide but the same problem still happened. When I connected, I couldn't setting my password. Only horizon prefix setting in array options.
