### ISSUE TITLE
Can not delete monitored tag if it contains forward slash (/)

### ISSUE THREAD

**Issue by sgotre** [laravel/horizon#1093]
- Horizon Version: 5.7.15
- Laravel Version: 8.70.2
- PHP Version: 8.0.10 

### Description:

When monitoring a Tag which contains Slashes it is impossible to remove it again. 

### Steps To Reproduce:
- open Horizon Monitoring `/horizon/monitoring`
- click on `Monitor Tag` Button
- enter any string containing a slash. For example `123/123`
- delete the tag by clicking on the small delete icon
- the DELETE  Request responds with 405 Method not allowed because the route params is not recognized correctly

### Reason
Forward Slashes have to be allowed explicitly in route params:
- [Laravel docs about forward slashed in route params](https://laravel.com/docs/8.x/routing#parameters-encoded-forward-slashes ) 
- If you wonder why: [ see this discussion why encoded forward slashes are not allowed](https://github.com/laravel/framework/issues/22125))

### Suggested Solution

```php
    Route::delete('/monitoring/{tag}', 'MonitoringController@destroy')->name('horizon.monitoring-tag.destroy');
```

could be

```php
    Route::delete('/monitoring/{tag}', 'MonitoringController@destroy')
        ->name('horizon.monitoring-tag.destroy')
        ->where('tag', '.*');
```

I will submit a PR if you want.

Thank you for your time and effor!

**Comment by driesvints** [comment]
This indeed isn't possible right now. Feel free to attempt a PR if you want. Thanks
