### ISSUE TITLE
Horizon does not behave like basic queue workers with WithoutOverlapping middleware

### ISSUE THREAD

**Issue by melicerte** [laravel/horizon#1094]
- Horizon Version: 5.7.15
- Laravel Version: 8.69.0
- PHP Version: 7.4.20
- Redis Driver & Version: predis 1.1.7
- Database Driver & Version: MySQL 5.7

### Description:
The "Don't release" feature of the WithoutOverlapping middleware does not seem to work.

### Steps To Reproduce:

I execute every minute a job which takes 70 secondes to execute (arbitrary for test), and I set the WithoutOverlapping to not release the job in the queue.
I release the lock after 130 seconds.

Console/Kernel.php:
```php
$schedule
            ->job(new MaintenanceJob())
            ->everyMinute()
            ->timezone($timezoneServer);
```

App/Jobs/MaintenanceJob.php:
```php
class MaintenanceJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;
    use HasLogChannel;

    public function __construct()
    {
        $this->queue = 'maintenance';
    }

    public function middleware(): array
    {
        return [
            (new WithoutOverlapping())
            ->dontRelease()
            ->expireAfter(130)
        ];
    }

    public function handle(AgentPrintInstallerCleaner $agentPrintInstallerCleaner)
    {
        sleep(70);
    }
}
```

horizon.php:
```php
'defaults' => [
        'anytime-supervisor' => [
            'connection' => 'redis-long-running',
            'queue' => [
                'default',
                'maintenance'
            ],
            'balance' => 'simple',
            'maxProcesses' => 2,
            'minProcesses' => 2,
            'memory' => 512,
            'tries' => 3,
            'timeout' => 3600 // Timeout after 1 hour
        ],
```

When I execute `php artisan horizon`, the MaintenanceJob jobs continue to stack in the pending jobs list:
![Horizon_-_Pending_Jobs](https://user-images.githubusercontent.com/4137883/141787531-71ffc644-f5ac-45ed-9c1e-9f6b40ad265a.png)

If I execute the classic queue worker without Horizon, it does mark the job as executed but the handle function is not executed, which is the behaviour described in the Laravel Queue documentation.

So my understanding is that somehow, Horizon does not use the middleware. Am I Correct or do I miss a point here ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
