### ISSUE TITLE
Batch stuck and cannot find a way to remove it

### ISSUE THREAD

**Issue by marques-nb** [laravel/horizon#1098]
- Horizon Version: 5.7.15
- Laravel Version: 8.70.2
- PHP Version: 7.4.12
- Redis Driver & Version: phpredis 5.1.1
- Database Driver & Version: MySQL 5.7

### Description:
I launched a simple job that simply performs a `sleep(3)` 1000 times from a command, like this:

```php
        $jobs = [];
        for($i = 0; $i < 1000; $i++) {
            $jobs[] = new JustSleepJob();
        }

        Bus::batch($jobs)
            ->name('Jobs Test')
            ->dispatch();
```

And when I check horizon the batch doesn't seem to report properly or jobs don't run. This is the stuck batch:
![image](https://user-images.githubusercontent.com/88875635/144133566-5e61fa47-0eaf-48fc-8e78-7dac8179145d.png)

Metrics section shows an amount of 1000 jobs on throughput, I don't know if this has some relation.

This is my horizon config:
```php
'main' => [
                'connection' => 'redis',
                'queue' => ['high', 'default'],
                'balance' => 'auto',
                'processes' => 8,
                'minProcesses' => 2,
                'maxProcesses' => 8,
                'tries' => 3,
                'timeout' => 600,
                'maxTime' => 3600,
                'maxJobs' => 1000,
            ]
````

Other jobs are running at the time of writing, so it doesn't seem to be a problem on that side.

Searching about the problem I read some comment that suggest that `auto` balance could cause troubles, it's recommended to use `simple` when using batches?

And how could I remove that entry from batches list?

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
