### ISSUE TITLE
Excessive use of Redis databases

### ISSUE THREAD

**Issue by tillkruss** [laravel/horizon#11]
By default Horizon uses Redis databases `9`, `10`, `11`, `12`, `13`, `14`, `15` for jobs, supervisors, tags, metrics, locks, etc.

I'm sure it makes sense to avoid userland namespace conflicts, like `job:{id}`. 

Can Horizon be configured to only use one or two databases? Are there any drawbacks to that? Maybe all Horizon keys could be prefixed with `horizon:`?

I'm asking because a lot of Redis hosting providers only supply a single database `0`, some offer more in higher tiers, very few offer `16` out of the box.

**Comment by alexbowers** [comment]
Any chance you could link a few redis providers? Since redis itself offers 16 databases out of the box, i'd be surprised any provider didn't offer the same functionality

**Comment by stayallive** [comment]
Even when hosting it myself I would like to contain Horizon to a single redis db tbh.

**Comment by tillkruss** [comment]
@alexbowers:
- https://www.heroku.com/redis
- https://redislabs.com/products/redis-cloud/

**Comment by vigneshgurusamy** [comment]
@alexbowers Redis Cluster does not support multiple databases like the stand alone version of Redis.

**Comment by alexbowers** [comment]
Ah, I was not aware. In that case, support

**Comment by tillkruss** [comment]
Right, that's a good point:
>Redis Cluster does not support multiple databases like the stand alone version of Redis. There is just database 0 and the SELECT command is not allowed.

**Comment by themsaid** [comment]
Taken care of, Horizon now ises a single database and a prefix.

**Comment by themsaid** [comment]
Taken care of, Horizon now ises a single database and a prefix.
