### ISSUE TITLE
Completed/pending jobs page returns empty

### ISSUE THREAD

**Issue by 0xGabrielel** [laravel/horizon#1101]
- Horizon Version: v5.7.16
- Laravel Version: 8.74.0
- PHP Version: 8.0.13
- Redis Driver & Version: phpredis 5.3.4 - redis-server 6.0.6
- Database Driver & Version: Server: MariaDB 10.6.5 - mysqlnd 8.0.13 with pdo_mysql

### Description:

As written in the title, most of the time my completed jobs list page returns empty.
It randomly happens also to my pending jobs list.

Here's an example:

![image](https://user-images.githubusercontent.com/14280443/144761500-ce3540f5-5c70-44f2-965a-31d7fad3a426.png)

From the browser's network log:
`/horizon/api/jobs/completed?starting_at=-1&limit=50` returns:
![image](https://user-images.githubusercontent.com/14280443/144761481-6368e0e5-b9fb-4643-ae06-33f5b5df020b.png)

sometimes it returns something:
![image](https://user-images.githubusercontent.com/14280443/144762089-5a888888-a061-43c5-90fd-ab1ee1b2a674.png)
and it disappears at the next auto/refresh. It's definitely not working as it should.

My only guess is that it's somehow related to the number of jobs?
Everything is showing fine in the Dashboard page, numbers included.

### Additional information:

Works fine in local environment but I'm on different versions:
- Horizon Version: v5.7.15
- Laravel Version: 8.71.0
- PHP Version: 8.0.11
- Redis Driver & Version: phpredis 5.3.4 - redis-server 6.0.6
- Database Driver & Version: Server: MySQL 8.0.26-0ubuntu0.20.04.3

Also, please note that in local env I don't have so many completed jobs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by idrisalshikh** [comment]
did you figure out how to solve the issue, I have the same issue

**Comment by 0xGabrielel** [comment]
> did you figure out how to solve the issue, I have the same issue

Not yet @idrisalshikh. Just to be clear: are you using my same versions? (you can find them in the first lines of the issue)

If so, are you having the exact same issue? (API returns jobs number but not jobs list/array)

**Comment by Jon78** [comment]
Similar to #1035

**Comment by idrisalshikh** [comment]
> > did you figure out how to solve the issue, I have the same issue
> 
> Not yet @idrisalshikh. Just to be clear: are you using my same versions? (you can find them in the first lines of the issue)
> 
> If so, are you having the exact same issue? (API returns jobs number but not jobs list/array)

PHP 8.0.13
Laravel Framework 8.75.0
horizon version: v5.7.17

Yes, I have the same issue API returns jobs number but not jobs list/array

**Comment by idrisalshikh** [comment]
> Similar to #1035

I did not change any localization files, and I tried to set setlocale(LC_ALL, 'en_US.UTF-8') but that did not help

**Comment by Jon78** [comment]
The reason this issue is because I can see from this screenshot that at least the browser is not in English:

![image](https://user-images.githubusercontent.com/14280443/144762089-5a888888-a061-43c5-90fd-ab1ee1b2a674.png)

**Comment by idrisalshikh** [comment]
Hi @0xGabrielel  I tried many things to solve this but I think the issue for me was that I have two websites on the same server one is API the second one is admin and I want to do the queue processing in admin, not in the API so I installed Horizon in the Admin site only when I tried and installed Horizon in the API site as well, it works now, I was hoping that I would not need to download horizon in my API to keep it clean as possible if anybody can guide me on how I can do that I will appreciate it.

**Comment by Excelautomation** [comment]
I'm having this issue aswell?

It worked to begin with, but now all lists are just empty.

**Comment by dominik-eller** [comment]
The completed and pending jobs per default get _trimmed_ after one hour. You can change that behavior inside the horizon config file:

`'trim' => [
        'recent' => 60,
        'pending' => 60, // change here for pending jobs
        'completed' => 60, // change here for completed jobs
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],`
around line 100
