### ISSUE TITLE
Start one worker to handle several queues

### ISSUE THREAD

**Issue by melicerte** [laravel/horizon#1102]
Sometimes, we want to use different queues from a logical point of view, but do not want to launch a worker for each queue.

Let say I have a queue named "email" to handle emails to send, and another queue named "maintenance" to handle maintenance jobs.
I don't want to launch 2 workers for that since one worker will be enough to handle the jobs.

I'd like to be able to configure horizon to create one worker for the 2 queues.

My understanding is that how Horizon is designed, it is not possible to do so, but maybe I'm wrong.
If I'm right, it would be a great feature to facilitate the configuration.

**Comment by driesvints** [comment]
We have no plans for this, sorry.
