### ISSUE TITLE
Delete Failed jobs after X days

### ISSUE THREAD

**Issue by antonkomarev** [laravel/horizon#1104]
It will be great to have a console command which will delete failed jobs after X days passed, to run it in scheduler. Otherwise too many failed jobs may lead to out of memory errors.

App logs:
```
[2021-10-18 07:13:20] production.ERROR: Redis server 127.0.0.1:6379 went away {"exception":"[object] (RedisException(code: 0): Redis server 127.0.0.1:6379 went away at /www/app/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:402)
```
Redis logs:
```
15301:C 18 Oct 07:12:46.496 * DB saved on disk
15301:C 18 Oct 07:12:46.728 * RDB: 149 MB of memory used by copy-on-write
8927:M 18 Oct 07:12:47.108 * Background saving terminated with success
8927:M 18 Oct 07:13:48.008 * 10000 changes in 60 seconds. Saving...
8927:M 18 Oct 07:13:48.317 * Background saving started by pid 16294
```

Nobody will retry jobs failed 1 month ago, it may lead to consistency issues.

**Comment by antonkomarev** [comment]
Or TrimFailedJobs listener do this job?

**Comment by driesvints** [comment]
Hey @antonkomarev. We already have an option for deleting failed jobs: https://laravel.com/docs/8.x/queues#pruning-failed-jobs

Is this what you were looking for?

**Comment by antonkomarev** [comment]
If Horizon displays failed jobs from the main Laravel failed queue list - yes.

**Comment by driesvints** [comment]
I just realised that this is configurable by adjusting this setting: https://github.com/laravel/horizon/blob/5.x/config/horizon.php#L106

Does that work for you?

**Comment by antonkomarev** [comment]
Yes, it will be good to have it in documentation. Becasue I spent hours to find it.

**Comment by driesvints** [comment]
@antonkomarev we're welcoming PR's, thanks
