### ISSUE TITLE
Operation Now In Progress errors on Redis/MYSQL connections

### ISSUE THREAD

**Issue by ocind** [laravel/horizon#1107]
- Horizon Version: 5.7.12
- Laravel Version: 8.60.0
- PHP Version: 7.4
- Redis Driver & Version: predis 1.1.7
- Database Version: MYSQL 5.7

### Description:
We are processing around 100K jobs daily and most of them are working fine. However, we have been getting these errors pretty often since around 1 month ago

**Redis exception**
`Predis\Connection\ConnectionException: Operation now in progress`

**MYSQL PDO Exception**
`Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] Operation now in progress`

These errors occurred ONLY from horizon workers. But NEVER occurred from our Laravel Application.

It was usually occurring only once or twice in a day, but recently it was around 500 times in a day

I can't quite pinpoint the exact setup that would trigger the issue as this happens to only <1% of the number of jobs that we processed daily.

From what I have been reading it seems that this error occurred when the Redis/PDO connection is actually being used by some other process. I do not think that is possible since each horizon worker is a separate process and there should be no connection sharing between workers.

This unanswered stackoverflow thread is describing the exact [issue](https://stackoverflow.com/questions/59622411/pdoexception-sqlstatehy000-2002-operation-in-progress-on-php-artisan-queue) that I am having.

### Steps To Reproduce:
No exact step to reproduce

**Comment by driesvints** [comment]
I'm very sorry but this is an issue we can't help you with. This seems specific to your situation. Please continue to try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by ocind** [comment]
@driesvints I see. I understand that this might not be a framework issue... 

However, we can't seem to find useful answers after posting in the forums. And this issue happens intermittently (mostly when the Queue is on higher load). But we can confirm that this happens to `Horizon Workers only` and not in the Laravel App itself. 

Was hoping that you could give some pointer/advise to debug this problem further 🙏
