### ISSUE TITLE
The Mix manifest does not exist. (View: /var/www/vendor/laravel/horizon/resources/views/app.blade.php)

### ISSUE THREAD

**Issue by dzanfardino** [laravel/horizon#111]
When running Horizon on a non-dev environment

**Comment by wells** [comment]
@dzanfardino you'll want to publish the assets again (looking for a manifest.js file) and hard refresh the page.

```
php artisan vendor:publish --provider="Laravel\Horizon\HorizonServiceProvider"
```

**Comment by themsaid** [comment]
Yes re-publish the files and make sure the mix-manifest is correctly pushed to your server.

**Comment by acidjazz** [comment]
why is this closed? is this step documented somehwere I didn't find @themsaid ? should we at least put something elsewhere so installing horizon doesn't involve googling and finding this issue?

**Comment by wells** [comment]
@acidjazz 

It is in fact documented at https://laravel.com/docs/5.5/horizon#installation

**Comment by acidjazz** [comment]
thanks @wells i wonder if this could be run w/in composer.json or as a suggested command?

**Comment by browner12** [comment]
do people commit their `public/vendor` directory to Github? currently I have it ignored, and I usually include something in my front end build script to copy stuff in there.

**Comment by hotmeteor** [comment]
In case anyone is still struggling with this, I resolved the issue by adjusting my base `.gitignore` file to have
```
/vendor/
```
instead of
```
vendor/
```
The first option was causing my `public/vendor` folder to be ignored and not deployed.

**Comment by andrewmclagan** [comment]
Yes this should be noted on the vendor ignore path somewhere...
