### ISSUE TITLE
should we add public/vendor/* at .gitignore?

### ISSUE THREAD

**Issue by falahatiali** [laravel/horizon#1111]
- Horizon Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
sometimes when I use "php artisan horizon" commands it creates some files. 
for example: 
   app.js
   mix-manifest.json
what changes should we have in .gitignore?

**Comment by driesvints** [comment]
No they should be committed.
