### ISSUE TITLE
Delayed jobs was trimmed after reach trim pending time

### ISSUE THREAD

**Issue by pingwiniasty** [laravel/horizon#1114]
- Horizon Version: 5.8
- Laravel Version: 8.50
- PHP Version: 8.0.9
- Redis Driver & Version: phpredis 5.3.4

### Description:

Horizon trims delayed jobs, after reach trim pending time. 
Default trimming time is set to 60 minutes.

```php
 'trim' => [
        'recent' => 60,
        'pending' => 60,
        'completed' => 60,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],
```

So, when I add job, delayed by > 60 minutes, horizon delete it from queue.

In my opinion, delayed jobs must be trimmed after delay time + pending time

### Steps To Reproduce:

Add job delayed by more than pending trim time. We tested this with the trim pending time set to 5 minutes.

**Comment by driesvints** [comment]
This is intended. Horizon is intended to take over this behaviour.
