### ISSUE TITLE
Gate not working in production

### ISSUE THREAD

**Issue by SamuelWei** [laravel/horizon#1116]
- Horizon Version: 5.8.0
- Laravel Version: 8.79.0
- PHP Version: 8.0.14
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:

Using horizon in production is giving me a 403 error, just like other issues reported before (e.g. #1009) 

Looking into this issue I think I found the reason for it.
In https://github.com/laravel/horizon/blob/5.x/src/HorizonApplicationServiceProvider.php#L31
the Gate is checked with `Gate::check('viewHorizon', [$request->user()])`

However in the Laravel Docs https://laravel.com/docs/7.x/authorization#authorizing-actions-via-gates it explicity says: 

> Note that you are **not** required to pass the currently authenticated user to these methods.

The line instead should be one of the following options:

- `Gate::check('viewHorizon'`)
- ` Gate::forUser($request->user())->check('viewHorizon')`
- `$request->user()->can('viewHorizon') `

### Steps To Reproduce:

Set .env APP_ENV=production

app/Providers/HorizonServiceProvider.php
```php
/**
     * Configure the Horizon authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Horizon::auth(function ($request) {
            return app()->environment('local') ||
                Gate::check('viewHorizon', [$request->user()]);     // invalid
                //$request->user()->can('viewHorizon');                     // valid
                //Gate::check('viewHorizon');                               // valid    
                //Gate::forUser($request->user())->check('viewHorizon');    // valid
        });
    }


    /**
     * Register the Horizon gate.
     *
     * This gate determines who can access Horizon in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewHorizon', function ($user) {
            return true; // just an example
        });
    }
```

**Comment by SamuelWei** [comment]
Hi Dries,

I created a new repo just like you wrote, but I'm unable to reproduce the issue. 
In the project I'm dealing with the issue, I have a lot of other dependenices that might impact this.

I'll continue to look into the issue and try to find the reason for it. 

However could you explain to me why you are calling the Gate::check function with the user as an argument, even if this syntax is wrong acording to the laravel docs. 

Source: https://laravel.com/docs/7.x/authorization#authorizing-actions-via-gates
> Note that you are not required to pass the currently authenticated user to these methods. Laravel will automatically take care of passing the user into the gate Closure

Is laravel somehow detecting that the parameter is a user model and then somehow using the argument as the user of the gate.

Thanks for your help

Greetings,
Samuel

**Comment by driesvints** [comment]
@SamuelWei hmm it seems this indeed isn't needed. You're free to send in a PR if you like 👍
