### ISSUE TITLE
Horizon Commands are only available in console.

### ISSUE THREAD

**Issue by roshangautam** [laravel/horizon#112]
If you resolve Console/Kernel and call all() method on it from a web route, the list of commands returned do not include horizon commands. Found out that horizon command registration is wrapped inside runningInConsole() check.

```
        if ($this->app->runningInConsole()) {
            $this->commands([
                Console\AssetsCommand::class,
                Console\HorizonCommand::class,
                Console\ListCommand::class,
                Console\PurgeCommand::class,
                Console\PauseCommand::class,
                Console\ContinueCommand::class,
                Console\SnapshotCommand::class,
                Console\SupervisorCommand::class,
                Console\SupervisorsCommand::class,
                Console\TerminateCommand::class,
                Console\TimeoutCommand::class,
                Console\WorkCommand::class,
            ]);
        }
```

I understand these commands are not required to be registered in the container for HTTP requests but would it be possible to at least take the Console\SnapshotCommand::class out of the console check and make it available in app container for HTTP requests. This would help if you are scheduling commands using http requests.

**Comment by roshangautam** [comment]
@themsaid thoughts ?

**Comment by aik099** [comment]
Also these commands might not be accessible (haven't checked it in code), when you do `Artisan::call` from http route associated controller.

**Comment by aik099** [comment]
@roshangautam , command registration is done as in documentation. What I think can be improved is the `Container::runningInConsole` to return `true` when it's being used as part of Artisan workflow.

For example, when doing `Artisan::all()` in the web route controller, then same service provider is called twice:

* during web kernel boot
* during console kernel boot

This way at least during service provider boot inside Artisan we can patch `Container::runningInConsole` to return `true` to return true.

**Comment by themsaid** [comment]
Check https://github.com/laravel/horizon/pull/149

**Comment by roshangautam** [comment]
Thanks.
