### ISSUE TITLE
Can't rewind with Pagination

### ISSUE THREAD

**Issue by erickneverson** [laravel/horizon#1123]
- Horizon Version: 5.8.0
- Laravel Version: 8.40
- PHP Version: 7.4.3
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: No database

### Description:
I can navigate to the next results on the /failed page.  There are no results once I get to the page.  also, the previous button is removed.

### Steps To Reproduce:
Create a bunch of failures for multiple pages.  Navigate forward, then try to navigate backwards.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
