### ISSUE TITLE
Memory leak due to job duration recording

### ISSUE THREAD

**Issue by Namoshek** [laravel/horizon#1124]
- Horizon Version: latest

### Description:
I was wondering why our queue workers consumed more memory over time in a more or less linear way. So I did some code digging and came across the [`Stopwatch` class](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Stopwatch.php#L5). Besides being [registered as singleton via `$serviceBindings`](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/HorizonServiceProvider.php#L174), its [`start($key)` method is called for started jobs](https://github.com/laravel/horizon/blob/14b0a3cabb195540dc5c35cb98cb1d0fbdd0d848/src/Listeners/StartTimingJob.php#L36) and [`check($key)` for stopped jobs](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Listeners/UpdateJobMetrics.php#L50). But that's it - there is no code which removes entries from the `$timers` array.

### Steps To Reproduce:

Add some logging to [`Stopwatch::check($key)`](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Stopwatch.php#L31-L36) which counts the `$timers` to see them increasing (per queue worker):
```php
class Stopwatch
{
    public function check($key)
    {
        Log::debug('Stopwatch', ['count' => count($this->timers)]);

        if (isset($this->timers[$key])) {
            return round((microtime(true) - $this->timers[$key]) * 1000, 2);
        }
    }
}
```

> {"message":"Stopwatch","context":{"count":1},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.782784+01:00"}
> {"message":"Stopwatch","context":{"count":2},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.782784+01:00"}
> {"message":"Stopwatch","context":{"count":3},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.784126+01:00"}
> {"message":"Stopwatch","context":{"count":4},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.785836+01:00"}

### Why this Issue?

I'm wondering whether I overlooked something or if this really is a 5 year old bug (last changes to `Stopwatch` were in 2017).

Also are there many ways to solve this issue, e.g.:
- by removing the entry from `$timers` in `check($key)`,
- by removing the entry from `$times` with a separate method after calling `check($key)`,
- by using a single `$timer` in `Stopwatch` (why have multiple anyway?) or
- by resetting the `Stopwatch::$timers` in `Queue::looping($callback)` using a new `Stopwatch::reset()` method.

I'm happy to provide a PR if you let me know which fix is the desired one.

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.

**Comment by Namoshek** [comment]
@driesvints The issue is located in this library and has nothing to do with the versions of other application components. Please read the analysis and it will be clear. You can assume `latest` for everything, if you want.

**Comment by driesvints** [comment]
The issue template is there for a reason. Please fill it out.
