### ISSUE TITLE
Memory leak due to job duration recording

### ISSUE THREAD

**Issue by Namoshek** [laravel/horizon#1125]
- Horizon Version: `v5.9.1`
- Laravel Version: `v9.1.0`
- PHP Version: `8.0.16`
- Redis Driver & Version: `phpredis v5.3.6`
- Database Driver & Version: `sqlsrv v5.9.0`

### Description:
Using Horizon to monitor queue jobs causes a memory in the queue workers. The memory increases with the number of jobs being executed.

The [`Stopwatch` class](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Stopwatch.php#L5) is [registered as singleton via `$serviceBindings`](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/HorizonServiceProvider.php#L174), which causes a memory leak in its `$timers` array.
The [`start($key)` method is called for started jobs](https://github.com/laravel/horizon/blob/14b0a3cabb195540dc5c35cb98cb1d0fbdd0d848/src/Listeners/StartTimingJob.php#L36) and [`check($key)` for stopped jobs](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Listeners/UpdateJobMetrics.php#L50). There is no code which removes entries from the `$timers` array.

### Steps To Reproduce:

- Add some logging to [`Stopwatch::check($key)`](https://github.com/laravel/horizon/blob/ff534ce86fa27623d49da8a4272d3301b7998e6f/src/Stopwatch.php#L31-L36) which counts the `$timers` to see them increasing (per queue worker) or use some other tool to monitor the array (xdebug):
    ```php
    class Stopwatch
    {
        public function check($key)
        {
            Log::debug('Stopwatch', ['count' => count($this->timers)]);

            if (isset($this->timers[$key])) {
                return round((microtime(true) - $this->timers[$key]) * 1000, 2);
            }
        }
    }
    ```
- Run a few queue jobs (it doesn't matter what they do)
- See the `$timers` increasing:
    > {"message":"Stopwatch","context":{"count":1},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.782784+01:00"}
    > {"message":"Stopwatch","context":{"count":2},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.782784+01:00"}
    > {"message":"Stopwatch","context":{"count":3},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.784126+01:00"}
    > {"message":"Stopwatch","context":{"count":4},"level":100,"level_name":"DEBUG","datetime":"2022-02-20T11:14:37.785836+01:00"}

### Why this Issue?

I'm wondering whether I overlooked something or if this really is a 5 year old bug (last changes to `Stopwatch` were in 2017).

Also are there many ways to solve this issue, e.g.:
- by removing the entry from `$timers` in `check($key)`,
- by removing the entry from `$times` with a separate method after calling `check($key)`,
- by using a single `$timer` in `Stopwatch` (why have multiple anyway?) or
- by resetting the `Stopwatch::$timers` in `Queue::looping($callback)` using a new `Stopwatch::reset()` method.

I'm happy to provide a PR if you let me know which fix is the desired one.

**Comment by driesvints** [comment]
Hmm, I think you might be right here. I'm not 100% sure but I also think the timer probably need to be removed as soon as the job gets deleted.

The multiple timers are probably there because jobs can be handled simultaneously so there needs to be a way to store multiple ID's in memory. But I agree the ones that have been handled should probably be removed. So maybe a new `->clear($id)` method that's called at the end of the `handle` method of `UpdateJobMetrics`?

**Comment by Namoshek** [comment]
I think jobs are only handled simultaneously by the `sync` queue driver, right? I realized that also after writing the issue.

**Comment by driesvints** [comment]
Not sure but the `StartTimingJob` is handled immediately and depending on simultaneous jobs there could be some concurrency happening. Horizon is a long running process so I think clearing the timer for a job after updating the metrics makes sense.

**Comment by Namoshek** [comment]
I'm not a 100% sure, but from my understanding, Horizon is (besides the supervisors) a wrapper around the `queue:work` command. And a normal queue worker processes one job after another, i.e. sequentially. So each queue worker should have its own singleton instance of `Stopwatch`. In my opinion that is what can be observed in the logs, when adding above mentioned logger call and running more than one queue worker / Horizon worker.

But since a job can wrap other jobs using `Bus::dispatchSync($innerJob)`, there can be nested calls to the `Stopwatch`. Although, also in my opinion, not with _overlapping_ timers. Let's assume the timers were stopped for processed jobs, then they should  always be nested, not overlapping.

Anyway, I also think clearing the timers is the way to go. Ad-hoc I'm not sure handling a single event will cover all cases, but I will look into this later this day.

**Comment by taylorotwell** [comment]
@Namoshek feel free to make the PR that makes the most sense to you. Only one job can be running at a time since PHP is not multi-threaded, etc.

**Comment by Namoshek** [comment]
You are right, synchronously executed jobs are not recorded by `Stopwatch` because they do not use a queue connection with the `redis` driver. So there really only ever is one active job per worker.

Since I'm not sure what backwards compatibility is required for this code (it's public after all), I kept the array. If breaking changes are fine, I would actually swap the `$timers` for a single `$timer` and make it private.

**Comment by driesvints** [comment]
@Namoshek its probably best that you try a new pr if you think it can be improved. Taylor doesn't sees comments on closed prs.
