### ISSUE TITLE
Horizon dashboard does not work when using Content-Security-Policy headers without unsafe-eval

### ISSUE THREAD

**Issue by shibinphilip789** [laravel/horizon#1128]
- Horizon Version: 5.9.1
- Laravel Version: 8.40.0
- PHP Version: 7.4.27
- Redis Driver & Version: predis 1.1.10
- Database Driver & Version: MySQL 8.0.28

### Description:
Horizon dashboard does not work when using content security headers without unsafe-eval
Here is the error displayed in my console.

<img width="730" alt="Screenshot 2022-03-07 at 1 15 53 PM" src="https://user-images.githubusercontent.com/10956988/156990272-d55a01fd-af23-4ce6-a5c1-45b58624166a.png">

### Steps To Reproduce:
I'm using a package bepsvpt/secure-headers to add CSP to header.
unsafe-eval is set to false in config/secure-headers.php which does not add unsafe-eval to CSP.

![Screenshot 2022-03-07 at 1 13 07 PM](https://user-images.githubusercontent.com/10956988/156991205-859b6450-38b5-474c-b3c4-f81d35aa3c51.png)

Dashboard does work when unsafe-eval is set to true, But I cannot have unsafe-eval added to CSP for security reasons.

**Comment by driesvints** [comment]
I see the warning too but Horizon works for me without that package. Would appreciate any PR that solves this issue but for now it doesn't seems to be a blocker on default Horizon installations.
