### ISSUE TITLE
Uploading video to AWS

### ISSUE THREAD

**Issue by yovanoc** [laravel/horizon#113]
Hi, i'm currently near to deploy a big app with Laravel 5.5 but a little issue persist...

when I put QUEUE_DRIVER to sync, my uploading job works perfectly but when i put redis, for working with the 'art horizon' command, it tooks a while and after a lot of retries my job fail ...

this is my job : 

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Storage;
use File;

class UploadVideo implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $filename;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($filename)
    {
        $this->filename = $filename;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $file = storage_path() . '/uploads/' . $this->filename;
        if (Storage::disk('s3drop')->put($this->filename, fopen($file, 'r+'))) {
            File::delete($file);
        }
    }
}
```

Hope someone can tell me what's is going on thanks :/

**Comment by wells** [comment]
@yovanoc The default queue timeout is likely the cause of these failures. Given you are uploading large files, you will need either a really big timeout (hours) defined for this job or have some way to avoid timeouts altogether. I'm not sure you can define a null timeout for horizon jobs without the default taking over and being enforced.

**Comment by yovanoc** [comment]
Its small file but when i upgrade the timeout i have another error now : 

GuzzleHttp\Exception\ClientException: Client error: `POST https://s3-us-west-2.amazonaws.com/XXXXXXXX/159a9bfb9e2315.mp4?uploads` resulted in a `403 Forbidden` response:

XXXX replace my bucket ... I've created an IAM user with S3FullAccess, and in sync is it working i don't understand...

**Comment by themsaid** [comment]
This doesn't look like an issue with Horizon, `403 Forbidden` means an issue in your credentials, make sure the environment where the worker is running is correctly configured.

**Comment by yovanoc** [comment]
Is it working when I put QUEUE_DRIVER to sync but not with redis for Horizon ... what's the problem so?

**Comment by yovanoc** [comment]
I put retry after 2 hours, in queue config and in horizon waits config too, when i do the same job for a simple .png image its working, when i upload 45 sec videos files long isn't .... but when i put queue driver on SYNC, is working perfectly .... where can be the problem?

**Comment by neorganic** [comment]
Same problem here - my all jobs when used with horizon keeps failing and I don't know how could I increase the timeout e.g. to 3600 , the horizon documentation doesn't help on this part.

**Comment by neorganic** [comment]
Resolved. This helped - https://divinglaravel.com/horizon/before-the-dive  to find out where the max timeout can be set. We desperately need official documentation !
