### ISSUE TITLE
Horizon Dashboard not loading.

### ISSUE THREAD

**Issue by rossuhms** [laravel/horizon#114]
Hi Guys,

I'm experiencing problems with the Horizon Dashboard. The stats on the main dashboard page are not loading at all. I am running PHP **7.1.8** on Laravel Valet 2.0.5.

I've used the Network tab on Chrome DevTools and there seems to be a few ajax requests that are failing due to being returned a 500 error: [Screenshot of Chrome DevTools](https://i.imgur.com/fPLsN7F.png)

I have put the two different stacktraces into Gist's as they are too long to post in this issue apparently. [Gist 1](https://gist.github.com/rossuhms/14d16f767142658171a533ce87076648) - [Gist 2
](https://gist.github.com/rossuhms/b97455d46fa8ac34f6aab05fc99a4ac9)

Any help is appreciated. Thanks in advance.

**Comment by themsaid** [comment]
Make sure you're running on php +7.0 because these errors means that you're not :)

**Comment by rossuhms** [comment]
This is what I get when I run php -v & valet restart.

[Screenshot of iTerm](http://i.imgur.com/CrS4RI6.png)

**Comment by rossuhms** [comment]
Today I investigated this problem further locally and discovered that php-fpm was running php 7.0. I've sorted this and the dashboard works as expected. Thanks for your help.

**Comment by damiani** [comment]
I ran into the same issue, where I had some old 7.0 php-fpm processes still running, even while running php 7.1. Running `ps -ef | grep php-fpm` and killing each of the resulting 7.0 processes, then `valet restart`, fixed it for me.

**Comment by stevebeyatte** [comment]
I had to point redis at the IP defined in my Homestead file for Horizon to work, posting here in case that's helpful for anyone.
