### ISSUE TITLE
(Laravel 8) In StreamConnection.php line 246: stream_socket_enable_crypto(): SSL: Handshake timed out

### ISSUE THREAD

**Issue by Dishkan** [laravel/horizon#1144]
I faced unusual problem with my horizon and my jobs stopped working due to the error with ssl handshake time out. I restarted horizon and supervisor but the problem didn't disappear. I would be glad if someone solved this problem and can help me

- Horizon Version: ^5.7
- Laravel Version: 8.12
- PHP Version: 8
- Redis Driver & Version: predis
- Database Driver & Version: Mysql 8

my configs:

database.php
     'redis' => [
    
            'client' => env('REDIS_CLIENT', 'predis'),
    
            'options' => [
                'cluster' => env('REDIS_CLUSTER', 'redis'),
                'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_'),
            ],
    
            'default' => [
                'scheme' => 'tls',
                'url' => env('REDIS_URL'),
                'host' => env('REDIS_HOST', '127.0.0.1'),
                'password' => env('REDIS_PASSWORD', null),
                'port' => env('REDIS_PORT', '6379'),
                'database' => env('REDIS_DB', '1'),
            ],
    ## Heading ##

horizon.php

'environments' => [
    'production' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => [
                env('QUEUE_NAME', 'service_royxat'),
                'default',
            ],
            'balance' => 'auto',
            'processes' => 12,
            'tries' => 3,
            'timeout' => 60,
        ],
    ],

    'local' => [
        'supervisor-1' => [
            'maxProcesses' => 3,
        ],
    ],
],

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
