### ISSUE TITLE
Timeout when loading completed jobs

### ISSUE THREAD

**Issue by aerni** [laravel/horizon#1151]
### Versions
- Horizon Version: 5.9.7
- Laravel Version: 8.83.11
- PHP Version: 8.0.14
- Redis Driver & Version: phpredis 5.3.6
- Database Driver & Version: MySQL 8.0.29

### Description:
When I navigate to the Completed Jobs in the Horizon Dashboard it loads forever. Eventually, the browser stops responding. My server CPU and RAM go nuts and spike close to 100%. I have no idea how to debug this. I've had issues with long loading times in the past. I've got mostly big and long-running tasks. Wondering what might cause this. Maybe you've got an idea?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
