### ISSUE TITLE
Obsolete Jobs/Queues in Metrics

### ISSUE THREAD

**Issue by Cellard** [laravel/horizon#1152]
- Horizon Version: 5.9.7
- Laravel Version: 9.12.2
- PHP Version: 8.1
- Redis Driver & Version: predis 1.1.10
- Database Driver & Version:

### Description:

Metrics is showing jobs and queues, that were already removed or renamed.

### Steps To Reproduce:

1. Create and run a job
2. Rename job class and run it again

1. Define a queue, run a job through it
2. Rename queue and run a job again

In both cases old names remained in Horizon Metics panel. I hoped they will be removed after `metrics.trim_snapshots`  exceeded, but they wasn't.

**Comment by driesvints** [comment]
This is expected. The metrics show historical data. Renaming doesn't changes the data that was snapshotted.

**Comment by Cellard** [comment]
Is there a way to completely reset metrics?

**Comment by erickneverson** [comment]
I recognize this issue is closed, but am also curious about how to reset this particular metric.  Do we need to create some sort of custom command until one is provided by the framework?

Thanks

**Comment by trevorgehman** [comment]
I'm also wondering the same thing. Is there some kind of command to just completely wipe the Horizon metrics that are stored in Redis?

**Comment by trevorgehman** [comment]
Here's something I came up with to clear all Horizon metrics:

```php

use Laravel\Horizon\Repositories\RedisMetricsRepository;

$redis = resolve(RedisMetricsRepository::class)->connection();

$redis->del('measured_jobs');
$redis->del('measured_queues');
$redis->del('last_snapshot_at');

foreach($redis->keys('snapshot:*') as $key) {
  $redis->del(str($key)->after(config('horizon.prefix')));
}

foreach($redis->keys('metrics:*') as $key) {
  $redis->del(str($key)->after(config('horizon.prefix')));
}

**Comment by trevorgehman** [comment]
> Here's something I came up with to clear all Horizon metrics:
> 
> ```
> use Laravel\Horizon\Repositories\RedisMetricsRepository;
> 
> $redis = resolve(RedisMetricsRepository::class)->connection();
> 
> $redis->del('measured_jobs');
> $redis->del('measured_queues');
> $redis->del('last_snapshot_at');
> 
> foreach($redis->keys('snapshot:*') as $key) {
>   $redis->del(str($key)->after(config('horizon.prefix')));
> }
> 
> foreach($redis->keys('metrics:*') as $key) {
>   $redis->del(str($key)->after(config('horizon.prefix')));
> }
> ```

@driesvints Would you consider a PR for adding this command?

**Comment by driesvints** [comment]
@trevorgehman I think that could maybe be useful yeah. You could attempt a PR to see if Taylor also finds it useful, thanks.
