### ISSUE TITLE
Exclude certain jobs from Completed Jobs list

### ISSUE THREAD

**Issue by hailwood** [laravel/horizon#1153]
Right now Horizon displays all jobs that have completed in the `Completed Jobs` list.
This is great, unless you've got jobs running that you don't really care about - 

For example we use OhDearApp so if the job fails we'll know about it from OhDearApp notifying us.
The issue we run into is that it fires one job per scheduled task per execution - and this is drowning out the less often jobs we *do* care about.

It would be great if either in the horizon config we could have a way to say 'hide these jobs'
```php
'hide_completed_jobs' => [
    PingOhDearJob::class,
],
```
Or a closure based approach like (complete pseudocode)
```php
Horizon::filterJob(function(Job $job) {
   return $job->className !== PingOhDearJob::class || !$job->isComplete;
});
```
![horizon_jobs_completed](https://user-images.githubusercontent.com/709773/170377582-4f8b3c77-8c00-4cf4-9810-ed0e8f38fb8f.png)

**Comment by driesvints** [comment]
I like the idea here. Maybe the following config?

```php
'jobs' => [
    'exclude' => [
        PingOhDearJob::class,
    ],
],
```

I'll ping @taylorotwell to see if we can accept a PR for this.

**Comment by taylorotwell** [comment]
I'm fine with this if someone wants to make a PR. 👍

**Comment by driesvints** [comment]
Feel free to PR something 👍

**Comment by driesvints** [comment]
@hailwood I've started working on something here: https://github.com/laravel/horizon/pull/1230
