### ISSUE TITLE
How to stop endless polling when a request returns a 4XX

### ISSUE THREAD

**Issue by khamazaspyan** [laravel/horizon#1155]
- Horizon Version: 5.9.4
- Laravel Version: 9.6.0
- PHP Version: 8.1.4

### Description:
After session is expired in horizon dashboard there are endless polling witch returns 401 error.
It's possible to stop api calls after it's returns 4XX error or redirect to my login page ?

### Steps To Reproduce:
1. Add auth middleware in horizon config.
2. Login to horizon dashboard (jobs/completed page).
3. Delete session data.
Every 3 second it's making api call witch returns 401 error.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by SimonMacIntyre** [comment]
I have reproduced this as well.
