### ISSUE TITLE
Jobs hung up on Status pending and prevent Chain from being Processed

### ISSUE THREAD

**Issue by hmennen90** [laravel/horizon#1156]
- Horizon Version: 5.9.7
- Laravel Version: 9.16.0
- PHP Version: 8.1.5
- Redis Driver & Version: predis/phpredis predis, 2.0
- Database Driver & Version: MySQL 8

### Description:

I use chained and subjobs for processing Imports (in this case Shopware Categories, Customer Groups and Products).

Local everything is running perfect (MacOS Monterey). On Stage (Ubuntu 22.04 - PHP 8.1) the first Job is running, firing it's subjobs and then hung up on status pending, so the Chain and other Jobs are not processed.

I also tried using Batches etc but nothing works - except using Database Driver for Queue and php artisan queue:work.

My Jobs doesn't have timeouts.

### Steps To Reproduce:

- Use Shopware 5 Demo Shop for example
- First fetch All Categories
- Then Fetch every Category with it's id in a single Request (Parent Categories in Sync, Sub Categories in Queue)
- Define another Job as Chain
- The another Job will not be executed

If needed, i can share Screenshots / Code Examples of the used Jobs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
