### ISSUE TITLE
Monitor process statistics

### ISSUE THREAD

**Issue by fruitl00p** [laravel/horizon#1159]
We're running horizon with a larger number of smaller jobs that easily scale and thus we're looking for statistics around:

- process growth (and decline over time) how well do the runners scale up and down and when the max-amount is reached et al
- job runtimes (avg, median, max etc)
- last succesful runt per specific job (having many different jobs some running multiple times per minute and others once a week, the latter can get buried in the results)

These might all be trivial, but would improve horizon alot ;)

**Comment by driesvints** [comment]
Heya. Right now, we don't have plans for this. You can either try a PR or fork Horizon if you want. Thanks

**Comment by fruitl00p** [comment]
Too bad, but it is what it is... Let's see if we can find some time ;)
