### ISSUE TITLE
installation wtih php7.1 and laravel 5.4.*

### ISSUE THREAD

**Issue by mahdiahmadi73** [laravel/horizon#116]
hi .when i use this command : composer require laravel/horizon
i get this error : 

  Problem 1
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.0|remove laravel/framework v5.4.36
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - laravel/horizon v1.0.0 requires illuminate/support ~5.5 -> satisfiable by illuminate/support[v5.5.0].
    - Installation request for laravel/horizon ^1.0 -> satisfiable by laravel/horizon[v1.0.0].
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].ramework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].

what is going wrong and how can i fix that ?

**Comment by brunogaspar** [comment]
Horizon only works on Laravel 5.5.

**Comment by vonec** [comment]
https://packagist.org/packages/laravel/horizon#v0.1.0 is compatible with 5.4 give it a try

**Comment by Hemantkumawat** [comment]
I have Laravel v5.5 but not installing using cmd in windows 7 pc
