### ISSUE TITLE
Not showing jobs from an older batch than the previous one

### ISSUE THREAD

**Issue by MrHDOLEK** [laravel/horizon#1167]
- Horizon Version: 5.9.9 
- Laravel Version: 9.20.0 
- PHP Version: 8.1.5
- Redis Driver & Version: predis/phpredis 2.0
- Database Driver & Version:
   postgres:13
### Description:
Only the failed jobs for the last batch performed are displayed. If he wants to check a job that is older than the last batch, he gets an empty array on / horizon / api / jobs / failed / <id jobs>

**Comment by driesvints** [comment]
You may want to check in increasing the trimming time here: https://github.com/laravel/horizon/blob/5.x/config/horizon.php#L101
