### ISSUE TITLE
Laravel Horizon lost control on some keys, some jobs always pending and consume a lot of space

### ISSUE THREAD

**Issue by mravdel** [laravel/horizon#1168]
- Horizon Version: 5.9.9
- Laravel Version: 9.20.#
- PHP Version: 8.1.8
- Redis Driver & Version: predis/predis 1.1.10
- Database Driver & Version: 

### Description:
Redis crushed around 10 time for last 2-3 weeks. After every crash I noticed the memory consumption of Redis increasing, and never going below that. It used to be 2GB, then 4GB, now it's 7GB, even though the size of queue not really changing over time.

I used RANDOMKEY and inspect payload and I see there is 90% of jobs that is very old (2-3 weeks), was dispatched without delay and still pending. Looks like Horizon not aware of these jobs anymore and I believe they appeared after every Redis crushing.

I optimised them for future dispatching (store less info inside job).
"Problem" jobs usually dispatched in a batch (1000 jobs for example)

How to delete those "always pending" jobs?

I can't lower trim value for pending jobs because I have jobs (a little amount, but important) which is delayed for a long time in future

### Steps To Reproduce:
Using Laravel Horizon and just every once in a while crushing Redis with "out of memory" error.
Now upgraded up to 16GB server, so there is enough space.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DimaVIII** [comment]
@mravdel Check your horizon.php config.

Trim's are set in minutes. This the actual expire time (TTL) that is used by Redis for the expire key time.
I guess yours is not set or set way too high.

```
    /*
    |--------------------------------------------------------------------------
    | Job Trimming Times
    |--------------------------------------------------------------------------
    |
    | Here you can configure for how long (in minutes) you desire Horizon to
    | persist the recent and failed jobs. Typically, recent jobs are kept
    | for one hour while all failed jobs are stored for an entire week.
    |
    */

    'trim' => [
        'recent' => 1440,
        'pending' => 1440,
        'completed' => 4320,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],
```
