### ISSUE TITLE
Horizon should keep failed jobs into the database and keep it until job completed

### ISSUE THREAD

**Issue by tulsiramk** [laravel/horizon#1169]
Here, I found few thing needs to be added, 
1. First Horizon should save failed jobs into database and keep it until job completed, 
2. Second provide an option to edit data of failed job so that job will compete without any exception. 
3. Other one is horizon should keep logged in user information and create separate dashboard for each user, A user should not able to view jobs of another users

**Comment by driesvints** [comment]
Right now we don't have plans for this sorry.
