### ISSUE TITLE
LongWait notification specifies exact queue

### ISSUE THREAD

**Issue by jasonmccreary** [laravel/horizon#1171]
When specifying multiple queues for a process, the `LongWait` notifications must be configured using the queue names concatenated with a comma (`,`). While it made sense after the fact, my initial inclination was to specify the individual queue inline with the example (e.g. `connection:queue`).

More importantly, when receiving the notification, the queue uses the concatenated name. This doesn't immediately let me know which queue has the long wait. Ideally, the notification would specify the individual queue which has the long wait.

**Current behavior**

Example configuration:
```php
    'waits' => [
        // ...
        'redis:automation,subscriber,paid,workbench' => 1800,
    ],

    // ...

    'environments' => [
        'worker' => [
            'shifts' => [
                // ...
                'queue' => ['automation', 'subscriber', 'paid', 'workbench'],
                'balance' => false,
            ],
        ],
    ],
```

The notification states:

> The "automation,subscriber,paid,workbench" queue on the "redis" connection has a wait time of 62 seconds.

**Desired behavior**

Ideally you could configure the `waits` by the individual queue:
```php
    'waits' => [
        // ...
        'redis:automation' => 1800,
    ],

    // ...

    'environments' => [
        'worker' => [
            'shifts' => [
                // ...
                'queue' => ['automation', 'subscriber', 'paid', 'workbench'],
                'balance' => false,
            ],
        ],
    ],
```

And the notification would specify the wait time for the specific queue:

> The "automation" queue on the "redis" connection has a wait time of 1803 seconds.

---

If this is an acceptable change, I'm glad to help work on it as I already dug around the code a bit to better understand how to configure the `waits`.

**Comment by taylorotwell** [comment]
Hey @jasonmccreary - sure feel free to send something over for us to review if you have time.
