### ISSUE TITLE
Hanging task in pending section

### ISSUE THREAD

**Issue by webocoders** [laravel/horizon#1173]
- Horizon Version: 5.9.10
- Laravel Version: 9.24.0
- PHP Version: 8.1.8
- Redis Driver & Version: predis/phpredis 5.3.7
- Database Driver & Version:

### Description:

I found a stuck task
https://quwi.com/share/draw-screen/Mk63AzDYIT2mH8cfWtj4OJFKguGYdG5Y

I don't understand why he doesn't go to work. All similar tasks are normally processed. For example:
https://quwi.com/share/draw-screen/z64O92GkRvhnEDqJi-moWbgZ_VDeECyz

config/queue.php:
```        
'redis' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => env('REDIS_QUEUE', 'default'),
    'retry_after' => 90,
    'block_for' => null,
    'after_commit' => true,
],
```

config/horizon.php:
```        
        'default' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'simple',
            'maxProcesses' => 3,
            'maxTime' => 0,
            'maxJobs' => 0,
            'memory' => 128,
            'tries' => 1,
            'timeout' => 0,
            'nice' => 0,
        ],
```

What additional information should I provide to understand the reason?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by barryvdh** [comment]
Duplicate of https://github.com/laravel/horizon/issues/1015 https://github.com/laravel/horizon/issues/1060 https://github.com/laravel/horizon/issues/1034

Did you solve this?

**Comment by leo108** [comment]
@barryvdh A dirty workaround is adding a sleep at the very beginning of the job 
https://github.com/laravel/horizon/issues/1034#issuecomment-861142296

**Comment by henzeb** [comment]
I experienced something similar. Whenever this happens, I see this job in pending as well in completed. Same job, same id. It seems to me it doesn't get removed from the pending list. 

as we can see here, removing from pending_jobs is supposed to happen, but that doesn't happen always. 

https://github.com/laravel/horizon/blob/d9c39ce4e9050b33a2ff9d2cee21646a18d4cc92/src/Repositories/RedisJobRepository.php#L472
