### ISSUE TITLE
Horizon dashboard not being updated when Horizon runs on different server.

### ISSUE THREAD

**Issue by geocfu** [laravel/horizon#1176]
- Horizon Version: 5.9.10
- Laravel Version: 9.24.0
- PHP Version: 8.1.9
- Redis Driver & Version: predis 5.3.7
- Database Driver & Version: pdo pdo_pgsql pgsql

### Description:
I am using Docker to bundle my application into production. After many hours of searching on how to run scheduler and horizon on docker, I have understood that each service needs to be on a separate container. 

So I have 4 containers (without the databases). NGINX, FPM, Horizon and Scheduler. All the containers have the same codebase and all of them are under the same network. I am using supervisor for running the Horizon process and cron for the Scheduler. 

The odd behavior is that the Horizon dashboard is displaying that a supervisor is active, along with the number of running processes, but no stats are being displayed whatsoever. The job processing is working but the stats part is not, and i dont understand why.

I have set inside the horizon:snapshot command but still the same.

From the FPM container, I can verify that the horizon process (Horizon container) is running and the same goes for the Scheduler. `php artisan horizon:list` `php artisan schedule:list`

Here is the docker-compose file.

```docker-compose
version: '3'

services:
  fpm:
    build:
      context: .
      target: fpm_server
    restart: unless-stopped
    depends_on:
      - pgsql
      - redis

  nginx:
    build:
      context: .
      target: web_server
    restart: unless-stopped
    environment:
      FPM_HOST: 'fpm:9000'
    depends_on:
      - fpm

  scheduler:
    build:
      context: .
      target: scheduler
    restart: unless-stopped
    depends_on:
      - pgsql
      - redis

  horizon:
    build:
      context: .
      target: horizon
    restart: unless-stopped
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:13
    restart: unless-stopped
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - pgsql:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}"
        ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

networks:
  default:
    external:
      name: "my-app"

volumes:
  pgsql:
    driver: local
  redis:
    driver: local
```  

I know docker is out of scope, but the same can happen on metal servers when using the same Redis database.

Let me know if anything more is required to debug this issue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
