### ISSUE TITLE
Using `:` may cause issues related to information display in the Dashboard

### ISSUE THREAD

**Issue by ThaDaVos** [laravel/horizon#1177]
- Horizon Version: 5.9.10
- Laravel Version: 9.24.0 
- PHP Version: 8.0.21
- Redis Driver & Version: predis/phpredis phpredis
- Database Driver & Version: MySQL

### Description:
When one used certain characters, like `:`, in the name of a connection - the parsing on the following line goes wrong:
![image](https://user-images.githubusercontent.com/5251028/184636926-e3ac61e3-ebb9-4d02-8099-c866991019c3.png)
See: https://github.com/laravel/horizon/blob/8cbdf156dbbc146be5527d0c5fae185a3d31fff0/src/Repositories/RedisWorkloadRepository.php#L71

Looking at the code following it, this may cause issues down the line - I am not sure if the same logic is used somewhere else, but if it is, maybe it's better to leave a **note** about this in the docs? (Maybe extend the docs with some more information about the config values too?)

I also noticed, if you use a `|` in the connection name it seems to be ignored or something a like...

### Steps To Reproduce:
1. Create a new connection in `queue.php` with a name like `redis:long`
2. Add a extra queue worker which consumes jobs on the new `redis:long` connection and a seperate queue `{CONFIGURED_QUEUE}`, in my case this is `default:long`
3. Startup Horizon
4. See in the dashboard that it working on a queue named `long:{CONFIGURED_QUEUE}` instead of the expected `{CONFIGURED_QUEUE}` -> so `long:default:long`

One thing I noticed, even though it displays the wrong queue, it does handle the jobs on the expected queue - the display is just wrong

**Comment by driesvints** [comment]
These connection names should not contain these characters but rather just alpha characters. We'd appreciate a PR to the docs if you can.
