### ISSUE TITLE
Can't "pick up" a pending job from redis subscribe

### ISSUE THREAD

**Issue by deviddev** [laravel/horizon#1178]
- Horizon Version: 5.9.10
- Laravel Version: 9.24.0
- PHP Version: 8.1.7
- Redis Driver & Version: phpredis 5.3.7
- Database Driver & Version: mariadb 10.8.3

### Description:

I'm trying to dispatch _(broadcast)_ an event from artisan command that handle redis subscriber _(pub-sub)_.
The event was passed to horizon/queue _(redis)_ and its pending but never processed _(any other jobs or broadcast are processed)_.
If I dispatch that event "outside" from `Redis::subscribe` or in `Redis::subscribe` but with implemented **SholdBroadcastNow** interface its processed successfully.

![just-pending](https://user-images.githubusercontent.com/14124968/185400159-07b2c1c9-ecce-47db-94ac-a290f0b41b4c.png)

### Steps To Reproduce:

RedisSubscribeCommand.php

```
class RedisSubscribe extends Command
{

    protected $signature = 'redis:subscribe';
 
    protected $description = 'Subscribe to a Redis channel';
 
    public function handle()
    {
        Redis::subscribe(['test-channel'], function ($message) {
            broadcast(new RecognizeBusEvent('test'));
        });
    }
}
```

TestEvent.php

```
// when imeplement ShouldBroadcastNow it works
// with ShouldBroadcast also dispatched to queue, but it just pending
class RecognizeBusEvent implements ShouldBroadcast 
{
    use Dispatchable, InteractsWithSockets;

    public function __construct(
        public $message
    ) {
        //
    }

    public function broadcastOn()
    {
        return new Channel('test');
    }

    public function broadcastWith()
    {
        return [
            'message' => $this->message
        ];
    }
}
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
