### ISSUE TITLE
Dashboard - Exception context always null

### ISSUE THREAD

**Issue by mttzzz** [laravel/horizon#1179]
- Horizon Version: v5.10.0
- Laravel Version: 9.25.1
- PHP Version: 8.1.7
- Redis Driver & Version: predis/phpredis phpredis
- Database Driver & Version: mysql 8.0

### Description:
When  job fails (manualy or not) i always see at Exception context - null. I try this->fail($exception), but this is not work.
![image](https://user-images.githubusercontent.com/16290052/185872079-f0daecd6-20e5-4d61-a751-1ec4ad71d294.png)

How i can see my exception and my my exception context?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
