### ISSUE TITLE
Remove or Document `pending` jobs key from trim options 

### ISSUE THREAD

**Issue by alignwebs** [laravel/horizon#1181]
It seems to have confusion when dealing with delayed jobs and trim configuration. We did not find any documentation on the Laravel website regarding the trim option inside `config/horizon.php`. For us, it was removing the jobs scheduled for 1 week later and we had no idea why it was until we tried googling and looking out for the issues on Github.

**In my opinion, the `pending` key should be removed from trim options or properly documented on the website.**

https://github.com/laravel/horizon/blob/72be93e11c478bad152777f48191d2c68d5fca8f/config/horizon.php#L103

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍
