### ISSUE TITLE
Horizon subdomain is redirecting to the wrong address

### ISSUE THREAD

**Issue by hmaesta** [laravel/horizon#1183]
Not actually code related. 

The subdomain `horizon.laravel.com` is pointing to `laravel.com/docs/9.x` — but I believe it should be `laravel.com/docs/9.x/horizon` instead.

**Comment by driesvints** [comment]
Thanks. I don't think we use horizon.laravel.com anymore. Do you know where we still use that subdomain?

**Comment by hmaesta** [comment]
I needed to look for something in Horizon's docs, so I just followed the _Laravel's websites pattern_ and typed the URL 😅
