### ISSUE TITLE
completed_at is filled, but the status is pending

### ISSUE THREAD

**Issue by winter-ice** [laravel/horizon#1185]
- Horizon Version: 5.10.1
- Laravel Version: 9.30.1
- PHP Version: 8.1.7
- Redis Driver & Version:phpredis 5.3.7
- Database Driver & Version: MySQL 8.0

### Description:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/24680921/190868353-d5e78a15-dc8d-4cb6-90c2-4a8ec082876a.png">

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/24680921/190868399-1d70026a-1c4f-489f-847e-39938b2f124c.png">

### Steps To Reproduce:

I don't know how to reproduce, is it normal?
The jobs is stuck at pending jobs tab, but the completed_at if filled.

**Comment by driesvints** [comment]
This seems to be different records? The ID's don't match.

**Comment by winter-ice** [comment]
Just an example, these 2 image doesn't has relation
You can only see the one of them, it is strange

**Comment by winter-ice** [comment]
@driesvints Why you close the issue so fast?
And not wait for a response from the originator?

**Comment by driesvints** [comment]
Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by winter-ice** [comment]
> 

I think this is a bug
