### ISSUE TITLE
The pendding Job can not excued

### ISSUE THREAD

**Issue by gakkiismywife** [laravel/horizon#1186]
- Horizon Version:5.0
- Laravel Version: 8.0
- PHP Version: 7.34
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
Verytime product 20 jobs but the  just exec 3 jobs.Ahe other jobs were pending.
And the job was fast,not spend too much time.

### Steps To Reproduce:
```
          'warning' => [
                'processes' => 40,
                'maxProcesses' => 30,
                'minProcesses' => 10,
                'connection' => 'redis',
                'queue' => [
                    'warning-post',
                    'warning-topic',
                ],
                'memory' => 256,
                'timeout' => 300,
                'tries' => 1,
                'balance' => 'auto',
            ],
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
