### ISSUE TITLE
Can this monitor other projects?

### ISSUE THREAD

**Issue by seekcx** [laravel/horizon#119]
I have a restful project, i do not want to be embedded directly inside horizon, can it stand out and then configure it to a new project?

**Comment by themsaid** [comment]
sorry but I don't understand what you want

**Comment by aglipanci** [comment]
@themsaid I think what @seekcx is trying to say is that he has a RESTful app and he wants to have horizon installed on another Laravel instance which is not the one used for API requests.

@seekcx I think it can work only the other project has all the models as your original app and connects to the same db, but I am not 100% sure.

**Comment by seekcx** [comment]
@aglipanci thank you very much. I am very poor in English, these are using google translation. I do not want it to be too invading the original project, I consider using an independent branch to monitor the current project.

**Comment by themsaid** [comment]
Sorry I still don't understand :) Please try to explain in more details what you mean.

**Comment by seekcx** [comment]
I have an api project and a backend project. I would like to be able to monitor the api queue execution in the backend. 

Sorry, I do not know if you can understand this.

**Comment by danieluyo** [comment]
¿Do you mean use Horizon like SAAS? If you say yes... well... I don't think so because Horizon communicate with your Laravel providers, controllers and configuration... ¿That's right @themsaid ?

**Comment by themsaid** [comment]
theoretically if you point horizon to a redis server it should read its metrics.
