### ISSUE TITLE
payload / data content not necessary in table view

### ISSUE THREAD

**Issue by avivsalman** [laravel/horizon#1192]
- Horizon Version: 5.10.2
- Laravel Version: 8
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis 9.9.9
- Database Driver & Version:

### Description:
Payload / Data content not necessary in table view, for example when i am routes to /horizon/jobs/pending in dashboard and got the first 50 jobs, when the payload size is 200kb the request size will be 10Mb, you need the payload data only when routes to specific job.

### Steps To Reproduce:
Go to dashboard to pending jobs and get the first 50 jobs that each one size is 200kb, this should be solved in pending, compleated, failed api endpoints.

**Comment by driesvints** [comment]
We could maybe optimize this. Feel free to attempt a PR if you like.
