### ISSUE TITLE
timeout config not working with horizon

### ISSUE THREAD

**Issue by sunil-panthercodx** [laravel/horizon#1194]
Hello
First of all thanks for this awesome package.

I have an issue with the `timeout` config.

I want to kill the job after a certain time so I set the `timeout => 5` in the horizon configuration file. And I have set sleep for 10 seconds in the job. Tries set to 3 so the expected behavior should be to terminate the job after 5 seconds and retry it but in my case, it is not working.

When I tried the timeout with `php artisan queue:work --timeout=5` then it works perfectly. So I think the issue might be with my configuration.
I also tried overriding the timeout property in the Job file.

Here are my configuration files:
`config/queue.php`
```
'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 0,
            'block_for' => null,
            'after_commit' => false,
        ],
```

`config/horizon.php`

```
'environments' => [
    'local' => [
        'supervisor-default' => [
            'connection' => 'redis',
            'queue' => ['high','medium','default'],
            'maxProcesses' => 2,
            'balanceMaxShift' => 1,
            'balanceCooldown' => 3,
            'tries' => 3,
            'timeout' => 5
        ],
    ],
],
```

Job File

```
<?php

namespace App\Jobs;

use App\Exceptions\UnprocessableException;
use Exception;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    // public $timeout = 5;
    
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        try{
            info('TestJob Run');
            sleep(10);
            info("Job Run Successfully");
        }catch(\Throwable $th){
            info("Job Failed",[$th->getMessage()]);
            $this->fail($th);
        }
    }
}
```

I go through many blogs, docs, and GitHub issues but didn't find any solution.
Any guide please,
@themsaid @driesvints 
Thank You.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
