### ISSUE TITLE
Provide a means to disable the Horizon front-end/routes independent of Horizon itself

### ISSUE THREAD

**Issue by 6XGate** [laravel/horizon#1197]
In our environment, we don't want Horizon to expose its user interface in certain environments/`APP_ENV` roles. We prefer it only be available locally or from the main web server environment, but not in our queue runners that are supervised by Horizon or other servers not serving our SPA..

It would be great if we could control route registration by either:
- Using a closure; for example: `Horizon::registerRoutes(fn () => $this->app->environment(['local', 'production']))`
- Using a simple boolean; for example: `Horizon::registerRoutes($this->app->environment(['local', 'production']))`
- Using a variable in `.env`
- Or all of the above

**Comment by driesvints** [comment]
There's already a few dashboard authorization strategies you can apply. I'm not sure we need other ways beside those? https://laravel.com/docs/9.x/horizon#dashboard-authorization

**Comment by 6XGate** [comment]
This still exposes route we don't want in a specific server role.

**Comment by driesvints** [comment]
@6XGate I understand. Feel free to attempt a PR if you like 👍
