### ISSUE TITLE
Completed Jobs, CSS table bug

### ISSUE THREAD

**Issue by george-martinec** [laravel/horizon#1201]
- Horizon Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Steps To Reproduce:

CompletedJobs table overflow, CSS bug

![Screenshot from 2022-10-25 10-03-31](https://user-images.githubusercontent.com/87377447/197718101-ec9efeab-9e42-4ba3-9f7d-98c148d5f4ae.png)

**Comment by driesvints** [comment]
Please do not ignore the issue template

**Comment by driesvints** [comment]
Honestly I don't see a huge issue here as I don't think it's reasonable to assume there's jobs which such long names. We'd appreciate a PR however if you'd like to see this resolved.
