### ISSUE TITLE
Missing support for PHP 8.1 Enums when viewing data

### ISSUE THREAD

**Issue by Cbrad24** [laravel/horizon#1207]
- Horizon Version: v5.10.3
- Laravel Version: v9.38.0
- PHP Version: v8.1.12
- Redis Driver & Version: PHP Redis Extension v5.3.7
- Database Driver & Version: psql

### Description:
[phpUnserialize v1.2](https://github.com/bd808/php-unserialize-js/releases/tag/v1.2.0) adds support for PHP 8.1 Enums. According to the [package-lock.json](https://github.com/laravel/horizon/blob/8d4b50585c661f4be48ffb6aeec1454c58500b1a/package-lock.json#L15179-L15184) file, the assets are built using phpUnserialize v1.0.1.

According to the prettyPrintJob function defined in [/resources/js/screens/recentJobs/job.vue#L162-L172](https://github.com/laravel/horizon/blob/8d4b50585c661f4be48ffb6aeec1454c58500b1a/resources/js/screens/recentJobs/job.vue#L162-L172), if un-serialization fails, it will not show the data as un-serialized.

### Steps To Reproduce:

- Create a job with a enum or object that contains an enum in it's properties.
- View the job in Horizon

**Bad output containing enum:**
![image](https://user-images.githubusercontent.com/2669153/199883832-f963aafe-e7fa-48d8-842d-8679b65ef500.png)

**Verses a job without an Enum:**
![image](https://user-images.githubusercontent.com/2669153/199883607-28935667-f22d-433f-b238-9ec0e60451eb.png)

### Resolution:
In a couple of days I will try to submit a PR however I'm a bit short on time until then so if someone wants to try bump the NPM package dependencies and test before I get the chance then it would be appreciated as I've never worked with packages so it might take me a little time to figure it all out.

**Comment by driesvints** [comment]
Thanks, we'd greatly appreciate a PR for this!
