### ISSUE TITLE
Add ability to start specific horizon supervisor.

### ISSUE THREAD

**Issue by qiulang** [laravel/horizon#1208]
As https://laravel.com/docs/9.x/horizon#running-horizon says I can  pause and continue specific Horizon supervisors using the `horizon:pause-supervisor` and `horizon:continue-supervisor`

But I can not start just specific Horizon supervisors currently.  If this is because the Master Supervisor can we just start master & the specific supervisors I provide ?

Thanks.

**Comment by driesvints** [comment]
I'm not sure starting specific supervisors makes sense? Horizon is indeed meant as an all-encompassing process to run all supervisors at once. Starting them individually would defeat the purpose of Horizon.

**Comment by qiulang** [comment]
In my case I want to let some worker docker instances just consume some specific queue while other workers run general works, basically to off-load heavy work to some specific worker docker instances. If horizon can support this it will be a lot easier for my home-made solution.

Besides, I can feel a bit "weird" that I can pause/resume specific Horizon supervisors, but I can not start them individually

**Comment by driesvints** [comment]
@qiulang feel free to attempt a PR if you want 👍
