### ISSUE TITLE
How to use horizon with lumen?

### ISSUE THREAD

**Issue by ibrunotome** [laravel/horizon#121]
How to use horizon to manage queues in a current project written with lumen? I will have to make a  laravel project and point the redis server port to the lumen server?

**Comment by boscowitch** [comment]
So will there be no Lumen support ? I tried to hack it in there but its missing to much:
config_path() //easily fixable in bootstrap/app.php
Call to undefined method Laravel\Lumen\Application::routesAreCached()  //also relatively easy to fix by commenting out the if call in the support librarie used
Call to undefined method Laravel\Lumen\Routing\Router::prefix()
....

At the last one i stopped since it seemed not to end...

**Comment by ibrunotome** [comment]
Hi, i just migrated all the project to Laravel, it's really easy (about one~two hours of work). Can't live more without horizon :)

**Comment by servocoder** [comment]
My adaptation of Horizon for Lumen. Tested with Lumen 5.5

https://github.com/servocoder/lumen-horizon

https://packagist.org/packages/servocoder/lumen-horizon

**Comment by ibrunotome** [comment]
Hi @servocoder , taking advantage of your goodwill, can you help with that? 

https://github.com/laravel/horizon/issues/263

My solution now it's call the fail and delete method every time the jobs fail, but i'm sure that there is a way to execute job only once, without call manually fail and delete methods.

**Comment by jfoliveira** [comment]
@taylorotwell @themsaid please help me solve the following puzzle:
Question:
* is Lumen going to be discontinued?

Assertions that lead to that question:
* Horizon process queues
* Queues are generally used for speeding up performance and process long running tasks in the background
* Performance is a common concern when building/deploying APIs and micro-services
* Lumen is intended to be used to implement `Stunningly fast APIs and micro-services`
* Horizon brings tools and visibility to help manage queues
* Horizon does not support Lumen - the `Stunningly fast micro-framework` - that is intended for usage to build high traffic APIs/micro-services - where even 10% increase in performance over Laravel really matters

**Comment by jfoliveira** [comment]
Hey @driesvints,
I've noticed that Horizon 2.1.0.
Is Lumen support completely discarded by Laravel team? :-(
Any recommended workaround for using Horizon with Lumen?

**Comment by xtrasmal** [comment]
Hello @jfoliveira,

Horizon and Telescope both have an API, so you could have a logger in Lumen that connects to the instances that have Horizon/Telescope running.

**Comment by raydvard** [comment]
Can I use Laravel Horizon like this >
- In my project, queue works with Lumen + Redis on a server
- Laravel Horizon running on another server
- Now connect that Laravel Horizon to the Redis on my project server

If so, is there any example or suggestions to achieve that?
