### ISSUE TITLE
Feature Request: Integrate `spatie/laravel-horizon-watcher` 

### ISSUE THREAD

**Issue by aneesdev** [laravel/horizon#1215]
Hi everyone.

Spatie recently released a nice package: https://github.com/spatie/laravel-horizon-watcher. which provides a command `horizon:watch` to watch for PHP file changes and auto restart horizon daemon. It requires https://github.com/paulmillr/chokidar to work.

How about can we integrate the package into horizon core? If possible. should we integrate the package itself (in composer.json) or take the code from there and put into the core?

What do you guys think?

@driesvints

**Comment by driesvints** [comment]
We usually don't include third party libraries like this, sorry.
