### ISSUE TITLE
Horizon don't start executing queued jobs

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/horizon#1217]
- Horizon Version: 5.10.4
- Laravel Version: 9.39.0
- PHP Version: 8.1.11
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
Horizon start in half. Jobs are added to queues. Jobs never executed. Horizon dashboard don't show queues list, what we can see in normal scenario.
1. Please add some warning after starting horizon from CLI, that configuration is mismatched.
2. Please add warning on horizon dashboard after it failed started.

### Steps To Reproduce:
1. Create .env file with APP_ENV value that don't exists in confilg/horizon.php file in keys from environments key.

Example
`.env` file"
```env
//
APP_ENV=prd
//
```
confilg/horizon.php file:
```php
//
    'environments' => [
        'prod' => [
            //
        ]
    ]
//
```
So environment form `.env` file don't mach with key in environments in horizon config file.

**Comment by driesvints** [comment]
This surely is a bug in your code? The issue is your incorrect app env value.

**Comment by LocalHeroPro** [comment]
Please write it loudly: you don't want to make small changes to improve code and usability for all users.
Yep, it's true.

**Comment by sketchtechnologies1** [comment]
@driesvints I'm facing the similar issue, jobs are being processed fine and sometimes horizon just refuses to pick the jobs and they stay pending forever no error in logs.

@LocalHeroPro I feel him, you just closed this issue and some previous similar issues without any resolution.

**Comment by LocalHeroPro** [comment]
I did not close this issue.
