### ISSUE TITLE
Queue blocked for 1 minute every X jobs

### ISSUE THREAD

**Issue by MartinRdw** [laravel/horizon#1219]
- Horizon Version: 5.7.9
- Laravel Version: 8.83.7
- PHP Version: 8.1.9
- Redis Driver & Version: predis/phpredis 6.2.6
- Database Driver & Version: MySql 8.0.31

### Description:

We have a strange behavior on our queues. On the horizon Dashboard we observe when we send several thousand jobs at once that the queue pauses every X jobs completed. The pause lasts 1 minute and during this time nothing happens, the queue is stuck.

Is this a known behavior?

horizon.php :

```
'defaults' => [
        'supervisor-default' => [
            'connection' => 'redis',
            'queue' => [
                'default'
            ],
            'balance' => 'auto',
            'maxProcesses' => 10,
            'minProcesses' => 3,
            'memory' => 128,
            'tries' => 1,
            'nice' => 0,
            'timeout' => 60 * 60 * 3
        ],
],

'environments' => [
        'production' => [
            'supervisor-default' => [
                'maxProcesses' => 10,
                'minProcesses' => 3,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
                'timeout' => 60 * 60 * 3
            ]
],
```

### Steps To Reproduce:

In our case we juste have to add more than 1000 jobs at once in a queue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
