### ISSUE TITLE
how do you clear failed jobs?

### ISSUE THREAD

**Issue by vesper8** [laravel/horizon#122]
I know that artisan cache:clear does the trick currently but that clears everything and if you're using a different redis for cache as recommended then that won't work

but isn't there another way? I thought I could just do pa queue:flush but it seems that now that we have horizon we can't use the queue commands to list failed jobs or flush them

it would be nice if some controls were added to the web interface to perform these tasks too

**Comment by themsaid** [comment]
Failed jobs are cleared every 7 days automatically.

**Comment by neorganic** [comment]
I agree that it would be nice to have a feature to remove a single failed job - via a button "remove" e.g.

**Comment by jasperf** [comment]
I am using redis for queues and `artisan queue:flush` works for mysql table only it seems and redis is not supported as a database.. So I am confused how I am supposed to remove queues from redis.

**Comment by dimsav** [comment]
@jasperf you can use the horizon dashboard, just open the "failed" tab on the left.

**Comment by jasperf** [comment]
@dimsav I can open that tab and see the failed jobs. I can retry them, but I cannot remove them.. 

![screen shot 2018-07-31 at 1 44 52 pm](https://user-images.githubusercontent.com/344138/43442367-ece2310e-94c7-11e8-8bf1-149b8b628873.png)

**Comment by stefblokdijk** [comment]
The easiest way for me was to delete these redis keys in an Redis GUI (or CLI) like Medis.

- `horizon:failed_jobs` will remove the list of failed jobs
- `horizon:failed:JOBNAME` every failed job has a key like this 

I manually deleted the `horizon:failed_jobs` key.
Then I deleted all the other failed jobs with this Redis CLI command. (source: [stackoverflow](https://stackoverflow.com/questions/4006324/how-to-atomically-delete-keys-matching-a-pattern-using-redis))
```
EVAL "return redis.call('del', unpack(redis.call('keys', ARGV[1])))" 0 horizon:failed:*
```

I really hope there will be a simple artisan command line for this.

**Comment by kharysharpe** [comment]
Hope this is helpful, you can create a command and execute:


```php
    public function handle()
    {
        Redis::connection()->del('horizon:failed:*'); 
        Redis::connection()->del('horizon:failed_jobs');
    }
```

Would be great if this came builtin

**Comment by Vercoutere** [comment]
I agree that it would be beneficial to allow the deletion of failed jobs.
Sometimes a failed job doesn't need retrying after it has been handled internally, and it's preferable to remove it from the list of failed jobs for clarity.

**Comment by robtesch** [comment]
Extending @kharysharpe's answer a bit, the below snippet will also respect your horizon config's custom prefix (if you have one).

`
Redis::connection()->del([config('horizon.prefix').'failed:*']);
Redis::connection()->del([config('horizon.prefix').'failed_jobs']);
`

I've wrapped all this up into an artisan command "horizon:flush" which calls the queue:flush first:

`
    public function handle()
    {
        $this->call('queue:flush');
        Redis::connection()
             ->del([config('horizon.prefix').'failed:*']);
        $this->info('each individual failed job flushed');
        Redis::connection()
             ->del([config('horizon.prefix').'failed_jobs']);
        $this->info('failed_jobs flushed');
    }
`

**Comment by mikeburton220** [comment]
> Hope this is helpful, you can create a command and execute:
> 
> ```
>     public function handle()
>     {
>         Redis::connection()->del('horizon:failed:*'); 
>         Redis::connection()->del('horizon:failed_jobs');
>     }
> ```
> 
> Would be great if this came builtin

I used tinker to run these lines. Works!

**Comment by jasperf** [comment]
@mikeburton220 @kharysharpe mentioned this function earlier on. Using tinker is a quick way to use it though. Do not think it is built in yet, but it can be done this way and or added as another job. Thanks for the feedback!

**Comment by ryancwalsh** [comment]
I appreciated the tips from @kharysharpe and @robtesch and adapted it to:

    public function handle() {
        $this->info('Calling queue:flush ...');
        $this->call('queue:flush');
        foreach ([config('horizon.prefix') . 'failed:*', config('horizon.prefix') . 'failed_jobs'] as $delCommand) {
            $this->info('In Redis, calling `del` with: ' . $delCommand);
            Redis::connection()->del([$delCommand]);//Remember to call `use Illuminate\Support\Facades\Redis;` above.
        }
        $this->info('Deleted each individual failed job from Horizon and deleted failed_jobs from Horizon.');
    }

But I found myself in a weird situation (presumably unrelated to those commands) where I still saw a lot of failed jobs on the webpage at /horizon/failed and a lot of old keys in Redis, but they did not have "failed" in their key names.

It was bizarre.

I then ended up deleting all of them by running `redis-cli --scan --pattern myPrefixHere_horizon:* | xargs redis-cli del` (from https://rdbtools.com/blog/redis-delete-keys-matching-pattern-using-scan/).

Now finally the webpage at /horizon/failed says "There aren't any failed jobs."

**Comment by fgilio** [comment]
> ...
> But I found myself in a weird situation (presumably unrelated to those commands) where I still saw a lot of failed jobs on the webpage at /horizon/failed and a lot of old keys in Redis, but they did not have "failed" in their key names.
> 
> It was bizarre.
> 
> I then ended up deleting all of them by running `redis-cli --scan --pattern myPrefixHere_horizon:* | xargs redis-cli del` (from https://rdbtools.com/blog/redis-delete-keys-matching-pattern-using-scan/).
> 
> Now finally the webpage at /horizon/failed says "There aren't any failed jobs."

Same thing happened to me, but I cannot just delete all keys. Does anyone know if this is something to be expected?

**Comment by preeteshjain** [comment]
This issue is kind of frustrating. Here's what I've done to flush Redis with a simple command:

Create a new command:

```shell
php artisan make:command FlushRedis --command=flush:redis
```

Add this `use` statement to your command:

```php
use Illuminate\Support\Facades\Redis;
```

_Note: If you add `use Redis;` on the command file, it will lead to errors, because it can't be called statically._

Now in the `handle()` method of this command, add this line:

```php
Redis::command('flushdb');
```

Register this command in `App\Console\Kernel.php`:

```php
protected $commands = [
    ...
    '\App\Console\Commands\FlushRedis',
];
```

### All done!

Now you can simply run this command in the future to clear all the jobs from Redis (and Horizon):

```
php artisan flush:redis
```

This should be the output:

![image](https://user-images.githubusercontent.com/6207830/91296259-f5fa2980-e7b9-11ea-95fa-36c641e14176.png)

**Comment by MarGul** [comment]
> > Hope this is helpful, you can create a command and execute:
> > ```
> >     public function handle()
> >     {
> >         Redis::connection()->del('horizon:failed:*'); 
> >         Redis::connection()->del('horizon:failed_jobs');
> >     }
> > ```
> > 
> > 
> > Would be great if this came builtin
> 
> I used tinker to run these lines. Works!

Don't forget to use the full namespace like `\Illuminate\Support\Facades\Redis::connection()->del('...');` or import it if using tinker.

**Comment by ibnIrshad** [comment]
I ended up making a bash shell script to execute `horizon:forget` on each failed job, not just remove the keys from Redis. Because you want to remove it gracefully, as the key is stored in multiple places in Redis, not just in the failed_jobs set.

```sh
echo -e  "SELECT 2\nZREVRANGE fintable_horizon:failed_jobs 0 -1" | redis-cli | tail -n +2 | xargs -L 1 -t php artisan horizon:forget
```

Note "fintable_horizon" is my prefix and "2" is my Redis database where horizon meta info is stored. Change those two variables.

**Comment by iKlsR** [comment]
Can we take another look at this? @preeteshjain's solution works.

**Comment by alielmajdaoui** [comment]
This is now supported in Horizon 5.

Simply, grab the job id from the `failed_jobs` table and execute this artisan command:

```shell
php artisan horizon:forget JOB_ID
```

It will delete it from MySQL/Postgres`failed_jobs` table, as well as Redis `PREFIX_horizon:failed_jobs` zset.

Docs: https://laravel.com/docs/8.x/horizon#deleting-failed-jobs

**Comment by marianvlad** [comment]
Based on Horizon source code, I set the trim config to 1 minute instead 7 days and run the code like [here](https://github.com/laravel/horizon/blob/5.x/src/Repositories/RedisJobRepository.php#L557)

```php
use Laravel\Horizon\Contracts\JobRepository;

config(['horizon.trim.failed' => 1]);
config('horizon.trim.failed');

$jobRepository = resolve(JobRepository::class);
$jobRepository->trimFailedJobs();
```

**Comment by martio** [comment]
For `Laravel 9` and `PHP 8.1`

`<?php
/**
 * Sports Manager PRO.
 *
 * PHP version 8.1
 *
 * LICENSE: Sports Manager PRO can not be copied and/or distributed
 * without the express permission of Sports Manager PRO.
 *
 * @author    Marcin Lewandowski <marcin.lewandowski@appcadabra.pl>
 * @copyright 2022 appcadabra.pl
 */

namespace App\Console\Commands\Horizon;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;

/**
 * Console.
 */
class ClearMetricsCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:horizon:clear-metrics';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Flush the Horizon metrics';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        Redis::connection(name: 'horizon')->client()->flushAll();

        $this->info(string: 'The command was successful!');

        return 0;
    }
}`

**Comment by martio** [comment]
For `Laravel 9` and `PHP 8.1`

```php
<?php
namespace App\Console\Commands\Horizon;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;

/**
 * Console.
 */
class ClearMetricsCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:horizon:clear-metrics';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Flush the Horizon metrics';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        Redis::connection(name: 'horizon')->client()->flushAll();

        $this->info(string: 'The command was successful!');

        return 0;
    }
}
```

**Comment by jimtaylor123** [comment]
This is what I use in my job to clear just the failed jobs on Laravel 10: 
```php 
    Redis::connection()->zremrangebyscore(
        'failed_jobs', CarbonImmutable::now()->subMinutes(config('horizon.trim.failed', 10080))->getTimestamp() * -1, '+inf'
     );
```

**Comment by Luke-SF** [comment]
> ```shell
> php artisan horizon:forget JOB_ID
> ```
> 

Too bad there isn't a clear "all" or "*" command in Horizon?

**Comment by james-astra** [comment]
https://github.com/laravel/framework/issues/36927#issuecomment-1932507985

**Comment by yipeecaiey** [comment]
stumbled across this old thread...looks like that option IS now available
`php artisan horizon:forget --all`

**Comment by ket-c** [comment]
> stumbled across this old thread...looks like that option IS now available `php artisan horizon:forget --all`

anytime i run the command i get same response
`28362 failed jobs deleted successfully!`

**Comment by nevmerzhitsky** [comment]
@preeteshjain @martio you both are just crazy if you advice things like this to broad people. Please delete your comments, don't embarrass yourself.

**Comment by fiko** [comment]
> stumbled across this old thread...looks like that option IS now available `php artisan horizon:forget --all`

it works for me, deleting all failed jobs
