### ISSUE TITLE
When worker docker restarts, all jobs can start immediately instead of waiting for `retry_after`

### ISSUE THREAD

**Issue by qiulang** [laravel/horizon#1220]
Kubernetes restarts worker docker for various reasons and that happens all jobs in queue will fail. But they will wait for what is set in `retry_after` before they restart. So I think it is better if horizon can detect if docker restarts and run the jobs immediately (clear retry counter as well).

But I am not sure if laravel/horizon can detect worker docker restarts.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by qiulang** [comment]
Hi actually I am not asking a question but a feature request.

**Comment by qiulang** [comment]
I have tried to write a standalone job whose job is to find all those failed job and dispatch them to a new queue and hope they will be run immediately.

But I find that when I dispatch those jobs to an async queue, they won't run immediately. They will still wait for `retry_after` before they restart. But when I dispatch them to a sync queue , onConnection('sync'), will jobs run immediately. So it looks like when dispatching jobs to a sync queue, retry_after will be ignored, is this the case ?
