### ISSUE TITLE
Horizon 5 is still using old Nexmo channel

### ISSUE THREAD

**Issue by ankurk91** [laravel/horizon#1222]
- Horizon Version: 5.10.4
- Laravel Version: 9.41
- PHP Version: 8.1
- Redis Driver & Version: predis/phpredis 7.x
- Database Driver & Version: MySql 8.0.31

### Description:
The docs says to install `laravel/vonage-notification-channel` package but Horizon is still using the old Nexmo channel

https://github.com/laravel/horizon/blob/01b26da26ca8abe3a525a307b1155d52d7293c8d/src/Notifications/LongWaitDetected.php#L114

### Steps To Reproduce:
* Follow the docs to setup SMS noticcations
* You wont get SMS

**Comment by driesvints** [comment]
We'd welcome a PR for this 👍
