### ISSUE TITLE
With auto balance, most workers are assigned to the queue with the most pending jobs, not the one with the highest priority

### ISSUE THREAD

**Issue by georgms** [laravel/horizon#1225]
- Horizon Version: v5.10.2
- Laravel Version: v9.35.1
- PHP Version: 8.1.10
- Redis Driver & Version: ext-redis 5.3.7
- Database Driver & Version: mysqlnd 81.10

### Description:

* [Laravel Queue works can be assigned to multiple queues and will work on them in the configured priority](https://laravel.com/docs/9.x/queues#queue-priorities).
* Laravel Horizon also has a `queue` option where multiple queues can be configured.
* My assumption is that, in `auto` balance mode, Horizon would assign most workers to the highest priority queue if it is not empty in order to empty it as fast as possible.
* Instead Horizon will assign most workers to the queue with the most pending jobs, regardless of the queue's priority.

### Steps To Reproduce:

1. In `horizon.php` configure Horizon like so:
    ```php
       'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default', 'low'],
            'balance' => 'auto',
            'maxProcesses' => 10,
        ],
    ]
    ```
2. Create 10 jobs on the `default` queue and 1.000 jobs on the `low` queue.

### Expected:

Horizon assigns most workers to the `default` queue because it has the higher priority.

### Actual:

Horizon assigns most workers to the `low` queue because it has more pending jobs:
![grafik](https://user-images.githubusercontent.com/2857634/205699330-4018bcb7-d824-43f8-9a44-17e4d1bbbd1c.png)

**Comment by Florisbosch** [comment]
Hi @georgms,

it seems to me that the current behaviour you are explaining is exactly what the 'auto' mode should do.

See documentation: https://laravel.com/docs/9.x/horizon#balancing-strategies
> The `auto` strategy adjusts the number of worker processes per queue based on the current workload of the queue. For example, if your `notifications` queue has 1,000 pending jobs while your `render` queue is empty, Horizon will allocate more workers to your `notifications` queue until the queue is empty.

I guess the reason behind this is to avoid having jobs which will never be resolved if all processes go to the highest priority queue. 

Remember it is for 'balancing' you want to even out the number of processes between all queues.
I think what you are looking for is just the default Laravel behaviour. Set balancing to 'false' to let Horizon process the queues by the order you have configured.

**Comment by bernardwiesner** [comment]
you have to set it to `false` if you want the default behavior of priority.

```
'balance' => 'false',
```

> When the balance option is set to false, the default Laravel behavior will be used, wherein queues are processed in the order they are listed in your configuration.

**Comment by georgms** [comment]
Thanks for the additional explanations @florisbosch @bernardwiesner! Turning off balancing actually does pretty much what I want. Closing this.
