### ISSUE TITLE
Supervisor configuration with dynamic queue name

### ISSUE THREAD

**Issue by medeirosinacio** [laravel/horizon#1228]
In some cases the developer may want to configure a worker to retrieve messages from dynamically created queues with some suffix.

It would be interesting for Horizon to allow regex in the definition of the work queue, is this feasible?

example:
```php
'environments' => [
    'production' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['tenant.*.tasks'], // or  'queue' => ['tasks-*']
            'balance' => 'auto',
            'minProcesses' => 1,
            'maxProcesses' => 10,
            'balanceMaxShift' => 1,
            'balanceCooldown' => 3,
            'tries' => 3,
        ],
    ],
],
```

I would love to be able to have a queue for each client and balance the delivery on the worker.

Is this acceptable? If you have any tips I can try to implement.

thank you

**Comment by taylorotwell** [comment]
Hey there! I'm not sure if it's feasible or not. I have never looked into something like that. If you dig into it the merging of the PR would just depend on code complexity, etc. Thanks!
