### ISSUE TITLE
Completed jobs not openning

### ISSUE THREAD

**Issue by simokassab** [laravel/horizon#1240]
- Horizon Version: 5.10
- Laravel Version: 9.19
- PHP Version: 8.1
- Redis Driver & Version: predis/phpredis 2.0
- Database Driver & Version: Mysql

### Steps To Reproduce:

Hello,
I installed Laravel Horizon with 3 supervisors and its working perfectly, but in the dashboard am not able to see the completed jobs, it keeps loading like below image 

![image](https://user-images.githubusercontent.com/16435213/214448141-d9014093-b187-4238-b33d-f18374ff45bc.png)

What is the issue here ?

Thank you

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
