### ISSUE TITLE
Lodash library special characters are breaking horizon dashboard

### ISSUE THREAD

**Issue by wesleyvieira12** [laravel/horizon#1245]
- Horizon Version: 5.14.1
- Laravel Version: 9.36.2
- PHP Version: 8.0.2
- Redis Driver & Version: predis 2.1
- Database Driver & Version: Not

**Description:**
I followed the correct steps to install horizon, but the browser was showing the error: "Uncaught SyntaxError: Invalid or unexpected token (at app.js?id=766b568d1924aa83b2a1f279d2c5ab9e:2:484352)".

We analyzed the app.js file and saw that it had the following error code:

`rn=Ue({À:"A",Á:"A",Â:"A",Ã:"A",Ä:"A",Å:"A",à:"a",á:"a",â:"a",ã:"a",ä:"a",å:"a",Ç:"C",ç:"c",Ð:"D",ð:"d",È:"E",É:"E",Ê:"E",Ë:"E",è:"e",é:"e",ê:"e",ë:"e",Ì:"I",Í:"I",Î:"I",Ï:"I",ì:"i",í:"i",î:"i",ï:"i",Ñ:"N",ñ:"n",Ò:"O",Ó:"O",Ô:"O",Õ:"O",Ö:"O",Ø:"O",ò:"o",ó:"o",ô:"o",õ:"o",ö:"o",ø:"o",Ù:"U",Ú:"U",Û:"U",Ü:"U",ù:"u",ú:"u",û:"u",ü:"u",Ý:"Y",ý:"y",ÿ:"y",Æ:"Ae",æ:"ae",Þ:"Th",þ:"th",ß:"ss",Ā:"A",Ă:"A",Ą:"A",ā:"a",ă:"a",ą:"a",Ć:"C",Ĉ:"C",Ċ:"C",Č:"C",ć:"c",ĉ:"c",ċ:"c",č:"c",Ď:"D",Đ:"D",ď:"d",đ:"d",Ē:"E",Ĕ:"E",Ė:"E",Ę:"E",Ě:"E",ē:"e",ĕ:"e",ė:"e",ę:"e",ě:"e",Ĝ:"G",Ğ:"G",Ġ:"G",Ģ:"G",ĝ:"g",ğ:"g",ġ:"g",ģ:"g",Ĥ:"H",Ħ:"H",ĥ:"h",ħ:"h",Ĩ:"I",Ī:"I",Ĭ:"I",Į:"I",İ:"I",ĩ:"i",ī:"i",ĭ:"i",į:"i",ı:"i",Ĵ:"J",ĵ:"j",Ķ:"K",ķ:"k",ĸ:"k",Ĺ:"L",Ļ:"L",Ľ:"L",Ŀ:"L",Ł:"L",ĺ:"l",ļ:"l",ľ:"l",ŀ:"l",ł:"l",Ń:"N",Ņ:"N",Ň:"N",Ŋ:"N",ń:"n",ņ:"n",ň:"n",ŋ:"n",Ō:"O",Ŏ:"O",Ő:"O",ō:"o",ŏ:"o",ő:"o",Ŕ:"R",Ŗ:"R",Ř:"R",ŕ:"r",ŗ:"r",ř:"r",Ś:"S",Ŝ:"S",Ş:"S",Š:"S",ś:"s",ŝ:"s",ş:"s",š:"s",Ţ:"T",Ť:"T",Ŧ:"T",ţ:"t",ť:"t",ŧ:"t",Ũ:"U",Ū:"U",Ŭ:"U",Ů:"U",Ű:"U",Ų:"U",ũ:"u",ū:"u",ŭ:"u",ů:"u",ű:"u",ų:"u",Ŵ:"W",ŵ:"w",Ŷ:"Y",ŷ:"y",Ÿ:"Y",Ź:"Z",Ż:"Z",Ž:"Z",ź:"z",ż:"z",ž:"z",Ĳ:"IJ",ĳ:"ij",Œ:"Oe",œ:"oe",ŉ:"'n",ſ:"s"})`

Because the object's keys were not enclosed in curly braces, the system did not work. By placing the object's keys using double quotes, we can see that the dashboard is working again. This code to be from the "Lodash" library imported in the dashboard.vue file.

**Comment by wesleyvieira12** [comment]
![image](https://user-images.githubusercontent.com/19576762/217914538-3029bb0a-ec2b-4c4f-b887-cd12f578be75.png)

**Comment by taylorotwell** [comment]
Horizon loads fine for me on fresh Laravel application:

<img width="1469" alt="CleanShot 2023-02-09 at 15 39 13@2x" src="https://user-images.githubusercontent.com/463230/217945138-2dc378fa-6437-4b09-a8ed-57ba094dadde.png">

**Comment by browner12** [comment]
Possibly separate issue, but I'd be curious if Lodash could be factored out of Horizon all-together? I see only 25 uses of a Lodash function in the project.

With today's modern Javascript, I've refactored Lodash out of most of my projects pretty easily. It also reduced the bundle size.

Would you guys be open to a PR for that?
