### ISSUE TITLE
Laravel horizon is not workin on laravel 10.x

### ISSUE THREAD

**Issue by mhcrocky** [laravel/horizon#1249]
- Horizon Version: #.#.#
- Laravel Version: 10.x
- PHP Version: 8.1.6
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
Laravel horizon is not working on laravel 10.x
![image](https://user-images.githubusercontent.com/32413982/219950684-793d351d-7a01-467d-9c5a-7395b1ed3900.png)

**Comment by browner12** [comment]
Show your `composer.json`.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by SDekkers** [comment]
Laravel Horizon never worked on Windows (looking at XAMPP in screenshot). You need the PCNTL extension in PHP which is not available for Windows.
