### ISSUE TITLE
Flag to exclude output of silenced jobs from `php artisan horizon` command

### ISSUE THREAD

**Issue by hailwood** [laravel/horizon#1251]
The new silenced feature is awesome for the Horizon dashboard, however silenced jobs still show up in the output the `php artisan horizon` command as
```
2023-02-28 01:32:31 App\Jobs\MySilencedJob 25516797-1449-41f0-a5c2-4a2ac2a8201e ................. 306.18ms DONE
```

I think we should keep this behaviour for outputting to logs etc, but I'd like to add a new flag 
```
-s, --silence      Do not output any messages from silenced jobs
```

The usecase here is I often watch the output to make sure my jobs are executing correctly in development, so having my silenced jobs cluttering the CLI output means it's much harder to scan (same reasoning for adding silenced jobs to the horizon UI I imagine).

Originally I was considering just implementing a simple `str_contains()` to search for the silenced class name here if the flag is set https://github.com/laravel/horizon/blob/5.x/src/Console/HorizonCommand.php#L38-L40. But realising with the new silenced logic now being on the payload I'm not sure of the best way to do this?

Happy to submit a PR if we can hash it out :)

**Comment by driesvints** [comment]
This is a good idea @hailwood. Although I think it should be the reverse? Silence them by default and output them with the `-s --silenced` flag?

You can submit a PR and see how it goes 👍

**Comment by hailwood** [comment]
I agree about it being reversed, but would it then be considered a breaking
change?

**Comment by driesvints** [comment]
I'm not 100% sure. I'd say no since it's only a visual log for the user when jobs are dispatched. Can you try to attempt to make the PR, give an explanation to Taylor of this discussion and let's see what he says?
