### ISSUE TITLE
Huge logo on dashboard

### ISSUE THREAD

**Issue by mro95** [laravel/horizon#1252]
- Horizon Version: 5.14.2
- Laravel Version: 9.52.4
- PHP Version: 8.1
- Redis Driver & Version: predis/phpredis: 1.1.10 
- Database Driver & Version: MySQL

### Description:
After upgrading Laravel horizon I see a huge logo in the Horizon dashboard, see screenshot.
![image](https://user-images.githubusercontent.com/2186121/222174268-e157107b-e162-46ae-b627-bebf244eaf06.png)

This happens in Chrome and Firefox, I did not test other browsers. It looks like this doesn't happen in horizon version 5.13.0. This happens after I use the `artisan horizon:publish` command

### Steps To Reproduce:
Open the horizon dashboard

**Comment by driesvints** [comment]
Most likely this is browser cache. Please clear your browser cache or wait for Cloudflare etc to clear their asset cache.

**Comment by mro95** [comment]
@driesvints Like I said, I tried this in 2 different browsers. On a local machine, so no CloudFlare assets.

**Comment by jamsouf** [comment]
Same for me.
@mro95 Did you get it solved?

**Comment by mro95** [comment]
> Same for me. @mro95 Did you get it solved?

Nope. I was about to investigate it further.

**Comment by dpslwk** [comment]
`php artisan view:clear`
or 
`php artisan view:cache` (if your cacheing them say in production)

**Comment by JoaoWitorFelipe** [comment]
I create PR https://github.com/laravel/horizon/pull/1316

**Comment by taylorotwell** [comment]
Unable to recreate:

<img width="913" alt="CleanShot 2023-09-13 at 20 07 21@2x" src="https://github.com/laravel/horizon/assets/463230/04a4bb82-bd4d-4c3f-8b8f-99971b23562d">

**Comment by JoaoWitorFelipe** [comment]
I dont no why, I just removed the horizon with `composer remove laravel/horizon` and re-installed with `composer require laravel/horizon:^5.20.1` and after ran the `php artisan horizon:publish` and `php artisan view:clear` and it worked

**Comment by JoaoWitorFelipe** [comment]
> Unable to recreate:
> 
> <img alt="CleanShot 2023-09-13 at 20 07 21@2x" width="913" src="https://user-images.githubusercontent.com/463230/267823217-04a4bb82-bd4d-4c3f-8b8f-99971b23562d.png">

This happens at least for me when I update the laravel version from 8/9 to 10

**Comment by JoaoWitorFelipe** [comment]
I noticed too that in my project we are using custom controller for render the horizon index, so @mro95 check if your `HorizonServiceProvider` has any change that can impact.
