### ISSUE TITLE
Unable to install laravel/horizon

### ISSUE THREAD

**Issue by lhj456** [laravel/horizon#1253]
Horizon Version: 5.14.2
Laravel Version: 9.54.2
PHP Version: 8.1.10
Redis Driver & Version: predis/phpredis 7.0.8.1
Database Driver & Version: PostgreSQL 14.5

composer require laravel/horizon  or  composer require laravel/horizon:* --ignore-platform-req=ext-pcntl
Info from https://repo.packagist.org: #StandWithUkraine
Cannot use laravel/horizon's latest version v5.14.2 as it requires ext-pcntl * which is missing from your platform.
./composer.json has been updated
Running composer update laravel/horizon
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/horizon v0.1.0 requires illuminate/contracts ~5.4 -> found illuminate/contracts[v5.4.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - laravel/horizon[dev-chore/adds-type-checking, dev-master, v0.2.0, v1.0.0, ..., v1.4.3, v2.0.0, ..., v2.2.2, v3.0.0, ..., v3.7.2, v5.4.0, ..., 5.x-dev, 6.x-dev] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - laravel/horizon[v4.0.0, ..., 4.x-dev] require php ^7.2 -> your php version (8.1.10) does not satisfy that requirement.
    - laravel/horizon[v5.0.0, ..., v5.3.0] require php ^7.3 -> your php version (8.1.10) does not satisfy that requirement.
    - Root composer.json requires laravel/horizon * -> satisfiable by laravel/horizon[dev-chore/adds-type-checking, dev-master, v0.1.0, v0.2.0, v1.0.0, ..., v1.4.3, v2.0.0, ..., v2.2.2, v3.0.0, ..., v3.7.2, v4.0.0, ..., 4.x-dev, v5.0.0, ..., 5.x-dev, 6.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - G:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-pcntl` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/horizon:*" to figure out if any version is installable, or "composer require laravel/horizon:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by driesvints** [comment]
> Cannot use laravel/horizon's latest version v5.14.2 as it requires ext-pcntl * which is missing from your platform.

You need this extension for Horizon to work.
