### ISSUE TITLE
[Question] What does the 'nice' config value do?

### ISSUE THREAD

**Issue by shealavington** [laravel/horizon#1256]
I've installed Horizon...
I've tried to configure it...
I can't find any details as to what the 'nice' configuration value is for. :D

https://github.com/laravel/horizon/blob/8799c74cd6bb5261d588e936c83bad61ef57c81c/config/horizon.php#L194

**Comment by ankurk91** [comment]
https://en.m.wikipedia.org/wiki/Nice_(Unix)#:~:text=nice%20is%20a%20program%20found,CPU%20time%20than%20other%20processes.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
