### ISSUE TITLE
wrong release in packagist

### ISSUE THREAD

**Issue by fabio-ivona** [laravel/horizon#1257]
@driesvints Packagist has a v515 release, maybe because of a release with a typo that you removed and replaced with v5.15.0, it should be deleted from packagist too:

![image](https://user-images.githubusercontent.com/8792274/223510882-e60382e7-f0eb-4056-a9b4-2b8b29187696.png)

**Comment by Spice-King** [comment]
Worth mentioning that this has an effect to end users with some dependency tracking software, like Renovate.

![image](https://user-images.githubusercontent.com/590498/223556020-709869bb-b38e-4ee9-ab71-2f9fefd62636.png)

The change log could use a scrub too: https://github.com/laravel/horizon/blob/5.x/CHANGELOG.md

**Comment by ankurk91** [comment]
@driesvints @taylorotwell 

This should be solved before more users updates to this bogus version.

**Comment by ankurk91** [comment]
![Screenshot from 2023-03-08 11-38-35](https://user-images.githubusercontent.com/6111524/223633165-91e6a969-a1b5-4055-bcca-2d683235d759.png)

**Comment by zoispag** [comment]
dependabot did the same and installed v515.0

**Comment by driesvints** [comment]
Hi everyone. We removed that faulty tag. Sorry about that!
