### ISSUE TITLE
Is there any possibility of turning  api/stats and api/workload and api/masters API into a private API?

### ISSUE THREAD

**Issue by lengjunbin-trec** [laravel/horizon#1260]
when I install the horizon into my project.it works well.but there is a safety issue here.
horizon dashboard has three apis for grab all states.`stats`、`masters` 、`workload`.
![image](https://user-images.githubusercontent.com/61955063/227075546-b64d3cc6-89d0-490e-a421-61e796ad7816.png)
but anyone can obtain this data without verifying any information via domain + '/api/stats'.
for example. `https:://xxxx/api/stats`
This is not safe.
so Is there any possibility of turning  those API into a private API?

**Comment by driesvints** [comment]
I cannot access this when I'm not authorised by https://laravel.com/docs/10.x/horizon#dashboard-authorization
