### ISSUE TITLE
AutoScaling when balance setting is disabled

### ISSUE THREAD

**Issue by alekseyp** [laravel/horizon#1261]
I propose a new feature for Laravel Horizon that allows users to configure a minimum and maximum number of processes when `balance` is set to `false`. This would enable autoscaling of processes based on the total number of jobs in all the queues, providing better control over resource usage in certain situations, such as containerized environments like Kubernetes.

Currently, we have to run the maximum number of workers we think the app would need, which can result in inefficient resource allocation. By allowing users to define a range for the number of processes, we can improve resource utilization and potentially reduce costs.

Example configuration:

```
    'defaults'         => [
        'supervisor-1' => [
            'connection'   => 'redis',
            'queue'        => [
                'high',
                'medium',
                'low',
            ],
            'balance'      => 'false',
            'maxProcesses' => 20,
        ],
    ],
```

With this configuration, if the total number of jobs across all queues is empty, only one worker would be kept. If the number of jobs increases, additional workers would be added, up to the maximum specified.

I've seen a couple of comments about such a feature but haven't found an existing feature request for it. I believe this would be a valuable addition to Laravel Horizon.

**Comment by driesvints** [comment]
Heya, thanks. If you could send us a PR which we could look at that'd be great! Right now we're not planning to put in the work ourselves.

**Comment by alekseyp** [comment]
I didn't expect another answer, but If you keep closing valid feature requests - I don't think anyone will have any mental rush to do anything here. just my opinion.  
I think a better approach would be to keep good ideas open for people to pick from.
