### ISSUE TITLE
Refresh tag jobs count

### ISSUE THREAD

**Issue by antoniovalenzuela** [laravel/horizon#1262]
- Horizon Version: 5.15
- Laravel Version: 10.4
- PHP Version: 8.1
- Redis Driver & Version: predis/phpredis (I use default laravel redis)
- Database Driver & Version: MariaDB

### Description:

The monitored tag jobs count is not refreshed automatically.

Is it normal or is it a problem?

Note: The automatic refresh of pending and completed Jobs works well.

![Screenshot_5](https://user-images.githubusercontent.com/28113584/229002286-19f3b40a-3be0-4f1a-8c4e-a93bfbb3580f.jpg)

**Comment by nunomaduro** [comment]
Thank you for this feature request, i've fixed it: https://github.com/laravel/horizon/pull/1274.
