### ISSUE TITLE
Clarify trim.pending config key

### ISSUE THREAD

**Issue by gbradley** [laravel/horizon#1263]
A recent Reddit thread highlighted some confusion around the purpose & effect of the `trim.pending` config key. From reading the config notes and various closed issues, it *seems* like the purpose of the trim keys is to remove the jobs from the list of *displayed* jobs:

> @themsaid Horizon stores recent the jobs in a set, it clears that set based on the trim.recent value you set and **that's not related to the actual queue.**

But it seems as through `trim.pending` value is additionally used as the key ttl, meaning not only will pending jobs that run over the trim time disappear from the list, but they will never be executed. This includes jobs that are given an explicit delay beyond the trim time.

If this is indeed by design, then may I suggest updating the docs to make it clear that such jobs will not be executed? In addition I’d suggest setting a higher default for this value, as there are many scenarios where a pending job may take more than 60 minutes (high volume, explicit delay, or even just maintenance downtime). It may be intended behaviour, but it is certainly *unexpected* that a dedicated queue package drops jobs that would be retained by the simpler DB driver.

Am happy to do a PR but would like to get confirmation that yes, this is the correct & intended behaviour. Cheers!

**Comment by driesvints** [comment]
Hi there, `trim.pending` indeed purges the jobs from the Redis queue after the expired time. I personally think that's clear enough from the description above these config values but we'd appreciate a PR to make this more clear in the Horizon docs. Thanks!
