### ISSUE TITLE
Use native redis commands in Horizon instead of EVAL

### ISSUE THREAD

**Issue by ANPez** [laravel/horizon#1266]
I've been checking the code, because it was generating a huge CPU load in our redis (we process millions of jobs per day with horizon through redis).
It would be nice to use something like BRPOPLPUSH for pushing/pulling jobs instead of just EVAL a piece of LUA code. That would alleviate the CPU load greatly.

**Comment by driesvints** [comment]
Heya, if you could whip up a PR for us to look at that'd be great. Thanks!
