### ISSUE TITLE
Unexpected behavior of the queue:forget command

### ISSUE THREAD

**Issue by markwalet** [laravel/horizon#1267]
First of all, I'm not sure if this ticket should be in the horizon or in the framework repository. I've decided to put it here because the change is related to Horizon. Depending on the chosen solution there should be a pr in the framework or in the horizon package.

**The problem**
When accidentally using the queue:forget command while using Laravel Horizon (with a failed_jobs table in MySQL), it becomes impossible to remove the failed job from the Horizon UI (except for when we wait until the failed job expires).

**The solution(s)**
We can tackle this problem in multiple ways IMO:

1. _Disable the `queue:forget` command when we detect horizon active/running._

This would be a breaking change in the framework as far as I know, I'm not a fan of disabling commands in the core from another package. I'm not even sure if that's possible. So an update in the framework is required.

2. _Let `queue:forget` also remove the job from Redis if Horizon is detected._

Looks possible, and there is a change we can introduce this in a minor update in the framework. If error handling is executed thoroughly here, there would (probably) not be a breaking change. But we'll have to dig into that if this is the preferred solution.

3. _Let `horizon:forget` accept jobs that are only present in the redis failed list._

This would not fix the "unexpected behavior, but it would enable developers to fix their mistakes. I'm not that familiar with the horizon source-code, so I'm just assuming that this is possible.

4. _Create a `horizon:prune-redis` command_

Please ignore the naming of this command, I hope it encapsulated the function of this new command. It will remove all failed jobs from Redis that are not present in mysql anymore. It would also not solve the underlying problem, but it would at least be a non-breaking change that can be patched in to the horizon package.

**Summary**
These are a few possible solutions that I've come up with for tackling this problem. If there are any other solutions that we want to discuss, please put them in this thread so I can complete the list. If there is a preferred solution here from one of the moderators, I'm ready to create a PR for it if it is in my technical capabilities. If there is already a solution for this that I completely missed, please let me know so I can close this ticket. Thanks in advance

**Comment by driesvints** [comment]
Thanks @markwalet. Paging @taylorotwell to see which solution would be best.

**Comment by taylorotwell** [comment]
I don't really have a strong opinion here. The documentation states to use `horizon:forget` to remove jobs when using Horizon. I don't have a strong opinion or stance or even desire to change much about `queue:forget` to solve situations where developers accidentally use the wrong command.

**Comment by markwalet** [comment]
I'd at least give developer the opportunity to fix their mistakes here. In which way we want to do it doesn't matter to me.

**Comment by driesvints** [comment]
@markwalet I'm sorry but it looks like right now we won't take any action here. If the docs can be improved here we'd appreciate a PR. Thanks
