### ISSUE TITLE
BUG: A supervisor with this name is already running.

### ISSUE THREAD

**Issue by ahkui** [laravel/horizon#1273]
### Horizon Version

v5.14.1

### Laravel Version

v9.51.0

### PHP Version

8.1.18

### Redis Driver

PhpRedis

### Redis Version

5.3.7

### Description

<img width="744" alt="image" src="https://github.com/laravel/horizon/assets/14049597/df3850cd-b472-4773-9efc-2f094f33809c">

maybe same with #695

### Steps To Reproduce

no idea

**Comment by nunomaduro** [comment]
Thank you for creating this issue. Do you mind of sharing additional context here? Such as the environment where horizon is being executed, your horizon configuration file, and the deployment script being used?

**Comment by ahkui** [comment]
found memory issue in k8s log, inc memory and fixed.

**Comment by nunomaduro** [comment]
Glad that you found a solution for your issue.
