### ISSUE TITLE
Undefined variable $cssFile

### ISSUE THREAD

**Issue by alexnogueirasilva** [laravel/horizon#1278]
### Horizon Version

5.16

### Laravel Version

10.12

### PHP Version

8.2

### Redis Driver

Predis

### Redis Version

2.1

### Description

After updating to Laravel 10.12, I started receiving this error. I tried reinstalling it, but I still haven't been successful in accessing Horizon.

`
  "message": "Undefined variable $cssFile",
  "exception": "Spatie\\LaravelIgnition\\Exceptions\\ViewException",
  "file": "/var/www/html/vendor/laravel/horizon/resources/views/layout.blade.php",
  "line": 16,`

### Steps To Reproduce

After updating Laravel and deploying the image with Sail, I am unable to access Horizon.

**Comment by jpgnz** [comment]
@alexnogueirasilva out of interest, why did you close this? I am having the same issue.

**Comment by alexnogueirasilva** [comment]
@jpgnz I closed it because I cloned my project again and it simply worked. I was curious, but I'm not sure if it was a bug, so I decided to close it.

**Comment by jpgnz** [comment]
Ok, for me I just had to do a `php artisan view:clear` - must have been a caching issue.
