### ISSUE TITLE
Timed out jobs are not reported

### ISSUE THREAD

**Issue by paulandroshchuk** [laravel/horizon#1293]
### Horizon Version

5.17.0

### Laravel Version

10.14.1

### PHP Version

8.2.3

### Redis Driver

Predis

### Redis Version

7.0.9

### Database Driver & Version

MySQL Ver 8.0.32 for macos13.0 on arm64 (Homebrew)

### Description

Timed out jobs are not reported. It looks like **TimeoutExceededException** is thrown but for some reason this particular exception is not reported (laravel.log is empty).

There is a way to actually have it reported: define a `failed()` method within the job and manually report the exception using the `report()` helper:
```php
public function failed(\Throwable $e)
{
    report($e);
}
```

If we don't specify this, the exception is not reported, which I think should be, right?

Other exceptions such as: **MaxAttemptsExceededException**, etc are reported correctly.

I've submitted a bug-report repository: https://github.com/paulandroshchuk/bug-report
and also made a Loom video showing the behaviour: https://www.loom.com/share/f5c7a487bf61462b950426915b87e8d7

### Steps To Reproduce

1. Pull bug-report repository https://github.com/paulandroshchuk/bug-report
2. `php artisan hey` - queue two jobs (or queue the jobs in any other way)
3. `php artisan horizon` - run the jobs (they will time out)
4. Open `laravel.log` and you'll see only one time out is reported where two jobs timed out. The reported exception is [the one that is manually reported](https://github.com/paulandroshchuk/bug-report/blob/main/app/Jobs/ManuallyReportedTimeOutJob.php#L27); if it was not reported, it would not be inside `laravel.log`.

**Comment by driesvints** [comment]
I'm not sure about this one... would appreciate some help in figuring this one out.

**Comment by driesvints** [comment]
Actually none of those report for me. I'm using your repo.

<img width="785" alt="Screenshot 2023-07-06 at 10 29 02" src="https://github.com/laravel/horizon/assets/594614/8b2b2ccb-12f3-44ed-905e-18a2d2f3fcf6">

**Comment by paulandroshchuk** [comment]
> Actually none of those report for me. I'm using your repo.
> 
> <img alt="Screenshot 2023-07-06 at 10 29 02" width="785" src="https://user-images.githubusercontent.com/594614/251392038-8b2b2ccb-12f3-44ed-905e-18a2d2f3fcf6.png">

Interesting they didn't time out. Do you have this extension installed? https://laravel.com/docs/10.x/queues#timeout

**Comment by driesvints** [comment]
With both errors not being reported I believe this is intentionally. So going to close this sorry.

**Comment by hivokas** [comment]
For anybody who finds this issue, I recommend taking a look at https://github.com/laravel/framework/pull/47107 and https://github.com/laravel/framework/pull/47068.
