### ISSUE TITLE
Why start at max processes for a new supervisor?

### ISSUE THREAD

**Issue by marcoskubis** [laravel/horizon#1295]
I noticed that when raising a new horizon instance, the horizon instantly scales the workers to the value defined in max processes. This causes server overhead whenever horizon is restarted, especially when we have a high number of workers and queues.

Wouldn't it be much better to start the workers using the value that's defined in min-processes, letting the balancer only scale if necessary?

Check this line. I suggest change max-processes to min-processes. What do you all think about it?

[https://github.com/laravel/horizon/blob/5.x/src/Console/SupervisorCommand.php#L98](https://github.com/laravel/horizon/blob/5.x/src/Console/SupervisorCommand.php#L98)

```
$supervisor->scale(max(
    0, $this->option('min-processes') - $supervisor->totalSystemProcessCount()
));
```

### More info? Ok.

Just setup a supervisor in `horizon.php`:

1. Define `maxProcesses=1000` and `minProcesses=1`
2. Define `balancer=auto`
3. Run `php artisan horizon`
4. See your laptop crash.

**Comment by taylorotwell** [comment]
Can't speak to whether it's better or worse really - but in theory you should not set `max-processes` greater than what your machine can reasonably handle. If settings your max processes to 1000 causes your machine to crash, then that's a possibility regardless of whether it scales to that number initially or not. It could always scale up to that number 5 minutes later when your queue is busy.

**Comment by marcoskubis** [comment]
Therefore, it would not be a good idea to make this configurable in `horizon.php`?

**Comment by cyppe** [comment]
I agree on this one. For me it's not about if server crashes or not. It's just a bit waste of resources to scale up to 100% just to scale down to minimum a few seconds later if there is no jobs. Would be nice to have it configurable.

**Comment by cyppe** [comment]
Added PR to address this. https://github.com/laravel/horizon/pull/1384

**Comment by cyppe** [comment]
Declined as expected. Sorry, I tried.

Hope they change default instead to be minimum, because current method to scale to max makes zero sense. If you run in kubernetes each scale up can just trigger a chain of scale ups as memory and cpu goes to max on startup. Just one example of why its good idea to default to minimum.
