### ISSUE TITLE
List total processes VS total capacity across all instances

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/horizon#1296]
How to get total processes used VS total capacity in controller? For example, in my current set up I'm using 800 or so workers, but my config defines a maximum set of processes, so I need to present this information somewhere else in my project. Is there some model or interface I can utilise in my controller to get these stats?

 
![Screenshot 2023-07-17 at 12 13 11](https://github.com/laravel/horizon/assets/25177538/5c8969ff-2b13-42e2-baac-dd6f2f8a1765)
![Screenshot 2023-07-17 at 12 13 04](https://github.com/laravel/horizon/assets/25177538/5ea9db5f-2078-41d3-bcdf-2c84ec1740b4)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
