### ISSUE TITLE
Distribute jobs to 4 processors

### ISSUE THREAD

**Issue by Kernel1453** [laravel/horizon#1302]
Hi All,
I'm new for Laravel and Horizon, so i'd like to learn that,
1. When I check Horizon, it usually says 1 process even though my 4 processors should be running, why could this be? You can see my horizon settings below.

2. There are approximately 35 jobs in my Laravel project. I want to distribute these jobs to the processors myself(4 processors). Because some jobs take seconds, while others take a very long time. Can I assign the jobs I want to the processor I want? If yes, how?
Your answers based on experience will be very valuable for me and will improve my project.

Here below is my horizon.php settings;

'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'maxProcesses' => 4,
            'maxTime' => 0,
            'maxJobs' => 0,
            'memory' => 128,
            'tries' => 1,
            'timeout' => 60,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-1' => [
                'queue' => ['default'],
                'balance' => 'auto',
                'processes' => 4,
                'maxProcesses' => 4,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
                'connection' => 'redis',
                'maxTime' => 0,
                'maxJobs' => 0,
                'memory' => 128,
                'tries' => 1,
                'timeout' => 60,
                'nice' => 0,
            ],
        ],

        'local' => [
            'supervisor-1' => [
                'maxProcesses' => 4,
            ],
        ],
    ],

Best Regards

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
