### ISSUE TITLE
Job feedback

### ISSUE THREAD

**Issue by allanmcarvalho** [laravel/horizon#1303]
Today on job info on Horizon panel we have some information about job how eg. id, created, the job payload and others.
Due to be a part of system that is strongly encapsulated, it's hard to know what really happened as a result of running that job and he don't have some feature to give this feedback.

I don't have certain if the main change that can make this possible is here on horizon or on Laravel queue, but I thing that the main feature can works with a trait in jobs, maybe called "WithFeedbacks". It will provide methods that you can provide one or more (maybe a timeline or ordered) feedbacks to be registred on job data. This is very helpfull to understand what is happen on that job, and when it fail, we can know the reason.

An example of what the trait could be
```php
trait WithFeedback
{
    /**
     * insert a feedback to feedbacks payload
     */
    public function feedback(string $message): void
    {
        // insert to feedback payload
    }

    /**
     * insert a feedback to feedbacks payload if condition is true
     */
    public function feedbackIf(bool $condition, string $message): void
    {
        // insert to feedback payload
    }

    /**
     * inserts the correct feedback according to the result
     */
    public function finalFeedback(?string $onSuccess, ?string $onFailure): void
    {
        // create a closure to insert the correct feedback on job end
    }
}
```

**Comment by driesvints** [comment]
Hi there. If you could whip up a PR for us to look at, that'd be helpful. Thanks
