### ISSUE TITLE
Ability to cancel currently running job batches

### ISSUE THREAD

**Issue by jasonmccreary** [laravel/horizon#1310]
It would be cool if there were a cancel button on the batches table and/or batches detail page that would send a cancel signal to the job batch.

This is helpful in the event you notice your jobs are failing (say due to a GitHub outage). Instead of logging into the server, determining the batch ID, and writing a bunch of tinker commands, I could just press a button. 🔥 

I'd be glad to PR something, but alas, I am an old dog and don't know Vue. 😞

**Comment by crynobone** [comment]
Hi @jasonmccreary 

I think we can work on this, I prepared `feature-1310` branch for this feature.

**Comment by driesvints** [comment]
Hey all. Gonna close this one since it's been so long. Feel free to attempt a PR!
