### ISSUE TITLE
Pending job number seems incorrect

### ISSUE THREAD

**Issue by jasonmccreary** [laravel/horizon#1311]
### Horizon Version

5.19.1

### Laravel Version

10.19.0

### PHP Version

8.2.9

### Redis Driver

Predis

### Redis Version

1.1.10

### Description

It appears the "Pending Jobs" number may be incorrect or misleading when there are failed jobs. This batch is complete and 160 did fail. However, no more are pending.

<img width="635" alt="Screenshot 2023-09-05 at 7 47 17 PM" src="https://github.com/laravel/horizon/assets/161071/deb90d21-79fd-4014-91a2-11edb4a4f5c0">

I would expect this number to be 0 since the batch is complete. Or, if it is to indicate the number of "Incomplete Jobs", then maybe that should have a separate title. Depending on the direction, the "Completed Jobs" and its subtitle might need to be adjusted as currently I would expect it to be `484`.

I see the same thing for all my recent batched jobs with failures - the "Pending Jobs" and "Failed Jobs" numbers are the same.

### Steps To Reproduce

Run a batched job with some failures. You should see "Pending Jobs" and "Failed Jobs" are the same number.

**Comment by driesvints** [comment]
Hey @jasonmccreary. I believe these numbers are correct. This view is just a direct representation of the values of a batch in Laravel: https://github.com/laravel/framework/blob/2e3d23fc89c5c9e9841962d5c9bf0e3881a81929/src/Illuminate/Bus/Batch.php#L445-L457

There's pending jobs which are basically the failed jobs which still need to run, there's completed jobs and then there's a total number of jobs (completed + pending/failed).

**Comment by jasonmccreary** [comment]
Thanks for the explanation. I still wonder if the wording could be adjusted as "pending" to me means needs to be run. I see how "failed" falls into that category though. No biggie.

**Comment by driesvints** [comment]
I think it's best we just use the wording as is on the batch array personally. You can always try a PR to see if Taylor would accept it 👍

**Comment by crynobone** [comment]
<img width="635" alt="Screenshot 2023-09-05 at 7 47 17 PM" src="https://github.com/laravel/horizon/assets/161071/deb90d21-79fd-4014-91a2-11edb4a4f5c0">

Total Job value is in fact incorrect, at the moment it calculated from (totals - pendingJobs), when in fact it should show **Completed Jobs (including failed) 484 (100%)**

**Comment by crynobone** [comment]
Alternatively we should follow `Illuminate\Bus\Batch` conversion of "Processed Jobs" (totals - pendingJobs) and displayed it as **Processed Jobs 324 (67%)**

**Comment by driesvints** [comment]
Right, good spot @crynobone. Sorry about that @jasonmccreary

**Comment by jasonmccreary** [comment]
@driesvints, no worries. Glad it got reopened.

**Comment by topclaudy** [comment]
Similar issue:

![Screenshot 2024-08-16 at 18 19 17](https://github.com/user-attachments/assets/27fa33df-b746-4994-a963-db6480f16d14)

Processed/Completed jobs 100%, no failures but 6 pending (stuck).
