### ISSUE TITLE
New command `horizon:clear-metrics` does not work

### ISSUE THREAD

**Issue by jihadadulrazaqjasim** [laravel/horizon#1320]
### Horizon Version

5.21.0

### Laravel Version

10.24.0

### PHP Version

8.2.10

### Redis Driver

Predis

### Redis Version

2.2.2

### Database Driver & Version

PostgreSql

### Description

The new command just added to Laravel horizon `5.21.0` does not work wiith `predis` driver, it throws below attached error:

![Screenshot 2023-09-20 at 8 08 39 PM](https://github.com/laravel/horizon/assets/87228058/552897a2-2609-4935-a8d8-47a4ac08cdb3)

### Steps To Reproduce

running `php artisan horizon:clear-metrics`

**Comment by trevorgehman** [comment]
This was fixed in https://github.com/laravel/horizon/pull/1319

**Comment by jihadadulrazaqjasim** [comment]
I've updated laravel and horizon to latest version, still same issue.

**Comment by driesvints** [comment]
This wasn't released yet but it is now: https://github.com/laravel/horizon/releases/tag/v5.21.1
