### ISSUE TITLE
pass arguments to horizon:work and horizon:supervisor

### ISSUE THREAD

**Issue by raulamoretti** [laravel/horizon#1324]
Hey guys,

We use gecche multidomain (https://github.com/gecche/laravel-multidomain) and we need pass argument like **--domain=api-example.company.com**  for supervisor process and horizon:work.

Can  I send arguments to work/supervisor command? 

Thanks

**Comment by driesvints** [comment]
Unfortunately Horizon does not support this at this time sorry. I don't think we have any plans for it any time soon.
