### ISSUE TITLE
Complete restart of workers when using `horizon:terminate` cmd

### ISSUE THREAD

**Issue by ChristopheBorcard** [laravel/horizon#1325]
### Horizon Version

5.21.1

### Laravel Version

10.4

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

5

### Description

I don't understand why a full worker restart is requested when using the `horizon:terminate` command.

You can see this line [Here](https://github.com/laravel/horizon/blob/5.x/src/Console/TerminateCommand.php#L59C9-L59C92)

```php
$this->laravel['cache']->forever('illuminate:queue:restart', $this->currentTime());
```

I use Laravel Horizon in Kubernetes with HPA, which allows me to have several worker Pods.
But during a scalldown or rollout update, all workers in all pods are restarted. 

I had to create my own terminate command to remove the queue:restart cache insertion but I was wondering if it really had a purpose or if it could be removed directly from the package.

### Steps To Reproduce

Start several Horizon using the same redis and terminate one of them. Workers in other Horizon will also quit and restart.

**Comment by driesvints** [comment]
Right now, we don't support running multiple Horizon instances on the same redis connection, sorry.
