### ISSUE TITLE
Be able to see date for job lists

### ISSUE THREAD

**Issue by pdewit** [laravel/horizon#133]
For the lists in `horizon/recent-jobs` and `horizon/failed`, I'd like to see the date at which they failed/were created, and not only the time. I have some jobs that have failed on different days and I'd like to see on which day they failed. Might be useful to add it to the `title` attribute so it can be seen on mouseover.

**Comment by bbashy** [comment]
Yeah, very confusing!

**Comment by themsaid** [comment]
This is currently added.
