### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33.  PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /myProject/vendor/composer/platform_check.php on line 24 Composer detected issues in your platform:

### ISSUE THREAD

**Issue by marctonon** [laravel/horizon#1337]
### Horizon Version

ˆ5.21

### Laravel Version

10.28

### PHP Version

PHP 8.1.18 (cli) (built: Apr 21 2023 18:36:56) (NTS)

### Redis Driver

Predis

### Redis Version

ˆ2.2

### Database Driver & Version

MariaDB

### Description

I am trying to put Laravel Horizon to run via Supervisor:

sudo vi /etc/supervisor/conf.d/laravel-horizon.conf

[program:laravel-horizon] 
process_name=%(program_name)s_%(process_num)02d 
command=php /myProject/artisan horizon 
autostart=true 
autorestart=true 
user=daemon 
redirect_stderr=true 
stdout_logfile=/myProject/storage/logs/horizon.log

I did:
sudo supervisorctl reread
sudo supervisorctl update
sudo supervisorctl start laravel-horizon

sudo supervisorctl start laravel-horizon
laravel-horizon: ERROR (no such process)

sudo supervisorctl status
$ sudo supervisorctl status
laravel-horizon:laravel-horizon_00   STARTING  
laravel-worker:laravel-worker_00     RUNNING   pid 822611, uptime 11:21:55
laravel-worker:laravel-worker_01     RUNNING   pid 822601, uptime 11:21:56

And the Horizon.log file is registering the following message in a constant loop:
Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33.  PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /myproject/vendor/composer/platform_check.php on line 24 Composer detected issues in your platform:

Why Laravel Horizon is requiring PHP 7.3 | 8.0? Is it correct and probably is causing the problem?

By the way, I can run Laravel Horizon manually through artisan horizon.

### Steps To Reproduce

This is my composer.json

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "barryvdh/laravel-dompdf": "^2.0",
        "darkaonline/l5-swagger": "^8.5",
        "filament/filament": "^3.0.62",
        "filament/forms": "^3.0-stable",
        "filament/notifications": "^3.0-stable",
        "filament/tables": "^3.0-stable",
        "google/apiclient": "^2.15",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/horizon": "^5.21",
        "laravel/jetstream": "^3.2",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "league/flysystem-sftp-v3": "^3.15",
        "livewire/livewire": "^3.0",
        "maatwebsite/excel": "^3.1",
        "openai-php/laravel": "^0.6.3",
        "predis/predis": "^2.2",
        "saade/filament-laravel-log": "^3.0",
        "spatie/laravel-permission": "^5.10"
    },
    "require-dev": {
        "doctrine/dbal": "^3.6",
        "fakerphp/faker": "1.23.0",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan filament:upgrade"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan filament:upgrade"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

Laravel Horizon is stating manually, but it fails when a I try to run via supervisor.

**Comment by marctonon** [comment]
I had to sudo update-alternatives --install /usr/bin/php php /opt/bitnami/php/bin/php 1 and sudo update-alternatives --set php /opt/bitnami/php/bin/php in order to Supervisor look for Php 8.1 version.

I really don't know why my server has 7.4.33, but I believe the Horizon requirements looks confuse.

**Comment by crynobone** [comment]
> I really don't know why my server has 7.4.33, but I believe the Horizon requirements looks confuse.

The above error came from Composer and is valid.

**Comment by mamuns95** [comment]
Disgusting  this error, lost whole day
