### ISSUE TITLE
Multiserver setup with Forge and Horizon

### ISSUE THREAD

**Issue by salvisb** [laravel/horizon#1339]
### Horizon Version

5.15.0

### Laravel Version

10.4.1

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

5.0.7

### Description

Hi, what's the correct way of setting up Horizon in multi-server setup?

I have two app servers running behind a load balancer. Then, I have an additional server for a Redis database. Both app servers are connected to the same Redis databse and running their own Horizon instances (via deamon). Now, the problem is that when I open the Horizon dashboard, there are no supervisors registered and status is showing as "inactive". However, when pushing a new job to the queue, it is registered (but never executed). When I switch the app servers to use their own Redis databases, everything works well.

### Steps To Reproduce

1. Setup a load balancer with two app servers.
2. Setup a server with Redis database.
3. Connect app servers to the Redis database.
4. Run Horizon on both servers via daemon (use the default configuration provided in config/horizon.php).
5. Open Horizon dashboard (I can be routed to either one of the two app servers, depending on load balancing strategy).

Expected result: One supervisor per each app server should be registered.
Actual result: No supervisors are registered and status is showing as "inactive".

**Comment by salvisb** [comment]
Hi @themsaid. Tagging you just in case you could advise on the above.

**Comment by ChristopheBorcard** [comment]
Horizon doesn't support running multiple Horizon instances on the same redis connection:

https://github.com/laravel/horizon/issues/1325#issuecomment-1731117438

**Comment by salvisb** [comment]
> Horizon doesn't support running multiple Horizon instances on the same redis connection:
> 
> [#1325 (comment)](https://github.com/laravel/horizon/issues/1325#issuecomment-1731117438)

Interesting. A while back Jonathan Reinink got it working on Heroku. @driesvints could it be that at some point it was possible to run several Horizon instances on the same Redis connection but then it was removed?

**Comment by driesvints** [comment]
Hi there, we never supported running multiple Horizon instances on the sane Redis connection, sorry. It's just not meant to be used that way.

**Comment by salvisb** [comment]
Hi @driesvints. Thanks for the replay.

Could you advise if there is another way of how to manage jobs across all of the app servers? Would the "correct" setup be having a dedicated server running Horizon and Redis?
