### ISSUE TITLE
Ability to add custom load balancing for realtime queues

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#134]
We have a use-case in which

1. Jobs should be immediately popped out of the queues after being pushed. The pop() method of the queue driver should support waiting when the queue is empty and should return the job immediately after the job is pushed. For that I have my own Redis queue driver.
2. There is no need to retry failed jobs.
3. A queue should be flushed when there are more than a configurable number of jobs waiting in it. The number may be as small as 1.
4. In order to minimize response time and minimize the need to flush the queues, the number of workers on each queue should ideally be more than the number of jobs at any given time.
5. There is really no need to monitor what goes into the queues.

In this use-case I think the load balancer should:
1. Flush the overflowing queues when it has to.
2. Detect the need for scaling up/down based on the amount of time it takes for a workers to pop a job from a queue. The faster the worker pop() the busier the queue is. The load balancer may also consider other metrics such as the average processing time for each job.

Can you help to find out the best way to add this custom load-balancing requirements?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by halaei** [comment]
It is actually a feature request not a question, so your answer is technically wrong. Although ok to close it 😊
