### ISSUE TITLE
Expected Throughput - Ability to see delayed job count as time series

### ISSUE THREAD

**Issue by irakliShengelia** [laravel/horizon#1343]
**Willing to contribute the work if idea is approved**
<img width="1176" alt="image" src="https://github.com/laravel/horizon/assets/59525444/d6b870fa-c065-4bd7-bd0c-11c85baaefeb">

It would be very helpful to have a page in horizon, where you can view the expected load on the queue(s), by time. Ideally, a graph or a table (e.g: hourly) - that would show how many jobs are scheduled to run each x period.

It could look very similar to queue throughput view - it would just show the expected future, instead of snapshots from past.

**Comment by driesvints** [comment]
Hi there, if you want, you can attempt a PR so we can have a look at the code 👍
