### ISSUE TITLE
Queues keep crashing

### ISSUE THREAD

**Issue by bardolf69** [laravel/horizon#1344]
### Horizon Version

5.21.1

### Laravel Version

10.28.0

### PHP Version

8.2.8

### Redis Driver

PhpRedis

### Redis Version

6.2.13

### Database Driver & Version

Postgres 15

### Description

2 or 3 queues are constantly dying and will not come back up until I restart the Horizon daemon with supervisorctl.  When I say they die they stop processing jobs and display a red x in a circle in front of their name.  I have a lot of long-running background jobs so I am running 5 different queues.  Horizon is running on a dedicated worker machine with 4 CPU cores and 8GB of ram.  I can not see anything is the laravel or system logs to explain this, is there somewhere else I should be looking?

### Steps To Reproduce

run many queues with long running jobs

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
