### ISSUE TITLE
Endpoint `/horizon/api/jobs/completed?starting_at=-1&limit=50` keeps returning empty results

### ISSUE THREAD

**Issue by bobmulder** [laravel/horizon#1345]
### Horizon Version

v5.21.3

### Laravel Version

v10.30.1

### PHP Version

8.1

### Redis Driver

Predis

### Redis Version

latest from Forge?

### Database Driver & Version

MySQL

### Description

I am running a Laravel application on Forge, using Horizon to manage our jobs. Today I've done some releases while Horizon kept running.

Since today, the results under 'Completed Jobs' is empty. Sometimes I see some records, but when I refresh the results are gone. I see that `/horizon/api/jobs/completed?starting_at=-1&limit=50` is called, and when I call this endpoint, I get zero results as well (or the few which disappear very soon).

Since Horizon has been working for weeks perfectly, and it's broken now, I think this might be a bug. But to be honest, I have no clue where to search for hints and solutions.

Some things that crossed my mind:
- It looks like the dashboard is providing false statistics, which might be related
- Jobs are certainly executed, I can confirm (via a double check in my database)
- Somewhere in the process I have cleared the cache through `art cache:clear` (which might have been broken something?)
- When calling the API endpoint, the `total` constantly changes (decreasing)

Please let me know if you need some extra information, or if you have some directions for me to work further with.

### Steps To Reproduce

Just run Horizon

**Comment by crynobone** [comment]
> Somewhere in the process I have cleared the cache through art cache:clear (which might have been broken something?)

Laravel Horizon should use RedisJobRepository by default and clearing cache could cause an issue.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by bobmulder** [comment]
Thank you for noticing, @crynobone. Because Horizon has been working perfect, and I'm working serious enough with the Laravel stack, I believe this might be a possible bug instead a support question. Please correct me if I'm wrong ;)
