### ISSUE TITLE
Eviction policy for Redis

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/horizon#1355]
Hi, I'm trying Redis in Digital Ocean. I'm given a few options for setting key eviction, the default is to not evict, however, I wondered if there's any harm in utilising the recommended option here to evict keys and whether Laravel Horizon could implement such a setting to evict keys beyond a memory limit?

![do-eviction](https://github.com/laravel/horizon/assets/25177538/0b2f0e24-c161-44d5-99b6-41ed8be5cdea)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
