### ISSUE TITLE
Show longest running jobs in runtime graph

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/horizon#1356]
Many of my jobs take a while to run, for instance, my `uptime` queue checks people's websites via the Http client within my job file. There could be as many as 300 checks per minute. Most, take less than a few seconds, but some might take 20 seconds, 30 seconds or more.

From what I gather, the Runtime graph is simply an average runtime over the period?

How could I see the max runtime? Would running the snapshot command more often show a better reality of my runtime?

![uptime-runtime](https://github.com/laravel/horizon/assets/25177538/0e2c91af-e2c4-4cbf-b38f-0da86d01ed24)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
