### ISSUE TITLE
Percentage Bug - Job Completed

### ISSUE THREAD

**Issue by suresh-ramani** [laravel/horizon#1357]
### Horizon Version

5.21.4

### Laravel Version

10.10

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

6.0

### Database Driver & Version

Mysql

### Description

![image](https://github.com/laravel/horizon/assets/58903201/78138dd4-2959-4d30-a326-7596a1e44ac6)
![image](https://github.com/laravel/horizon/assets/58903201/572c9d98-68f7-4c3f-9e78-71449b400edf)

### Steps To Reproduce

Automatically

**Comment by driesvints** [comment]
Since only one report has been made so far, I'm going to close this one. We'd appreciate a PR if you could ever figure this one out, thanks.
