### ISSUE TITLE
Laravel Horizon in sub-folder route issue

### ISSUE THREAD

**Issue by mohitsimp** [laravel/horizon#1358]
### Horizon Version

5.21

### Laravel Version

8.83.27

### PHP Version

8.0.30

### Redis Driver

Predis

### Redis Version

7.2.1

### Database Driver & Version

MySQl 8

### Description

I have installed laravel into my cpanel subfolder 

Subfolder Url. :  https://mydomina.com/staging/

I have installed laravel/horizon in the same path with composer but APIS and all working is fine but when we redirect to any other URL it will not work 

if I want to redirect Batches it will auto redirect.to https://mydomina.com/horizon/batches instead of https://mydomina.com/staging/horizon/batches

### Steps To Reproduce

Install Laravel  and horizon into subfolder and run with subfolder URL in browser u will get error

**Comment by driesvints** [comment]
We don't support Laravel in subdirectories sorry. You should not attempt to do this. See https://laravel.com/docs/10.x/installation#directory-configuration
