### ISSUE TITLE
The "--force" option does not exist.

### ISSUE THREAD

**Issue by tanshiqi** [laravel/horizon#1362]
### Horizon Version

5.21.4

### Laravel Version

10.33.0

### PHP Version

8.3.0

### Redis Driver

PhpRedis

### Redis Version

7.2.3

### Description

I used the following command to enter maintenance mode：`php artisan down --secret=1234`
After I use secret to access website. The horizon dashboard show: 

> This application is in "maintenance mode". Queued jobs may not be processed unless your worker is using the "force" flag.

But when I use `php artisan horizon --force`. It returns:  `The "--force" option does not exist.`

So how to use horizon to continue process jobs in maintenance mode？

### Steps To Reproduce

php artisan horizon --force

**Comment by driesvints** [comment]
You typically add this option to your supervisor config. I've sent in a PR to the docs for this: https://github.com/laravel/docs/pull/9233
