### ISSUE TITLE
Jobs are pending and are never processed

### ISSUE THREAD

**Issue by bruniagus** [laravel/horizon#1365]
### Horizon Version

5.21

### Laravel Version

10

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

7.2

### Database Driver & Version

Maria DB 10

### Description

I am processing Jobs, and in some cases when the processes within a function pass to the horizon but are never processed, they remain pending forever.
![image](https://github.com/laravel/horizon/assets/54518256/ce09c1d0-e545-41a7-9eee-fd8e3e5cab55)

### Steps To Reproduce

I am processing Jobs, and in some cases when the processes within a function pass to the horizon but are never processed, they remain pending forever.
![image](https://github.com/laravel/horizon/assets/54518256/ce09c1d0-e545-41a7-9eee-fd8e3e5cab55)

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
