### ISSUE TITLE
Possibility to run via database without using redis

### ISSUE THREAD

**Issue by felipeArnold** [laravel/horizon#1371]
Hello, I would like to check the possibility of using the larave horizon package via the database, without having to use redis in the application, is there a possibility of using the same QUEUE_CONNECTION=database service?

**Comment by crynobone** [comment]
Horizon can only be used with Redis at the moment.

**Comment by joelharkes** [comment]
@crynobone  is all redis logic abstracted in seperate classes? is it possible to build my own driver?

It seems like it is: https://github.com/search?q=repo%3Alaravel%2Fhorizon%20Redis&type=code

I could try to make my own driver perhaps
