### ISSUE TITLE
UI bugs, app.js error

### ISSUE THREAD

**Issue by peterAyd** [laravel/horizon#1372]
### Horizon Version

5.22.0

### Laravel Version

10.31.0

### PHP Version

8.2.7

### Redis Driver

PhpRedis

### Redis Version

7.0.11

## Dashbord
![image](https://github.com/laravel/horizon/assets/125861950/14fb10eb-bc34-4a28-83ca-7c9387f53e91)
![image](https://github.com/laravel/horizon/assets/125861950/06bade77-4d94-4257-ba28-b0774e60bfbb)
![image](https://github.com/laravel/horizon/assets/125861950/69a81c1a-ffd3-4341-9685-ee97df3a07ca)

## Batches / Pending Jobs / Completed Jobs / Silenced Jobs / Failed Jobs
![image](https://github.com/laravel/horizon/assets/125861950/87b060dc-ac97-4209-a0ce-960f998ff2e4)
![image](https://github.com/laravel/horizon/assets/125861950/6b6752a0-4e41-4db1-bd4c-5b54be4da8ab)
![image](https://github.com/laravel/horizon/assets/125861950/6224091f-a80b-4eaa-b1e6-9997a1d1a8da)

### Steps To Reproduce

It's a new project and new installed horizon version.
1. I installed it and excuted the publish command in local, and commit all assets to git.
2. run composer install in server, then i see the horizon page not working.
3. try these two commands: `php artisan vendor:publish --tag=laravel-assets --ansi --force` and `php artisan view:clear`, still the same problems.

**Comment by driesvints** [comment]
I'm currently running this version just fine in production without errors. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
