### ISSUE TITLE
Config to display or hide retry button on failed jobs page

### ISSUE THREAD

**Issue by steelze** [laravel/horizon#1376]
Adding a config option to hide/show the retry button on the failed jobs page would be a valuable feature. Setting the default value to true would ensure the button is initially visible.

This will help to restrict the retrying of failed jobs directly from the horizon page. I'm willing to submit a pull request for this, but I'm uncertain about its general acceptance among other contributors.

**Comment by driesvints** [comment]
Thank you but we have no plans for this right now, sorry.
