### ISSUE TITLE
Drop trimmed jobs

### ISSUE THREAD

**Issue by alirezadp10** [laravel/horizon#1378]
Hey there! 
I've just looked into the workflow of trimming jobs, and I'm wondering why jobs remain in Redis storage when they are removed from the sorted set in Redis. I guess it doesn't have any benefit to abandon these kinds of jobs.
I can send a PR to drop these kind of jobs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
