### ISSUE TITLE
Attempt to read property "failedJobIds" on null - when you navigate to a completed batch

### ISSUE THREAD

**Issue by irakliShengelia** [laravel/horizon#1381]
### Horizon Version

5.16

### Laravel Version

10.42

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

^2.0.2

### Description

When navigating to a completed or a non-existent batch id - horizon throws internal errors in the background.

### Steps To Reproduce

**Reproduction 1**
1. Navigate to https://myapp.test/horizon/batches/9b374ff9-eadd-4f0d-913c-bd3e16d034dc (or any non-existent/completed batch id)
2. See an infinite loader. Check The logs. Stack Trace Below.

**Reproduction 2**
1. Create a batch
2. Click on it on the batches page so you see navigate to the single batch page (with automatic updates)
3. As soon as the batch is completed (reaches 100%) - horizon starts throwing errors in the background
4. Refresh - infinite loader - errors in the background continue

{
    "class": "ErrorException",
    "message": "Attempt to read property \"failedJobIds\" on null",
    "code": 0,
    "file": "/opt/app/vendor/laravel/horizon/src/Http/Controllers/BatchesController.php:63",
    "trace": [
        "/opt/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:254",
        "/opt/app/vendor/laravel/horizon/src/Http/Controllers/BatchesController.php:63",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:43",
        "/opt/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php:21",
        "/opt/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php:19",
        "/opt/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php:20",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:259",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:799",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141",
        "/opt/app/vendor/laravel/horizon/src/Http/Middleware/Authenticate.php:23",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180",
        "/opt/app/app/Http/Middleware/HorizonAuth.php:26",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:180",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:798",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:777",
        "/opt/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php:741",
        "/opt/app/vendor/laravel/framew...
}

**Comment by driesvints** [comment]
Thanks, would love to see a PR for this one.

**Comment by irakliShengelia** [comment]
@driesvints 
Here's a draft PR #1383

**Comment by driesvints** [comment]
We'd still appreciate the same PR being sent to v5, thanks.
