### ISSUE TITLE
Some failed jobs will attempts twice

### ISSUE THREAD

**Issue by lengjunbin-trec** [laravel/horizon#1382]
### Horizon Version

4.3

### Laravel Version

7

### PHP Version

7.4

### Redis Driver

PhpRedis

### Redis Version

7.0.4

### Description

when I check the horizon failed jobs. I saw some failed jobs attempts number is 2.but I didn't set any parameters to make it retry twice.
![image](https://github.com/laravel/horizon/assets/61955063/241b13ba-5688-44b6-b15d-e295cc34851a)

### Steps To Reproduce

I checked the failed jobs detail.if the shows `job has been attempted too many times or run too long. The job may have previously timed out`.the number of Attempts is 2.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
