### ISSUE TITLE
Horizon Gate not work. 5.23

### ISSUE THREAD

**Issue by David-Grass-Feria** [laravel/horizon#1392]
### Horizon Version

5.23

### Laravel Version

10.10

### PHP Version

8.2.15

### Redis Driver

Predis

### Redis Version

2.2

### Database Driver & Version

Mysql

### Description

1. composer require laravel/horizon
2. php artisan horizon:install
3. /app/providers/horizonServiceProvider

```
protected function gate(): void
    {
        Gate::define('viewHorizon', function ($user) {
            return in_array($user->id, [
                1
            ]);
        });
    }
```
5. APP_ENV=production

Anyone can open "http://localhost/horizon/dashboard". Even guests who are not logged in. Only the user with ID 1 should have access.

### Steps To Reproduce

I dont know where the error is. But i think your Gate::authorize not work.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
