### ISSUE TITLE
Horizon Gate Bug 5.23. Anyone can access.

### ISSUE THREAD

**Issue by David-Grass-Feria** [laravel/horizon#1393]
### Horizon Version

5.23

### Laravel Version

10.10

### PHP Version

8.2.15

### Redis Driver

Predis

### Redis Version

Predis

### Database Driver & Version

Mysql

### Description

```
protected function gate(): void
    {
        Gate::define('viewHorizon', function ($user) {
            return in_array($user->id, [
                1
            ]);
        });
    }
```

APP_ENV=production

### Steps To Reproduce

Check Gate::authorize.

**Comment by driesvints** [comment]
I think I just closed an issue for this. Please check out the links I shared on it and do not re-open this.
