### ISSUE TITLE
Redirect Back to Application Dashboard/Homepage

### ISSUE THREAD

**Issue by zarulizham** [laravel/horizon#1395]
Hi, I believe clicking on the "Laravel Horizon" does the same action with "Dashboard" navigation. It is nicer if we have options to redirect back to application dashboard/homepage when click "Laravel Horizon" on the top left.

<img width="292" alt="image" src="https://github.com/laravel/horizon/assets/10229855/0eca664d-e624-469c-97ae-b4a3931b33c1">

**Comment by driesvints** [comment]
No plans for that right now, sorry.
