### ISSUE TITLE
Searching Completed / Pending Jobs

### ISSUE THREAD

**Issue by CharlesBilbo** [laravel/horizon#1398]
Im creating a package for searching the pending / completed jobs but i was wondering if this would be something yall would be interested in as a native feature in horizon.

Here is a link to the repo if you want to look at the code its pretty unintrusive since Redis supports full text searching already.  Let me know what y'all think and if this is a feature y'all want in Horizon I'll open a pull request. 

The only real reason I made this is because at my last company we would run millions of jobs an hour and instead of making a code change to tag the jobs we would just want to search ad hawk. also monitoring jobs starts to take up a lot of memory in redis since there is no TTL on a monitor so this is just a simpler way of searching for jobs ad hawk.

https://github.com/CharlesBilbo/SearchableHorizon

![image](https://github.com/laravel/horizon/assets/9604666/270d31bc-a054-47ea-b0b3-b70196ddef4a)

**Comment by driesvints** [comment]
Hi @CharlesBilbo. I think that idea is great but something like this depends on the amount of code involved and how complicated things get. If you have a PR you can send it over and we can have a look at it. Thanks
