### ISSUE TITLE
failed jobs insert uuid column not found

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/horizon#1402]
### Horizon Version

5.23.2

### Laravel Version

11.1.0

### PHP Version

8.3.*

### Redis Driver

PhpRedis

### Redis Version

latest

### Description

When a job fails, after upgrading to Laravel 11, failed jobs throws Sentry errors relating to my failed jobs table being unable to find a column named `uuid`. I do not have a column that's uuid, I have `id` which is a bigint.

> Column not found: 1054 Unknown column 'uuid' in 'field list' (Connection: mysql, SQL: insert into `failed_jobs`

### Steps To Reproduce

My failed jobs schema:

```php
        Schema::create('failed_jobs', function (Blueprint $table) {
            $table->id();
            $table->text('connection');
            $table->text('queue');
            $table->longText('payload');
            $table->longText('exception');
            $table->timestamp('failed_at')->useCurrent();
        });
```

**Comment by driesvints** [comment]
This table should have a uuid column: https://github.com/laravel/laravel/blob/11.x/database/migrations/0001_01_01_000002_create_jobs_table.php#L39
