### ISSUE TITLE
Jobs per minute is incorrect

### ISSUE THREAD

**Issue by NiclasHedam** [laravel/horizon#141]
![image](https://user-images.githubusercontent.com/770169/30420263-50d674b2-9939-11e7-8e24-f5f3e8662bdf.png)

I have no idea why or where that number is coming from, but It's not correct. The jobs past hour is correct. Is there someplace you want me to look or something I should investigate?

**Comment by themsaid** [comment]
How often do you run snapshots?

**Comment by NiclasHedam** [comment]
I don't run the snapshot command, so unless it has a default, the answer is never.

**Comment by themsaid** [comment]
That's the reason then, what you see is the number of jobs ran since the beginning, you need to schedule the snapshot command every 10 minutes so metrics are properly calculated.

**Comment by NiclasHedam** [comment]
Yeah, I can see it now. Sorry for the inconvenience.

**Comment by vesper8** [comment]
how many snapshots need to exist before the metrics start to work?

I don't know why his defaulted at such a high number.. I have over 7000 jobs queued and mine is stuck on showing 0

and I run a snapshot every 5 minutes too.. is there a way to inspect the list of snapshots?
