### ISSUE TITLE
PHP 8.3 compatibility issue: json_decode() - Passing null to parameter #1 ($json) of type string is deprecated

### ISSUE THREAD

**Issue by deniscsz** [laravel/horizon#1411]
### Horizon Version

5.23.2

### Laravel Version

10.48.4

### PHP Version

8.3.4

### Redis Driver

PhpRedis

### Redis Version

7.2.4

### Database Driver & Version

Mysql 8.0.30 (official DockerHub image)

### Description

After loaded the "Failed Jobs" page in the browser, I'm getting deprecated warnings.

Request:
GET localhost/horizon/api/jobs/failed

Message:
```
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /app/vendor/laravel/horizon/src/Http/Controllers/FailedJobsController.php on line 120
```

### Steps To Reproduce

1. Runs Horizon
2. Dispatch a Job that will be failed
3. Open Horizon Dashboard
4. Goes to "Failed Jobs" section
5. The warning log will be displayed for each ajax request made by the "Failed Jobs" page.

**Comment by driesvints** [comment]
This will be in today's release. Thanks!
