### ISSUE TITLE
The horizon and queue methods must be consistent, so I suggest reading the same value

### ISSUE THREAD

**Issue by shijunti19** [laravel/horizon#1423]
config/horizon.php
`
'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 1,
            'maxTime' => 0,
            'maxJobs' => 0,
            'memory' => 128,
            'tries' => 1,
            'timeout' => 60,
            'nice' => 0,
        ],
    ],
`
   'connection' => 'redis',
Should default to
  'connection'          => env('QUEUE_CONNECTION', 'database'),

The horizon and queue methods must be consistent, so I suggest reading the same value

**Comment by driesvints** [comment]
Horizon only works with Redis so this default is fine.
