### ISSUE TITLE
Dashboard problems with a wrong absolute path

### ISSUE THREAD

**Issue by sergiq** [laravel/horizon#1431]
### Horizon Version

5.24.3

### Laravel Version

11.5.0

### PHP Version

8.2.14

### Redis Driver

PhpRedis

### Redis Version

6.0.2

### Description

I'm having issues with the Dashboard. Every time I load it, it shows a problem related to the open_base dir.

Upon investigating, I noticed that the file `vendor/laravel/horizon/resources/views/layout.blade.php` assigns the absolute path` /vendor/horizon/nonExistentFile` to the variable `$nonExistentFileName` (line 5). This path is used by Vite in `vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:792` to detect the mode in which to run.

The issue is that when it tries to do `is_file`, as the absolute directory `/vendor/horizon/nonExistentFile` is not usually included in the `open_base_dir ` (and I don't think it should be), it fails and displays a 5XX error.

If line 5 `$nonExistentFileName = '/vendor/horizon/nonExistentFile';` is changed to a relative path or to the correct absolute path, the Dashboard panel works correctly` $nonExistentFileName = 'vendor/horizon/nonExistentFile';`

I have migrated to Laravel 11 from Laravel 10.

### Steps To Reproduce

Deploy any laravel 11 project that use Horizon

**Comment by mmachatschek** [comment]
Fixed by https://github.com/laravel/horizon/pull/1427

**Comment by driesvints** [comment]
Gonna close this one as a duplicate for now. Thanks
