### ISSUE TITLE
Filter by Queue on recent jobs.

### ISSUE THREAD

**Issue by fhferreira** [laravel/horizon#1434]
my suggestion is to add a filter by queue direct into **horizon/recent-jobs** to make easy to see a specific queue on it.

**Comment by fhferreira** [comment]
also the same for failed_jobs

**Comment by driesvints** [comment]
Thanks. Right now we don't have plans for this sorry.

**Comment by fhferreira** [comment]
And what about just adding a view link in
*monitoring recent/failed jobs?*
![image](https://github.com/laravel/horizon/assets/140686/d3be53e6-22e0-4311-95a4-b213401e547a)
