### ISSUE TITLE
Dashboard opens blank page

### ISSUE THREAD

**Issue by vldmrnktn** [laravel/horizon#1437]
### Horizon Version

5.24.3

### Laravel Version

11.6.0

### PHP Version

8.3.6

### Redis Driver

PhpRedis

### Redis Version

6.0.2

### Description

Horizon dashboard opens blank page
Browser console only shows error:
`Uncaught SyntaxError: export declarations may only appear at top level of a module`

### Steps To Reproduce

Open `localhost/horizon` in browser

**Comment by vldmrnktn** [comment]
Works fine with horizon **5.23.2**

**Comment by mmachatschek** [comment]
same as https://github.com/laravel/horizon/issues/1430

**Comment by driesvints** [comment]
This is now fixed in v5.24.4
