### ISSUE TITLE
is_file(): open_basedir restriction in effect. File(/vendor/horizon/nonExistentFile) is not within the allowed path(s): (/var/www:/var/lib/php/session:/tmp:/usr/bin)

### ISSUE THREAD

**Issue by ArthurPatriot** [laravel/horizon#1443]
### Horizon Version

5.24.4

### Laravel Version

10

### PHP Version

8.2

### Redis Driver

PhpRedis

### Redis Version

6

### Description

`is_file(): open_basedir restriction in effect. File(/vendor/horizon/nonExistentFile) is not within the allowed path(s): (/var/www:/var/lib/php/session:/tmp:/usr/bin)`

### Steps To Reproduce

Use Horizon 5.24.4 and open home page

**Comment by ArthurPatriot** [comment]
`vendor\laravel\horizon\resources\views\layout.blade.php` - problem with this path `/vendor/horizon/nonExistentFile`.

**Comment by timacdonald** [comment]
v5.24.4 does not include any reference to `nonExistentFile`.

Perhaps you have a cached view from v5.24.3. Can you please try running `php artisan view:clear`?

**Comment by davidgil** [comment]
Same here, I see this stacktrace, cleaning view cache without effect:

`ERROR
is_file(): open_basedir restriction in effect. File(/vendor/horizon/nonExistentFile) is not within the allowed path(s): (/var/www/vhost/online.saltoki.com:/tmp/) (View: /var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/horizon/resources/views/layout.blade.php)
Context
{
    "url": "https://online.saltoki.com/horizon",
    "input": [],
    "userId": 43,
    "exception": {
        "class": "Illuminate\\View\\ViewException",
        "message": "is_file(): open_basedir restriction in effect. File(/vendor/horizon/nonExistentFile) is not within the allowed path(s): (/var/www/vhost/online.saltoki.com:/tmp/) (View: /var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/horizon/resources/views/layout.blade.php)",
        "code": 0,
        "file": "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:794",
        "trace": [
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:60",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:72",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/View/View.php:207",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/View/View.php:190",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/View/View.php:159",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/Http/Response.php:69",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/Http/Response.php:35",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/Routing/Router.php:918",
            "/var/www/vhost/online.saltoki.com/htdocs/releases/20240513171809Z/vendor/laravel/framework/src/Illuminate/Routing/Router.php:885",
            "/var/www/vhost/online.s`

**Comment by timacdonald** [comment]
Going to close this one. Let us know if you are still having issues.

**Comment by michaelklopf** [comment]
I'd like to add that I had this problem out of the blue and upgrading to v5.24.4 helped to solve the problem. Took a while to find the issue though.

**Comment by timacdonald** [comment]
Great to know that 5.24.4 fixed the issue for you.
