### ISSUE TITLE
laravel horizon on remove says HorizonApplicationServiceProvider not found

### ISSUE THREAD

**Issue by raphaelobinna** [laravel/horizon#1444]
### Horizon Version

5.24

### Laravel Version

10.48.10

### PHP Version

8.1

### Redis Driver

PhpRedis

### Redis Version

0

### Description

I innstalled the laravel horizon package to help monitor my queues but I later found out that I didn't need it any more, I tried to uninstall it from my application and it says 

In HorizonServiceProvider.php line 9:
                                                                       
  Class "Laravel\Horizon\HorizonApplicationServiceProvider" not found  
                                                                       

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### Steps To Reproduce

I just ran 

`composer remove laravel/horizon`

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DonCamillo11** [comment]
Same here. The package appears not to be completely uninstalled

**Comment by nuzulfikrie** [comment]
i also encounter similar situation, reinstalling it also raised similar issue

**Comment by ccqwe123** [comment]
still the same until now
im using laravel 9 and 10
but im getting this error when i try to uninstall it
i uninstalled it coz it doesnt support windows

**Comment by lucianolima00** [comment]
For those who still having this problem, the solution is going to `bootstrap/cache/packages.php` and search for `laravel/horizon` and remove it, run the `php artisan config:clear` and `php artisan cache:clear`
