### ISSUE TITLE
How to throw the job into horizon

### ISSUE THREAD

**Issue by lengjunbin-trec** [laravel/horizon#1446]
I will explain why I am asking this question.
I have a laravel project with horizon.and this laravel framework has some api.
when a new api request coming.laravel need load all service provider file.it need a lot of time.
so I decide to create another project Lumen.because Lumen faster than Laravel.
new api call Lumen.and Lumen throw the job into laravel horizon .then laravel deal with the api request.

now my question is how Lumen throw the job into laravel horizon.Can anyone help me?

**Comment by driesvints** [comment]
Our first party packages aren't compatible with Lumen: https://lumen.laravel.com/docs/11.x#compatibility

<img width="724" alt="Screenshot 2024-05-16 at 09 44 27" src="https://github.com/laravel/horizon/assets/594614/f2f096a2-d988-4e65-97fc-27720b5fc6c5">


We also very much recommend stepping away from Lumen and using Laravel instead. We no longer recommend new apps on Lumen. https://laravelshift.com/convert-lumen-to-laravel
