### ISSUE TITLE
Feature Request: Warn the user if no supervisor configuration is present in the selected environment

### ISSUE THREAD

**Issue by yudikubota** [laravel/horizon#1447]
I just spent an awful lot of time trying to debug why horizon was not running just to realize I was on staging environment and there was no staging supervisors... 

I think it would be nice to warn the user if no supervisors are configured.

**Comment by driesvints** [comment]
But doesn't the dashboard show no supervisors in the list in that scenario?

**Comment by yudikubota** [comment]
> But doesn't the dashboard show no supervisors in the list in that scenario?

Yeah, but I didn't check the dashboard, only the CLI as it was running inside a docker container for staging environment.

This is a feature request for the CLI. Something like:

```bash
php artisan horizon

INFO  Horizon started successfully.  

WARN no supervisor configuration for environment "staging"
```

I ask you to consider reopening this issue. Maybe other people stumble upon this exact mistake.

**Comment by driesvints** [comment]
Ah right, I understand. Yeah I can see that being useful, feel free to attempt a PR 👍

**Comment by yudikubota** [comment]
> Ah right, I understand. Yeah I can see that being useful, feel free to attempt a PR 👍

Just made my first PR to this repo.
