### ISSUE TITLE
Behind an nginx TLS proxy, Horizon tries to load ajax calls from HTTP

### ISSUE THREAD

**Issue by mattiasgeniar** [laravel/horizon#145]
I run Horizon behind an Nginx proxy that handles SSL/TLS, and Apache is acting as the webserver that only does HTTP + PHP handling.

When I try to load the recent jobs, Horizon gives this error in the console;

```
Mixed Content: The page at 'https://staging.xxx/horizon/recent-jobs' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://staging.xxx/horizon/api/jobs/recent?starting_at=-1&limit=50'. This request has been blocked; the content must be served over HTTPS.
```

I'm not sure where to fix this in vuejs, it appears to come from `resources/assets/js/pages/RecentJobs/Jobs.vue` with this line;

```
return this.$http.get('/horizon/api/jobs/recent/' + '?starting_at=' + starting + '&limit=' +
```

It _looks_ like `this.$http.get` doesn't keep the `X-Forwarded-Proto` in mind, like [fideloper/TrustedProxy](https://github.com/fideloper/TrustedProxy)?

**Comment by alexgarrett** [comment]
I'm having the same issue here.

**Comment by mattiasgeniar** [comment]
I tracked this down to the [axios HTTP client](https://github.com/mzabriskie/axios#creating-an-instance) used by Vuejs, but it looks like a rabbithole to get it fixed. Would need a config to be passed on to the view to overwrite the `baseURL`.

The Horizon code defines the HTTP client as such;

```
resources/assets/js/app.js:Vue.prototype.$http = axios.create();
````
Currently without the ability to overwrite the options given to the `create()` call.

**Comment by alexgarrett** [comment]
I've actually found a solution my end, hope this helps you.

In the default .htaccess for Laravel, I removed this:

```
# Redirect Trailing Slashes If Not A Folder...
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L,R=301]
```

Probably not the best solution long-term, but I'm using a standalone app just for Horizon, so it doesn't affect anything else for me.

**Comment by mattiasgeniar** [comment]
Interesting, that fixes it for me as well. Will look at that .htaccess file to determine the protocol better!

**Comment by cucxabeng** [comment]
I have a same issue, I use forge and envoyer to manage env and deploy my source code 

I just want use https only (behind cloudeflare https)

Please help me..

**Comment by jstenquist** [comment]
I have the same issue. I experimented with .htaccess, but was unable to work around it.

**Comment by mattiasgeniar** [comment]
I made PR #165 that should resolve this.

**Comment by AndreFilho0** [comment]
To solve this (Mixed Content error ), I used this in my env :  ASSET_URL
