### ISSUE TITLE
Undefined variable $assetsAreCurrent

### ISSUE THREAD

**Issue by aleedksa** [laravel/horizon#1457]
### Horizon Version

5.24

### Laravel Version

10.30.1

### PHP Version

8.2.18

### Redis Driver

PhpRedis

### Redis Version

6.0.16

### Database Driver & Version

MySQL 8 on WSL for windows

### Description

When accessing the horizon dashboard in the web using the URL site.test/horizon it throws this error. Also sharing the Flare share URL of the error. https://flareapp.io/share/q5YJB4xm

### Steps To Reproduce

Go to the /horizon URL of your application to access the Horizon dashboard.

**Comment by aleedksa** [comment]
Need to run `php artisan view:clear` after you run the `composer update`.

**Comment by njoguamos** [comment]
`php artisan clear` worked. Thank you.
