### ISSUE TITLE
Any interest for a PR to move from Vue 2 to Vue 3?

### ISSUE THREAD

**Issue by nckrtl** [laravel/horizon#1458]
I noticed the project is still using Vue 2. As Vue 2 has officially reached EoL this year (https://v2.vuejs.org/eol/) it would make sense to move to Vue 3 at some point. Would there be any interest for a PR to make the switch to Vue 3?

I would consider moving the components to the new Composition API out of scope, as the Options API in which the components are currently written is still supported in Vue 3. However, if there is interest to transform the components to use the Composition API I can look into that as well.

**Comment by crynobone** [comment]
Feel free to send PR if you wish to contribute. However, it might be best to stick with Option API on Vue 3 to get it pass code reviews.
