### ISSUE TITLE
Specifying path to php

### ISSUE THREAD

**Issue by jamesmills** [laravel/horizon#146]
Hi,

In both vendor/laravel/horizon/src/SupervisorCommandString.php and vendor/laravel/horizon/src/WorkerCommandString.php we have 'exec php...' commands. 

Unfortunately for me I have to specify the full path to php so I am unable to use Supervisord to monitor Horizon.

Can we add a config option to optionally override the path to php for custom setups, please?

**Comment by neorganic** [comment]
Why is specifying the full path to php causes a problem ?

**Comment by jamesmills** [comment]
Inside my Supervisord config I have this

```
command=/usr/local/bin/php /home/webs/website.com/current/artisan horizon
```

I cannot use just 'php' because the user that runs Supervisord does not know where that is. So Supervisord actually starts up fine but then there are some 'exec php artisan horison:whatever' commands as part of the boot up and when the user gets to these it cannot run them. So it's the part that boots the process workers that is not working because I have to tell it where php is.

Hope this clarifies, I am not sure how unique this case is.

**Comment by neorganic** [comment]
@jamesmills  try adding `environment=PATH="/usr/local/bin"` to your supervisor .conf file. This helped for me #117 <-- for more info you can check this issue.

**Comment by jamesmills** [comment]
@neorganic thank you. This has fixed our issue.
