### ISSUE TITLE
Incorrect status on duplicate worker

### ISSUE THREAD

**Issue by jasonmccreary** [laravel/horizon#1461]
### Horizon Version

5.24.5

### Laravel Version

10.48.12

### PHP Version

8.3.1

### Redis Driver

Predis

### Redis Version

2.2.2

### Description

A bit of an edge-case here, but I have duplicate workers that spin up which have the same configuration - supervisor and horizon.

I noticed that if I run `horizon:pause` on _worker-1_, then spin up a new worker (_worker-2_) `horizon:status` still says "Paused". However, the Horizon web dashboard correct shows the "play" icon for _worker-2_ and "paused" icon for _worker-1_.

I'm glad to dig into the code, but don't have time now. So I wanted to get this tracked somewhere. My guess is the logic the `horizon:status` command uses to check status is not the same as the logic the web dashboard uses.

---
I've attached some screenshots for a visual diff of the issue where the web dashboard show the status correctly, but CLI does not.

**Horizon Dashboard**
<img width="1209" alt="Horizon web dashboard" src="https://github.com/laravel/horizon/assets/161071/2e64dc0c-d9c2-4e27-82c6-4145c5f90783">

**CLI**
<img width="618" alt="horizon:status command output" src="https://github.com/laravel/horizon/assets/161071/8075b051-c333-4de4-8a73-5a70b754ac64">

### Steps To Reproduce

- Start two identical workers with the same supervisor and horizon config
- Run `horizon:pause` on one
- Start the other worker
- Run `horizon:status` on the other

**Comment by mfrieswyk** [comment]
The `horizon:list` command checks all registered supervisors, and if just one has a "paused" status it outputs "Horizon is paused". What would be the preferred output here @jasonmccreary? A table similar to the dashboard?

**Comment by jasonmccreary** [comment]
@mfrieswyk, I would expect if I am on the worker and run `horizon:status` it would show the current status for that worker.

In lieu of that, then yeah, a list of all worker statuses would be better, imo, than saying "paused" when the current worker is not the one that is paused.

**Comment by mfrieswyk** [comment]
@jasonmccreary I went ahead and made [this PR](https://github.com/laravel/horizon/pull/1467) to address this issue. It's not a full list of all worker statuses because I felt like changing the behavior of the main status command might be a bit much. Instead I made a new command in the style of the pause/continue commands that requires a name of the supervisor you would like the status for. Hope this helps.

**Comment by driesvints** [comment]
@mfrieswyk do you have time to answer Taylor's question on that PR?

**Comment by driesvints** [comment]
I'm going to close this one for now since it's been a while. Would still love to receive a working PR or work being picked up on the PR above. Thanks

**Comment by mfrieswyk** [comment]
@driesvints sorry for the delay, pushed updates to the PR
