### ISSUE TITLE
Laravel Action Used As Job Is Not Implementing Silenced Interface

### ISSUE THREAD

**Issue by nouman-ashraf-awan** [laravel/horizon#1463]
I have a laravel action which is being dispatched via command. AsJob trait is initialized in Action. Also it implements shouldQueue. I have also implemented Silenced Interface along with ShouldQueue. Also defined Action in silenced array in horizon.php. But its not working. Jobs can be seen in Completed and Failed Jobs On Horizon.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
