### ISSUE TITLE
Display Laravel Context on the Job view

### ISSUE THREAD

**Issue by flexchar** [laravel/horizon#1470]
Hey, the new laravel context feature is great. 

Often times custom logging is not needed but sometimes it would be extremely helpful to see the existing context on the jobs in Horizon just as we see the payload or custom tags for the lifetime of the job. 

> When the job is dispatched, any information currently stored in the context is captured and shared with the job. The captured information is then hydrated back into the current context while the job is executing. So, if our job's handle method was to write to the log ... The resulting log entry would contain the information that was added to the context during the request that originally dispatched the job.
https://laravel.com/docs/11.x/context#how-it-works

Would it be possible to expose that in UI since it's already made available for logging?

**Comment by driesvints** [comment]
Hi @flexchar. Best that you attempt a PR to see if Taylor would accept. Thanks.
