### ISSUE TITLE
Ability to customise notifications

### ISSUE THREAD

**Issue by lukemorcom** [laravel/horizon#1475]
We are running multiple test environments for our app, and only one Slack channel, to avoid having tons of channels. It would be great to be able to customise the notifications we receive, so we can include the server name in the message that's sent. I imagine this would be useful for other notification channels too. Anyone know if it's possible? Looking at the source it doesn't seem so

**Comment by driesvints** [comment]
Thanks. Right now we don't have plans to work on this. Feel free to attempt a PR to achieve what you need.
