### ISSUE TITLE
Redis RAM than expected ！

### ISSUE THREAD

**Issue by fangyuan0306** [laravel/horizon#1477]
### Horizon Version

5.16.1

### Laravel Version

10.13.2

### PHP Version

8.1.28

### Redis Driver

PhpRedis

### Redis Version

6.2.1

### Description

Key	Data Type	Encoding	Memory Usage (Bytes)	Number of Elements	Max Element Length	Average Element Length	Expiration Timestamp
ai_orion_horizon:recent_jobs set	skiplist	577,221,526	4,204,694	36	36	0
ai_orion_horizon:completed_jobs set	skiplist	577,185,982	4,204,534	36	36	0
ai_orion_horizon:failed_jobs	set	skiplist	21478	159	36	36	0
ai_orion_horizon:recent_failed_jobs	set	skiplist	21422	159	36	36	0
<img width="532" alt="image" src="https://github.com/user-attachments/assets/866291fc-216b-40da-9bb4-3d56196f6647">
I've found that its elements are continuously growing and they do not expire.
    'trim' => [
        'recent' => 60,
        'pending' => 60,
        'completed' => 60,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],

### Steps To Reproduce

The elements are always present; why isn't the expiration policy taking effect?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
