### ISSUE TITLE
Monitored tags not displaying recent or failed jobs

### ISSUE THREAD

**Issue by therobfonz** [laravel/horizon#1478]
### Horizon Version

5.25.0

### Laravel Version

10.48.14

### PHP Version

8.3.8

### Redis Driver

PhpRedis

### Redis Version

6.2.6

### Database Driver & Version

Postgis 14 for Ubuntu 22.04

### Description

We have several jobs that have tags defined in them for horizon to use
```
public function tags(): array
    {
        return ['customer-teams-migration'];
    }
```

When visiting `horizon/monitoring`, and adding a tag to monitor, I can see the tag and the count just fine.
<img width="1046" alt="Screenshot 2024-07-22 at 4 09 44 PM" src="https://github.com/user-attachments/assets/665bb013-95d4-490e-94db-81d40852d370">

However, when clicking into that monitored tag to see the most recent or failed jobs, the loading indicator just keeps spinning and the following error is thrown
```
Too few arguments to function Laravel\\Horizon\\Http\\Controllers\\MonitoringController::paginate(), 1 passed in 
```

### Steps To Reproduce

1. Add a tag definition to any job
2. Go into Horizon and add that tag to be monitored
3. Drop a job with that tag into the queue and let it finish
4. Go to `horizon/monitoring` and click on the monitored tag name to view the details.  The loading indicator will just spin and throw the network error mentioned above

**Comment by driesvints** [comment]
Thank you. Would appreciate a PR for this one.

**Comment by antoniovalenzuela** [comment]
Hi,
Updated to v5.27.1 but I can see the jobs from monitored Tags.

Message "There aren't any jobs for this tag"

- Flush Redis Keys
- Cleaned Artisan config, cache, views
- Jobs Completed Ok

Completed
![image](https://github.com/user-attachments/assets/6a9283c3-d80b-4db0-addd-088fe3fa61cd)

Monitoring
![image](https://github.com/user-attachments/assets/e4e425d6-3719-474a-a1ac-eab4c29c2aef)
![image](https://github.com/user-attachments/assets/cbc290c7-56f9-4d12-966c-2857c65ef74f)

**Comment by driesvints** [comment]
cc @therobfonz ^

**Comment by therobfonz** [comment]
I think I forgot to recompile the JS for distribution with the fix (newb contributor here). 

I'll try and carve out some time to investigate this week.

**Comment by driesvints** [comment]
@therobfonz assets are compiled whenever something's merged to the default branch so that can't be it. Maybe you didn't recompile locally while testing?

**Comment by therobfonz** [comment]
@driesvints i thought I did and had it working but possible I missed something when I moved over to the repo.

**Comment by therobfonz** [comment]
@driesvints I checked this morning, and it doesn't look like  `/dist/app.js` updated with the merge of my PR. I confirmed this by running `npm run build` with the latest horizon installed in my project and the tag monitoring page worked.

When I look at the Action that commits the recompiled assets after the merge of my PR it says 'Nothing to commit', which is most likely the issue. 

After compiling the JS locally
<img width="1226" alt="Screenshot 2024-08-20 at 9 05 08 AM" src="https://github.com/user-attachments/assets/f4f44c90-8280-4ecb-97a0-9b01919651ec">

**Comment by driesvints** [comment]
Bit stumped here. I can't figure out why assets aren't compiling the same on the action as they do locally. Here's a new run I tried with Node 21 like I have locally: https://github.com/laravel/horizon/actions/runs/10473422636/job/29005245820

Still shows no changes to commit. Really need to figure this one out because it's not good if changes like these aren't being compiled anymore...

**Comment by daniser** [comment]
@driesvints I think I found the reason behind this (see PR #1495).

**Comment by daniser** [comment]
That's weird, but [still nothing](/laravel/horizon/actions/runs/10703353084/job/29673733201)😕. Maybe assets are already up-to-date?
```
Run stefanzweifel/git-auto-commit-action@v5
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: dist/
Working tree clean. Nothing to commit.
```

**Comment by driesvints** [comment]
Yeah I think so. I've just done a new release so let's see if things work now.

**Comment by ariamVille** [comment]
> Hi, Updated to v5.27.1 but I can see the jobs from monitored Tags.
> 
> Message "There aren't any jobs for this tag"
> 
> * Flush Redis Keys
> * Cleaned Artisan config, cache, views
> * Jobs Completed Ok
> 
> Completed ![image](https://private-user-images.githubusercontent.com/28113584/357505830-6a9283c3-d80b-4db0-addd-088fe3fa61cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTc3NjUsIm5iZiI6MTcyNzg1NzQ2NSwicGF0aCI6Ii8yODExMzU4NC8zNTc1MDU4MzAtNmE5MjgzYzMtZDgwYi00ZGIwLWFkZGQtMDg4ZmUzZmE2MWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA4MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMGNmZDlkOTgxOTU4YTUxOTM1NjUxZGY1MTQxMjYzZmY5NDkxODYwY2JlMzFhMDY1NDE0ZWZjYTY4Zjg0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dg_fu5iabO56d5fPiqO0nKOnr-_KyZEBI2_45FSodCA)
> 
> Monitoring ![image](https://private-user-images.githubusercontent.com/28113584/357505456-e4e425d6-3719-474a-a1ac-eab4c29c2aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTc3NjUsIm5iZiI6MTcyNzg1NzQ2NSwicGF0aCI6Ii8yODExMzU4NC8zNTc1MDU0NTYtZTRlNDI1ZDYtMzcxOS00NzRhLWExYWMtZWFiNGMyOWMyYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA4MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGY2ODg5ZjkxZGI1MGVlYzFjOGUzOWJjMWVhM2JjYWVmYmQwNTdmN2ZlNmY4YzQ5ZjFhOTcwMWJlNDI4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kfr47uUx5i7cfMeJU1R4JfJPLvX-qBoFHeyxPhlFFsI) ![image](https://private-user-images.githubusercontent.com/28113584/357506279-cbc290c7-56f9-4d12-966c-2857c65ef74f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTc3NjUsIm5iZiI6MTcyNzg1NzQ2NSwicGF0aCI6Ii8yODExMzU4NC8zNTc1MDYyNzktY2JjMjkwYzctNTZmOS00ZDEyLTk2NmMtMjg1N2M2NWVmNzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA4MjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MDhjOThmYWIzMTBkNmFmYzY4YjkyODlkYWU4OGMwZjRiOWE1ODc4MjZkODM1OTcxNWJhNzUzNTczZTY3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-U44Jur-4C_tbK2H6wOCx4a9oqBO0OCs_Q6tR4M4gqg)

this issue still not fixed
