### ISSUE TITLE
Inactive status but jobs are still processing

### ISSUE THREAD

**Issue by timelabs-lucvt** [laravel/horizon#1479]
### Horizon Version

5.25

### Laravel Version

10.10

### PHP Version

8.3.8

### Redis Driver

Predis

### Redis Version

2.2

### Database Driver & Version

mariadb from 11.4.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using readline 5.2

### Description

I used the command "php artisan horizon:pause" and stops all supervisors and crons related to horizon but somehow it still runs. I check my redis data is still generated. Is there any way that can help me?

### Steps To Reproduce

I launch the application with supervisor config
php artisan horizon

Then I stop by command
php artisan horizon:pause

I deleted php artisan horizon in supervisor config and restarted

**Comment by timelabs-lucvt** [comment]
Redis server version is 5.0.7

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
