### ISSUE TITLE
Focused line gets hightlighted

### ISSUE THREAD

**Issue by salfel** [laravel/horizon#1488]
### Horizon Version

5.27

### Laravel Version

11.20

### PHP Version

8.3.9

### Redis Driver

Predis

### Redis Version

7.2

### Database Driver & Version

sqlite on macos

### Description

After I upgraded my laravel application to laravel 11 and updated laravel horizon as well, I noticed, that when hovering, the entire line was highlighted white

I don't know if this is a bug specific to horizon or rather a bug of code display library

https://github.com/user-attachments/assets/7485c26a-cac7-4176-8ff2-ef50750ee111

### Steps To Reproduce

- create fresh new laravel application
- install horizon
- dispatch job
- look into horizon dashboard

**Comment by singleseeker** [comment]
when you get a 5.x version, you'll see the highlights.

https://github.com/laravel/horizon/blob/5.x/dist/styles.css#L6
