### ISSUE TITLE
Big data loses accuracy during front-end rendering

### ISSUE THREAD

**Issue by yangjisen** [laravel/horizon#1490]
### Horizon Version

master

### Laravel Version

10.x

### PHP Version

8.1

### Redis Driver

PhpRedis

### Redis Version

5.0

### Description

![image](https://github.com/user-attachments/assets/9c461218-faa9-4835-9bae-ba3980c28e65)

![image](https://github.com/user-attachments/assets/b91ce0b3-2e47-4252-8375-aa4f4c184bd4)

### Steps To Reproduce

{"android_convert_count":0,"author_amount":0,"author_id":7383119501262323724,"author_name":"云儿短剧","bill_detail":null,"channel_id":"1171257","clue_cnt":0,"demand_id":7405102475113414692,"demand_name":"","douyin_id":null,"iaa_commercial_income_hour":null,"iaa_income":null,"iap_order_income_hour":null,"install_finish_cnt":0,"ios_convert_count":0,"is_own":false,"is_violated":null,"item_click_rate":null,"item_click_rate_double":null,"item_comment":null,"item_feel_good":null,"item_forward":null,"item_id":7405510508809309503,"item_info_daily_list":null,"item_interact_rate":null,"item_view":null,"mcn_amount":0,"open_state":null,"overall_audit_status":null,"play":0,"publish_time":1724230259,"service_provider_amount":null,"share_price":0,"share_price_hour":null,"share_price_total":0,"share_price_total_hour":null,"share_vv":0,"uncorrelated":null,"partner_id":5}

**Comment by driesvints** [comment]
Not really sure what this all is about. Please try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
