### ISSUE TITLE
dispatch job only triggered when other dispatch is called.

### ISSUE THREAD

**Issue by singleseeker** [laravel/horizon#1491]
### Horizon Version

5.27.1

### Laravel Version

10.39.0

### PHP Version

8.2.22

### Redis Driver

PhpRedis

### Redis Version

6.0.2

### Description

I have a Job.

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class SimpleJob implements ShouldQueue
{

    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $message;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($message = "Default message")
    {
        $this->message = $message;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        Log::info("SimpleJob executed with message: " . $this->message);

        echo "SimpleJob executed with message: " . $this->message . "\n";
    }
}
```

And when I use tinker to debug
```
dispatch(new App\Jobs\SimpleJob("Delayed Job!"));
```
It didn't run at all until the next time I called dispatch.

### Steps To Reproduce

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/8d671021-a69e-4cd5-a7d5-dadac7fd6b10">

**Comment by yangjisen** [comment]
I also encountered the same situation

**Comment by singleseeker** [comment]
@driesvints  you've time to have a look? It's weird. Hope to get your help.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
