### ISSUE TITLE
Add a section for Jobs actually executing

### ISSUE THREAD

**Issue by kpconnell** [laravel/horizon#1494]
Pending can mean:
1) Waiting for release time
2) Waiting for resources
3) Running
4) Orphaned (supervisor stopped while job was running) 

It would be extremely useful to be able to interrogate what is actually executing.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. For these, we'd appreciate a pull request instead so we can look at actual code. If you need feedback about an idea, we suggest to [post an idea discussion here](https://github.com/laravel/framework/discussions/categories/ideas) first. Please only use the issue tracker to report bugs and issues with this library.

Thanks!
