### ISSUE TITLE
Horizon does not respect timezone settings

### ISSUE THREAD

**Issue by KristofMorva** [laravel/horizon#151]
I have timezone set in Laravel config, on the VPS and also in PHP config to UTC. Yet, RecentJobs' QueuedAt column still uses some kind of local timezone setting. While it's not necessarily important, it'd be great if it was somehow reliable, preferably dependent on Laravel's config.

**Comment by themsaid** [comment]
Horizon displays time based on the browser timezone.

**Comment by KristofMorva** [comment]
@themsaid thank you, that makes it clear. However, it may be a little misleading when you compare these times with logs, or other team members in a different timezone.
