### ISSUE TITLE
Impossible to determine what is running

### ISSUE THREAD

**Issue by kpconnell** [laravel/horizon#1523]
### Horizon Version

5.1.3

### Laravel Version

9.52.16

### PHP Version

8.1.3

### Redis Driver

PhpRedis

### Redis Version

7.2.4

### Database Driver & Version

na

### Description

Mark job as reserved does not provide enough information in the repository to determine where it is running, and there is no mechanism to determine if something is presently executing (as opposed to orphaned, in the the situation where the supervisor/worker has restarted)   This is a fatal flaw for any job scheduling solution.  

### Steps To Reproduce

start a job
stop horizon
inspect redis for reserved data
find that job is still there and job has no metadata about where it was/is running

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
