### ISSUE TITLE
Failed jobs always show loading

### ISSUE THREAD

**Issue by xarasbir** [laravel/horizon#153]
![image](https://user-images.githubusercontent.com/918850/30740417-7766b85e-9fc3-11e7-9dba-70964942d018.png)

 Failed Jobs displays endless loading indicator even when the requests already respond (below).

![image](https://user-images.githubusercontent.com/918850/30740469-a636dc04-9fc3-11e7-9556-191426bff734.png)

**Comment by themsaid** [comment]
Check if there are any errors in the console.

**Comment by vivg** [comment]
I'm having the same problem. No errors in console. Though I'm queueing from Laravel 5.4 while using horizon to process the queued data. There's one difference I noticed. All the items queued from Laravel 5.5 have a numeric id while items queued from 5.4 have an alphanumeric id.

**Comment by themsaid** [comment]
@vivg 

>I'm queueing from Laravel 5.4

Don't do that :) This is very wrong, Horizon is 5.5 only and requires php 7.1

**Comment by vivg** [comment]
@themsaid Yep. I know but I didn't see any mention in the release notes for 5.5 changing the id type so I thought it was interoperable. Once I've some time I'll go through the internals. I've gone through the queue internals carefully earlier to get a legacy CakePHP app to queue stuff which was processed by Laravel workers.

**Comment by reinink** [comment]
For what it's worth, we're running into the same issue. We are on Laravel 5.5. No console errors, and yet the loading indicator continues and no failed jobs are shown. Weirder yet, this isn't happening locally, only in staging.

![image](https://user-images.githubusercontent.com/882133/30989146-b1f96dd0-a46a-11e7-8ed2-7134bc0f548b.png)

![image](https://user-images.githubusercontent.com/882133/30989162-be0b9a8a-a46a-11e7-9097-39989baac0fc.png)

**Comment by hotmeteor** [comment]
Update to @reinink's post, this is happening in our production environment too.

**Comment by jwondrusch** [comment]
Same story in our production server as well.  Recent jobs works fine.

Using Redis Elasticache.

**Comment by themsaid** [comment]
Hello everyone, I've setup a simple error handler in dev-master that should display some useful information in the console with the case mentioned, can someone who can replicate the issue please pull the latest on dev-master and make sure he's running the latest assets and share the error he sees in the console?

**Comment by elghobaty** [comment]
Having the same issue but on the failed job details page (for a particular job only)

**Comment by SturmDrangAltaar** [comment]
Had the same problem as stated here after initial install. Seemed like there was some old failed jobs in the failed_jobs table and redis. Truncated the failed_jobs table and deleted the key in redis, then restarted horizon, seems to be ok now.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
