### ISSUE TITLE
Laravel Horizon with XAMPP

### ISSUE THREAD

**Issue by ForzaSFerrari** [laravel/horizon#154]
Hi,
I've installed a new Laravel with XAMPP 7.1.9 (PHP 7.1.9) and get following error. 'Could not find package laravel/horizon at any version matching your PHP version 7.0.9.0'

How I can get Laravel Horizion if phpinfo says too that I have PHP Version 7.1.9?

**Comment by themsaid** [comment]
check the php version of your php-cli .. the one in phpinfo() is the one for php-fpm.

I'm not familiar with XAMPP to give more details, sorry :)

**Comment by ForzaSFerrari** [comment]
Don't know why but php-cli says 7.0.9 too. That's everyting is included for XAMPP 7.1.9 https://www.apachefriends.org/download.html

**Comment by danieluyo** [comment]
Check you PHP-CLI  version
![captura de pantalla 2017-09-25 a la s 12 13 35](https://user-images.githubusercontent.com/17558554/30821431-fc9628c4-a1ea-11e7-95a0-c29769b43c21.png)

XAMPP its a web server solution stack only... ¿Why not trying [Homested](https://laravel.com/docs/5.5/homestead) or [Valet](https://laravel.com/docs/5.5/valet) ... or [MAMP 4](https://www.mamp.info/en/downloads/)?

**Comment by PixellUp** [comment]
**pcntl ** extension is not supported on Windows. (based on your XAMPP information)

#131 
#78

**Comment by ForzaSFerrari** [comment]
if i understand it right then is horizon not usable on windows?

**Comment by chrisbjr** [comment]
Okay, the only solution I see with this for now is moving the whole team to Mac or Ubuntu. lol 🙄

**Comment by danieluyo** [comment]
¿Why not trying use php, apache/nginx, MySQL stack (not MAMP/XAMPP)?

**Comment by devcircus** [comment]
If you're developing on windows just use a vm. Laravel Homestead is a simple solution here.

**Comment by ronnyandre** [comment]
Same issue on Google Cloud VM (Debian 9, PHP-FPM 7.0.19)

**Comment by royalabhi17** [comment]
you can solve it by using composer with this command   
 $composer install --ignore-platform-reqs ext-pcntl ext-posix
else 
composer install --ignore-platform-reqs

**Comment by pedrogaldino** [comment]
Same issue here on windows. 
I don't think that change all my environment because of a php extension is not really a good solution...

Solving for now using the @royalabhi17 solution...

**Comment by youkineko** [comment]
@pedrogaldino @ForzaSFerrari on windows 10 you can try the Ubuntu app from the windows app store.
It will allow you to install horizon and you can run it from there.

**Comment by driesvints** [comment]
Closing this in favor of https://github.com/laravel/horizon/issues/170#issuecomment-433040421

**Comment by PhilippeDirx** [comment]
I think it's sad that we can't work on Windows with Horizon just because of an extension...
I have worked with Homestead before, but it's 10 times slower than for example XAMPP.

**Comment by safakocamanoglu** [comment]
> I think it's sad that we can't work on Windows with Horizon just because of an extension...
> I have worked with Homestead before, but it's 10 times slower than for example XAMPP.

Greetings from 2021. It is very unfortunate that no progress has been made in this regard.

**Comment by driesvints** [comment]
@safakocamanoglu it's also very unfortunate that you expect us to work on this for free.

**Comment by thgiang** [comment]
![image](https://github.com/laravel/horizon/assets/9299251/8804b898-fb0d-4e45-9f19-54af09644083)
Even if you go through the composer installation step, you still cannot run horizon because it calls the pcntl function unforgivingly

**Comment by jcsoriano** [comment]
> I think it's sad that we can't work on Windows with Horizon just because of an extension... I have worked with Homestead before, but it's 10 times slower than for example XAMPP.

Just curious, is `sail` any better now? I think it has replaced Homestead and is the go-to in 2024
