### ISSUE TITLE
Horizon named routes

### ISSUE THREAD

**Issue by lriggle-strib** [laravel/horizon#155]
If I want to provide a click-to-use link within my application for accessing horizon's dashboard, there are no route names to use with laravel's `route` function. While there are obviously other ways to create URLs/links within the laravel application, using the route helper requires no additional includes to work on any page and can easily be used in templates to generate correctly formatted URLs.

This would be a small, but useful, addition.

**Comment by markwalet** [comment]
Every route is named except for the one I want to see named. I want to redirect my users to the `HomeController@index` route.

**Comment by driesvints** [comment]
Seems like every route is named now.
