### ISSUE TITLE
long prefix and long model names cause could use some overflow handling

### ISSUE THREAD

**Issue by vesper8** [laravel/horizon#156]
I know there was a recent change to overflow-x on panel-content but it is still causing a problem in the Recent Jobs view if you have very long Model names

![screenshot 2017-09-22 18 33 04](https://user-images.githubusercontent.com/816028/30766663-a227585e-9fc4-11e7-8fbc-ede2b2d54afa.png)

Also on the dashboard if you use a long prefix it cuts it off. Would be nice if this area was also scrollable

![screenshot 2017-09-22 18 33 29](https://user-images.githubusercontent.com/816028/30766667-a79b4f0c-9fc4-11e7-9ada-c39d972a5bae.png)

**Comment by themsaid** [comment]
Thanks, we're aware of it and will be optimized for in a future UI enhancement.
