### ISSUE TITLE
Call to undefined method Laravel\Horizon\Horizon::getName()

### ISSUE THREAD

**Issue by dfoxxdfoxx** [laravel/horizon#157]
I have setup the horizon command in the schedule method but keep gettting the below error from the cronjob, can anyone tell me how this can be fixed?

command:`$schedule->command('horizon')
             ->everyMinute()
             ->name('run-horizon')
             ->withoutOverlapping();`

Error:
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Laravel\Horizon\Horizon::getName()

**Comment by themsaid** [comment]
Why do you schedule the horizon command? You only need to schedule the `horizon:snapshot` command.
