### ISSUE TITLE
Timeout not failing job

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#159]
I've noticed that the default timeout is 60 seconds. Seems like currently Horizon does fail the job when the timeout is hit like in the traditional queue:work listener. Instead it just seems to hang forever in the queue.

**Comment by themsaid** [comment]
No it fails normally for me after the timeout passes.

**Comment by lasselehtinen** [comment]
I've retried this. Created a fresh Laravel app, required horizon and created a following job:

```
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        sleep(99999);
    }
```

Seems like it indeed failing the job but it takes a lot longer than expected. With the the timeout of 60 seconds 3 retries, it should take around 3 minutes to fail this job. But in the example below, the job was triggered at 14:31:47 and appeared in the failed queue at 14:39:20. The difference is actually around eight minutes instead of three. Or am I missing something obvious here?

![image](https://user-images.githubusercontent.com/1290186/31123566-2436f41c-a849-11e7-9214-d15a15c5c204.png)

![image](https://user-images.githubusercontent.com/1290186/31123614-55ddc6e4-a849-11e7-9a44-95eaa5e53061.png)


`php artisan horizon:work redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=3 --supervisor=CPB2189-FkWX:supervisor-1`

**Comment by NiclasHedam** [comment]
I've seen Horizon behave likewise. Timeout set to 30 seconds, timeout after 20 minutes.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
