### ISSUE TITLE
Database driver support ?

### ISSUE THREAD

**Issue by yamenarahman** [laravel/horizon#160]
Is there any plan to support database driver? otherwise If somebody can illustrates to me whether redis driver is better or not and If moved to redis I'd only change the QUEUE_DRIVER in .env to redis, right? "I've already setup redis before and tested the ping"

**Comment by themsaid** [comment]
Yes you only need to choose the redis driver in your configuration file, basically no plans to support other drivers at the moment.

**Comment by joelharkes** [comment]
Did anyone consider making a database driver?

it seems feasible if i check the code: https://github.com/search?q=repo%3Alaravel%2Fhorizon%20Redis&type=code

All Redis things seem abstracted?
