### ISSUE TITLE
Metrics do not load due to array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by jstenquist** [laravel/horizon#161]
Laravel 5.5.5
Horizon 1.0.3
PHP 7.1.8

`ErrorException: array_flip(): Can only flip STRING and INTEGER values!
#61 vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(234): handleError
#60 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): handleError
#59 [Anonymous function](0): array_flip
#58 vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(234): snapshotsFor
#57 vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(212): snapshotsForJob
#56 vendor/laravel/horizon/src/Http/Controllers/JobMetricsController.php(47): show
#55 [Anonymous function](0): call_user_func_array
#54 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): callAction
#53 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): dispatch
#52 vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): runController
#51 vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): run
#50 vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\{closure}
#49 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#48 vendor/laravel/horizon/src/Http/Middleware/Authenticate.php(18): handle
#47 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#46 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#45 vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(41): handle
#44 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#43 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#42 app/Http/Middleware/CORS.php(34): handle
#41 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#40 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#39 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#37 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#35 vendor/laravel/framework/src/Illuminate/Routing/Router.php(627): runRouteWithinStack
#34 vendor/laravel/framework/src/Illuminate/Routing/Router.php(586): dispatchToRoute
#33 vendor/laravel/framework/src/Illuminate/Routing/Router.php(564): dispatch
#32 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#31 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#30 vendor/fideloper/proxy/src/TrustProxies.php(56): handle
#29 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#28 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#27 app/Http/Middleware/HttpRequestsMiddleware.php(16): handle
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#25 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#24 vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(41): handle
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#22 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#21 app/Http/Middleware/CORS.php(34): handle
#20 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#19 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#18 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): handle
#17 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#16 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#15 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): handle
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#13 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): handle
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#10 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#9 app/Http/Middleware/FormatBearerToken.php(28): handle
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#6 vendor/ventureapp/dingo-api/src/Http/Middleware/Request.php(111): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(55): null`

![array_flip](https://user-images.githubusercontent.com/1971648/30818700-4b5adc30-a1ea-11e7-9fe0-5b3efd15911b.png)

**Comment by themsaid** [comment]
This is already fixed and will be released on the next patch.
