### ISSUE TITLE
ServerException WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by gozozo** [laravel/horizon#162]
## This error happens when a monitoring is created and a number is placed in the tag name field

> Laravel 5.5.13
> Horizon 1.0.4
> Predis 1.1.1

(1/1) ServerException WRONGTYPE Operation against a key holding the wrong kind of value
--
in Client.php (line 370)
at Client->onErrorResponse(object(ZSetCardinality), object(Error))in Client.php (line 335)
at Client->executeCommand(object(ZSetCardinality))in Client.php (line 314)
at Client->__call('zcard', array('7'))in Connection.php (line 96)
at Connection->command('zcard', array('7'))in Connection.php (line 108)
at Connection->__call('zcard', array('7'))in RedisTagRepository.php (line 114)
at RedisTagRepository->count('7')in MonitoringController.php (line 52)
at MonitoringController->Laravel\Horizon\Http\Controllers\{closure}('7', 0)
at array_map(object(Closure), array('7', 'Glitzi\\Models\\Appointment:7'), array(0, 1))in Collection.php (line 833)
at Collection->map(object(Closure))in MonitoringController.php (line 54)
at MonitoringController->index()
at call_user_func_array(array(object(MonitoringController), 'index'), array())in Controller.php (line 54)
at Controller->callAction('index', array())in ControllerDispatcher.php (line 45)
at ControllerDispatcher->dispatch(object(Route), object(MonitoringController), 'index')in Route.php (line 212)
at Route->runController()in Route.php (line 169)
at Route->run()in Router.php (line 645)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 18)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 67)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 63)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 647)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 622)
at Router->runRoute(object(Request), object(Route))in Router.php (line 588)
at Router->dispatchToRoute(object(Request))in Router.php (line 577)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 149)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 54)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
