### ISSUE TITLE
Request count

### ISSUE THREAD

**Issue by dpde** [laravel/horizon#163]
I notices that there a a lot request to the backend fired.
Are there any plans to reduce the amount of requests fired?

See https://www.dropbox.com/s/qy9ejmnjrpjjdun/horizon_requests.mp4?dl=0

**Comment by themsaid** [comment]
That's horizon auto refreshing your metrics.

**Comment by dpde** [comment]
I know.
But is it really necessary that this happens so many times?

Did you watch the screencast that I linked?

**Comment by themsaid** [comment]
Make sure you're on the latest Horizon and re-publish the assets, looks like you're using an old JS file.

**Comment by dpde** [comment]
I'm using the latest version of dev-master. (df65f5b3f5119cc5f0a6bfbd501f83580efd0842)
Assets are published.

**Comment by themsaid** [comment]
I can't replicate your issue.

**Comment by dpde** [comment]
It happens after keeping the dashboard open for a while.
I'll investigate this one some day this week and if there is a bug I'll create a pull request.
