### ISSUE TITLE
Paused state still runs jobs

### ISSUE THREAD

**Issue by denaje** [laravel/horizon#168]
Horizon: 1.0.4
Laravel: 5.5.13

So I have Horizon running and all seems great. I run:

```
$ php artisan horizon:pause
Sending USR2 Signal To Process: 7487
```

After a couple seconds, the dashboard shows that it is paused:

![image](https://user-images.githubusercontent.com/115632/31029597-543a1ae4-a520-11e7-9e1c-2397c08e1f76.png)

Then I trigger some jobs. Immediately in the dashboard I can see "Max Wait Time" change from "-" to about 3 seconds. My queues show some jobs, but then almost immediately afterward they go back to 0 and the "Jobs Past Hour" increments by the number of jobs:

![image](https://user-images.githubusercontent.com/115632/31029678-a94a3f96-a520-11e7-88d1-421de9eed0ea.png)

I checked out my email logs and discovered that the emails have actually been sent, despite that Horizon should have been paused. These jobs also all show up in the "Recent Jobs" list, but all of them have a status of paused, unlike #167.

(Also notice the weird "eue:default" in "Max Runtime" and "Max Throughput". It doesn't really bother me, but seemed a bit strange.)

**Comment by denaje** [comment]
Nevermind, I actually figured out what was causing both this issue and #167. I have two websites (dev and pre) that both run on the same server. Dev uses Horizon, but Pre still used redis queues. I switched those drivers to `sync` and stopped the supervisor processes that work those queues, and now Horizon is behaving normally. Hopefully when Pre is switched to use Horizon then the `HORIZON_PREFIX` will prevent them from interfering.

**Comment by ModernArtisan** [comment]
@denaje Can you please tell me how exactly it works?
I also have 2 sites on the same server(dev and prod), both uses Laravel Horizon with different prefixes.
I have status **Active** on dashboard

![Horizon status](http://prntscr.com/i0vst9)

And paused job

![Horizon paused](http://prntscr.com/i0vuh7)

What could be the problem?

**Comment by denaje** [comment]
@ModernArtisan One other thing you could try is to set the config `database.redis.default.database` to different values in each of your environments. That was suggested to me elsewhere and it worked for me, though I thought that I managed to get it working just by changing the prefix. It's worth a shot at least!
