### ISSUE TITLE
Metrics are reset after horizon:terminate

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#171]
Seems like all the metrics including the recent jobs are reset on deployment. I run horizon:terminate as instructed. Would it be possible to keep these intact?

**Comment by themsaid** [comment]
No reset happens on termination, but Horizon becomes inactive for a few seconds before a process control starts it again.

**Comment by lasselehtinen** [comment]
I was going through our deployment process and found out that it is not actually horizon:terminate, but cache:clear that completely resets the Horizon panel. This actually default in the Deployer Laravel recipe. There are good reasons to clear the cache during deployment, but it should reset everything in Horizon. I am pretty sure it also deletes the queued (not processed) jobs as well. How this should be done?

https://github.com/deployphp/deployer/blob/master/recipe/laravel.php#L166

**Comment by neorganic** [comment]
Anyone has an answer how to prevent queued jobs being deleted on deployment ?

**Comment by lasselehtinen** [comment]
@neorganic There is a another discussion about this [here](https://github.com/laravel/horizon/issues/72). Basically you should create separate redis connection either to Horizon or the cache. I will test this soon as I can.
