### ISSUE TITLE
The retry button renders incorrectly when using a lenghty class name

### ISSUE THREAD

**Issue by freekmurze** [laravel/horizon#174]
Example:

<img width="1061" alt="screen shot 2017-10-02 at 22 54 00" src="https://user-images.githubusercontent.com/483853/31098966-b8d3bcca-a7c4-11e7-8f25-68d13b473143.png">

**Comment by uber1337** [comment]
fixed with:


```
.panel-heading {
  .ft22;
  .acc;
  .aic;
  .df;
  .jcsb;
  .ph2;
  .tcg4;
  min-height: 6rem;
  heigh: auto;
}

.panel-title {
  width: 600px;
  word-break: break-word;
}
<span class="panel-title">{{job.name}}</span>
```

I will add a fix these days if is ok with my approach. @themsaid ?

**Comment by themsaid** [comment]
fixed that by moving to using bootstrap4.
