### ISSUE TITLE
Can you separate horizon client and server side in different packages?

### ISSUE THREAD

**Issue by Exitialis** [laravel/horizon#184]
Hello. I use laravel as API server and my client side is a [nuxt](https://nuxtjs.org/) application. Nuxt application and laravel application working on the different domains, and at this time, i don't have any possibilities to use laravel horizon dashboard, because my API is stateless, and working with JWT. I see only one possibility to handle that - insert api token right into link to the horizon dashboard, and this is very unsecure.

**Comment by themsaid** [comment]
no plans for this at the moment.

**Comment by marensas** [comment]
That would be nice feature. Our projects are API/SPA only.
