### ISSUE TITLE
Metrics in microseconds

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#187]
The metrics graphs are all usually flat to 0 or 1. I thing supporting microseconds will be good unless you expect the jobs to usually run more than 10 seconds?

**Comment by dpde** [comment]
I have a project that has a lot of scraping jobs that take around 6 seconds but might also take way longer.

**Comment by francislavoie** [comment]
@themsaid why was this closed? I have the same question, I'd appreciate if metrics weren't only by second. I have a lot of jobs that run in 100-200ms, and I'd really like being able to see more accurate times. It's just honestly useless to only see second resolution.
