### ISSUE TITLE
Runtime timestamps are wrong when running queue:retry

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#190]
I had a over 100 jobs that failed because an external API was down. I went to console to do a `queue:retry all`  and noticed that the runtime timestamps in Horizon are showing large negative numbers for those jobs. This is a minor issue, but it would be nice if these would actually correct.

![image](https://user-images.githubusercontent.com/1290186/31393592-c2e4416e-ade4-11e7-944d-96040d048897.png)

![image](https://user-images.githubusercontent.com/1290186/31393598-c6874cb2-ade4-11e7-986f-13f6d463b111.png)

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by lasselehtinen** [comment]
I can still see this time to time, when retrying jobs. But this is an issue I can live with.

**Comment by glamorous** [comment]
Where is this fixed? Just had it again with Nova 3.10

**Comment by ankurk91** [comment]
This issue still exists:

* Laravel v9.6
* Horizon: 5.9.4
* php 8.1
* Redis : 6.2

I had several failed jobs, and retired them all via `php artisan queue:retry all` and time is in negative now.

Some of Runtime value are `-116026.61s`

**Comment by anne-gropler** [comment]
Had this today, too.
