### ISSUE TITLE
Horizon 403 on production

### ISSUE THREAD

**Issue by shy7lo** [laravel/horizon#207]
Hi, 
I have a production server provisioned by forge and a laravel 5.5 app with PHP 7.1. I installed horizon and configured it according to my needs including queues by Redis and Daemon according to laravel documentation. I have not enabled Auth for Horizon for now. 

When I try to access /horizon, I get this whoops and the status code of request is 403. I am not sure what is the problem here. 

On my local machine and development VPS (provisioned by forge and app is deployed by forge too), it is working perfectly. 

Attached is a screenshot of the error. 

Any help and guidance will be appreciated.

Thank you 

<img width="1470" alt="screen shot 2017-10-23 at 12 01 42 pm" src="https://user-images.githubusercontent.com/19299780/31881102-24fea6e0-b7eb-11e7-8392-e448b1e43a42.png">

<img width="1006" alt="screen shot 2017-10-23 at 12 10 35 pm" src="https://user-images.githubusercontent.com/19299780/31881127-3df6b6a6-b7eb-11e7-96d2-92d78c2d20cc.png">

**Comment by NiclasHedam** [comment]
>I have not enabled Auth for Horizon for now.
If you do not provide a specific authentication callback, Horizon will only be available in the `local` environment. Horizon should never be publicly accessible, as this would be a major security issue.

**Comment by aditya-rewari-cb** [comment]
> > I have not enabled Auth for Horizon for now.
> 
> If you do not provide a specific authentication callback, Horizon will only be available in the `local` environment. Horizon should never be publicly accessible, as this would be a major security issue.

How to do this ?
I mean how rather where do I provide this specific authentication callback?
Thanks

**Comment by marcosdsdba** [comment]
> > > I have not enabled Auth for Horizon for now.
> > 
> > 
> > If you do not provide a specific authentication callback, Horizon will only be available in the `local` environment. Horizon should never be publicly accessible, as this would be a major security issue.
> 
> How to do this ?
> I mean how rather where do I provide this specific authentication callback?
> Thanks

After register Horzion in config/app.php 

providers[
...
App\Providers\HorizonServiceProvider::class,,
]  

Add on HorizonServiceProvider.php
'use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

In boot() function place this code:


Horizon::auth(function ($request) {
            if ($request->ajax()){
                return true;
            }
            else if (isset($request->checkstatus) && $request->checkstatus == 'ok'){
                return true;
            }else{
                throw new UnauthorizedHttpException('Unauthorized');
            }


Run php artisan config:clear 

Acces Horizon sending querystring parameter: checkstatus=ok
Ex.:
mydomain.com/**horizon/dashboard/?checkstatus=ok**

Have a fun!

**Comment by niclashedam** [comment]
> Acces Horizon sending querystring parameter: checkstatus=ok
> Ex.:
> mydomain.com/**horizon/dashboard/?checkstatus=ok**

This is not a very good authorization scheme. You should check that the user is logged in and is an administrator.
