### ISSUE TITLE
Installation errors on CentOS 7 server

### ISSUE THREAD

**Issue by mortenscheel** [laravel/horizon#209]
I'm not sure if this is related to Horizon or if it's an issue with Composer (or just me), but I'll share this here in case anyone else has the same problem.

Horizon was installed without any issues on my dev environment, but when deploying to a CentOS server, the composer install command failed with the following message:
```
Problem 1
    - Installation request for laravel/horizon v1.0.5 -> satisfiable by laravel/horizon[v1.0.5].
    - laravel/horizon v1.0.5 requires ext-posix * -> the requested PHP extension posix is missing from your system.
```
To my surprise, running composer update directly on the CentOS server fixed the issue. Subsequent composer install commands work, so I suspect there must have been an issue with my composer.lock file. What confuses me is that it's true ext-posix is missing from the system, and now Composer doesn't seem to care.

**Comment by lasselehtinen** [comment]
If your deployment prepares it by running composer install, then it is missing the ext-posix extension? Generally it is good idea to run composer install on the machine you are deploying to, so it can properly check for all the composer dependencies (missing extensions for example).

**Comment by mortenscheel** [comment]
My workflow is this: Artisan down => Update files (including composer.lock) => Composer install => Artisan migrate => Artisan up.

What I didn't understand was why `composer install` failed and `composer update` worked (and why it seems to work even without ext-posix). But I've come a bit closer now. The lock file required Horizon v1.0.5 which *does* require ext-posix. My composer.json version constraint is "^1.0", so when I ran composer update, it grabbed Horizon v1.0.0 which *doesn't* require ext-posix.

So it's my bad for only testing on Ubuntu before deploying to CentOS. Lesson learned. But I still haven't been able to find any information on *why* ext-posix has been introduced as a mandatory dependency.

**Comment by mortenscheel** [comment]
Sorry, just found your [pull request](https://github.com/laravel/horizon/pull/107) where you explain it. And I can confirm that I get the same error when running `terminate` and `pause` commands.

Now I just need to figure out the next mystery. When the server guy recompiled php with posix enabled, a lot of other critical extensions went missing on the production server (mbstring, calendar, zip and soap just to name a few). Suddenly 500 errors everywhere, so we got him to revert to the previous config in a hurry. I'm far from an expert in compiling software from source, but I'm a little suspicious of the claim that 10 other extensions disabled themselves during the build process without throwing errors all over the place. Guess I'll just have to try for myself.

You're welcome to close this issue. I seem to have gone a bit off topic here.

**Comment by mortenscheel** [comment]
Just a quick followup in case anyone is interested.
The server guy accidentally commented out a bit too much in his compile script, causing all extensions listed after ext-posix to not be included in the build.

I've personally learned a lot from this, but the issue has nothing to do with Horizon, Composer or CentOS. I'm closing this issue and moving on with my life now :)
