### ISSUE TITLE
Horizon dashboard causing high php-fpm usage

### ISSUE THREAD

**Issue by apbassi89** [laravel/horizon#211]
I've been able to replicate this on a standard Laravel Homestead box, as well as on DigitalOcean droplets. Each time I try the following steps, I am able to replicate the exact same scenario:

1. Start homestead
2. SSH into homestead and start horizon using `php artisan horizon`
3. With nothing on the queue, load the Horizon dashboard
4. Within ~5 seconds, several `php-fpm` processes will start up on the server and peg the CPU
![skitch](https://user-images.githubusercontent.com/4567815/32034931-a2ddf6a2-b9ca-11e7-8832-d9d220b17b62.png)
5. This slows down page load considerably, and if left unchecked, causes homestead/the server to hang indefinitely and require a reboot.
6. Once I close the horizon dashboard, it takes ~5 seconds for the php-fpm process to die off, but once they do the server is back to normal.

Essentially, I'm left in a position where I can't use the dashboard for debugging. Any ideas? I'm using Horizon `v1.0.5` with Laravel `v5.5.18`, and my Horizon config is nothing fancy. I lowered `local` down to 1 process and 1 try:

```php
'local' => [
    'supervisor-1' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 1,
        'tries' => 1,
    ],
],
```

**Comment by themsaid** [comment]
Testing on a DO droplet the php-fpm process had a maximum CPU usage of 1% for 10 minutes of activity.

**Comment by apbassi89** [comment]
I'll run this again when I get home tonight and see if I can provide more insight

**Comment by apbassi89** [comment]
Ran some additional tests. First, I flushed redis to ensure that I didn't have an issue related to something in the queue.

After testing for a while, I discovered that the way the dashboard polls appears to be at consistent intervals, and that this interval was faster than my Homestead instance would respond (not sure why it's so slow). After a while of this, the requests would keep backing up, and overwhelm the server. 

As you can see the in the network log I included below, each request was taking longer than the previous one, and the number of requests kept piling up.

![skitch 1](https://user-images.githubusercontent.com/4567815/32088985-2f3b2986-ba9c-11e7-8eb7-d0ab2be9f409.png)

I think the solution is straightforward. Instead of polling on a fixed time interval, the dashboard should queue up a poll after the previous request completes. This will keep requests from pilling up on each other if, for whatever reason, the server can't respond fast enough.

**Comment by themsaid** [comment]
OK I'll work on that.

**Comment by spham** [comment]
i try and have issue about CPU usage with DO

![image](https://user-images.githubusercontent.com/1083631/33656273-dbdc1d96-da75-11e7-9087-79037ac8ef7d.png)

**Comment by juhasev** [comment]
Same problem here..... This happens on brand new Homestead v-box. After quitting Horizon dashboard loads came back down. So definitely Horizon is doing extra work, no dashboard should kill 2GB dev server :-)

**Comment by sebastiaanluca** [comment]
Same here, 4-5 php-fpm processes that take up 20 to 40% CPU each and then my Homestead VM just crashes. Not sure what's happening. Horizon bug or misconfiguration on our part?

**Comment by williansebastiao** [comment]
Hello
Has anyone managed to find a solution?

**Comment by dbpolito** [comment]
My PR (#323) should have helped fixing this issue, have you guys tried latest horizon?

**Comment by driesvints** [comment]
Please check if the above PR has helped. Update to the latest version.
