### ISSUE TITLE
Dashboard not loading

### ISSUE THREAD

**Issue by mikebautista** [laravel/horizon#214]
Is there an easy way to modify the directory that Horizon can be in. We have a few projects that sit within subdirectories on the server and we need a Horizon instance for each site. So far I have found that if you update the base path in the `index.js` file and update the API routes in the other `.vue` files it will work once you recompile. I am just wondering if there is an easier way.

**Comment by browner12** [comment]
there are a couple customizations in master, that will hopefully be released soon. might not get you all the way there, but should help.

**Comment by themsaid** [comment]
Closing since there are no plans for this at the moment.
