### ISSUE TITLE
400 Error - Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by robertzimmerman** [laravel/horizon#215]
Hi,

   I just recently upgraded to 5.5 and installed horizon. I noticed that when I go to Horizon, and about 3 to 5 clicks around the dashboard / metrics, I end up getting a 400 error - Request Header Or Cookie Too Large. Anything I can debug or has anyone else had this issue?

Thank you

**Comment by robertzimmerman** [comment]
i noticed that this is happening when it calls app.js on the horizon vendor folder

<img width="1420" alt="screen shot 2017-10-30 at 4 22 11 pm" src="https://user-images.githubusercontent.com/3916791/32200390-9bf1f06a-bd8e-11e7-9fdf-cecce086c6cc.png">

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
