### ISSUE TITLE
displayableTagsList() in resources/assets/js/app.js

### ISSUE THREAD

**Issue by davi5e** [laravel/horizon#226]
[Version: v1.0.8]

I'm experiencing a bug where the function `displayableTagsList() `returns only the last item of the array preceded by a comma.

e.g.: If `tags = ['a', 'b', 'c']`, then the function returns `', c'`

No problem for when the array only have one item.

For what I could gather, the intention should be the same as `tags.toString()` but adding a space after the comma, which I myself would do with a regex.

Opinion aside, currently I can't see more than one tag in the Recent Jobs page.

Regards, DAVI

**Comment by themsaid** [comment]
Just fixed that on dev master, thanks for the heads up :)
