### ISSUE TITLE
Weird timeout behavior

### ISSUE THREAD

**Issue by Radostin** [laravel/horizon#228]
- Laravel Version: 5.5.19
- PHP Version: 7.1.8

### Description:
Hello,

In my application, I need the queue processes to be working for at least 5 minutes (300 seconds). I've been struggling to find where to put those configurations and I tried both:
- Setting a public property "public $timeout = 300;" on the job itself
- Editing the horizon.php configuration like this

``` php
//...
'supervisor-1' => [
     'connection' => 'redis',
     'queue'      => ['default'],
     'balance'    => 'simple',
     'processes'  => 10,
     'tries'      => 3,
     'timeout'    => 300
],
//...
```

### Steps To Reproduce:
Anyway, the public property option doesn't seem to be working at all. However, I do notice that the second option works but not quite good. There's something strange in it.

Here are the steps to reproduce:

Let's say we have a queue job "A" that is suppose to work for $seconds seconds (it will actually sleep).

```php
// app/Jobs/A.php

class A implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $seconds;

  
    public function __construct($seconds)
    {
        $this->seconds = $seconds;
    }

    public function handle()
    {
        sleep($this->seconds);
    }

    public function tags()
    {
        return ['a:' . $this->seconds];
    }
}
```

We will invoke it 5 times with 5 different time values:

```php
dispatch(new A(1));
dispatch(new A(10));
dispatch(new A(35));
dispatch(new A(65));
dispatch(new A(350));
```

My expectation is that the first 4 will be executed successfully and only the last one A(350) will fail (because it will timeout), but this is not always the case.

Here's an example:
<img width="808" alt="screen shot 2017-11-09 at 08 18 06" src="https://user-images.githubusercontent.com/1559946/32607926-7ece6832-c528-11e7-9ca5-604933bc9476.png">

Another instance is:
<img width="821" alt="screen shot 2017-11-09 at 08 33 29" src="https://user-images.githubusercontent.com/1559946/32608008-cd4f63e4-c528-11e7-9ebb-2417cb3b3519.png">

If I do 5 runs of the code, I will get 5 different results. There's no consistency at all.

The error that I do get every single time is:
```
Illuminate\Queue\MaxAttemptsExceededException: A queued job has been attempted too many times or run too long. The job may have previously timed out.
```

Sometimes the job will retry and the initially-failed queued job will be successful, sometimes it won't. It is totally unpredictable.

Finally, my questions:

- Am I setting up the timeout seconds correctly?
- Is this behavior of horizon/queues expected?
- Is it just my computer?
- Is there a remedy for the issue?

**Comment by themsaid** [comment]
Did you set the value of `retry_after` to be more than the maximum timeout?

**Comment by Radostin** [comment]
In fact, I set the value to be less than that. I was left to believe that retry_after defines the number of seconds, which the daemon should wait to retry a failed queued job. 

Thank you!

I'm closing.
