### ISSUE TITLE
horizon:terminate kills my running jobs

### ISSUE THREAD

**Issue by marianvlad** [laravel/horizon#229]
When I'm running **horizon:terminate** in the deployment script on Forge, Horizon kills my processing jobs. There is a way to avoid this? I have multiple jobs where I'm uploading videos and my jobs are killed in the middle of uploading.

**Comment by themsaid** [comment]
Can't seem to replicate this, the process keeps running even after horizon is terminated, please verify the behaviour with simple code, could be something in your job that's killing the process.

**Comment by mfn** [comment]
I experienced the same problem today. Haven't yet started analyzing but will do soon hopefully.

**Comment by mfn** [comment]
Here's a reproducible case I did today

### Software
- Laravel 5.5.21
- Laravel Horzion 1.0.8
- Ubuntu 14.04

### Preparation
- Create job and command
```sh
$ ./artisan make:job LongRunning
Job created successfully.
$ ./artisan make:command EnqueueLongRunning
Console command created successfully.
```
- Job
`LongRunning::handle()`:
```php
    public function handle()
    {
        echo "Before loop\n";
        foreach (range(0, 29) as $second) {
            echo "Second $second\n";
            sleep(1);
        }
        echo "After loop\n";
        file_put_contents('/tmp/finished', 'job finished');
    }
```
The idea is to show then after 30s the job should write something into the file `/tmp/finished` which doesn't exist beforehand. I.e. this emulates long running DB queries, etc.
- Command
`EnqueueLongRunning::handle()`:
```php
    public function handle()
    {
        dispatch(new LongRunning());
    }
```
Horizon configuration:
```php
        'local' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 1,
            ],
        ],
```

### Reproduce
- In a terminal start `./artisan horizon`
- In another terminal `./artisan command:name` (just the default which was generated…)
- The horizon terminal will show this:
```sh
$ ./artisan horizon
Horizon started successfully.
[2017-11-16 15:28:39] Processing: App\Jobs\LongRunning
Before loop
Second 0
Second 1
Second 2
```
- Run `./artisan horizon:terminate`:
```
$ ./artisan horizon:terminate
Sending TERM Signal To Process: 7995
```
- The horizon output stops:
```
$ ./artisan horizon
Horizon started successfully.
[2017-11-16 15:28:39] Processing: App\Jobs\LongRunning
Before loop
Second 0
Second 1
Second 2
Second 3
Second 4
Second 5
$ 
```
- There's no `artisan` process at all anymore, i.e. `ps auxw|grep artisan` shows nothing
- No matter how long you wait, `/tmp/finished` never appears
- Start artisan again, and you will see that the job is now marked as failed:
```
$ ./artisan horizon
Horizon started successfully.
[2017-11-16 15:31:09] Processing: App\Jobs\LongRunning
[2017-11-16 15:31:09] Failed:     App\Jobs\LongRunning
```

**Comment by Artistan** [comment]
hmm. mine is not killing the long running jobs I want to kill (dev) interesting.

**Comment by mfn** [comment]
> Can't seem to replicate this, the process keeps running even after horizon is terminated, please verify the behaviour with simple code, could be something in your job that's killing the process.

@themsaid can you give this another try?

I tried to make easy-to-follow steps in https://github.com/laravel/horizon/issues/229#issuecomment-344971187 and as of today I can easily replicate this with Laravel 5.6 and Horizon 1.2.1 too, nothing changed in that regard.

Issuing `./artisan horizon:terminate` immediately kills a still-running job in the background.

**Comment by mfn** [comment]
Here's a screen cast I made, showing the problem. It may be a bit confusing first, so here's s short description what you're looking at (describing things clock-wise):
- `tmux` using panes to show 4 shells
- top-left: the actual `./artisan horizon`
- top-right: one-liner to enqueue 5 jobs
- bottom-right: tail command of a temporary file where all jobs write their current iteration too
- bottom-left: where I executed `./artisan horizon:terminate`

![laravel_horizin_terminate_cast](https://user-images.githubusercontent.com/87493/36074186-c26173d8-0f3c-11e8-99e7-0a1f959b1cbd.gif)


### Observations:
- `./artisan horizon:terminate` *immediately* kills all the processes
- I did restart horizon after termination, emulating how `supervisor` would do it
- jobs picked up once more
- when I kill it again, jobs are *not* picked up again

### Thoughts
- Unclear to me why jobs get retried once but not more often (I've a default installation, so tries should be 3, can also be seen in the process output after horizon terminates)
- My expectations:
 - horizon should terminate itself immediately and restart 👍 
 - any job _currently_ running should *finish* their iteration without interruption and then the process should cleanly exit

### Requirement of the cast
- Ubuntu 14.04 LTS
- Redis already running in the background
- Fresh Laravel installation with minimum changes, see https://github.com/mfn/laravel-horizon-terminate
- Ensure that `QUEUE_DRIVER=redis` in your `.env`

**Comment by themsaid** [comment]
Guys please upgrade to v1.2.2, we believe we solved the matter.

**Comment by mfn** [comment]
@themsaid I can confirm: the jobs are not killed anymore, `./artisan horizon` waits until the current jobs are finished and then exits cleanly!

Referencing my screenshot: also the `ps auxw |  grep artisan` command does **not** show any processed after this (which the screencast still does).

Thanks 👍

**Comment by marianvlad** [comment]
After `1.2.2`, everything works perfectly. No more orphan jobs and old code.
