### ISSUE TITLE
Horizon Dashboard inside Spark Kiosk

### ISSUE THREAD

**Issue by genintho** [laravel/horizon#231]
Thank you for this great package.

I was curious to know if there is an easy way to integrate the Dashboard inside Spark Kiosk? Adding a link in the user dropdown, is simple, but sharing the ACL mechanism and having a nicely integrated UI would be amazing.

**Comment by themsaid** [comment]
Thanks for your suggestion, adding the link in the UI and use the Horizon auth callback is sufficient enough for this to work, you get an instance of the user and you can run any type of checks.
