### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by azhard4int** [laravel/horizon#232]
Hi,

It would be a great feature if we can add the redis-sentinel support.

Right now, It throws an error `READONLY You can't write against a read only slave.` when using it with https://github.com/monospice/laravel-redis-sentinel-drivers.

**Comment by themsaid** [comment]
How would we support that?

**Comment by cyrossignol** [comment]
@azhard4int I recently updated that package for [Horizon](https://github.com/monospice/laravel-redis-sentinel-drivers#laravel-horizon).

**Comment by azhard4int** [comment]
Thank you Cy.

I will be checking it today!
