### ISSUE TITLE
Problem if "public" Directory renamed

### ISSUE THREAD

**Issue by rajsingh8220** [laravel/horizon#236]
The following command will work and create public directory
`php artisan vendor:publish --provider="Laravel\Horizon\HorizonServiceProvider"`
But if I dont have public directory, Horizon will not gonna work.

Suggest be what to do?
Rename the directory to public or something else?

**Comment by olssonm** [comment]
Is it the `app/public`-path you've removed or renamed? Have you written your own function to handle public_path() instead?

I would highly recommend you sticking with a proper public path, else you might run into this issue with several (or most even) packages that publishes assets to the public path, probably with Laravel Elixir and more.

**Comment by rajsingh8220** [comment]
Yes, I have renamed my `app/public` path. What should I do for this issue. If I write my own handle for `public_path()`, the problem will be solved????
and I will work on your suggestion too.

**Comment by olssonm** [comment]
Yeah, in Laravel 5.* the bets way to approach it is probably by registering a new directory as the public path, you can do this in your AppServiceProviders `register`-method:

```
$this->app->bind('path.public', function() {
    return base_path().DIRECTORY_SEPARATOR.'your_public_path_substitute';
});
```

This should work as a starting point, however, haven't researched Horizon to see if there are any "hard coded" string to /public to see if you might still encounter issues.

**Comment by rajsingh8220** [comment]
Wow works now, thank you.

**Comment by markwalet** [comment]
This issue can be closed.
