### ISSUE TITLE
Multiple tags not showing in 'recent jobs'

### ISSUE THREAD

**Issue by trizz** [laravel/horizon#238]
When settings tags manually (`public function tags()`) and returning more than one tag (for example `['tag1', 'tag2', 'tag3']`) the 'Recent Jobs' page only show `, tag3` instead of `tag1, tag2, tag3`.

When I add a monitoring entry for `tag1` and open that page (`/horizon/monitoring/tag1/`) I see all tags, as expected.

**Comment by Luukvdo** [comment]
This was fixed in f4732a2580154ee23717da26b2d23aea7a2501d7.
It just needs a tagged release

**Comment by driesvints** [comment]
This should be fixed now.
