### ISSUE TITLE
Log worker crashes

### ISSUE THREAD

**Issue by cweiske** [laravel/horizon#239]
The horizon supervisor command should write log entries when a worker process crashes.
At least it should write a log entry that restarting a worker process has been given up because it crashed too often.

You can reproduce that by putting {{exit(1);}} into a job and put 100 of that jobs into the queue. The workers will fail, horizon:supervisor will restart them and finally give up, leaving the supervisor without workers.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
