### ISSUE TITLE
Chart.js Code

### ISSUE THREAD

**Issue by apertureless** [laravel/horizon#241]
Hey @taylorotwell ! ✌️ 

I saw that you're using chart.js for your charting. And more explicit you are actually using code from [vue-chartjs](https://github.com/apertureless/vue-chartjs) for the base components, mixins and chart component.

I just wanted to ask if there's a reason behind it, why you are not using the package ? 
(Like limitations in customization etc.) Would be good to know, so I can improve it.

I know that `vue-chartjs` is MIT licensed and I am totally okay if people copy and modifiy it. However it would be nice if the copyright & premission notice would be included. :)

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Cheers! ✌️

**Comment by taylorotwell** [comment]
@themsaid may know :) ... I did not built the front-end.

**Comment by themsaid** [comment]
We've removed the copied code, thanks for understanding and sorry for the violations.

**Comment by apertureless** [comment]
No Problem! Was just wondering if theres like a technical reason behind it, like you could not properly use it or not customize it enough.

Cheers!
