### ISSUE TITLE
Horizon stops consuming jobs

### ISSUE THREAD

**Issue by paulomanrique** [laravel/horizon#242]
I'm using Horizon to balance some cron jobs in 3 clusters. So, once a day  I add around 4000 jobs to the queue and Horizon starts consuming those jobs.

However, when it gets around 1000 jobs left, it just stops consuming those jobs. If I look at "current workload", it shows the ammount of jobs left, but on "Recent jobs" tab, it shows "There aren't any recent jobs.".

And those jobs stays there until I remove them from redis.

How can I fix that?

**Comment by webpatser** [comment]
I have the same thing. When a lot of jobs are added but not processed within a certain period. They are still being processed but they fall off the recent jobs list.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
