### ISSUE TITLE
Extract container to blade template

### ISSUE THREAD

**Issue by markwalet** [laravel/horizon#250]
I want to override the blade template for the dashboard in my application. But the `.container` div doesn't align properly.

I suggest we extract this `.container` element from the `MainLayout.vue` template to the `app.blade.php` file template because this gives more freedom in resizing the vue components.

Edit: Yes I can also update my own styling to override the width of the container class. But in my opinion vue components shouldn't (completely) dictate the size of an element.

**Comment by driesvints** [comment]
We're currently looking at some redesigning for Horizon so I'm going to close this off until after that has been released.

**Comment by kesm0** [comment]
I you can use **.container-fluid** unstead It would be marvelous !! 
I spent so much time seleting the line to see statuses
