### ISSUE TITLE
Add default uri & middleware to config file

### ISSUE THREAD

**Issue by markwalet** [laravel/horizon#251]
When browsing the code in the `HorizonServiceProvider` class, I found out that you can customize the `uri` and `middleware` options for Horizon.

Maybe it is a good idea to add this options to the configuration file. That will clarify which options are customizable.

**Comment by SirLamer** [comment]
Having experimented a little, at this time I don't think it actually responds well to configuring those options yet.

**Comment by markwalet** [comment]
I know. but it does give you the option to do so.

**Comment by SirLamer** [comment]
Yeah but it breaks everything, so mostly don't do it.

I suspect it's setup for future support.

**Comment by SirLamer** [comment]
Just to add to this, it responds well to changes to the 'middleware' but seemingly not the 'uri'.

Example:
```php
// ...

'middleware' => ['web', 'horizon'],

// ...
```

**Comment by markwalet** [comment]
I agree. But what does the `horizon` middleware do in your example? In the base `Controller` class the `Authenticate` middleware gets registered regardless of the middleware config option. And `horizon` isn't an existing middleware.

This should be reworked. I think that the `Authenticate` middleware should be registered with a name. I suggest `horizon`. Then we can make the middleware optional via configuration.

**Comment by SirLamer** [comment]
Well I introduced a hypothetical custom middleware group, otherwise I don't see the point of changing it.

In my case I am handling the Horizon auth check via a middleware implementation, similar to [here](https://github.com/laravel/docs/issues/3590#issuecomment-346991788) except modified as described below the linked post.

**Comment by markwalet** [comment]
Ah okay. I understand

I still think the `Authenticate` middleware from this package should be optional. Not mandatory. You could even remove the `Horizon::auth()` method completely when you can provide your own middleware. But that's something for v2.

**Comment by SirLamer** [comment]
It's required because otherwise people will install it and then expose their Horizon admin UI to the public, it's a huge security risk.

Note you only need to do auth handling when deployed to production, the default is to allow access from the local machine.

**Comment by umairali** [comment]
I think simple solution is just to add this line to config/horizon.php file

`'middleware' => ['web', 'auth'],`

**Comment by driesvints** [comment]
I'm not sure why the middleware option in the config file was removed again but it might return at a later time. At the moment you're free to add it to your own `horizon.php` file.
