### ISSUE TITLE
retry_after and timeout

### ISSUE THREAD

**Issue by xakzona** [laravel/horizon#254]
Sorry for stupid, Should be timeout in horizon.php be lower that retry_after in queue.php?
What different between horizon.environment.[env].timeout and horizon.waits?

**Comment by mvieghofer** [comment]
Hi,
I just had a very similar question and solved it for me. I've created the issue #255 and posted the solution there, too. Maybe it helps you.

**Comment by xakzona** [comment]
Thank you @mvieghofer

**Comment by furey** [comment]
Hi @xakzona/@mvieghofer,

After following this thread, my understanding is that…

```
/config/queue.php > 'connections.redis.retry_after'
```

…should be larger than…

```
/config/horizon.php > 'waits.redis:default'
```

…which should be larger than…

```
/config/horizon.php > 'environments.[env].supervisor-1.timeout'
```

Can someone correct me if I'm wrong?

I'd love to definitively understand the queue/horizon timeout "hierarchy"!

Cheers.

**Comment by goyote** [comment]
@furey did you find a solution?

**Comment by furey** [comment]
@goyote Been a while so can't remember, sorry! 🥴
