### ISSUE TITLE
How can i Hook To A Job After and Before it was Processed in Laravel Horizon?

### ISSUE THREAD

**Issue by codeitlikemiley** [laravel/horizon#256]
Hi, 

I have a job that is triggered...
but sadly if i follow laravel docs on hooking to job Processing and Job Processed...
I simply cannot trigger any method on it...

it is said in the documentation you would do it on AppServiceProvider

```
Queue::before(function (JobProcessing $event) {
            Log::info('Event Job '.$event->connectionName);
            Log::info('Event Job '.$event->job);
            Log::info('Event Job '.$event->job->payload());
        });
        //! Update Posted AT
        Queue::after(function (JobProcessed $event) {
            // $event->connectionName
            // $event->job
            // $event->job->payload()
            Log::info('Event Job '.$event->connectionName);
            Log::info('Event Job '.$event->job);
            Log::info('Event Job '.$event->job->payload());
        });
        //!  rollback any transactions that were left open by a previously failed job
        Queue::looping(function () {
            while (DB::transactionLevel() > 0) {
                DB::rollBack();
            }
        });
```

this is how i trigger the job

```

Route::get('/post', function () {
    $post = TwitterPost::first();
    PublishTwitterPost::dispatch($post)->onQueue('twitter-post');
});
```

Surprisingly it is being processed and is working...
but on the other hand , i want of course to hook to the event
after it is successfully posted...

coz i wanna updated the database column updated_at at my twitterpost model..

but even a simple log event wouldnt even give me a Log in laravel.log

Just for the record im using Windows 10 WSL to run Supervisor and Laravel Horizon...

**Comment by cytRasch** [comment]
Doing it in your AppServiceProvider file is correct.

I log my queued jobs like this and it works fine:

```php
 /**
* Log jobs
*
 * Job dispatched & processing
 */
 Queue::before(function ( JobProcessing $event ) {
    Log::info('Job ready: ' . $event->job->resolveName());
    Log::info('Job startet: ' . $event->job->resolveName());
 });

/**
* Log jobs
*
* Job processed
*/
Queue::after(function ( JobProcessed $event ) {
    Log::notice('Job done: ' . $event->job->resolveName());
 });

/**
* Log jobs
*
* Job failed
*/
Queue::after(function ( JobFailed $event ) {
    Log::error('Job failed: ' . $event->job->resolveName() . '(' . $event->exception->getMessage() . ')');
});
```

**Comment by cytRasch** [comment]
Changed Queue::after to Queue::failing

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
