### ISSUE TITLE
Tagging Queued Artisan Commands

### ISSUE THREAD

**Issue by ragingdave** [laravel/horizon#257]
In using this amazingly simple queue management system, I found something that I find kind of counter-intuitive. and maybe horizon isn't the place to fix this.

Basically when you queue a job you get all the benefits of knowing the class name and the ability to tag the job based on the job params. When you run an artisan command through the queue, it seems to remove all of that great functionality. Ideally, when a command is queued, the same abilities should be available that are there for jobs. I understand the class of the command might not be possible since the QUeuedCommand class is what actually hits the queue and not the Artisan command directly, but the tags functionality seems like an easy fix. I would be happy to submit a PR to enable tags method call pass through on the QueuedCommand but wasn't sure if that was a viable fix.

For clarity, Here is the desired workflow:
1. Send an Artisan Command through the queue, and see that the class name reflects the actual command called (as noted above might be impossible/impractical to implement).
2. Enable Command based tagging to get greater insight into command driven jobs.

**Comment by driesvints** [comment]
I think it's best to simply send jobs from within the queued command. I don't see how this would be useful really. Horizon only monitors jobs and adding commands in the mix might get cumbersome. Feel free to respond back and provide more use cases.
