### ISSUE TITLE
Throttling Jobs

### ISSUE THREAD

**Issue by chris-schofield1** [laravel/horizon#259]
Is it possible, using the horizon queue to throttle Jobs' execution? If so, how (as I can't find anything on the matter, even though it seems like a fairly fundamental feature) and is it possible to filter this by particular Job?

Cheers.

**Comment by cytRasch** [comment]
Hey,

maybe this is the solution: [https://laravel.com/docs/5.5/queues#rate-limiting](https://laravel.com/docs/5.5/queues#rate-limiting)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
