### ISSUE TITLE
Settings to execute job only once.

### ISSUE THREAD

**Issue by ibrunotome** [laravel/horizon#263]
Hi, I'm a bit confuse about how to run the job only once, because when I set the parameter "tries" to 1 and the job fails, it execute one more time. If I set the tries parameter to 3, the job runs 4 times. And finally if I set to 0, the jobs run indefinitely. Below my settings in config/horizon.php:

```php
'production' =
'default' => [
                'connection'   => 'redis',
                'queue'        => [
                    'default',
                    'notifications',
                    'dom'
                ],
                'balance'      => 'auto',
                'maxProcesses' => env('MAX_PROCESSES', 45),
                'timeout'      => 60,
                'tries'        => 1,
            ],
        ],
```

And below my settings in config/queue.php

```php
'redis' => [
            'driver'      => 'redis',
            'connection'  => 'default',
            'queue'       => 'default',
            'retry_after' => 90,
        ],
```

And other question, what setting dispatch the "has been attempted to many times or run too along"?

**Comment by servocoder** [comment]
Have you tried to assign value to the `$tries` public property of your Job class?

https://laravel.com/docs/5.5/queues#max-job-attempts-and-timeout

Possible reason of yout issue:

https://stackoverflow.com/a/45281768/7095038

**Comment by ibrunotome** [comment]
Hi @servocoder, I seth both, maxTries on horizon and public $tries on class Job that other Jobs extends, all values set to 1.

My solution to solve the problem for now is, when i detect that a Job has failed by a throw exception, i kill the job with $this->delete(), and it won't run again.

**Comment by AdilDar213** [comment]
You should use --tries parameter with 1 value, for example:
php artisan queue:work --tries=1
