### ISSUE TITLE
Manual tagging

### ISSUE THREAD

**Issue by tillkruss** [laravel/horizon#265]
I'm manually tagging jobs:

```php
public function tags()
{
    return ['job', class_basename(__CLASS__)];
}
```

But I see this in horizon:

<img width="956" alt="screen shot 2017-12-18 at 5 57 32 pm" src="https://user-images.githubusercontent.com/665029/34136951-201d52ee-e41d-11e7-9885-bc8f745e52ac.png">

And the jobs don't show up under metrics:

<img width="967" alt="screen shot 2017-12-18 at 5 58 11 pm" src="https://user-images.githubusercontent.com/665029/34136970-2bbbf290-e41d-11e7-862b-f93a0de73d3d.png">

**Comment by trizz** [comment]
Your first screenshot is probably related to https://github.com/laravel/horizon/issues/238.

**Comment by driesvints** [comment]
This is fixed I think in the latest version. Just tried it and it works for me.
