### ISSUE TITLE
How long is Horizon supposed to persist metrics?

### ISSUE THREAD

**Issue by Victor-emil** [laravel/horizon#275]
I've followed the guide/documentation on the Laravel website. I'm currently running 5 different kind of jobs. Some of them are smaller jobs that runs every hour. Others run in big batches at night (approx 3500 jobs). Currently I'm running a big batch of jobs as seen in the picture below. Everything looks good while they are running and I can easily see the metrics like throughput and wait times.

<img width="954" alt="metrics" src="https://user-images.githubusercontent.com/8555068/34713734-5e15c48a-f527-11e7-8169-0bf58a4feb97.png">

However, when I return to the dashboard a couple of hours after the batch has finished all metrics are gone. I'm running the Snapshot command every 5 minutes as seen in the images below. I'm using Laravel Forge and have followed the official guides by Taylor.

<img width="363" alt="schedule" src="https://user-images.githubusercontent.com/8555068/34714166-de7bcbf0-f528-11e7-9d2b-8efee5f1e115.png">

<img width="1048" alt="cronjob" src="https://user-images.githubusercontent.com/8555068/34714301-5e5cd904-f529-11e7-9144-9cf5469d4a61.png">

I had the impression that metrics would be saved "forever", but I might be wrong. Maybe they are only persisted for a limited period of time? I'm not a specialist in queues and redis and might be missing/misunderstanding something, but I assumed that I would be able to follow metrics for weeks/months to see peak periods, bottlenecks and so on.

The only thing that is actually persisted is what kind of jobs that were run:

<img width="268" alt="metrics" src="https://user-images.githubusercontent.com/8555068/34716099-20bda49c-f52f-11e7-8dcd-273118440c9d.png">

But under each is just empty data. The graph shows nothing.

<img width="929" alt="graph" src="https://user-images.githubusercontent.com/8555068/34716126-36d294e0-f52f-11e7-9804-b0698e78fd5c.png">

<img width="955" alt="dashboard" src="https://user-images.githubusercontent.com/8555068/34716143-46381dba-f52f-11e7-9d91-b9723a63ff12.png">

**Comment by larsbo** [comment]
the same here. I didn't found any documentation if this the correct behavior but it looks like an bug.

**Comment by solofeed** [comment]
+1. I want to persist metrics data, for example, for one month.

**Comment by driesvints** [comment]
In your `horizon.php` config file there's a `trim.recent` setting which defaults to 60 minutes. You can increase this as you see fit to persists data longer. I'll send a PR to the docs to document this behavior.
