### ISSUE TITLE
Jobs stays on pause with multiple horizon workers on server

### ISSUE THREAD

**Issue by slavarazum** [laravel/horizon#279]
I have 2 sites on the same server(dev and prod), both uses Laravel Horizon with different prefixes.
I have status **Active** on dashboard

![Horizon status](https://image.prntscr.com/image/8eVjULPeTNiRj7McdXxSEw.png)

And paused job

![Horizon paused](https://image.prntscr.com/image/-zcImAPdSPeedaytpDLuvA.png)

What could be the problem?

**Comment by anjestar** [comment]
![image](https://i.loli.net/2018/01/23/5a66a99d33a26.jpg) these jobs were all completed,but status not changed

**Comment by ModernArtisan** [comment]
So, still no solution?

**Comment by johannitsa** [comment]
Same problem but two different websites (both in production) with different prefixes.

**Comment by leitom** [comment]
We have the same problem, using forge and envoyer for deployment.

**Comment by leitom** [comment]
Can someone provide a setup for running two queue boxes with horizon? :)

**Comment by sisve** [comment]
What version of Laravel are you using in this issue?

**Comment by ModernArtisan** [comment]
I'm using
Laravel: **v5.5.21**
Horizon: **v1.0.8**

**Comment by anjestar** [comment]
I'm using
Laravel: v5.5.32
Horizon: v1.1.0

If I push some delayed jobs to the queue, in Recent Jobs , they are visible, but status are paused,I want to know that if these delayed jobs will change their own status when they are actually executed.

**Comment by egorsgor** [comment]
same problem. Redis, laravel 5.6

**Comment by sisve** [comment]
@egorsgor Since you're on Laravel 5.6, have you checked if a single configuration entry solves this for you, as suggested in https://github.com/laravel/horizon/issues/292 ?

**Comment by ModernArtisan** [comment]
Try to change default redis database to a different value.

https://github.com/laravel/laravel/pull/4571

**Comment by derekmd** [comment]
Depending on the job duration, a possible explanation may be `config("horizon.environments.{$env}.{$queueName}.timeout')` being lower than `config('queue.connections.redis.retry_after')` (or missing.)

config/horizon.php doesn't come with any queue `'timeout'` OOTB ( https://github.com/laravel/horizon/blob/1.0/config/horizon.php#L75-L81 ) so AFAIK the default timeout is 60 seconds: https://github.com/laravel/horizon/blob/1.0/src/SupervisorOptions.php#L76

So **jobs will continuously timeout with no retry if they take more than 60 seconds**.

It's the same issue mentioned here: https://github.com/laravel/framework/issues/14160 (`retry_after` was once named `expire`.)

Try setting the queue timeout to the max value that you expect your jobs to run:

```
return [
    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
                'timeout' => 300, // 5 minutes, set retry_after to 6min
            ],
        ],
    ],
];
```

https://laravel.com/docs/5.6/horizon needs a mention of timeout/retry configuration with a link to https://laravel.com/docs/5.6/queues#job-expirations-and-timeouts

**Comment by reachsampath** [comment]
@ModernArtisan 

Same problem i'm getting , do you find any solution?

**Comment by ModernArtisan** [comment]
@reachsampath https://github.com/laravel/horizon/issues/279#issuecomment-364775141

**Comment by santoshachari** [comment]
If it helps. In my case it was because the job name wasn't included in config/horizon.php

```
'queue' => ['default','your_job_name'],
``

**Comment by vbarbarosh** [comment]
I have the same issue. After executing `./artisan horizon`  I can see "Horizon started successfully." but no processing of jobs was made at all. The error was in `APP_ENV` variable. The proper configuration of Horizon implies that `APP_ENV` will be set to value listed in `config/horizon.php:environments`, usually `production` or `development`.

**Comment by David-Martinez** [comment]
I was facing the same issue. What worked for me was to change supervisor name for each environment:

`    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => [env('DEFAULT_QUEUE_NAME', 'default')],
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
            ],
        ],

        'local' => [
            'supervisor-local' => [
                'connection' => 'redis',
                'queue' => [env('DEFAULT_QUEUE_NAME', 'local')],
                'balance' => 'simple',
                'processes' => 3,
                'tries' => 3,
            ],
        ],
    ],
`

**Comment by driesvints** [comment]
Please try to use different connections per environment and if not at least different queues. If this doesn't helps feel free to respond back.

**Comment by rrolla** [comment]
I have conflicts when two envoirments run `php artisan horizon` on same server.
Solution:

add options array with prefix key

in config/database.php

```
    'redis' => [
        'client' => 'predis',

        'options' => [
            'prefix' => env('REDIS_PREFIX', 'prod:')
        ],

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
    ],
```
For example for staging env add to `.env`
```
REDIS_PREFIX="staging:"
```

More information: https://stackoverflow.com/a/50354984

**Comment by v1nk0** [comment]
I had this problem with Horizon as soon as the job reads a file as a stream (e.g. importing a csv-file and read that file as a stream). Did not find a solution so far....

**Comment by jezmck** [comment]
I found a workaround; run the standard `artisan queue:work`, **as well as** `artisan horizon`.
