### ISSUE TITLE
Windows compatible posix_kill method

### ISSUE THREAD

**Issue by wsmsn** [laravel/horizon#284]
1. Remove `"ext-posix": "*",`from `composer.json`  
2. Change line 93 of the `src/Console/PurgeCommand.php` file to 
```
            if (function_exists('posix_kill')) {
                posix_kill($processId, SIGTERM);
            } elseif (function_exists('exec') && strstr(PHP_OS, 'WIN')) {
                exec("taskkill /F /PID $processId") ? TRUE : FALSE;
            }
```
and`src/Console/ContinueCommand.php
src/Console/PauseCommand.php
src/Console/TerminateCommand.php`

**Comment by mfn** [comment]
> Remove "ext-posix": "*",from composer.json

This would miss then the proper requirements (at least for the system supporting it).

What is the proper composer declaration so this works for both Unix/Windows environments?

**Comment by driesvints** [comment]
Closing this in favor of https://github.com/laravel/horizon/issues/170
