### ISSUE TITLE
Jobs are always put on 'default' queue, while explicitly choosing another queue

### ISSUE THREAD

**Issue by brusselsregular** [laravel/horizon#285]
Hey guys! 

I just started using Horizon, and it seems awesome. 
I do have something weird going on: all my jobs are being put on the same queue.

- I defined 2 queues in my horizon.php file 
`
        'local' => [

            'supervisor-1' => [

                'connection' => 'redis',

                'queue' => ['default','reminders'],

                'balance' => 'auto',

                'processes' => 6,

                'tries' => 3,

            ],`

- In my code I explicitly choose the 'reminders' queue for a job:
`		SetupReminders::dispatch($user,$calendar)->onQueue('reminders');
`
- But these jobs are being executed by the default queue (recent jobs -> they are all on default). The 'reminders' queue does show up in the dashboard under 'current workload'...

What am I missing here?

**Comment by brusselsregular** [comment]
Any ideas on this? Reread the documentation but can't nail it down...

**Comment by mfn** [comment]
There's another way you can invoke it, can you test if this works for you?
```php
dispatch((new Job)->onQueue('high'));
```
See https://laravel.com/docs/5.5/queues , section "Queue Priorities". The "priority" shouldn't matter, it's just queues after all.

**Comment by robtesch** [comment]
I know this is an old issue, but for those of you coming across this. I believe the correct way to set up multiple queues in horizon is as follows:

Old: 'queue' => ['default','reminders'],

New: 'queue' => ['default,reminders'],

Note one comma separated string rather than multiple strings.

**Comment by dpde** [comment]
I have no issues with multiple queues.

Here is my horizon config:
```
'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => [
                    'default',
                    'emails',
                    'api-worker',
                    'a-nother-api-worker',
                    // etc..
                ],
                'balance' => 'simple',
                'processes' => 12,
                'tries' => 3,
            ],
        ],
```

And this is how is dispatch jobs:

```
dispatch(new DoSomething($parameter))->onQueue($queue);
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
