### ISSUE TITLE
horizon:terminate must be executed on the same node as horizon is deployed

### ISSUE THREAD

**Issue by mattbucci** [laravel/horizon#287]
I thought that horizon:terminate was a drop in for queue:restart which can be executed from anywhere.

If horizon:terminate is executed somewhere other than where horizon is hosted, horizon won't be restarted and will fail silently with no output.

**Comment by mfn** [comment]
Is this a documentation issue?

Since horizon is killing processes directly, I assume it won't change anytime soon.

**Comment by driesvints** [comment]
I fail to see how executing `horizon:terminate` somewhere else than where the actual code is hosted would work.
