### ISSUE TITLE
horizon:terminate must be executed as the same user horizon is running as. 

### ISSUE THREAD

**Issue by mattbucci** [laravel/horizon#288]
Because horizon:terminate utilizes posix_kill it's unable to end other user processes and bounce horizon during deployment. This means that your deployment user MUST be the same as your horizon user. Additionally, this issue fails silently. The only way to tell is that issuing the command over and over gives the same output over and over while repeating a successful command should result in a change in process ID output by the command. 

This is not the case for queue:restart

**Comment by mattbucci** [comment]
I came across this issue because

We have 3 nodes
2 lamp nodes and 1 worker.

All 3 share an NFS mount containing the codebase. On deploy we ssh into node1 and do our thing and we used to run PHP artisan queue:restart from there. When we switched to horizon it seemed to be suggested we could just swap this for horizon:terminate but that's not the case and horizon:terminate will fail silently if no horizon process is found.

**Comment by mfn** [comment]
Unless someone changes how Horizon works under the hook (killing processes), this seems to be a documentation issue?

**Comment by lukepolo** [comment]
Ah thanks, I am having this issue currently

**Comment by driesvints** [comment]
As @mfn I think it's just necessary to perhaps document this instead of it being an actual issue.
