### ISSUE TITLE
Queue Failed 

### ISSUE THREAD

**Issue by pyaesone17** [laravel/horizon#290]
I retry failed jobs from terminal like this
"php artisan queue:retry all". 
All of the jobs has been successfully processed. 
But there are failed jobs that doesn't disappear from the dashboard 
although jobs failed table was cleared.

**Comment by mfn** [comment]
What version of Laravel? What version of Horizon?

**Comment by andreladocruz** [comment]
@mfn ,

I'm having the same issue here.

After reprocessing the jobs manually by horizon's interface, they are still listed as failed. 

The retry button in the list is not showing any more, but if I go to job details, I can retry it.

laravel/framework - v5.5.34
laravel/horizon - v1.2.2

**Comment by andreladocruz** [comment]
@mfn,

![captura de tela 2018-02-18 as 16 36 24](https://user-images.githubusercontent.com/3315596/36354287-fa238ff8-14c9-11e8-899e-b979d994fcf1.png)

**Comment by pyaesone17** [comment]
@andreladocruz 
For temporary workaround, I have to run php artisan cache:clear.
But it will remove ur current processing jobs too.

**Comment by andreladocruz** [comment]
@pyaesone17 
So it can't be done LOL. 
I can't vanish the jobs on the line just to see an empty list =)

**Comment by danijelk** [comment]
Indeed, this is still a problem today, there is no sync between the artisan command and horizon regarding failed jobs.

**Comment by driesvints** [comment]
You shouldn't be using the `queue:retry` command when using Horizon. Just use the Horizon UI to retry jobs.
