### ISSUE TITLE
Failed job handler

### ISSUE THREAD

**Issue by mewejo** [laravel/horizon#291]
Hi,

Thanks for this awesome framework.

Forgive me if I'm being blind, but I can't see any handers for a failed job. For example, if my job fails, and after Horizon has retried it X times, I'd like to know so I can dispatch another job to do something else.

I'm having problems with jobs timing out, but never knowing if they've been given up on by Horizon.

Is this possible?

Thank you

**Comment by Donny5300** [comment]
Did you took a look at the `failed()` method in a job?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
