### ISSUE TITLE
Metrics with StatsD/Graphite?

### ISSUE THREAD

**Issue by fedeisas** [laravel/horizon#295]
I'm working on a project where I'm working with queues, Redis and PHP, even using some Illuminate components. 

So even when I couldn't use Horizon directly on my project, I looked into it for _inspiration_. When I tried to implement some ideas from the Metrics layer into my own project, I decided that it was *much* simpler to just use StatsD/graphite.

I think that, even when the installation steps can be more complex, that switch could clean up the codebase and give much more powerful metrics.

Now that everyone is using Docker, adding new software to the stack shouldn't be that difficult.

Just my two cents.

**Comment by mfn** [comment]
> Now that everyone is using Docker, adding new software to the stack shouldn't be that difficult.

I'm not using docker in production.

And the built-in capabilities were exactly right for us to start with. In the end, we too extract custom information right right our Laravels Redis key information regarding the jobs (but not actually Horizon).

So, what are you actually proposing?

**Comment by fedeisas** [comment]
> So, what are you actually proposing?

Remove all the code that keeps Redis metrics and generates snapshots, remove the cronjobs for that, you can delete a lot of code and send metrics via UDP to StatsD, store them on Graphite, and make queries to that server to render the graphs on the dashboard.

I love that horizon handles worker scaling, but for tracking metrics, I just felt that it could be replaced with an existing solution that's not so hard to use and a battle-tested solution.

I'm not totally sold on the idea, just wanted to open the discussion to others.

**Comment by driesvints** [comment]
We have no plans on switching to anything else than Redis at the moment.
