### ISSUE TITLE
Feature request: Progress bar

### ISSUE THREAD

**Issue by vincemukiiri** [laravel/horizon#298]
It would be nice to have a progress bar in the horizon dashboard for long running jobs, similar to the way console commands can output progress bars.

I was thinking that a job could accept a progress bar class similar to `Symfony\Component\Console\Helper\ProgressBar` and the job would do all the necessary logic e.g. `$progressBar->start($max)`, `$progressBar->advance()`, `$progressBar->finish()`

**Comment by driesvints** [comment]
I'm not really sure how this would even be implemented. This would mean that each job needs to provide info on how long it would run?

**Comment by tpetry** [comment]
@driesvints This cloud work like https://github.com/imTigger/laravel-job-status

So the implementation of a queue job is calling progress information functions on the job and these values are saved to the redis database and displayed in horizon. This would really improve the functionality of horizon for some long running jobs which need minutes.
