### ISSUE TITLE
Can't access /horizon

### ISSUE THREAD

**Issue by Dartanjan** [laravel/horizon#300]
Initially I had `Horizon::auth` inside of `routes/web.php` and it worked as I could access `/horizon`. Then it stopped working for reason unknown to me.

I now moved the code into AppServiceProvider.php:
```php
\Horizon::auth(function ($request) {
    \Log::info('horizon auth!');
    return true;
});
```
But still no dice. `/horizon` returns 403. I cleared route cache, config cache. Really weird as it has definitely worked before.

**Comment by Dartanjan** [comment]
This has resolved itself after I pushed a few commits, so maybe it's the `config:clear` that fixed it, I don't really know.

**Comment by xlcrr** [comment]
I had the same error trying to access horizon in production which was returning 403 

```
php artisan config:clear 

php artisan config:cache 
```

solved it
