### ISSUE TITLE
Empty Failed Job Detail

### ISSUE THREAD

**Issue by andreladocruz** [laravel/horizon#301]
When trying to access the details of a failed job I got a blank one.
Attached images. 
![captura de tela 2018-02-24 as 15 17 52](https://user-images.githubusercontent.com/3315596/36631820-38d92130-1976-11e8-92f5-c219a55efb26.png)
![captura de tela 2018-02-24 as 15 18 08](https://user-images.githubusercontent.com/3315596/36631821-38f2bcee-1976-11e8-90f5-e769572b877e.png)
Job payload:
`{"type":"job","timeout":null,"tags":["App\\Lead:8a32225e-4b2f-4756-b127-01ddfb4f16a0"],"id":"78751","data":{"command":"O:59:\"App\\Jobs\\Autoresponders\\Infusionsoft\\ProcessLeadIntegration\":13:{s:4:\"lead\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:8:\"App\\Lead\";s:2:\"id\";C:16:\"Ramsey\\Uuid\\Uuid\":36:{8a32225e-4b2f-4756-b127-01ddfb4f16a0}s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";}s:7:\"request\";a:3:{s:4:\"name\";s:31:\"Manoela Jaqueline pereira pires\";s:5:\"email\";s:21:\"manuhpiress@xxxxxx.com\";s:6:\"Phone1\";N;}s:8:\"settings\";a:1:{s:3:\"tag\";s:4:\"1668\";}s:4:\"cost\";d:0;s:9:\"queued_at\";O:13:\"Carbon\\Carbon\":3:{s:4:\"date\";s:26:\"2018-02-24 10:34:56.111242\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:17:\"America\/Sao_Paulo\";}s:10:\"started_at\";N;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:13:\"autoresponder\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\Autoresponders\\Infusionsoft\\ProcessLeadIntegration"},"displayName":"App\\Jobs\\Autoresponders\\Infusionsoft\\ProcessLeadIntegration","timeoutAt":null,"pushedAt":1519479296,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"attempts":2}`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
