### ISSUE TITLE
Horizon dashboard doesn't wait for previous Ajax requests

### ISSUE THREAD

**Issue by williamvicary** [laravel/horizon#303]
When a server is under high load Horizon's dashboard ends up effectively DDOSing the web server via it's Ajax requests. I only experienced this on a local environment when running a lot of workers but I'm sure this could also occur in production.

The cause is the Ajax pings it uses to request updated data, it doesn't await a response and/or kill the last request before requesting more data. 

Either the time between pings needs increasing or the app needs to wait/abort the previous requests before requesting more data, I had a queue of 500 requests and my laptop was screaming before I realised what the issue was!

**Comment by mkingbe** [comment]
related with #211

**Comment by driesvints** [comment]
Should be ok now I guess with the above PR merged?
