### ISSUE TITLE
How to remove --memory and --timeout from command.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/horizon#305]
When run horizon, It will auto insert `--memory` and `--timeout` to command.

But I don't want it, With my queue work for some reason.

```
[ThunderBirdsX3@lucky e-slip]$ ps -fC php
UID        PID  PPID  C STIME TTY          TIME CMD
horizon+  3207  1066  2 11:51 ?        00:00:00 php /var/www/vhosts/mysite.com/html/e-slip/artisan horizon
horizon+  3214  3207  3 11:51 ?        00:00:00 /usr/bin/php artisan horizon:supervisor mysite.com-OQfz:generate redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=5 --balance=simple --max-processes=10 --min-processes=1
horizon+  3224  3214  9 11:51 ?        00:00:00 /usr/bin/php artisan horizon:work redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=5 --supervisor=mysite.com-OQfz:generate
horizon+  3225  3214  9 11:51 ?        00:00:00 /usr/bin/php artisan horizon:work redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=5 --supervisor=mysite.com-OQfz:generate
```

Can i change some line in config to remove it?

**Comment by halaei** [comment]
These options have default values so you can't disable them by not providing them in the command line.
I think `--memory=0` `--timeout=0` will disable them.

**Comment by SlyDave** [comment]
Worth noting that none of the extra settings are documented here: https://laravel.com/docs/6.x/horizon#configuration

So it's non-obvious that you can set memory, timeout, delay, tries, nice etc. in the 'environments' section of the  `config/horizon.php`

**Comment by driesvints** [comment]
@SlyDave feel free to send in a pr for that
