### ISSUE TITLE
Serialization or possible cacheing issue in the constructor

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#314]
I have a constructor on the job, which refreshes the authentication token and caches it for one hour. This is so that I don't have to refresh the token on every single job. The issue seems that if you retry a failed job, the caching does not work anymore and it retains the old initial value forever.

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($gtin)
    {
        ...

        $this->accessToken = Cache::remember('accessToken', 60, function () use ($provider) {
            return  $provider->getAccessToken('refresh_token', [
                'refresh_token' => config('services.zoho.refreshToken'),
            ]);
        });
    }

In the example below, the retried job in the bottom will always fail with "incorrect auth token", but when manually calling the job again from a controller, it will work just fine. I've tried all available options, like running php artisan cache:clear and php artisan horizon:terminate before retrying the job, but the original job will always keep failing.

So I have strong hunch that it has stored the $this->accessToken during the initial failed run and when I retry the job >1 hour later, it will still have the same value. I guess it shouldn't be like this? The AccessToken implements JsonSerializable if it makes any difference.

![image](https://user-images.githubusercontent.com/1290186/37715942-fc0e5cb6-2d25-11e8-99f8-929d123acb77.png)

**Comment by lasselehtinen** [comment]
I am not familiar with the Laravel internals enough, but now that I checked the payload on the failed, the accessToken is actually there. I thought Laravel would reserialize the job on runtime or does that only include models? If that is the case, the fix would be to move the token generation from the constructor to the handle method?

**Comment by driesvints** [comment]
Heya. So the way this works is that the values for the job are indeed serialized and saved so the job can be retried with the data it had at construction time. It won't re-use the constructor content.
