### ISSUE TITLE
Laravel version < 5.5?

### ISSUE THREAD

**Issue by eleftrik** [laravel/horizon#32]
Is there any chance to use Horizon with Laravel 5.3 or 5.4?
Thanks

**Comment by ntzm** [comment]
I don't believe there are any plans to do that:

> Horizon requires Laravel 5.5, which is currently in beta

**Comment by vladimir-yuldashev** [comment]
According to `composer.json` you can install it on 5.4:

```
"illuminate/contracts": "~5.4",
"illuminate/queue": "~5.4",
"illuminate/support": "~5.4",
```

**Comment by alexbowers** [comment]
It _may_ work, but it isn't supported.

**Comment by Dylan-DPC** [comment]
@vyuldashev 
>>> According to composer.json you can install it on 5.4:

"illuminate/contracts": "~5.4",
"illuminate/queue": "~5.4",
"illuminate/support": "~5.4",

No this will change when 5.5 releases and could cause issues later

**Comment by jbrooksuk** [comment]
I'm sure @taylorotwell said he'd been testing with 5.4 too though.

**Comment by brexis** [comment]
It works with Laravel 5.4 except some a JS issue. I'm not sure that the issue is related to the laravel version.

**Comment by themsaid** [comment]
No plans for supporting 5.4

**Comment by timgavin** [comment]
Can the [docs](https://laravel.com/docs/master/horizon) be updated to reflect that it only works with 5.5?

**Comment by ntzm** [comment]
@timgavin You can submit a PR to laravel/docs

**Comment by vzool** [comment]
@eleftrik I made a fork [here](https://github.com/vzool/horizon) for 5.4.

Hope it helps <3

**Comment by eleftrik** [comment]
Thank you @vzool! I'll try it as soon as I can
