### ISSUE TITLE
OnOneServer executing multiple times

### ISSUE THREAD

**Issue by benjaminsweney** [laravel/horizon#322]
I have the following job running:

`$schedule->job(new \App\Jobs\RenewCharges)->hourly()->onOneServer();`

However in the Horizon Dashboard I see it executes twice (as I'm running two servers). 

Environment setup as:

```
'production' => [
    'default' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 10,
        'tries' => 3,
    ],
    'overtime' => [
        'connection' => 'overtime',
        'queue' => ['overtime'],
        'balance' => 'simple',
        'processes' => 3,
        'tries' => 2,
        'timeout' => 2700, // forty five minutes
    ],
],
```

and: 

```
'redis' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => 'default',
    'retry_after' => 90,
],

'overtime' => [
    'driver' => 'redis',
    'connection' => 'default',
    'queue' => 'overtime',
    'retry_after' => 3000, // Run for max 50 minutes
],
```

**Comment by driesvints** [comment]
The docs say the following:

> To utilize this feature, your application must be using the memcached or redis cache driver as your application's default cache driver. In addition, all servers must be communicating with the same central cache server.

Can you check if you have this set up correctly?

**Comment by benjaminsweney** [comment]
Yes can confirm this is setup correctly.

**Comment by driesvints** [comment]
Can you post the config of your cache?

**Comment by benjaminsweney** [comment]
It's a redis connection running on ElastiCache on AWS. What config are looking exactly?

**Comment by driesvints** [comment]
I want to check what the settings for your cache are. If you're using the same Redis connection, this might be a hint that things are overlapping.

**Comment by benjaminsweney** [comment]
Is this what you are after?

`'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],`

`'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],`

Sorry I'm not 100% where you're wanting the settings from.

**Comment by driesvints** [comment]
I meant the full contents of your `cache.php` file.

**Comment by driesvints** [comment]
Ah and your `database.php` file as well.

**Comment by benjaminsweney** [comment]
Cache.php

` . <?php

    return [

    /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache connection that gets used while
    | using this caching library. This connection is used when another is
    | not explicitly specified when executing a given caching function.
    |
    | Supported: "apc", "array", "database", "file", "memcached", "redis"
    |
    */

    'default' => env('CACHE_DRIVER', 'file'),

    /*
    |--------------------------------------------------------------------------
    | Cache Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the cache "stores" for your application as
    | well as their drivers. You may even define multiple stores for the
    | same cache driver to group types of items stored in your caches.
    |
    */

    'stores' => [

        'apc' => [
            'driver' => 'apc',
        ],

        'array' => [
            'driver' => 'array',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
        ],

        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],

        'memcached' => [
            'driver' => 'memcached',
            'persistent_id' => env('MEMCACHED_PERSISTENT_ID'),
            'sasl' => [
                env('MEMCACHED_USERNAME'),
                env('MEMCACHED_PASSWORD'),
            ],
            'options' => [
                // Memcached::OPT_CONNECT_TIMEOUT  => 2000,
            ],
            'servers' => [
                [
                    'host' => env('MEMCACHED_HOST', '127.0.0.1'),
                    'port' => env('MEMCACHED_PORT', 11211),
                    'weight' => 100,
                ],
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */

    'prefix' => 'laravel',

  ];`

Database.php
`  <?php

    return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'mysql'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],

  ];`

Thanks for your help.

**Comment by driesvints** [comment]
Ah ok, I think I know what's going on. It seems you're sharing the same DB with Horizon and your cache store. It's best to separate these because otherwise you'll get issues with your cache being cleared and also your jobs etc (or the problem you're facing).

The current Laravel skeleton has separate Redis connections for cache and queues: https://github.com/laravel/laravel/blob/master/config/database.php

```php
    'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

    ],
```

And in the `cache.php` the Redis driver setup looks like this (note the "cache" connection):

```php
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],
```

So what I would suggest is to update your config files with the latest Laravel skeleton files (even update Laravel itself to the latest version) and definitely make sure you're using different Redis connections for your cache and queue. Let me know if that helps.

**Comment by benjaminsweney** [comment]
Sorry for the delay - I thought you may have cracked it with that one, setup new redis database etc. but finally realised I'm not actually using redis as the cache driver. 

Anything else pop to mind? Thanks!

**Comment by driesvints** [comment]
What are you using as a cache driver then? Can you post some of your `.env` values? (without sensitive keys of course)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by McKean** [comment]
We are encountering the same issue so I'm re-opening this.

Our setup on AWS:
4 beanstalk environments (web, worker1, worker2, preprod-web)
instance count is normally as follows:
web: 2 (can scale to 8)
worker1: 1 (can scale to 8)
worker2: 1 (can scale to 8)
preprod-web: 1

cron scheduled jobs are only triggered on the worker environments but the tasks are processed twice from what we observe.
Based on beanstalk conf it will only trigger cron on one instance in the environment.

we use the onOneServer command and have redis as a cache server to keep track of the command locking.

Yet we still see the issue.

If we use withoutOverlapping it works as expected. But this isn't really clean.

Any ideas? Happy for  any inputs.

Redis db conf:
```
    'redis' => [

        'client' => 'predis',

        'default' => [
            'host'     => env('REDIS_HOST', 'redis'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

        'cache' => [
            'host'     => env('REDIS_HOST', 'redis'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 1,
        ],

    ],
```

Redis cache store:
```
...
    'default' => env('CACHE_DRIVER', 'redis'),
...
    'stores' => [
...
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],
    ],
...
```

**Comment by McKean** [comment]
@driesvints should I create a new issue or do you want to re-open this?

**Comment by driesvints** [comment]
@McKean I honestly think it's better that you switch to Laravel for scheduling. Scheduling isn't even documented for Lumen.

**Comment by McKean** [comment]
@driesvints thanks for the response, I thought this might have been related, we are in fact using laravel, so I'll post this where relevant.

**Comment by driade** [comment]
I'd really interested in knowing if for onOneServer to correctly work, servers' time must be completely synchronized, as it seems.

I'm looking for some way to have 2 or more servers running the scheduler and be sure each job executes just once when it has to. I'm not really sure "onOneServer" would fit, it'd be something like "onceEachTime".

**Comment by matthiasPOE** [comment]
@driade having the exact same issue at the moment that we want to have multiple servers running the scheduler but `onOneServer` enabled. However we are noticing that some jobs are so quick that due to time diffs its running it on a second.

Did you manage to solve this?

**Comment by driade** [comment]
Hi @matthiasPOE Well, finally I didn't get an exact answer to the question. I asked in a few places and got nothing.

What I did read is the way the machines syncronize their time in AWS EC2, and it seemed by then that AWS handles time at hardware level, but I'm not sure.

What I can tell you is that "it works on my machines" :), all in groups of 2 in EC2.

If you don't find the solution, I may suggest you to have a table of "finished commands" where you can "check" if there's < X seconds that the command ran in another machine, as a matter of fallback.
