### ISSUE TITLE
Interval of livedata dashboard

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#327]
Hi,

Is there some config file for changing the interval of the livedata on dashboard screen?

**Comment by driesvints** [comment]
Hmm. Seems like some others have requested this as well. I can see that this might be something that you'd like configured so I'll mark this as a feature request. Feel free to send in a PR which implements this in a nice and clean way.

**Comment by tomswinkels** [comment]
I have make a pr https://github.com/laravel/horizon/pull/514

**Comment by darki73** [comment]
My preferred way for changing interval would be something like dropdown (the way it implemented in Grafana) right next to the "Refresh" button in the top right corner of the application

**Comment by tomswinkels** [comment]
@darki73 good idea! Maybe you can make a PR for that?

**Comment by driesvints** [comment]
Closing this as Taylor rejected the PR for this back in the day.
