### ISSUE TITLE
Clear all jobs of one queue

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#328]
Hi,

In beanstalk there is some button "Delete all ready jobs" is there in horizon also a button for that action?

**Comment by bryceadams** [comment]
You can create a command that executes code like:

```
use Redis;

Redis::connection()->del('queues:queue-name');
```

And it will clear that queue's jobs (which are ready/have not yet been run).

**Comment by neorganic** [comment]
Can you give a real life example ?because this doesn't seem to give me any effect.

**Comment by tomswinkels** [comment]
Yeah, but its better that i can do this in Horizon self! 👍

**Comment by neorganic** [comment]
@tomswinkels  Fully agree - that would be a great improvement !

**Comment by divdax** [comment]
yup! for would be cool to clear the queue! +1

**Comment by tomswinkels** [comment]
@taylorotwell :-) ?

**Comment by vmosoti** [comment]
Try using this package: https://github.com/morrislaptop/laravel-queue-clear

**Comment by driesvints** [comment]
I'll mark this as a feature request for now. Would be open to PRs which would implement this in a nice and clean way.

**Comment by mfn** [comment]
Ideally the functionality is available in Laravel but Horizon can expose an UI for that…

**Comment by dillingham** [comment]
Currently looking for this now
I have 90k jobs that are false due to a user clicking a import button too many times.

**Comment by ronlobo** [comment]
@dillingham what a diligent user, clicking that button 90k times 😆

**Comment by dmitryuk** [comment]
https://github.com/RoboFinance/laravel-redis-queue-clear

**Comment by andreladocruz** [comment]
Any news about when this feature will be added to horizon???

**Comment by driesvints** [comment]
@andreladocruz as soon as someone sends in a pr

**Comment by andreladocruz** [comment]
@neorganic, do you know how to run it in tinker?

**Comment by andreladocruz** [comment]
thanks...

do you know how to run the command 

Redis::connection('horizon')->del('queues:queue-name')

in tinker?

> @andreladocruz as soon as someone sends in a pr

**Comment by tomswinkels** [comment]
@parkourben99 thnx for creating a pr :)

**Comment by driesvints** [comment]
Since Taylor rejected the PR we're probably not going to implement this anytime soon, sorry. Anyone's free to do another attempt of the related PR which solves all the things that still need to be taken care of.

**Comment by rana01645** [comment]
I'm using this command for clearing queue.
`use Illuminate\Support\Facades\Redis;
Redis::connection()->del('queues:queue-name')
`
Unfortunately it's not removing **delayed** jobs.

Anyone have any clue about this.

**Comment by garbinmarcelo** [comment]
> I'm using this command for clearing queue.
> 
> ```
> use Illuminate\Support\Facades\Redis;
> Redis::connection()->del('queues:queue-name');
> ```
> 
> Unfortunately it's not removing **delayed** jobs.
> 
> Anyone have any clue about this.
> 
> **Update:**
> This command removed my delayed jobs
> `Redis::connection()->del('queues:queue-name:delayed');`

Hi, does that remove the complete jobs too? I have the version of Laravel 7.
![image](https://user-images.githubusercontent.com/9335588/78616191-ef3e3a80-7849-11ea-8730-86b38aff3a7e.png)

**Comment by sentiasa** [comment]
I had to give id explicitly like so:

`\Redis::connection('horizon')->del('queues:my-queue:delayed', 39);`

**Comment by marcosdsdba** [comment]
to cleaning all failed and completed :
Open redis-cli (my redis not using default port)
#redis-cli
 127.0.0.1:6378> FLUSHDB

**if u uses password:**
127.0.0.1:6379> auth your_secret_here

after:
 127.0.0.1:6378> FLUSHDB
