### ISSUE TITLE
Horizon.log

### ISSUE THREAD

**Issue by gbryant200** [laravel/horizon#330]
What's the best way to control the size of the horizon.log file and/or setup the log file to rotate?

Can you setup a logging channel in Laravel or in the laravel/horizon framework somewhere?

something like this maybe?
```
'horizon' => [
	        'driver' => 'daily',
	        'path' => storage_path('logs/horizon.log'),
	        'level' => 'debug',
	        'days' => 7,
        ],
```

**Comment by driesvints** [comment]
This is something you'd have to do yourself on your infrastructure. Perhaps clear the log every x days or something. The example in the docs is managed by Supervisor so Horizon itself doesn't touches it.
