### ISSUE TITLE
Job trimming for monitored tags

### ISSUE THREAD

**Issue by antons-** [laravel/horizon#333]
From what I can tell, when you monitor a tag in Horizon it does so indefinitely until you stop monitoring that tag or your Redis instance runs out of ram.

We would like to keep monitoring tags over an extended period of time, but have a way of configuring job trimming for monitored tags, just like with recent and failed jobs.

Ideally I would like to trim jobs older than a week automatically with monitored tags.

Is this already possible or is there a different approach here I can take?

**Comment by driesvints** [comment]
Could be a nice feature to add an input box with the desired minutes on how long to monitor a tag. I'll mark this as a feature request.

**Comment by mfn** [comment]
I believe this is (or: related to) https://github.com/laravel/horizon/issues/271

**Comment by driesvints** [comment]
@mfn @fgilio do you believe this can solve #271?

**Comment by fgilio** [comment]
Yes, I think it can partially solve that issue.
What I mean with partially is that it will depend on the amount of jobs. If a system has 1000 jobs per minute then the Redis db could be filled in just an hour. But this may be solved by just making the value configurable and stating this fact clearly in the docs, so every dev chooses an appropriate value.

**Comment by mfn** [comment]
@driesvints I second what @fgilio said above: depending on the amount of activity there seems to be always a possibility to "eat too much ram".

I guess the only real solution would be an implementation of an RRD which usually have fixed sizes, but I digress.

**Comment by driesvints** [comment]
I've sent in a PR for this: https://github.com/laravel/horizon/pull/484

About the problem of speedy fill ups: I think you'll probably have bigger problems in that case and it doesn't really makes sense to monitor anyway if your DB can't keep up.

**Comment by driesvints** [comment]
@mfn @fgilio can you both have a look at https://github.com/laravel/horizon/pull/484 and let me know on the PR itself if it looks ok to you?
