### ISSUE TITLE
Horizon jobs running very slowly

### ISSUE THREAD

**Issue by reachsampath** [laravel/horizon#334]
@taylorotwell 
I updated the prefix in config/horizon.php file
in horizon dashboard it is active and 
queues are running very slow, or not working perfectly.
I configured two environments in same server in Forge. And added the php /path/artisan horizon

**Comment by ellisio** [comment]
Check your database, ensure you're not pegging the CPU to 100%. We had a single job, running a single query, that causes the database to spike to 100% and a `70ms` job ended up taking `60-90s`.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
