### ISSUE TITLE
Recent Jobs are not running with SSL

### ISSUE THREAD

**Issue by Starkmann** [laravel/horizon#335]
Hi,

i just switched to SSL and now the recent jobs are loading forever.

The requests are:
https://server/horizon/api/jobs/recent/?starting_at=-1&limit=50 [canceled]
http:/server/horizon/api/jobs/recent?starting_at=-1&limit=50 [blocked:mixed-content]

My apache is configured to redirect all requests to ssl.

All other views are working just this one seems to be broken, thats why i think this might be a bug.

I have to mention that i'm running the application inside of a docker with no ssl and an apache proxy that has ssl.

**Comment by Starkmann** [comment]
Might be connected to #145

**Comment by Starkmann** [comment]
Removing
```
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]
```
 in default htaccess helps but that can not be the solution.
I'm using horizon 1.3.1 so that pull request (https://github.com/laravel/horizon/pull/165/) is included

**Comment by driesvints** [comment]
This works fine for me so I suspect there's some configuration issue on your end. Try one of these support channels to see if someone can help you:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
