### ISSUE TITLE
Improved Pagination

### ISSUE THREAD

**Issue by mhndev** [laravel/horizon#336]
using horizon pagination we just access to next and prev
what we need is number of pages go to last page
or first page and any other page

**Comment by fridzema** [comment]
Maybe infinite scroll with counters is even better.

**Comment by themsaid** [comment]
No plans to implement this. Sorry.

**Comment by fh32000** [comment]
any update here 
it will be good if i can set `starting_at` and `limit` as  input or at least  set   `limit` in config
