### ISSUE TITLE
Recent jobs doesn't show older jobs

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#339]
I pushed around 1000 jobs to the queue which takes around 8 hours to process. Seems like jobs listed in "Recent jobs" is based purely when the job was pushed to the queue. It means that jobs that are really old are not shown after a certain period of time. Would it make sense to show jobs are that never than X minutes OR if they have not been processed yet?

![image](https://user-images.githubusercontent.com/1290186/39915417-92d2191e-5510-11e8-8e7d-5e1f5dff54a2.png)

![image](https://user-images.githubusercontent.com/1290186/39915433-9b895842-5510-11e8-826e-b4a268c15dda.png)

**Comment by driesvints** [comment]
If you check the `horizon.php` config file you can extend the retention time for the recent jobs tab at `trim.recent`. Is this what you needed? Feel free to respond back and provide more info.
