### ISSUE TITLE
RedisJobRepository::findFailed() includes successful jobs

### ISSUE THREAD

**Issue by garando** [laravel/horizon#340]
What I'm trying to implement: I want to dispatch job only if another job with the same tag isn't running already. Unfortunately, I haven't found such method in this framework, so I'm trying to implement it myself using Horizon's services. I would be glad if you point me how I am supposed to do it the right way.

A bug I found: I took job IDs from TagRepository and now I'm trying to check if this job is failed. I supposed that RedisJobRepository::findFailed() will return job only if it's failed and return null otherwise. However, right now it seems to just return job by ID regardless of its status.

**Comment by driesvints** [comment]
I believe you're right and that this indeed isn't correct. I'll try to have a look at a later time to see if this can be fixed.
