### ISSUE TITLE
Does Laravel Horizon sent Notification via Slack or email etc when a Job Fails

### ISSUE THREAD

**Issue by jofomah** [laravel/horizon#341]
I have read the document and it is not clear whether Laravel Horizon sends out notification when a job fails or not, please can someone that knows help me clarify this?

**Comment by ellisio** [comment]
It does not, at least not that I'm aware of. You can use services like [Sentry](https://sentry.io) or [New Relic](https://newrelic.com/) to configure monitoring on your application. Both of these services integrate with Slack for alert notifications.
