### ISSUE TITLE
[enhancement] Allow Horizon to run specific queue worker

### ISSUE THREAD

**Issue by sunel** [laravel/horizon#343]
For Example

I have 2 server for queues, One can handle simple jobs and Other can handle jobs that are complex.

As of now we can run the 'horizon' which will run all the queue worker to process both kind on job based on the current workload.

But it would be great if the master process can handle specific worker

```bash
php artisan horizon --worker=supervisor-1,supervisor-2
```

```bash
php artisan horizon --worker=supervisor-3
```

This will enable server to  work on specific targeted queues.

**Comment by hubertnnn** [comment]
I came here looking for similar thing, but I would suggest using the  current "environment" variable, since I don't really see a use for having different setups per environment rather than per machine.

My suggestion is to use environments like this:
```
    'environments' => [
        'standard-work' => [
            'mailer-supervisor' => [
                'connection' => 'redis',
                'queue' => 'mail',
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
            ],
            'default-supervisor' => [
                'connection' => 'redis',
                'queue' => 'default',
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
            ],
        ],
        'encoding' => [
            'encoding-supervisor' => [
                'connection' => 'redis',
                'queue' => 'encoding',
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
            ],
        ],
    ],
```

And then in .env set one of this:

```
HORIZON_ENV=encoding #encoding server
HORIZON_ENV=standard-work #main server
HORIZON_ENV=standard-work,encoding #development server
```

This way it should be possible to make a fine grained distribution of workers between machines, and still keep the config in one place

**Comment by driesvints** [comment]
You could replace the `queue` value with an `env` variable which depends on the app/service. Or use different environments like @hubertnnn suggested.

**Comment by poseidonphp** [comment]
@hubertnnn 
This is working really well, but i have one small hiccup. What is the "environment" field doing in the config file?
I would like to keep APP_ENV to "local", "production", etc.. as i have other logic that is based on those values. 
However, i can only seem to get this to work properly if i change the value of APP_ENV. I set a HORIZON_ENV value in my .env, but it doesnt appear to have any effect when i start up my queues. Did i miss a step? Looking at the source code of Horizon, it looks like it's set to load based on APP_ENV only. 
Thank you for this suggestion!

**Comment by driesvints** [comment]
@poseidonphp `HORIZON_ENV` is something he's added himself to his config. It's not an official env variable of Horizon.

**Comment by bkuhl** [comment]
Thanks @itailulu, after tinkering with this more, the `HORIZON_ENV` is not necessary.  Horizon's use of "environment" vs the app environment is just a little confusing IMO.  You don't need the `HORIZON_ENV`, instead you can just pass `environment` as instructed in the docs.  For example, if I run the 2 commands

```
php /var/www/html/artisan horizon --environment=production
php /var/www/html/artisan horizon --environment=laravel-cloud
```

it runs the queues I expected on the supervisors I expect basd on the below config:

**config/horizon.php**

```
    'environments' => [
        'production' => [
            'let-it-die'        => [
                ...
            ],

            'live-forever'        => [
                ...
            ],

            // Used for jobs that may take a while to run
            'let-it-die-long-running' => [
                ...
            ],
        ],

        'laravel-cloud' => [
            'live-forever'        => [
                ...
            ],
        ],
    ],
```

And I see each supervisor and their expected queues reflected in the web interface:

<img width="1008" alt="Image" src="https://github.com/user-attachments/assets/723b3546-7520-4c61-bdd7-68c873924b51" />
