### ISSUE TITLE
/tmp directory is not cleaned on live server 

### ISSUE THREAD

**Issue by yamenarahman** [laravel/horizon#344]
Laravel: 5.5
Horizon: 1.2.3
php: 7.2
ubuntu: 16.04, LAMP

I don't know if this issue is related to redis server of horizon, but what I'm sure that this happens. When using database driver the `/tmp` starts to fill with tmp php files with pattern like this `php34gs1 phpwrd42` after the queue is processed the /tmp is cleaned and reverted. 

However when I use redis driver with horizon the `/tmp` directory is filled untill my my 60GB server is full and I only resolve this either by deleting them manual from cli or worse to reboot server.

with redis driver:
![screenshot from 2018-05-21 14-51-50](https://user-images.githubusercontent.com/24607365/40308469-ab958a46-5d06-11e8-8d05-ecca3d47972d.png)

with database driver:
![screenshot from 2018-05-21 14-52-12](https://user-images.githubusercontent.com/24607365/40308493-c0e0cb22-5d06-11e8-9da0-7750d378cc86.png)

the tmp php files that keep there permenantly:
![screenshot from 2018-05-21 14-54-33](https://user-images.githubusercontent.com/24607365/40308582-03701678-5d07-11e8-8051-c4fe2fb946e7.png)

**Comment by yamenarahman** [comment]
Till now I can't solve this or know why it happens, but there is a work around to install a cron job to clean `/tmp` directory.

The cron job will delete any file that is older that one day and will run daily at midnight.

By running `crontab -e` and paste the following:

`0 0 * * * sudo find /tmp -type f -atime +1 -delete`

Waiting to know any clue about why this is happening.

**Comment by Jarrid** [comment]
Just wanted to jump in and say I've seen the same issue too in the past week.  I woke up to the hard drive full, and 5k (SUPER fun) notifications sent to rollbar within a 10 minute window because the REDIS driver couldn't write to the hard drive (just glad this wasn't production). 
This is on version 1.2 of Horizon.

I have an older version of Horizon installed on another machine, and it does not have this issue (that's using version 1.0 - knocks on wood). And that one is processing like a MADMAN.

**Comment by Jarrid** [comment]
Just wanted to jump back in - this was NOT a Horizon or Redis issue for me.
I am using Redis to manage my queue, and the job that I was queueing was one that transfers data from the clients system to a third party API (Quickbooks - https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/104).  

Their API has a bug which was prevented logging from being disabled, and their logs are placed in the /tmp directory...to the tune of 100mb or so every couple of hours.

**Comment by driesvints** [comment]
Gonna close this one as this doesn't seems to be a Horizon issue.
