### ISSUE TITLE
Horizon should report when it drops timeouted job

### ISSUE THREAD

**Issue by psychob** [laravel/horizon#349]
So i have job that do a lot of stuff, and that takes some time. But for some reason mid-processing: it just disappeared:

- horizon dashboard **failed jobs** shows nothing
- **failed_jobs table** also don't have anything
- **logs** also don't have anything
- **output from horizon worker** also don't mention anything

It turns out, it was horizon worker, that just dropped that job without any trace. I don't think that should be default behavior.

```laravel/horizon: v1.2.3```

**Comment by driesvints** [comment]
Even though the process could be long running they can still time out. This is not something we can catch. Either update the max execution time or try to split up whatever you're doing in your job into multiple jobs with a shorter runtime.
