### ISSUE TITLE
Enhancement - Interface based on DB instead of Redis

### ISSUE THREAD

**Issue by Donny5300** [laravel/horizon#350]
Hi Themsaid/Tailor,

The Horizon stats like failed and processed jobs are loaded from Redis which doesnt allow to create a nice pagination for your job (what i've read from earlier threats). Maybe its an idea to write the processed jobs to the database too so it would be possible to run a query and extract information from the database for lets say items from a week ago, or maybe longer (depends on user preference). Having to many jobs in Redis also causes a Memory Limit Exceeded exception on the dashboard. Using a database will allow users to log better and perhaps in a more advanced way.

**Comment by driesvints** [comment]
Heya. At the moment we have no plans on providing integrations other than Redis. You could technically overwrite the `QueueManager` but it's unsure if Horizon would still properly function without Redis.
