### ISSUE TITLE
Seperate Queue Management Application

### ISSUE THREAD

**Issue by jefvanhoyweghen** [laravel/horizon#353]
We are working with a Lumen application and would like to user Horizon to get better queue management. 

We created a seperate Laravel App with Horizon installed and pointed it to our Redis server. It picks up the jobs well but immediately fails because it can't unserialize the object (which makes sense).

Would there be any way to run Horizon on a seperate app and run jobs from other app? 

Thanks for the suggestions!

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs or problems. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
