### ISSUE TITLE
Horizon Remote Queue Server

### ISSUE THREAD

**Issue by xemose** [laravel/horizon#358]
Hello,

I've integrated Laravel Queue into Slim3's framework and it is successfully querying jobs. I have a Horizon dashboard installed on the same server but in a different directory and subdomain. When I fire a job from Laravel queue, Horizon does pick up on it, since they're both using Redis, however, Horizon is trying to execute the queue with its own classes. From my understanding, Horizon is a monitoring tool that monitors jobs, not execute them. The error I am getting is 

> ReflectionException: Class TasksDomain does not exist in /opt/horizon/html/releases/20180625123803/vendor/laravel/framework/src/Illuminate/Container/Container.php:767

How can I have Horizon just monitor the queues instead of trying to execute them?

**Comment by DyceDAViBE** [comment]
Hi X,

From my understanding, horizon is not only for monitoring, he use the redis for execute too and he was made only for Laravel, so i dont think you can use it outside this scope.

I'm trying to integrated the ShoulQueue from Laravel to a similary Slim3 Framework project, how did you did this integration ?

Thanks

**Comment by driesvints** [comment]
As explained by @DyceDAViBE, Horizon monitors and scales your queues so it actively tries to distribute your jobs etc according to your config. Horizon only works with a Laravel application.
