### ISSUE TITLE
Runtime with several decimals

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#360]
Hi,

I have a new Laravel project that is using Horizon. I noticed that on the recent jobs listing the runtime is showing quite a few decimals, before this was always rounded to the nearest full seconds. Any ideas what might be causing this? I am using release v1.3.1. Could it be related to [this PR](https://github.com/laravel/horizon/pull/308)? I have tried to following command to force update on the assets, but it did not seem to help.

`php artisan vendor:publish --force --tag=horizon-assets`

![image](https://user-images.githubusercontent.com/1290186/41967133-972b3072-7a09-11e8-850c-e472a65b97b5.png)

**Comment by rAfitiiixxx** [comment]
I have the same problem, hope you will get a fix because i don't even know were to look for to solve this thing.

**Comment by JayBizzle** [comment]
Forcing the asset publishing worked for me when i had this issue, so not sure what your issue could be 😕

**Comment by lasselehtinen** [comment]
I actually tried this one again and Horizon package probably has been updated several times since the original ticket was created and it seemed to work this time. Should this be closed?

**Comment by driesvints** [comment]
This should be fixed in the latest version. Please let us know if the problem persists.
