### ISSUE TITLE
Job runtime format

### ISSUE THREAD

**Issue by yamenarahman** [laravel/horizon#364]
![screenshot from 2018-07-12 10-27-57](https://user-images.githubusercontent.com/24607365/42622896-c0c53cd4-85c1-11e8-87ea-c6b76a4c014b.png)

How to fix this? I think nobody needs all these digits.

**Comment by keesh7663** [comment]
I agree, that's an insane amount of fractional seconds to have for the runtime..  perhaps make it configurable in `/config/horizon.php`?

**Comment by JayBizzle** [comment]
This was fixed a few version ago, make sure you republish your assets...

Here's a screenshot from my Horizon...

<img width="79" alt="screen shot 2018-08-21 at 11 31 51" src="https://user-images.githubusercontent.com/340752/44396775-e9d99280-a535-11e8-9122-1dc2c0d2fffe.png">

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
