### ISSUE TITLE
Problems with timestamps (NaNs, Invalid date)

### ISSUE THREAD

**Issue by iShotFT** [laravel/horizon#371]
On both staging (centos) and local (ubuntu) environment I'm having issues with the timestamps.
- On the page 'Recent Jobs' I'm always getting Runtime 'NaNs'. 
- On the page 'Failed' I'm getting 'Invalid date' for 'Failed At' and 'NaNs' for 'Runtime'.

This combined with experiencing issue #366  is giving me headaches.

**Comment by cmizzi** [comment]
Same bug here... I don't have any timestamp (NaNs values) on all queued (recent and failed) jobs.

**Comment by davidruigrok** [comment]
Same issue. I think the problems occurs because horizon api returns failed_at and reserved_at as string (not as float) which can not be parsed within the vue component (result: _NaNs_ and _Invalid date_) :
```
{{ job.failed_at ? String((job.failed_at - job.reserved_at).toFixed(3))+'s' : '-' }}
```
```
{{ readableTimestamp(job.failed_at) }}
``` 
Part of API response (/horizon/api/jobs/failed):
```json
{"jobs": [
{
"id": "808121",
"connection": "redis",
"queue": "title:resources",
"name": "App\\Jobs\\TrackTitle",
"status": "failed",
"payload": {},
"exception": "...",
"failed_at": "1535147607,7085",
"completed_at": null,
"retried_by": [],
"reserved_at": "1535147607,6773",
"index": 0
}
]}
```
I have not yet figured out why failed_at and reserved_at are not set / parsed correctly in the api response. Same problems occurs with /horizon/api/jobs/recent and horizon/monitoring (detail page) API requests.

**Comment by webpatser** [comment]
I had the same some time ago. Republishing the assets did the trick then..?

**Comment by davidruigrok** [comment]
Unfortunately, republishing the assets did not solve it. 
Somehow, failed_at, completed_at, and reserved_at are stored as strings instead of floats.
Within redis (for _random_ job with id 1213931):
```
127.0.0.1:6379> HMGET horizon:1213931 id connection status exception failed_at completed_at retried_by reserved_at
 1) "1213931"
 2) "redis"
 3) "completed"
 4) (nil)
 5) (nil)
 6) "1538225702,0793"
 7) (nil)
 8) "1538225699,2691"
```
Temporary solution for now is changing the indexJobs method on _Laravel\Horizon\Repositories\RedisJobRepository_ (on line 195). I'm now forcing the failed_at, completed_at, and reserved_at to act as float instead of being a string:
```
protected function indexJobs($jobs, $indexFrom)
    {
        return $jobs->map(function ($job) use (&$indexFrom) {
            $job = (object) array_combine($this->keys, $job);
            if (!empty($job->failed_at)) {
                $job->failed_at = (float) str_replace(',', '.', (string) $job->failed_at);
            }
            if (!empty($job->completed_at)) {
                $job->completed_at = (float) str_replace(',', '.', (string) $job->completed_at);
            }
            if (!empty($job->reserved_at)) {
                $job->reserved_at = (float) str_replace(',', '.', (string) $job->reserved_at);
            }
            $job->index = $indexFrom;

            $indexFrom++;

            return $job;
        });
    }
```
Will have to look further why values are stored as strings.

**Comment by driesvints** [comment]
Hmm I can see how this can be a problem. Like you indicated @davidruigrok we'd probably need to cast the values to their proper types first. Not sure if your approach is the best one though.

Welcoming PRs for this.

**Comment by davidruigrok** [comment]
@driesvints, this was a dirty quick solution to get it working again. I will dive deeper into the code and create a better approach.

**Comment by philippe-tellier** [comment]
Any updates on this?

**Comment by driesvints** [comment]
Can you all give me your PHP, Redis and Horizon versions where you're experiencing this problem?

**Comment by driesvints** [comment]
I believe I might have found the problem. It's probably the same problem as https://github.com/laravel/horizon/pull/123 so we might need to do this everywhere microtime is used. I'll send in a PR.

**Comment by driesvints** [comment]
Related: https://stackoverflow.com/questions/30052461/php-why-is-the-dot-in-a-decimal-replaced-by-comma-when-casted-to-string

**Comment by philippe-tellier** [comment]
> Can you all give me your PHP, Redis and Horizon versions where you're experiencing this problem?

PHP: 7.2.11
Redis: 4.0.11
Horizon: 2.0.0

**Comment by iShotFT** [comment]
> Can you all give me your PHP, Redis and Horizon versions where you're experiencing this problem?


PHP 7.2.12 (cli)
redis_version:3.0.3
laravel/horizon: v1.4.3

**Comment by killgt** [comment]
@driesvints this is still happening if you use `'client' => 'phpredis'` and you set a locale in your app service provider:

`
setlocale(LC_TIME, 'es_ES.utf8');
`

Maybe it's related to #788 . I'm not sure if is there anything to be fixed on the laravel end...But It works well with the old predis package.
