### ISSUE TITLE
 /horizon/failed: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by yeyupl** [laravel/horizon#374]
errer: "https://www.***.com/horizon/failed"
2018/07/24 08:38:49 [error] 18777#0: *65181286 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 46706688 bytes) in /home/path/vendor/symfony/http-foundation/Response.php on line 346" while reading response header from upstream, client: 183.2.217.26, server: www.***.com, request: "GET /horizon/api/jobs/failed?starting_at=-1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.***.com", referrer: "https://www.***.com/horizon/failed"

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by backstageel** [comment]
I'm still experiencing this issue:

`{
    "message": "Allowed memory size of 33554432 bytes exhausted (tried to allocate 10567680 bytes)",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/var/www/siga/releases/20181115191238/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php",
    "line": 71,
    "trace": []
}`

I'm using PHP7.2 tried increasing memory_limit to 1GB in php.ini, tried to put ini_set("memory_limit",-1); in public/index.php and in FailedJobsController.php both without success.

**Comment by mfn** [comment]
@backstageel please provide more information, for example:
- is it a recent problem? Did you recently upgrade PHP? Laravel? Horzion?
- does this happen instantly? if not, how long does it take to trigger this problem
- only on certain jobs?
- are you **sure** your job/code does not allocate too much memory?
- please try to debug `\Laravel\Horizon\Supervisor::memoryUsage` and see how much it reports on its iterations (best is log it somewhere)
