### ISSUE TITLE
Horizon dies after few seconds

### ISSUE THREAD

**Issue by spwin** [laravel/horizon#375]
Hey,
I am trying to set up the local environment. I can see horizon dashboard with `Inactive` status.
When I am running `php artisan horizon` the status changes to `Active` for a second and then changes back to `Inactive` again. I tried using `supervisor` to run horizon but the same problem. From the supervisor logs I can see that it's running for a second, then restarting and starting again all the time. Is there any way to debug horizon and check why is it dying? I tried running `php artisan horizon -vvv` but every time the output is the same: Horizon started successfully. and then terminating the process. I can also confirm the queue is working fine when I run it using `php artisan horizon:work`.

**Environment details:**
Using Apache as a server on
Ubuntu 16.04.
Laravel version:  5.6.14
PHP version: 7.2
Redis server version: 4.0.11
Horizon version: 1.3

**Configuration**
config/queue.php
```
'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => 'default',
            'retry_after' => 90,
            'block_for' => null,
        ],
```

config/horizon.php
```
'local' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'auto',
                'processes' => 3,
                'tries' => 3,
            ],
        ],
```

.env
```
APP_ENV=local
QUEUE_DRIVER=redis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
```

**Any suggestions?**

**Comment by spwin** [comment]
Changed OS to Ubuntu 18.04 - this solved the problem. But some logging on horizon would be useful anyway.

**Comment by spwin** [comment]
@mfn I couldn't find other way than just comment `MonitorMasterSupervisorMemory.php` line 20 in vendor folder:
```
public function handle(MasterSupervisorLooped $event)
    {
        $master = $event->master;

        if ($master->memoryUsage() > 64) {
            // $master->terminate(12);
        }
    }
```
Works fine on local machine. If it's happening in production for you I think it's not a solution and you should increase memory on the server. 
Cheers!

**Comment by mfn** [comment]
Hardcoded memory usage checks are never awesome; I think it would be very interesting what `$master->memoryUsage()` reports in your case. Do you think you will be able to get this value, e.g. via `\Log::debug($master->memoryUsage());`?

**Comment by spwin** [comment]
Now it's `44.018829345703`, but this was happening for me periodically so I don't know what was the value before when it was crashing. This added line shows value every second so you can easily track it after `php artisan horizon`:
```
public function handle(MasterSupervisorLooped $event)
    {
        $master = $event->master;

        echo($master->memoryUsage() . "\n");
        if ($master->memoryUsage() > 64) {
            $master->terminate(12);
        }
    }
```

**Comment by Mohanrau** [comment]
Im having same issue any resolution team.Can anybody explain how this calculation happens `$master->memoryUsage()`.

**Comment by mohammed1146** [comment]
I have the same issue, and I noticed $master->memoryUsage() is affected if your app loading many things in ServiceProviders, such as app/Console/kernel.php if you have many commands. @spwin  if you disable theses things, the $master->memoryUsage() will be lower.

**Comment by mfn** [comment]
> Can anybody explain how this calculation calculating

You can see for yourself:
https://github.com/laravel/horizon/blob/cc67213034f68de7607f6ba682c3f08d3866b0dc/src/MasterSupervisor.php#L322-L325

> I have the same issue, and I noticed $master->memoryUsage() is affected if your app loading many things in ServiceProviders, 

What does `memoryUsage()` report in your case?

Maybe the hardcoded value in https://github.com/laravel/horizon/blob/cc67213034f68de7607f6ba682c3f08d3866b0dc/src/Listeners/MonitorMasterSupervisorMemory.php#L19-L21 needs to be simply configurable?

**Comment by driesvints** [comment]
Yeah we could maybe make this configurable.

**Comment by driesvints** [comment]
The PR to make this configurable was merged.

**Comment by robclancy** [comment]
I wish the error was added... 3am last night I had to setup worker daemons because I couldn't work out why horizon was just shutting down. Then today only realizing the problem because of this issue.
