### ISSUE TITLE
Runtime seems to be wrong sometimes.

### ISSUE THREAD

**Issue by joveice** [laravel/horizon#386]
Laravel 5.6
OS: Tested on: Fedora, RHEL, Homestead on windows, Ubuntu 16.04.

What:
Job runs for 3 mins, fails then repeats 3 times then gets marked as failed.
Now the runtime is 0.034s, this time changes each time so It's not the same every time, but it's allways way lower than the total job time. I had a job run for 2 hours, failed and it said it ran for only 43s.

Etc:
Queued at: 18-09-07 09:37:45
Failed at: 18-09-07 09:41:48
Runtime: 0.034s

This has happens on both jobs that fail and succeeds.

Have I configured something wrong or is this a bug?

**Comment by joveice** [comment]
Had to do with retries and it would then continue where the old one failed resulting in wrong times.

**Comment by fgilio** [comment]
@joveice did you fixed this? Was it a problem in your code or Horizon's?

**Comment by fgilio** [comment]
Ooh ok, thanks for the explanation!
