### ISSUE TITLE
Configurable Tag Display on Recent Jobs 

### ISSUE THREAD

**Issue by ragingdave** [laravel/horizon#388]
Some Jobs might have hundreds of model ids in cases where bulk queuing is in use. This makes the recent jobs ui basically useless as each recent job takes up a full window height.

Any chance that could be converted to something like a tooltip for all and then maybe a simplified tag display?

**Comment by driesvints** [comment]
Hmm yeah I can see how this can be improved. Just for anyone who's wondering how this would look:

![screen shot 2018-10-23 at 4 31 42 pm](https://user-images.githubusercontent.com/594614/47368032-2e71dd80-d6e1-11e8-8a0d-98ac9da68999.png)

I've tagged this as a feature request so we can take a look at a later time. If you're up for it, feel free to send in a PR.

**Comment by pactode** [comment]
Would it make sense to show a count of the tags instead? Then only show the tags in the tooltip. 

Something similar to:
![screenshot 2019-01-10 at 11 50 37](https://user-images.githubusercontent.com/5956778/50963814-09199200-14ce-11e9-922c-b39416b16085.png)

Let me know your thoughts.

**Comment by themsaid** [comment]
No plans to change this at the moment since I don't think it's a common problem.

**Comment by driesvints** [comment]
Talked to @themsaid about this and we're going to keep this open for now. I personally think clipping the content and clicking to show the rest is a good solution but feel free to say a different proposal.

**Comment by ragingdave** [comment]
So v3 is SO much better but I feel like there could still be improvement for batch jobs. Here is an example of a normally occurring batch job and how the tag display ends up looking (again way better in v3 but still):

![screen shot 2019-03-05 at 9 16 50 am](https://user-images.githubusercontent.com/1168344/53811444-6f97bb00-3f27-11e9-8efd-59480d42c5cd.png)

And there are more tags than in that screenshot for that single job

**Comment by driesvints** [comment]
https://github.com/laravel/horizon/pull/754 introduces a new way to display tags.
