### ISSUE TITLE
Horizon dashboard UI is all zeros

### ISSUE THREAD

**Issue by jab1000** [laravel/horizon#395]
We wanted more functionality and had previously been using Beanstalk -- we upgraded to Laravel 5.7 and are running Redis via RedisLabs.   We have 5 different queues and about 20 workers divided up between 3 "supervisors" -- these all "show" correctly on the Horizon dashboard.   When we look at our "log files" (inside storage/logs) we are seeing "data" from our jobs that are continually running/processed.

Challenge is without the UI we have no idea what is being processed and ensuring that things are "running" overall.  FYI, we also tried AWS Elasticache Redis and same problem there -- all the "UI Dashboard counts are 0".

Thoughts on how to fix this?

**Comment by mpatzner** [comment]
Are you using phpredis? I've got the same problem and when I switch to predis, everything is fine and I actually get proper numbers and entries in "Recent Jobs" in the Horizon dashboard.

**Comment by jab1000** [comment]
Hi Mpatzner, my challenge was in upgrading to 5.7 where the default environment variable name changed in config/queue.php -- I saw the change in "code comparison" and moved it over but when going over all the config files I didn't pay exact attention to it.  I made the change in the .env file from Beanstalkd to Redis and was thinking "all good".  Synch was the default then since "queue_connection" variable was not found in my .env file.

As for my overall debugging - I did download a Redis GUI app (Medis is Apple app store) and that helped me see.  I could see the "horizon settings" entries but no "jobs" -- yes, the all 0's was truly valid for my scenario.

**Comment by mpatzner** [comment]
Hi @jab1000, thanks for the reply and the tip with Medis, it is really useful indeed.
So the problem seems related to phpRedis (PECL version), because whenever I use it, the Dashboard's "Recent Jobs" just remains empty, even though the jobs have actually been processed successfully.

I've just switched back to "predis" and then these issues disappear.

**Comment by driesvints** [comment]
So if I read this correct you managed to solve your problem by using the new env variable? Let me know if you still are experiencing problems.
