### ISSUE TITLE
Empty Failed Job Details

### ISSUE THREAD

**Issue by jofomah** [laravel/horizon#397]
I have Laravel Horizon setup, but i noticed that some failed job does not contained details why they failed and have wrong `failed at` **70-01-01 00:59:59** date time, see attached screenshott
![screenshot 82](https://user-images.githubusercontent.com/5929681/46834925-ad434e00-cda4-11e8-9df0-cf8a83505db3.png)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a Horizon bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

At the very least we need much more info: code samples, settings, environment details, etc.
