### ISSUE TITLE
Nightmode

### ISSUE THREAD

**Issue by fridzema** [laravel/horizon#407]
Hello, 

Maybe it is a bit hard to implement at this moment, but i really like to see the same option as in laravel/telescope `Telescope::night()`

**Comment by browner12** [comment]
I would suggest waiting until Horizon gets off of the Bootstrap beta, since there are some breaking changes there.

**Comment by themsaid** [comment]
A frontend overhaul is planned, night mode in mind :)

**Comment by browner12** [comment]
Horizon is off the Bootstrap beta now.

https://github.com/laravel/horizon/pull/410

**Comment by themsaid** [comment]
Will be available in the upcoming release.
