### ISSUE TITLE
Dashboard Authorization with Gate

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/horizon#411]
It would be nice when Horizon can have simple authorization as [Laravel Telescope](https://github.com/laravel/telescope#dashboard-authorization)

```
/**
 * Register the Telescope gate.
 *
 * This gate determines who can access Telescope in non-local environments.
 *
 * @return void
 */
protected function gate()
{
    Gate::define('viewTelescope', function ($user) {
        return in_array($user->email, [
            'taylor@laravel.com',
        ]);
    });
}
```

**Comment by driesvints** [comment]
The difference with Telescope is that Telescope publishes a serviceprovider while Horizon does not.

**Comment by michaelnguyen547** [comment]
I understood. My ticket was asking to ad feature to Horizon so that its authorization clear and simple as Telescope
