### ISSUE TITLE
horizon:terminate fails with "Call to a member function all() on string"

### ISSUE THREAD

**Issue by etiennellipse** [laravel/horizon#429]
- Laravel 5.6.39
- Horizon 1.4.1
- PHP 7.2

When running `artisan horizon:terminate`, I get this:
![capture d ecran le 2018-10-31 a 10 02 40](https://user-images.githubusercontent.com/13202064/47793200-22df7180-dcf4-11e8-9da3-12f21809425f.png)

After some investigation, I found that a package I am using, [Hoa\Ruler](https://github.com/hoaproject/Ruler) is causing a conflict on the `resolve()` global function now used in Horizon 1.4.1 `TerminateCommand` at line 44.

The term `resolve` being rather common, and using global namespaces being what it is, are there no better way of resolving the dependency?

**Comment by mfn** [comment]
I believe it was broken recently with https://github.com/laravel/horizon/commit/2270812c2dcb1524ae4f39bfd488b3773e9f6613

Interestingly, this incompatibility can up in the past and there was a dedicated PR to fix it but the reason I guess was lost over time: https://github.com/laravel/horizon/pull/272

**Comment by driesvints** [comment]
I'm sending in a fix for this.

**Comment by driesvints** [comment]
https://github.com/laravel/horizon/pull/430
