### ISSUE TITLE
[Feature Request] Restart command while running horizon

### ISSUE THREAD

**Issue by wotta** [laravel/horizon#433]
The title explains quite a bit about the idea but I will explain in more detail.

Today a coworker and I were working on a project that heavily relies on jobs and events.
And came to the conclusion that restarting horizon after every code change is doable but takes you out of the workflow.

So we were thinking about a possible feature that would improve horizon and the workflow while testing and development.

The best possible workflow would be that horizon restart automatically every each code change that involves jobs, events or listeners.
Guess this is not completely doable since this would mean that horizon needs to check some files which could lead to performance issues.

What also an option be an option would be a restart function how nodemon it has.
When you changed a bit and know you want to test again you could go to the terminal and type `rs` and hit enter.
This would in turn restart the horizon process and grab the latest code changes.

Please let me know how you would feel with this functionality 🙂

**Comment by themsaid** [comment]
hmmm I guess I don't see the problem, we can't automatically detect a code change without having to watch all your files, and if you have to run a command in the terminal why not just restart horizon then?

**Comment by wotta** [comment]
Hello Mohammed,

Thanks for responding, the automatic restart function is a ideal situation which I know is almost not done.

And entering a two letter command doesn't break up the flow, at least for me that is.
I used nodemon a lot which helps when something crashes.

For me that doesn't break up the flow.
While the following example does.

For example i edit a listener and i directly want to test it.
Often i forget to restart now, but my experience from nodemon is that I am more triggered to type the rs command after I change a file before going back to test.

Hopefully I explained a bit better what I think would be a good small edition to the horizon command.

In the end for me personally the developer experience would go up and make me much more productive.

**Comment by themsaid** [comment]
On dev you may use `queue:listen` so you don't have to restart the worker to catch the new code.

**Comment by wotta** [comment]
I will take a look at it tonight and see if that would solve my problem 👌

**Comment by driesvints** [comment]
You could also simply alias the `rs` command to whatever horizon commands you need in order to restart the process. As Mohamed has explained you'd always *have* to run some command.

**Comment by jayenne** [comment]
I understand the argument for having a horizon:listen to save having to restart horizon each time we change a job's code ...like we have queue:listen and npm watch too. it's just simpler no?
