### ISSUE TITLE
unable to have php-posix in safe mode

### ISSUE THREAD

**Issue by eduarguz** [laravel/horizon#434]
Hi, is there a way to use Horizon without `php-posix`? I am not an expert in why or how could it be changed, I have used Horizon locally and in some projects and it works perfectly.

But this time, the production environment (centOs) does not have `php-posix` and according to http://php.net/manual/en/intro.posix.php the extension is not fully recommended in a "Secure" environment (which is very critical for this app).

Is there a way to make it work?, the devops area asked me to remove Horizon :/

**Comment by driesvints** [comment]
Unfortunately no. php-posix is a vital part of Horizon. There is a request to remove them [here](https://github.com/laravel/horizon/issues/170).
