### ISSUE TITLE
Horizon jobs being marked as paused despite having 10 processors ready to run

### ISSUE THREAD

**Issue by chrispage1** [laravel/horizon#435]
Hi,

I've had some customer complaints regarding not receiving emails. Having had a look on the system I've noticed that tasks are getting queued but seem to remain on pause and aren't getting executed. However some seem to run no problem - there is no real logic to it? I'm running Horizon with an external Redis server and 10 processes running.

Its worth noting that pretty much all of these tasks are quick and easy to run - I am struggling to see why they would be getting queued up?

![image](https://user-images.githubusercontent.com/2487374/47998158-388ad780-e0f6-11e8-9fd5-f13d79262ec6.png)

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
