### ISSUE TITLE
Allow default for config->horizon.environment

### ISSUE THREAD

**Issue by kohlerdominik** [laravel/horizon#438]
I think it would make sense to have possibility of making a "default"-config for the queue worker configuration.

It could be as easy as:

`src/Console/TimoutCommand.php:38`

from
```php
config('horizon.environments.'.$this->argument('environment'), [])
```

to
```php
config('horizon.environments.'.$this->argument('environment'),
    config('horizon.environments.default', []))
```

It would change from directly returning an empty array if the environment doesn't exist to first check if default exists, and then returning the empty array.

**Comment by driesvints** [comment]
I don't think this is necessary as Horizon at least needs an environment to run. How would an empty default help here?

**Comment by kohlerdominik** [comment]
Well i don't meant to discuss about empty default (which, just to say, is current implementation).

It's about possibility to create the "default" environment in the config file, working for example for production, stage and integration. I think, often these three environments would be exactly the same, so why do i need to copy/paste it 3 times instead of using the "default"-environment and only if local, its loading the local-configuration.

**Comment by driesvints** [comment]
Ah I see what you mean. Yeah, could be useful perhaps. Feel free to send in a PR to master.

**Comment by djtarazona** [comment]
@kohlerdominik I'm thinking of giving this a try:

```php
// in config/horizon.php

'environments' => [
    env('APP_ENV') => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'simple',
            'processes' => 10,
            'tries' => 1,
        ],
    ],
],
```

**Comment by hackel** [comment]
Another reason it would be very useful to be able to set environment defaults in the config is so we can set the default values once, and only customize what we need per environment.  All of my environments are identical aside from maxProcesses.

It would be very nice if I could quickly spin up a new testing environment without having to commit a temporary change to my config.

**Comment by driesvints** [comment]
I'm attempting a PR for this: https://github.com/laravel/horizon/pull/869

Feedback welcome on it.

**Comment by driesvints** [comment]
This got merged. Here's the new config:

```php
    /*
    |--------------------------------------------------------------------------
    | Queue Worker Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may define the queue worker settings used by your application
    | in all environments. These supervisors and settings handle all your
    | queued jobs and will be provisioned by Horizon during deployment.
    |
    */

    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'simple',
            'processes' => 1,
            'tries' => 1,
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-1' => [
                'processes' => 10,
            ],
        ],

        'local' => [
            'supervisor-1' => [
                'processes' => 3,
            ],
        ],
    ],
```

Will be in the next major release (no ETA).

**Comment by fgilio** [comment]
Very useful improvement

**Comment by mfn** [comment]
Game changer, thank you!

**Comment by hivokas** [comment]
Wow, that's cool. Just thought that it might be cool to have an ability to avoid specifying the config per environment, found this GitHub issue (which was created 2 years ago), and found out that @driesvints sent a PR just a few days ago.
