### ISSUE TITLE
Call to undefined function Laravel\Horizon\Console\pcntl_async_signals()

### ISSUE THREAD

**Issue by tankerkiller125** [laravel/horizon#44]
Brand new installation of Laravel 5.5 and horizon. Nothing else has been added to Laravel. For installation I ran:
```
composer create-project laravel/laravel laravel55 dev-develop

cd laravel55

composer install laravel/horizon

php artisan vendor:publish # (Selected option 0)

php artisan serv
```

and in another console I ran `php artisan horizon`

In case it helps I am running this on a Windows development machine if that might cause any issues.

**Comment by tankerkiller125** [comment]
It might help to note in the future that this will NOT work in windows because of its dependency on pcntl which is not windows compatible. Or even better add the extension to the composer list so composer informs users.

**Comment by themsaid** [comment]
It was added earlier yesterday https://github.com/laravel/horizon/blob/master/composer.json#L17
