### ISSUE TITLE
Job is marked with Pause-Symbol

### ISSUE THREAD

**Issue by daylaborers** [laravel/horizon#440]
Hi there,

i use horizon for email jobs. It works fine on my local homestead instance, but not on my stage system.

This is my horizon config:
`
'environments' => [
    'live' => [
        'supervisor-live' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'simple',
            'processes' => 10,
            'tries' => 3,
        ],
    ],
    'local' => [
        'supervisor-local' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'processes' => 3,
            'tries' => 3,
        ],
    ],
],
`

This is my Supervisor Configuration:
`[program:horizon]
process_name=%(program_name)s
command=php /var/www/gpapi/current/artisan horizon
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/gpapi/horizon.log`

In the Horizon Dashboard i see the status is active. But the Job is marked with an Pause-Symbol. When i insert on the server console php artisan horizon:work the Jobs are processed.

What is wrong here?

Cheers Ralf

**Comment by ludo237** [comment]
Some checks

- Check that one of your environments in `config/horizon`  matches the one in you `.env` file
- Every time you edit something need to restart your supervisor program, if you are under systemd try using that instead.

**Comment by ludo237** [comment]
I remember an issue saying that Horizon seems to recognize only "production" and "development" as environments, take this with a grain of salt I need to find the issue itself

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by ultrono** [comment]
In case anyone lands here from Google I just ran into this exact situation on my staging server. 

This is because the default config file (see [here](https://github.com/laravel/horizon/blob/3.0/config/horizon.php#L128-L147)) only includes the local and production environments. If you use anything other than local or production, you need to add a new key.

**Comment by Keftaa** [comment]
> Some checks
> 
> * Check that one of your environments in `config/horizon`  matches the one in you `.env` file
> * Every time you edit something need to restart your supervisor program, if you are under systemd try using that instead.

In case anyone lands here too, this one solved it for me!
I had in my .env file, APP_ENV=development and there were only 'production' and 'local' under 'envrionments' in config/horizon.php. I renamed 'local' to 'development' and everything worked after running `php artisan horizon`
