### ISSUE TITLE
rename failed job entry

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/horizon#441]
Horizon saves failed job as "horizon:job_id" (e.g. "horizon:44"). It would be nicer if it is saved as "horizon:failed_job:job_id" (e.g. "horizon:failed_job:44")

**Comment by michaelnguyen547** [comment]
mostly for GUI purposes. 

It is difficult to see what's going on in a redis database when I have a lot of failed jobs (100+). 

Please see the screencast (https://screencast.com/t/o41QgK54gO1u)

**Comment by driesvints** [comment]
I can't see the screencast because it requires flash.

Anyhow, the `JobRepository` class has a `failed` method which you may use to do whatever you like with the failed jobs.
