### ISSUE TITLE
Static resources URL is using an absolute root reference

### ISSUE THREAD

**Issue by n0099** [laravel/horizon#442]
#### How to reproduction:
When requesting `example.com/laravel/horizon` the page will be blank and css/js resources can't be loaded.

#### Possible cause:
https://github.com/laravel/horizon/blob/384c84512cdf929886343c2e498f8dc4180d8728/resources/views/app.blade.php#L6-L17
Here's using mix() to generate url for css/js, but without calling asset(mix()) to fix absolute path, these url will be like `example.com/vendor/horizon` (should be `example.com/laravel/vendor/horizon`) when laravel's url is using subfolder path like `example.com/laravel/horizon`.

**Comment by eduarguz** [comment]
Is it related to...
https://github.com/laravel/horizon/pull/355
https://github.com/laravel/horizon/pull/223
https://github.com/laravel/horizon/issues/245
https://github.com/laravel/horizon/pull/379
...I think there are more...

same thing happens with telescope & I probably with Nova. There are some alternatives in the linked issues but not a built in feature :(

**Comment by n0099** [comment]
> Is it related to...
> #355
> #223
> #245
> #379
> ...I think there are more...
> 
> same thing happens with telescope & probably with Nova. There are some alternatives in the linked issues but not a built in feature :(

laravel/telescope#414

**Comment by driesvints** [comment]
We could fix this. Feel free to send in a PR to the current release with the asset helper like on telescope.

**Comment by driesvints** [comment]
As for https://github.com/laravel/horizon/issues/245 we would consider resending https://github.com/laravel/horizon/pull/223 perhaps.

**Comment by n0099** [comment]
> We could fix this. Feel free to send in a PR to the current release with the asset helper like on telescope.

Telescope seems doesn't want to fix this laravel/telescope#281 and https://github.com/laravel/telescope/issues/414#issuecomment-440155289

**Comment by driesvints** [comment]
Heya, I'm sorry. Was a little confused there. Seems like this is indeed a no-go sorry.
