### ISSUE TITLE
Horizon inactive and still processing

### ISSUE THREAD

**Issue by JulianMar** [laravel/horizon#447]
I run my Application on Kubernetes.
I have one Service for requests and one service for the worker processes.
If I access the Horizon UI it often shows the Inactive Status, but there are still jobs being processed by the worker. I know this because the `JOBS PAST HOUR` are getting more.

If I scale up my worker service there will be constantly "failing" Jobs with this exception `Illuminate\Queue\MaxAttemptsExceededException`. 
If I connect directly to the pods and run `ps aux` I will see that there are horizon instances running.

If I connect to a pod on which the worker is running and execute the `horizon:list` command it tells me that one (or multiple) Masters are running.

How can I further debug this?

Laravel version: 5.7.15
Horizon version: 2.0.0
Redis version: 3.2.4

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
