### ISSUE TITLE
Horizon::auth does not work, and closure is not called

### ISSUE THREAD

**Issue by Alan796** [laravel/horizon#451]
I put Horizon::auth in boot() function of AuthServiceProvider, but the closure is not even called:
```
\Horizon::auth(function($request) {
    return dd('help');
});
```
my-site/horizon still show the horizon page, instead of _help_

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by Alan796** [comment]
> 
> 
> Hi there,
> 
> Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:
> 
>     * [Laracasts Forums](https://laracasts.com/discuss)
> 
>     * [Laravel.io Forums](https://laravel.io/forum)
> 
>     * [Discord](https://discordapp.com/invite/KxwQuKb)
> 
>     * [Larachat](https://larachat.co)
> 
>     * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
>     * [StackOverflow](https://stackoverflow.com)

OK. THX
