### ISSUE TITLE
Useless predis dependency ?

### ISSUE THREAD

**Issue by neoteknic** [laravel/horizon#456]
You should remove "predis/predis": "^1.1", in the dependency because it's useless with phpredis C extension.
Laravel don't add it by default but horizon add this useless dependency.
Better to detect if no redis extention install and suggest to install phpredis or predis if you can't install extension. phpredis have a lot better performance than predis so it should be the first choice.

Fix is to add this in your project's composer : 
`"replace": {
      "predis/predis": "*"
    },`

**Comment by driesvints** [comment]
Afaik it should work with predis? What's not working for you?

**Comment by neoteknic** [comment]
I don't want to add and use predis because it's useless, phpredis is better. It work perfectly with phpredis C extension.
It should be removed from dependencies.
predis is only needed if you can't install phpredis (shared hosting for example).
I have to add a replace in my composer to avoid downloading predis.

**Comment by driesvints** [comment]
Hmm, well I do see some hardcoded dependencies but I believe you can use it with phpredis for a large part already. I'll mark this as an enhancement so we can have a look at how we could proceed with this. I wouldn't remove the predis dependency just yet since there are some hardcoded dependencies there.

**Comment by driesvints** [comment]
Actually, I think the place where I'm pointing to is just a place where the comment might be wrong. Anyway, this needs some further looking at a later time. At the moment you could already just use the phpredis extension I believe.

https://github.com/laravel/horizon/blob/2.0/src/Repositories/RedisJobRepository.php#L366

**Comment by xiatian** [comment]
it can't work with phpredis.

php artisan horizon

Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Illuminate\Support\Facades\Redis::connect()

  at /vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:109
    105|         if (version_compare(phpversion('redis'), '3.1.3', '>=')) {
    106|             $parameters[] = Arr::get($config, 'read_timeout', 0.0);
    107|         }
    108|
  > 109|         $client->{($persistent ? 'pconnect' : 'connect')}(...$parameters);
    110|     }
    111|
    112|     /**
    113|      * Create a new redis cluster instance.

**Comment by driesvints** [comment]
Will be fixed in the next major release.

**Comment by mfn** [comment]
The `require` dependency was removed in `master` branch ("next major release"); it's only in `required-dev` there.
