### ISSUE TITLE
Failed jobs not showing

### ISSUE THREAD

**Issue by shawnhind** [laravel/horizon#458]
Recently on one of our environments the failed jobs page has stopped listing failed jobs.  The jobs are still being put into the failed jobs table in the database but when I go to the failed jobs page on Horizon it just says there aren't any failed jobs.

Recent and monitored tags still show up but failed jobs do not.

I've tested this by triggering a failed job and then checking to see it in the failed jobs table in the database and then loading the horizon page to see if it's there.

I've tried republishing the assets, restarting horizon on all 3 servers that it's running on and still haven't been able to get them to display.  Nothing in our configuration has changed recently and the failed jobs used to display on that page.  

Laravel version is 5.6
PHP version 7.2

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
