### ISSUE TITLE
Large XHR request for polling

### ISSUE THREAD

**Issue by Donny5300** [laravel/horizon#464]
Hi,

Making a request to get failed or recent jobs can be huge. I did some monitoring and sometimes a request can get up 10mb (what I had so far). Using a slow internet connection with 20mbps will make the internet line get stuck because of the requests per second or two. Is there some way to shrink those requests?

**Comment by driesvints** [comment]
The solution would be https://github.com/laravel/horizon/issues/327 so closing this in favor of that. Feel free to send in a PR if you want to see this added.
