### ISSUE TITLE
Failed Jobs Getting Marked as Complete

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#465]
I am using Laravel 5.7 with php 7.3, Apache2, Redis for Laravel Horizon. 

I am getting an issue, the jobs never get fail if there is any error. Ex. 
If I forget to add the use App\Order; then ideally this shall be marked as Failed but currently it does now which creates a lot of confusion that the jobs are getting executed. I am getting this issue since the very beginning. 

In addition to this, the job is not marked as complete even if there is any other error like calculation error (divide by 0) and missing key for array etc.

**Comment by mfn** [comment]
> with php 7.3

Did it work with your previous version? Is this a new problem?

**Comment by xyrintech** [comment]
I think yes, php 7.2 was working. 
I am not sure whether a new problem or not?
I use Bugsnag, I am getting an error for the failed job on Bugsnag but Jobs are marking as complete.

**Comment by mfn** [comment]
> I use Bugsnag

I've no idea about Bugsnag. Any error? Stacktrace?

**Comment by tomswinkels** [comment]
I running also PHP 7.3 on NGINX + Apache2 Hybrid and i have no problems.

**Comment by driesvints** [comment]
Can you provide the stacktrace from bugsnag and any other info from it? The code from the part where it fails?

**Comment by xyrintech** [comment]
Sure, I will a copy of that. 
I can share more details here as well. 

Lets say you have a model Order.php and we call a static function in this model inside the handle method for job. 
Ex. Order::getOrders() then if any errors inside the getOrders then the job do not marked as fail

**Comment by driesvints** [comment]
@xyrintech did you run `php artisan horizon:terminate`? You can read more about deploying Horizon here: https://laravel.com/docs/5.7/horizon#deploying-horizon

You don't need to run `php artisan queue:restart`. Do you also restart php-fpm so your changes are picked up?

**Comment by xyrintech** [comment]
Yes, I did.
I have tried everything. 

Still issue is there. 
Lemme give you one more way to replicate - I tried inserting the record with unique validation error (knowingly did to test) and as expected I got unique constraint error by database server but Jobs successfully marks as complete.

**Comment by driesvints** [comment]
@xyrintech are you still experiencing this problem?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by JHIH-LEI** [comment]
same issue. my job failed because I access not exist instance property. But horizon mark as completed instead of failed even my laravel.log show there was an error in job.

my php version is 7.2
