### ISSUE TITLE
Feature: Run some queues only on one server

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#470]
Hi,

We have multiple servers and the most queues we wan't to run between all the servers but there are queues that we want only run on one server. If that server are down than the queue must to the other server. But not load-balance between the servers.

<img width="959" alt="screen shot 2019-01-16 at 4 07 58 pm" src="https://user-images.githubusercontent.com/9036151/51258023-3de38880-19a9-11e9-950e-d60f1cc13f07.png">

Maybe this is a good idea.

**Comment by driesvints** [comment]
I'm wondering if this is already possible with some combination of ENV vars which you may replace the horizon supervisor settings with. Although I'm not sure about the auto switch for downtime. I think that would be very hard to do as the other Horizon servers would need to be in touch with each other to know about their downtime.

**Comment by tomswinkels** [comment]
The issue what we have is that we have jobs with sorting. 

First job1, if that job is ready? Than the next job (job2).

Problem now is that job1 is running on server one and job2 on server two. (at the same time)

**Comment by driesvints** [comment]
@tomswinkels sounds more like an architectural problem than a problem with Horizon? Can't you implement some sort of way of knowing that job 1 ran?

**Comment by tomswinkels** [comment]
Yeah, but i think than it is to slow.

Example; we have webhooks like 'created' and 'changed' first we want send the created but sometimes is changed faster and was send before created.

Maybe a balance option for horizon?

**Comment by tomswinkels** [comment]
What i mean is an job that send webhook to external urls.

**Comment by driesvints** [comment]
You do know that you can specify the queue connection and queue on a job? https://laravel.com/docs/master/queues#customizing-the-queue-and-connection

**Comment by ibrunotome** [comment]
@driesvints I have a similar situation: Horizon settings with 60 processes, that means that I have 60 opened database connections. If the load balance put another instance up, that will turn into 120 opened database connections... 3 instances means 180... etc. All they for horizon. So if I could set "the maximum number of horizon instances is 2" or something like that, it will prevent problems of "too many connections to database" and whatever other instances will be used only to serve the http requests.

**Comment by ryantbrown** [comment]
@driesvints we are running into the same (or similar) issue when trying to scale horizon by running specific queues on specific servers. We use Envoyer for deployment so the `.env` is the same for all servers, as it should be (hacking the environment is not a good solution).

It seems to me that there is a simple fix, allowing the `horizon` command to accept an optional configuration. On line 49 of `Laravel\Horizon\Console\HorizonCommand` the environment is passed in, which deploys the configuration.

```php
ProvisioningPlan::get(MasterSupervisor::name())->deploy(
    config('horizon.env') ?? config('app.env')
);
```
The new signature would look something like this:
`protected $signature = 'horizon {--env= : The environment to deploy}';`

And the `handle()` method changes:

```php
ProvisioningPlan::get(MasterSupervisor::name())->deploy(
    $this->option('env') ?? config('horizon.env') ?? config('app.env')
);
```

Currently we are overriding the `horizon` command to make these changes internally, would be happy to submit a PR if this would be considered.

**Comment by driesvints** [comment]
@tomswinkels @ibrunotome would the solution from @ryantbrown also work for you?

**Comment by tomswinkels** [comment]
Yeah, i think it is a good solution.

**Comment by ryantbrown** [comment]
@tomswinkels This issue is for running specific queues on specific servers, failover is a separate issue that should be handled at the infrastructure level.

**Comment by Muffinman** [comment]
@tomswinkels  Would [job chaining](https://laravel.com/docs/5.8/queues#job-chaining) be a good solution for your issue in this case?

It seems like it was designed to solve the issue of making sure jobs are processed in the correct order. But I guess if they are sent to the queue via two different actions this may not be viable.

This is actually very similar to a requirement we have, where we're receiving some zip files from a legacy desktop app, and each zip file assumes the one previously has already been processed. This creates a situation where a 'small' update file can easily be picked up and processed before a previous 'large'  one has finished.

We're currently getting around this by implementing our own locks at the database level and deferring jobs until the last one has finished processing and released the lock.

I was thinking about job chaining, and whether it's possible to extend that in a way where new jobs can be injected/appended at any point in time (until the chain is empty/complete, at which point a new chain would be started). It sounds complicated, and even if a PR could be created to add such a feature I don't think it would get accepted.

**Comment by driesvints** [comment]
I'm going to close this as this is a bit outside the scope for Horizon. You can configure specific queues for specific servers by making use of env variables and different APP_ENV's if you like. And the problem with the order of jobs you can solve by implementing that inside the jobs itself.
