### ISSUE TITLE
BUG: Not all switch when change the HORIZON_PREFIX

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#472]
When we change the Horizon prefix, recent jobs give us all jobs.

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
