### ISSUE TITLE
Run time incorrect

### ISSUE THREAD

**Issue by CraigHarley** [laravel/horizon#474]
Not sure how you can reproduce this because I'm not 100% sure what's causing it, and I can't really post a code sample publicly.

But something is definitely broken here:
![image](https://user-images.githubusercontent.com/8432365/51596745-94911b00-1ef1-11e9-81ca-04b6d4f74970.png)

Horizon reckons one job has been running for 49 years 👴. 
And the other looks like it's overflowed into the negatives.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
