### ISSUE TITLE
This is by design. When a job has failed and is retried it's considered to be a new job.

### ISSUE THREAD

**Issue by setkyar** [laravel/horizon#479]
This is by design. When a job has failed and is retried it's considered to be a new job.

_Originally posted by @driesvints in https://github.com/laravel/horizon/issues/310#issuecomment-433106716_

What to do other failed jobs after one successful retry? 

Let's say I have one queue Job. Which retry 3 times and failed. So, there will be total 4 failed jobs which do the same thing. I retried one job and it was success. What to do with my other 3 failed jobs?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
