### ISSUE TITLE
Using custom env instead of APP_ENV

### ISSUE THREAD

**Issue by setkyar** [laravel/horizon#482]
I have 2 Horizon servers which handle different `supervisor`. For example, currently I have to use like the following and I need to update my `.env` file `environment` as `workerOne` and `workerTwo` separately. 

```php
'workerOne' => [
    'supervisor-2' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 10,
        'tries' => 3,
    ],
]
'workerTwo' => [
    'supervisor-2' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 10,
        'tries' => 3,
    ],
]
```

What happened was some worker check `.env` environment as well. So, I got environment sharing problems. Can we use separately? If that's open for PR. I would submit.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by setkyar** [comment]
@driesvints No, I am not asking problem question here. I am asking, does horizon plan to add custom env instead of `APP_ENV` for Horizon? If so, I would PR.

**Comment by driesvints** [comment]
Ah I see. I think you're looking for: https://github.com/laravel/horizon/issues/438

**Comment by setkyar** [comment]
#438 is only for Timeout. Mine is for `php artisan horizon` command which currently check by using `.env` environment instead I want let user choose. They still can continue using `.env` enviornment and also giving a way to add custom.
