### ISSUE TITLE
PHP PCNTL not enabled by default

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/horizon#5]
Should note on README.md that most or all PHP versions do not enable PCNTL by default. The php versions should be compiled with --enable-pcntl

https://gist.github.com/jbanety/35d01689608ad89777d349f65c7b39c9

Added a repository with the PHP extensions compiled to version:
https://github.com/johnpaulmedina/php7-pcntl-extensions

**Comment by tillkruss** [comment]
`ext-pcntl` should also be added to `composer.json`.

**Comment by themsaid** [comment]
https://github.com/laravel/horizon/pull/9
