### ISSUE TITLE
Wrong ratio of jobs per minute over recent jobs

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#501]
I have the following `horizon.trim` config:
```
    'trim' => [
        'recent' => 5,
        'failed' => 1000,
    ],
```

So the number of recent jobs should be around 5 times the number of jobs in the last minute, but it is not, the ratio is closer to 1 to 3 and always less than 1 to 4:

![screenshot from 2019-02-04 13-06-53](https://user-images.githubusercontent.com/7089140/52200346-cb661a00-287d-11e9-8e23-3f4bbfeec4d2.png)
![screenshot from 2019-02-04 13-03-36](https://user-images.githubusercontent.com/7089140/52200357-cef9a100-287d-11e9-9c97-c03766b1aad5.png)

**Comment by driesvints** [comment]
Heya, thanks for reporting. This isn't how it's calculated though. It's the amount of throughput since the last snapshot / the amount of minutes since the last snapshot: https://github.com/laravel/horizon/blob/ea877727927326e60e1a01c82ed523b4eab98bad/src/Repositories/RedisMetricsRepository.php#L67

**Comment by halaei** [comment]
@driesvints I think the bug is in `minutesSinceLastSnapshot()`. I am trying a PR. Maybe this shouldn't be closed.

**Comment by driesvints** [comment]
@halaei I thought the number could differ from the jobs per 5 minutes since the last snapshot period isn't the same as that and thus your total of jobs per minute isn't either.

**Comment by halaei** [comment]
@driesvints From what I see, the computations are wrong because of using round() funcion. I think the correction can be changing
```php
    protected function minutesSinceLastSnapshot()
    {
        $lastSnapshotAt = $this->connection()->get('last_snapshot_at')
                    ?: $this->storeSnapshotTimestamp();

        return round(max(
            (Chronos::now()->getTimestamp() - $lastSnapshotAt) / 60, 1
        ));
    }
```
to
```php
    protected function minutesSinceLastSnapshot()
    {
        $lastSnapshotAt = $this->connection()->get('last_snapshot_at')
                    ?: $this->storeSnapshotTimestamp();

        return max(
            (Chronos::now()->getTimestamp() - $lastSnapshotAt), 1
        ) / 60;
    }

```
But I assume in the first minute after every snapshot, numbers are more inaccurate.

**Comment by driesvints** [comment]
Wouldn't that return a float instead of an integer?

**Comment by halaei** [comment]
Also why not just show (Jobs Past 5 Minutes) / 5? If the number is intended to mean something else, then shouldn't it be reflected in the title, e.g. **processed** jobs in the last minute?

**Comment by halaei** [comment]
It is a float, but the formula uses the return value needs a float?

**Comment by halaei** [comment]
To make my issue clearer, you may see that immediately after every snapshot, `Jobs Per Minute` is reset to zero.

**Comment by driesvints** [comment]
> Also why not just show (Jobs Past 5 Minutes) / 5? If the number is intended to mean something else, then shouldn't it be reflected in the title, e.g. processed jobs in the last minute?

Because it's not based on the last 5 minutes but on the last snapshot. 

> It is a float, but the formula uses the return value needs a float?

Hmm, was confused because the method name said "minutes" and I didn't understand why it could be a float. Not sure why it's like that.

> To make my issue clearer, you may see that immediately after every snapshot, Jobs Per Minute is reset to zero.

Where is this done?

**Comment by driesvints** [comment]
@halaei I see. Thanks for explaining. Would you believe a default value of 1 would work? Can you test with that change?

**Comment by halaei** [comment]
@driesvints Also I noted that the number of recent jobs is also incorrect, because the jobs saved before config('horizon.trim.recent') minutes ago might not get immediately trimmed.

**Comment by halaei** [comment]
I tested my 2 PRs together. Now metrics are more smooth, they don't fluctuate that much. This shows improvement. However, the ratio is now 2 to 5 (instead of 1 to 5). That is because every job is computed 2ice in throughput metric, which is to me a more serious bug. I can confirm that Events\JobDeleted is fired 2 times per job. Metrics aside, you may regard it as a terrible performance bug.

**Comment by halaei** [comment]
![screenshot from 2019-02-06 12-37-53](https://user-images.githubusercontent.com/7089140/52331310-1498a400-2a0d-11e9-9a86-221f2767067f.png)

**Comment by halaei** [comment]
Firing events twice was due to some third party package. That aside, still my PRs are good to be merged.
![screenshot from 2019-02-06 16-11-11](https://user-images.githubusercontent.com/7089140/52342302-4b30e780-2a2a-11e9-9b1b-1659259e88e0.png)
