### ISSUE TITLE
Supervisors not restarting after deploy (forge daemon)

### ISSUE THREAD

**Issue by booni3** [laravel/horizon#504]
Horizon runs fine but only recently, after a deploy, supervisor and queue workers do not start back up again with Horizon GUI showing "Inactive"

To get them running again I can:
- restart the daemon worker from within forge
- restart the supervisor `/etc/init.d/supervisor restart`

My deploy script has `php artisan horizon:terminate` within it. I have also tried reset/purge and a combination thereof.

When I run terminate in the command with an inactive horizon, it seems to do nothing. When I run the same command with horizon active, it shuts it down but the daemon does not reboot supervisor.

The daemon runs without any errors throughout all of this.

Should terminate take down and bring up the service or is it the daemon itself?

**Comment by mfn** [comment]
> When I run terminate in the command with an inactive horizon, it seems to do nothing.

This is expected. Can't terminate or expect action from something which isn't running.

> it shuts it down but the daemon does not reboot supervisor.

It's the other way around: supervisor (and that is its sole purpose) always runs and watches the configured processes and starts them if they exit.

> Should terminate take down and bring up the service or is it the daemon itself?

The artisan instructs horizon to terminate and supervisor will bring it back up again. Since "daemon" would refer to anything running (horizon, supervisor; it gets confusing 😜) we should stick to their names (horizon, supervisor).

Which version of horizon?

What does the supervisor log say?

From here it reads like a supervisor issue.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by barryvdh** [comment]
@booni3 did you solve this? I've had a few (rare) occasions  of this as well, but not sure how to reproduce.

**Comment by booni3** [comment]
@barryvdh - I am afraid not entirely. I believe that it may be something to do with a large number of jobs sitting in within the redis memory of some sorts. And actually in my case I believe that horizon would have started again but I was just being impatient. I have since just left it and have found it always to restart again eventually, even though it may take an hour or more.

I noticed that even when horizon said it was not running, checking my logs in papertrail showed that jobs were in fact running. This generally only happens when horizon was shut down with a large number of pending jobs. So my guess is that it is actually completing some/all of these jobs (maybe just those already committed to the redis memory) before horizon is showing as running again.

All that said, if it it not restarting immediately and you need it too, restarting the daemon (in my case within forge) does get new jobs processing through again within 30 seconds or so.

**Comment by barryvdh** [comment]
Yeah restarting is not the issue (I killed it manually and Supervistor restarted), but it's a bit dangerous when they stall without noticing. In my case it was just 1 queue that was stopped, the others continued.

**Comment by nickpoulos** [comment]
Also experiencing this after Forge deploys sometimes. Horizon shows as Active/running, but no supervisor listed as running underneath.  In order to correct, I have to ssh in to prod, horizon:terminate, and usually that will bring things back in order.  A little strange bc I have very basic queues setup: one local server, one prod server, for one site with just the one queue (default).

**Comment by spooksie** [comment]
I have the exact same issue, I had to resolve this by scheduling an hourly command to ensure Horizon stays alive. 

With Daemons, are they automatically executed after you push on Envoyer?

**Comment by jonathan-bird** [comment]
Had this randomly today and horizon:terminate didn't make the jobs start running, but reloading the supervisor job kicked off my outstanding jobs. It had been running without issue for 6+ months.

Very strange. Thinking of just having a CRON that restarts supervisor every week just to ensure everything works as expected

**Comment by wesleylether** [comment]
Hi All, I have fixed this issue with a little linux knowledge :)

First learn where the supervisorctl command runs from with `which supervisorctl`
In my server it gives `/usr/bin/supervisorctl`

Login to your forge server and become root user with `sudo -i`

then type `visudo`

And past this line on the end of your file (your supervisorctl full path ofcourse):
```
forge   ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl
```

With this, you give your forge user the rights to sudo a supervisor command without to have to type the sudo password!

So now in your deployment script you can add the following:

```
sudo /usr/bin/supervisorctl restart
```
or
```
sudo /usr/bin/supervisorctl restart <name>
```
