### ISSUE TITLE
maxAttemptsExceededException failed job loop

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/horizon#509]
Horizon v2.0.3

Horizon, for whatever reason, keep spawning new job for MaxAttemptsExceededException failed job.

This is the screenshots:

![screen shot 2019-02-08 at 4 51 42 pm](https://user-images.githubusercontent.com/436950/52512413-dee8ec00-2bc1-11e9-823f-d0bc7e2e6252.png)

![screen shot 2019-02-08 at 4 52 18 pm](https://user-images.githubusercontent.com/436950/52512421-ea3c1780-2bc1-11e9-8eda-1235b112b5eb.png)

Even after I terminated Horizon, new job keep showing of the same MaxAttemptsExceededException.

The Recent Jobs panel is empty

![screen shot 2019-02-08 at 4 53 24 pm](https://user-images.githubusercontent.com/436950/52512454-16579880-2bc2-11e9-939a-395ae5d5c0e8.png)

And the Failed Jobs page does not list all new failed jobs as showed above

![screen shot 2019-02-08 at 4 53 49 pm](https://user-images.githubusercontent.com/436950/52512475-2c655900-2bc2-11e9-8cfb-e569606cf775.png)

**Comment by driesvints** [comment]
Have you read https://github.com/laravel/horizon/issues/128 ? Which OS are you on? Which Laravel version? Can you provide a basic app which recreates this problem?

**Comment by michaelnguyen547** [comment]
I fixed the issue by going to Failed job and click Retry. Horizon stopped creating more jobs after that.
