### ISSUE TITLE
Dashboard losing data on refresh

### ISSUE THREAD

**Issue by danielfaulknor** [laravel/horizon#510]
When I load up Horizon for the first time, I see the full dashboard. Overview, Current Workload, List of Supervisors. This is with all queues empty.

If I add some jobs, and then refresh the page, Current Workload goes away, and on 1/2 refreshes, the Overview is all zeros and even the polling doesn't fill it in.

Is it intended for Current Workload not to load when there are jobs in the queue? I'm guessing not.

Laravel 5.7 on PHP7.2 running in the "local" environment with separate web, queue, redis and database VMs.

I can see the AJAX requests and they appear to have the correct data.

Empty queues:
```[{"name":"bulk-email","length":0,"wait":0,"processes":1},{"name":"default","length":0,"wait":0,"processes":1},{"name":"high","length":0,"wait":0,"processes":1},{"name":"low","length":0,"wait":0,"processes":1},{"name":"medium","length":0,"wait":0,"processes":1}]```

Medium queue processing:
```[{"name":"bulk-email","length":0,"wait":0,"processes":1},{"name":"default","length":0,"wait":0,"processes":1},{"name":"high","length":0,"wait":0,"processes":1},{"name":"low","length":0,"wait":0,"processes":1},{"name":"medium","length":809,"wait":7,"processes":1}]```

With the queue processing, Current Workload stays at 0 jobs, and then vanishes on manual page refresh.

There are no JavaScript errors in the browser console.

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by danielfaulknor** [comment]
@driesvints can you please explain how this is a support question and not a bug? It would help me in getting the support. It definitely feels like a bug. It's unexpected behaviour and does not seem to be intended (not mentioned in docs)

I've asked on Discord, Larachat and the Laracasts forums and got no responses.

**Comment by driesvints** [comment]
Heya. So what I suspect that's happening is that your current workload is empty because at that time there isn't anything on your queue. Your job is either still being pushed or already been taken care of. Please note that "current workload" only displays jobs which are waiting to be processed.

**Comment by danielfaulknor** [comment]
Hello. Thanks for the response!
The current workload card goes away completely when there are jobs. It's there when there are none.
This is what it looks like with no jobs - https://imgur.com/NEikrJ1
Then as soon as I submit jobs - https://imgur.com/jwAd0vF
I can see from the logs and also the JSON response from the AJAX queries that there are many hundreds of jobs in the queues.

Also with manual page refreshes, it goes from https://imgur.com/X4qCZEK to https://imgur.com/gBOpAoB at random

**Comment by driesvints** [comment]
Can you link to the Laracasts forum post?

**Comment by danielfaulknor** [comment]
https://laracasts.com/discuss/channels/laravel/horizon-dashboard-issue-with-current-workload

**Comment by hylke94** [comment]
Can this issue be opened again? I have the same in our app. We run import jobs from an old MongoDB to our new MySQL. 

Most of the time it shows only this:
![image](https://user-images.githubusercontent.com/1220076/69440691-94e48780-0d49-11ea-9b6f-0880d4f3148d.png)

There is a whole import queue with up to one million jobs sometimes. But even if there is as many as lets say 10 jobs, the queue does not come back in the dashboard..
![image](https://user-images.githubusercontent.com/1220076/69440981-16d4b080-0d4a-11ea-8ee3-1c8dd00da2b2.png)

Can someone please look at this issue?

**Comment by danielfaulknor** [comment]
@driesvints 3 of us reporting this issue now (please see the Laracasts forum for the 3rd)

**Comment by driesvints** [comment]
@danielfaulknor did you republish the assets? Are you at the latest horizon/laravel version?

**Comment by hylke94** [comment]
> @danielfaulknor did you republish the assets? Are you at the latest horizon/laravel version?

I work on latest versions of all packages. Product is still in development. And didn't publish the Horizon assets..

**Comment by rocramer** [comment]
You did and you should republish them after each upgrade: https://laravel.com/docs/6.x/horizon#upgrading

**Comment by hylke94** [comment]
I didn't publish them at all. So vendor versions are used.. ;)

**Comment by driesvints** [comment]
@hylke94 the publishing of the assets is a step in the install guide: https://laravel.com/docs/6.x/horizon#installation

**Comment by hylke94** [comment]
Hmm, good point. It of course needs the css and js in the public folder.. 
I run the asset command tomorrow first thing (and check the diffs ;p). Need to wait for our next import/export. But will be looking for any weird issues ;). 

Maybe it can be added as command in the composer json install/update commands section? It is only one command for both functions, but easily forgotten to run ;).

**Comment by driesvints** [comment]
There's an issue about that here: https://github.com/laravel/horizon/issues/554

**Comment by talovicnedim** [comment]
I get something similar but still, I'm not able to replicate it. Note that:

1. I use Docker

2. Every Docker container has the same `HORIZON_PREFIX` and `REDIS_PREFIX`

3. Queues are processing correctly.

The problem I experience is I can't see queues listed in the **Current Workload**. It happens after a while. If I restart a container then everything will be good for some time.

If I scroll down a bit, I can see this:

<img width="982" alt="Screenshot 2020-12-25 at 19 18 36" src="https://user-images.githubusercontent.com/4561819/103140641-5c03a880-46e9-11eb-9018-3a93910a98f5.png">

However, when I push it into the queue I can't see it, but it will be listed in the Completed Jobs section. Processing definitely works.

Also, `php artisan horizon:status` says that Horizon is running.

<img width="405" alt="Screenshot 2020-12-25 at 19 44 47" src="https://user-images.githubusercontent.com/4561819/103140662-ad139c80-46e9-11eb-8c9b-94385eb5c617.png">

But, `artisan horizon:supervisors` won't show anything.

Do you think it might be a bug or something related to me? @driesvints 

p.s. In my `docker-compse.yml` I have:

`entrypoint: php /var/www/html/artisan horizon`.

p.p.s. I use Swarm for orchestration.

**Comment by sthales** [comment]
> artisan horizon:supervisors

I do have the same issue. Did you managed to fix it?

**Comment by deepesharora** [comment]
@danielfaulknor did you ever find a solution to your problem? i'm seeing the exat same issues as you all...

**Comment by danielfaulknor** [comment]
@deepesharora Nope!

**Comment by vladamir** [comment]
Check config `horizon.php`, your environment should be in environments array.

**Comment by deepesharora** [comment]
Thank you. It was a configuration issue on my end   
  

  

  
  

  

  

  
  

  

  

  

  

  
---
  

  
NOTICE - CONFIDENTIAL INFORMATION   
  
The information in this communication is privileged and strictly confidential. It is intended solely for the use of the individual or entity named above. If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, any dissemination, distribution, copying or other use of the information contained in this communication is strictly prohibited. If you have received this communication in error, please first notify the sender immediately and then delete this communication from all data storage devices and destroy all hard copies.
  

          
  
  
>
