### ISSUE TITLE
Feature: Add version number

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#512]
Maybe its a good idea to add the version number in the copyright line of Horizon. So that i can see with version of Horizon is running.

**Comment by driesvints** [comment]
It would require us to update the version with every release which will lead to confusion if we forget to do it. You can know which version you're running by looking at your `composer.lock` file.

**Comment by JayBizzle** [comment]
You could automatically get the installed version number something like this...then you'd never forget 😄 

```php
$installedVersion = collect(json_decode(file_get_contents('../vendor/composer/installed.json')))->where('name', 'laravel/horizon')->first()->version;
```
