### ISSUE TITLE
Failed Jobs not reporting accurately

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/horizon#517]
Failed jobs not showing reason for error. I am also seeing that on the failed jobs list page they show the correct time however when I open the failed jobs the time and date is completely inaccurate and the error is empty.

<img width="993" alt="screen shot 2019-02-22 at 3 31 26 pm" src="https://user-images.githubusercontent.com/1139439/53269746-aebc4580-36b7-11e9-89b4-a58b1f0d5de4.png">
<img width="973" alt="screen shot 2019-02-22 at 3 37 45 pm" src="https://user-images.githubusercontent.com/1139439/53269794-d3b0b880-36b7-11e9-8017-5af56a03340d.png">

**Comment by johnpaulmedina** [comment]
That was on the recent job view (not specifically on failed jobs view)

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
