### ISSUE TITLE
Click to copy tooltip

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/horizon#520]
If your tag ID is longer than x chars Horizon will shorten and add eclipses to the end of the text. The tooltip will show the correct value, maybe a click to copy full value to clipboard is useful.

**Comment by driesvints** [comment]
Can you show some screenshots of the current behavior and how it goes wrong?

**Comment by themsaid** [comment]
@johnpaulmedina working on a frontend overhaul, however I don't see this coming soon.
