### ISSUE TITLE
Unable to locate Mix file: /app.css. 

### ISSUE THREAD

**Issue by tshafer** [laravel/horizon#525]
Upgraded to 3.0

Ran php artisan horizon:install

Unable to locate Mix file: /app.css. (View: /vendor/laravel/horizon/resources/views/layout.blade.php)

**Comment by themsaid** [comment]
Make sure you re-publish the assets:

```
php artisan vendor:publish --tag=horizon-assets --force
```

**Comment by tshafer** [comment]
Oops, thanks!

**Comment by king724** [comment]
I wonder if it would be appropriate for an "Upgrade Guide" to be added to the docs for each of the officially supported modules?

**Comment by MannikJ** [comment]
Finally found this one to solve the exact same problem after upgrading horizon. I already started copying the assets to public directory myself via laravel mix.
Shouldn't `php artisan horizon:install` already ensure all assets are in the right places? At the very least there should be a note in the docs that you might need to force publish the assets when upgrading.

**Comment by driesvints** [comment]
@MannikJ technically it should be possible to run the command with a post-composer hook. I'll create an issue for it and try to pick it up if I find time.
