### ISSUE TITLE
Failed Jobs date format can be ambiguous 

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/horizon#526]
The column that shows the date for failed jobs (and also some other locations in the app) is sometimes ambiguous.

For example, lets assume it's January 2020. You have an app that doesn't get many failed jobs. But when you look at the table in mid January look you see this:

![image](https://user-images.githubusercontent.com/2513663/53510662-71402980-3ab6-11e9-9168-7148f6d75e92.png)

On first glance it's hard to know if this job failed on 19th Jan 2020 or 20th Jan 2019.

Having a 2 digit number for the year is not enough IMO.

I see this this format is forced in the following method:

https://github.com/laravel/horizon/blob/11acb6eafee4a0ea3bea87c6277f4342ebd2e1e3/resources/js/base.js#L86-L88

Would a PR be accepted to change this to `YYYY` instead?

Thanks.

**Comment by travisaustin** [comment]
If you submit a PR, would you add a config option that supports editing the default format, instead of hard-coding a format? This would allow a user to define a relative format, or add a day of the week, etc.

**Comment by driesvints** [comment]
Feel free to send in a PR.

**Comment by driesvints** [comment]
I feel like a user defined format would be a little overkill in terms of customization. Let's just keep it at making it the full year now.

**Comment by jonnywilliamson** [comment]
Thanks! This was done before I got back from my trip. Much appreciated.
