### ISSUE TITLE
Failed job not showing

### ISSUE THREAD

**Issue by shadoWalker89** [laravel/horizon#530]
Hi,

So i have a failed job that is not showing on the horizon failed jobs tab. But it is showing in the dashboard

![image](https://user-images.githubusercontent.com/1449151/53565414-b79a9480-3b59-11e9-8e77-fe54944f84db.png)

But the list of failed jobs is empty

![image](https://user-images.githubusercontent.com/1449151/53567289-0696f880-3b5f-11e9-8fee-d05c9c20a096.png)

Even though the ajax request shows the total as 1 but the jobs array is empty

![image](https://user-images.githubusercontent.com/1449151/53565448-d4cf6300-3b59-11e9-8df2-e752664d3d91.png)

And this is also a screenshot of the database

![image](https://user-images.githubusercontent.com/1449151/53565470-e44eac00-3b59-11e9-9baa-c6a128df9cac.png)

If i go to the recent jobs tab i see the failed job

![image](https://user-images.githubusercontent.com/1449151/53567118-8a9cb080-3b5e-11e9-899d-b46755c3d655.png)

And when i click on it it opens the failed job details page at this uri ".../failed/11"

![image](https://user-images.githubusercontent.com/1449151/53567240-e6673980-3b5e-11e9-9036-8b8481ecea81.png)

I'm using

php 7.2.15
laravel 5.7.28
horizon 3.0.0

**Comment by driesvints** [comment]
Hmm. I've been looking into this but can't seem to reproduce it. Can you perhaps post some code and/or set up a test app?

**Comment by shadoWalker89** [comment]
I'm not doing anything fancy.

Just using the ShouldQueue interface on a mail class.

The error that you are seeing is caused by me making a syntax error in the email markdown file to test the failed jobs tab.

I'm not familiar with horizon code, and this is my first time using horizon but i suspect that this has something to do with redis and this is why.

The redis command being executed to get the failed jobs is `zrange failed_jobs 1 50`
The redis command being executed to get the failed jobs count is `zcount failed_jobs -inf -1550754504`

In my redis-cli if i do ` zrangebyscore horizon:failed_jobs 1 50` i get `(empty list or set)`
If i do ` zrangebyscore horizon:failed_jobs -inf 50` i get `(empty list or set)` i get 
```
1) "11"
```

I think the problem is when trying to get the failed jobs but with `1` instead of `-info`

If you follow this call 
https://github.com/laravel/horizon/blob/c32b172586d4693df235d7e8855c811ca208e5a9/src/Http/Controllers/FailedJobsController.php#L49
down to 
https://github.com/laravel/horizon/blob/c32b172586d4693df235d7e8855c811ca208e5a9/src/Repositories/RedisJobRepository.php#L160

You will see that in the ajax request the query string starting_at=0, to the `$afterIndex + 1` will give `1` that is reflected in the redis command to get failed jobs ids `zrange failed_jobs 1 50`

**Comment by driesvints** [comment]
Can you try to replace line 160 with the following and see what happens?

```
$type, $afterIndex ? $afterIndex + 1 : '-inf', $afterIndex + 50
```

**Comment by shadoWalker89** [comment]
That will give an error `Redis::zRange() expects parameter 2 to be integer, string given`
But replacing the `-inf` with `-1` does the trick and the failed job is displayed.

But if you check this line

https://github.com/laravel/horizon/blob/c32b172586d4693df235d7e8855c811ca208e5a9/src/Repositories/RedisJobRepository.php#L157

You will see that similar check is there with the exception that is checking for `=== null`

I think that maybe the line below is the one that should change

https://github.com/laravel/horizon/blob/c32b172586d4693df235d7e8855c811ca208e5a9/src/Http/Controllers/FailedJobsController.php#L70

if the starting_at is `0` then pass null

Also should change the default value to `null` if the parameter `starting_at` does not exist.
Because back to the line `160` if -1 is passed the will have -1 + 1 which gives 0 and then the command will be 

```
zrange failed_jobs 0 50
```
Which does not work and return an empty set

I think maybe this is the proper change (it works for me)

```
// Failed jobs controller
    protected function paginate(Request $request)
    {
        $starting_at = $request->query('starting_at', null);

        return $this->jobs->getFailed($starting_at === '0' ? null : $starting_at)->map(function ($job) {
            return $this->decode($job);
        });
    }
```

Note: I don't know but maybe you should also the `paginateByTag()` method on the controller

**Comment by driesvints** [comment]
Can you try this?

```php
return $this->jobs->getFailed($request->query('starting_at') ?: -1)->map(function ($job) {
    return $this->decode($job);
});
```

**Comment by shadoWalker89** [comment]
Yeah that works as well

**Comment by driesvints** [comment]
Cool. I think the `paginateByTag` method is ok because the implementation is slightly different there. Actually I believe that's the solution all along. Can you try one more time with this change:

```php
return $this->jobs->getFailed($request->query('starting_at', -1) + 1)->map(function ($job) {
    return $this->decode($job);
});
```

**Comment by shadoWalker89** [comment]
Not this last one does not work.
Go back to having an empty array for the jobs

**Comment by driesvints** [comment]
Ah I see, that's because it's a different method call. I'll send in a PR with the fix. Thanks for reporting.
