### ISSUE TITLE
Add the force option to horizon:install

### ISSUE THREAD

**Issue by mikeminckler** [laravel/horizon#533]
While upgrading to v3.0 I was getting an error that Laravel Mix was unable to find the app.css file referenced in the horizon index. 

I tried to republish the assets using php artisan `horizon:install` but since I had already published these files nothing was overwritten as this is the default behaviour for `vendor:publish`

I was able to correct the problem by checking the `Console/InstallCommand.php` file to see which tags to force update via `vendor:publish`. 

`php artisan vendor:publish --tag horizon-assets --force`

Not sure how much customizing devs are doing in the UI of horizon but perhaps there should be a `--force` option for `horizon:install` which would solve this upgrading issue.

**Comment by driesvints** [comment]
`php artisan vendor:publish --tag=horizon-assets --force` is the way to go.

**Comment by browner12** [comment]
you can also use the Horizon specific command `php artisan horizon:assets`, which calls exactly what @driesvints is suggesting.

I have this Artisan command as part of my deploy process.

**Comment by Jokerwin** [comment]
Thanks, I was upgrading `v2` to `v3` and I found the same problem.
