### ISSUE TITLE
unable to local Mix file: /app.css

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/horizon#534]
Laravel 5.7.20
Horizon 3.0.0

After installing Horizon 3.0.0, i ran `php artisan horizon:install`

start horizon by `php artisan horizon` and go to `http://localhost/horizon/dashboard`, I got Error Exception, Unable to local Mix fie: /app.css (View:..../vendor/laravel/horizon/resources/views/layout.blade.php)

**Comment by browner12** [comment]
`php artisan horizon:install` publishes assets without 'force' flag, which is why your assets are not being overwritten.

use the `php artisan horizon:assets` command instead.

**Comment by king724** [comment]
I had the same issue. 

See https://github.com/laravel/horizon/issues/525#issuecomment-467952910
