### ISSUE TITLE
more information on status, retries, planned exection datetime, would be lovely

### ISSUE THREAD

**Issue by vesper8** [laravel/horizon#536]
I am having issues with jobs being queued and then just ignored.. they remain with the orange status icon indefinitely, while new jobs of the same type will get executed and become green

the ones that remain orange, I have no idea why, there is no error, they do not end up in the failed job section. These are short running jobs that should take no longer than 2 or 3 seconds to execute.

I would love for a way to know more about why a job is stuck. It would be nice to see if jobs are being retried, why not have a "try" column to see if they run on first try or N try (in the case where a retry of 3 is set for example)

also I can see when jobs were "queued" but not when they actually ran. It's very frustrating seeing these jobs get stuck for no reason. I'm using the newly released V3 by the way. I like the new UI but it's still lacking in terms of information available for debugging IMO.

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by vesper8** [comment]
i ended up resolving my issue. i was doing thing in the constructor that were not meant to be there and needed to be moved to the handle method. i had not realized that the constructor gets called as soon as a job is queued as opposed to only once it is "handled"

in any case this is more of a feature request than dealing with a specific issue. It would be nice to. For example the tries/retries, it would be nice to be able to see this in the UI, when a job succeeded on the first try vs the Nth try

**Comment by atymic** [comment]
@driesvints 

I'd love to take a crack at adding some of this stuff. Are you open to PRs?

**Comment by driesvints** [comment]
@atymic definitely

**Comment by driesvints** [comment]
Hey all, this is not something we'll be working on ourselves but we're still open to PRs for this.
