### ISSUE TITLE
Display `artisan horizon` command description in artisan list

### ISSUE THREAD

**Issue by olavski** [laravel/horizon#538]
It is not clear from running `php artisan` that the command `php artisan horizon` is available and that it will start all of your configured workers.

The list shows description for sub-commands such as `horizon:continue` but it does not explain what `horizon` itself does.

At the moment you have to check the Horizon documentation website to find that out, but it would be good to show this in the artisan list.

```bash
$ php artisan
 horizon
  horizon:assets            Re-publish the Horizon assets
  horizon:continue          Instruct the master supervisor to continue processing jobs
  horizon:list              List all of the deployed machines
  horizon:pause             Pause the master supervisor
  horizon:purge             Terminate any rogue Horizon processes
  horizon:snapshot          Store a snapshot of the queue metrics
  horizon:supervisors       List all of the supervisors
  horizon:terminate         Terminate the master supervisor so it can be restarted
```

Thanks for building a great project!

**Comment by driesvints** [comment]
Hmm, you're correct. We might want to change this.

**Comment by driesvints** [comment]
Or we could look at supporting commands without a `:` notation in the framework itself.

**Comment by olavski** [comment]
Sorry if this is a bit off topic.

With Horizon, Nova, Spark, Scout and other packages the artisan list gets very long. 
My app's artisan list has almost 200 commands now, so it would also be good have an option to only show my own commands from App/Console/Comands.

**Comment by driesvints** [comment]
@olavski you can do that with the list command: `php artisan list horizon`

**Comment by olavski** [comment]
@driesvints Ok, I meant more the reverse of that, so list everything apart from Nova,Spark,Horizon and default Laravel commands, so only show the commands I have built that are specific for this app.

But don't worry about it for now, this is getting a bit off topic. I'll see if I can create a package to do this instead. 

Thanks! :)

**Comment by alexbowers** [comment]
@olavski Perhaps put an issue on https://github.com/laravel/ideas for a `--simple` output showing only the core things you care about (App namespaced stuff)

**Comment by web64** [comment]
@alexbowers Thanks for the suggestion. I'll do that!

**Comment by olavski** [comment]
@alexbowers Thanks for the suggestion. I'll do that!

**Comment by alexbowers** [comment]
@driesvints This can be closed :)
