### ISSUE TITLE
Missing latest job in recent jobs list

### ISSUE THREAD

**Issue by hubertnnn** [laravel/horizon#540]
Version: 3.0.2

After resetting my redis I found that one of jobs is missing. 
After digging deeper I found that recent jobs always lacks the newest job.
Reason seem to be incorrect parameter in api call `/horizon/api/jobs/recent?starting_at=0&limit=50`.
After changing statring_at to -1 (default value in controller) I am getting all jobs.

**Comment by browner12** [comment]
I am getting the same issue.

**Comment by browner12** [comment]
https://github.com/laravel/horizon/blob/3.0/resources/js/screens/recentJobs/index.vue

**Comment by themsaid** [comment]
Thanks.

I've fixed that in v3.0.3.

https://github.com/laravel/horizon/commit/1ab57492f66014849b51364315c875b7f76bb435

**Comment by ARKKYN** [comment]
@themsaid not fixed

**Comment by driesvints** [comment]
@ARKKYN did you re-publish the assets with `php artisan horizon:assets` ?

**Comment by ARKKYN** [comment]
@driesvints Did that but no luck

**Comment by themsaid** [comment]
@browner12 @hubertnnn can you confirm or deny the issue is fixed?

**Comment by hubertnnn** [comment]
For me it was fixed. 
Recent jobs contain job that I just dispatched. (bug I found is fixed)
Also checked failed jobs to confirm if that one is ok and it is.
Also checked monitored tags (I never used them before) and seem to also work fine.

**Comment by browner12** [comment]
I believe it was working for me in 3.0.3, but now I'm on 3.0.5 and it appears to be broken again. I will dig in a little more and see what I can find.

**Comment by driesvints** [comment]
@ARKKYN since this issue was fixed for other and not you I suggest you first try to re-install horizon completely to resolve the issue. Can you try that and report back? Make sure you remove any assets, vendor dir, etc.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
