### ISSUE TITLE
Horizon nigh mode not working on prod

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/horizon#546]
Laravel Version: 5.8.3
PHP Version: 7.3.0
Composer Version: 1.8.3
Horizon Version: 3.0.3
Description:

I have an issue running night mode on prod. It works fine on my local but not on prod. I ran `php artisan horizon:assets` on my prod server but it didn't help.

Thanks,

**Comment by browner12** [comment]
You're going to have to explain a little more if you want help debugging this. What does your `HorizonServiceProvider` look like?  Try running a hard refresh, there could be caching issues.

Also, as a side note, your Composer is pretty far behind, would recommend updating that to the latest version.

**Comment by asivaneswaran** [comment]
Hi,

So yeah, I activated the `Horizon::night();` in the ServiceProvider. I hard refreshed, cleared the cache... I am not sure if I missed a step. Here is what I did:

1- Update composer.json
2- Republish the assets
3- Activate the night mode

I am not sure if I missed something on prod?

Also, I edited the correct version of composer.

**Comment by driesvints** [comment]
Copy/paste your service provider please.

**Comment by asivaneswaran** [comment]
```
<?php

namespace App\Providers;

use Laravel\Horizon\Horizon;
use Illuminate\Support\Facades\Gate;
use Laravel\Horizon\HorizonApplicationServiceProvider;

class HorizonServiceProvider extends HorizonApplicationServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        // Horizon::routeSmsNotificationsTo('15556667777');
        // Horizon::routeMailNotificationsTo('example@example.com');
        // Horizon::routeSlackNotificationsTo('slack-webhook-url', '#channel');
        
        Horizon::night();
    }

    /**
     * Register the Horizon gate.
     *
     * This gate determines who can access Horizon in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewHorizon', function ($user) {
            return in_array($user->email, [
                //
            ]);
        });
    }
}
```

**Comment by driesvints** [comment]
I can get the night mode to display correctly. I'm not really sure what's going wrong on your production environment. Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
