### ISSUE TITLE
Horizon creates too many php processes

### ISSUE THREAD

**Issue by oluomotoso** [laravel/horizon#548]
I use Horizon 2.0 with Laravel 5.7. I notice horizon has too many php processes. This end up crashing the server. I need help on this please, I've been debugging this for more than 7 days and it's driving me nut

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by oluomotoso** [comment]
I've posted more than 3 times on Laracat without any reply

**Comment by driesvints** [comment]
Please link to these threads
