### ISSUE TITLE
Setting supervisor niceness

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#549]
I was thinking of sending a PR to set process niceness on each supervisor via config:
```php
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 3,
                'nice' => 5,
            ],
```
Then in supervisor doing this:
```php
if ($config['nice']) proc_nice($config['nice']);
```
Do you think horizon's config is a good place to set process niceness? Or instead just calling proc_nice() in the jobs. Please note that niceness can only be increased in a process (unless maybe the process is run by the root user).

**Comment by driesvints** [comment]
Can you maybe give some background info on what this does and how it will benefit users?

**Comment by halaei** [comment]
In cases of high server load, when CPU usage is 100%, setting proc_nice can help OS to prioritize other processes that needs to be near-real time, e.g. PHP processes that handle web requests or maybe redis and mysql servers.

The benefit can be for example users won't experience lag in site just because some workers are processing some audio files, that are fine to be processes a few second or even hours later.

**Comment by driesvints** [comment]
Pinging @taylorotwell to see if we might get this into Horizon.

**Comment by driesvints** [comment]
@halaei you can send in a PR if you want :)

**Comment by halaei** [comment]
OK thanks. I have issues with backward compatibility, because I can't get away from adding parameter to `SupervisorOptions::__construct()`

**Comment by driesvints** [comment]
If you need to make breaking changes you can send to master

**Comment by francislavoie** [comment]
@driesvints this can be closed now, can't it? The PR's been merged.

**Comment by halaei** [comment]
Yes
