### ISSUE TITLE
[3.0.5] Undefined index: connection

### ISSUE THREAD

**Issue by tomswinkels** [laravel/horizon#552]
Error when i was restart supervisor.

`Undefined index: connection`

<img width="683" alt="image" src="https://user-images.githubusercontent.com/9036151/54723474-f4114d00-4b67-11e9-8887-b9fd801ab0e1.png">

**Comment by tomswinkels** [comment]
Whoops i was missing some array "production" in my horizon.php configuration file.

**Comment by driesvints** [comment]
No problem. Please always close your issue if you find a solution.
