### ISSUE TITLE
Failed job second page does not remove refresh icon on success

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/horizon#559]
- Horizon Version: v3.1.0
- Laravel Version: v5.8.8
- PHP Version: 7.3.3
- Database Driver & Version: MariaDB 10.3.8

### Description:

In Failed Jobs, there is a refresh icon for each failed job. Click on it will retry the failed job and on success the icon is removed.

This works as expected on the first page but not on the second and the rests of the pages.

### Steps To Reproduce:

In this gif, the Failed Jobs are on page 2, click refresh and then next page and then the previous page, boom the icon is gone!

![Grabación de pantalla 2019-03-28 a la(s) 11 38 00 a  m](https://user-images.githubusercontent.com/6526545/55176612-704ef600-514f-11e9-84cd-3efda7e4128a.gif)

**Comment by driesvints** [comment]
@themsaid

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/horizon/commit/7d282723792f3dd6d058b8d7b87a18350635c029

Thanks 👍🏼

**Comment by driesvints** [comment]
Will be released next Tuesday.
