### ISSUE TITLE
Bogus failed job causes dupe job retry 

### ISSUE THREAD

**Issue by danetzer** [laravel/horizon#560]
- Horizon Version: 2.2
- Laravel Version: 5.5
- PHP Version: 7.2.16
- Database Driver & Version: MySQL 5.6

### Description:

Getting intermittent falsely reported failed jobs which results in duplicate jobs when they are retried. The time out is ~ 30 seconds and retry time is like 1000 seconds out. 

### Steps To Reproduce:

hard to reproduce only happens randomly a few times a week.

**Comment by danetzer** [comment]
FYI the runtime of the jobs are ~ .1 seconds which is another reason why this is puzzling. So not seeing a chance of their being conflict between timeout and retry values.

**Comment by setkyar** [comment]
@danetzer I think you should describe how you are using the jobs with the code simple. I also face that kind of problem and it was because of the code for my case.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
