### ISSUE TITLE
A queued job has been attempted too many times. The job may have previously timed out

### ISSUE THREAD

**Issue by dharmendrakumartiwari** [laravel/horizon#561]
- Horizon Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

**Comment by dharmendrakumartiwari** [comment]
in laravel :- A queued job has been attempted too many times. The job may have previously timed out

**Comment by dharmendrakumartiwari** [comment]
error show in laravel A queued job has been attempted too many times. The job may have previously timed out

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mohsinmj1** [comment]
facing same issue. did any one found any solution for this?? 
local.ERROR: Maatwebsite\Excel\Jobs\ReadChunk has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): Maatwebsite\\Excel\\Jobs\\ReadChunk has been attempted too many times or run too long. The job may have previously timed out. at /home/weboqysw/infoimpex.webocitytech.website/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:632
