### ISSUE TITLE
Queued At Time zone issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#562]
- Horizon Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: Redis, Postgresql 11

### Description:
Queued At is not considering the local browser time instead showing the date in some other time zone. The previous versions seems to be local browser time.

**Comment by driesvints** [comment]
Have you used `php artisan horizon:assets` as said in https://laravel.com/docs/5.8/horizon#upgrading to update the front-end assets?

**Comment by xyrintech** [comment]
I did use this - php artisan horizon:assets but the issue is still there. I believe its taking the timezone from app.php rather than local (browser) time. I tried changing the timezone in app.php from UTC to Los Angeles time and horizon starts showing up the time in Los Angeles time. Before this version the horizon always have been timezone in local time. 

There is an another issue with this, when we add a monitoring then on page it shows maximum 3 records. The recent jobs show 50 records and this is fine but monitoring tags shows only 3 records at max.

**Comment by driesvints** [comment]
Server time has always been used for Horizon and I believe we won't change that any time soon.

> There is an another issue with this, when we add a monitoring then on page it shows maximum 3 records. The recent jobs show 50 records and this is fine but monitoring tags shows only 3 records at max.

Please create a separate issue for this.
