### ISSUE TITLE
Sleep function and timeout issue

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#564]
- Horizon Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: Redis

### Description:
1) First of all, timeout inside the job file is not killing the worker. 
2) Using the sleep function inside the job freeze the worker and nothing happens. 

```
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class FetchAmazonOrders implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    
    public $timeout = 1;

    
    public function __construct()
    {
        
    }
    
    public function handle()
    {
        myLog("before sleep");
        sleep(2);
        myLog("after sleep");
        
    }
    
    public function failed($exception = null)
    {
        myLog("failed");
    }
}

```

horizon config:
```
['local' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default', 'high', 'medium', 'low'],
                'balance' => 'auto',
                'processes' => 10,
                'tries' => 1,
                'timeout' => 1,
                'retry_after' => 1
            ],
        ],]
```

Log:
[2019-04-03 19:53:25] local.INFO: before sleep

![Screenshot 2019-04-04 at 1 38 27 AM](https://user-images.githubusercontent.com/7784136/55509776-63179700-567a-11e9-95d1-de443218d676.png)

**Comment by code-creeper** [comment]
@xyrintech why did you close this issue what solution did you find?

**Comment by ellermister** [comment]
@code-creeper Have you solved it?

I found that sleep does not work in horizon.

`php artisan horizon:terminate --wait` is also not work, Return immediately.


I want to simulate a timeout task and safe exit, but I can't seem to solve it.

but. queue:work is everything works fine!

**Comment by code-creeper** [comment]
@ellermister No, I didn’t solve it.
