### ISSUE TITLE
All routes return 404 codeStatus

### ISSUE THREAD

**Issue by elhajouji5** [laravel/horizon#565]
- Horizon Version: 2.0
- Laravel Version: 5.5.*
- PHP Version: 7.2
- APP_ENV: staging

### Description
Hello everyone hope you're doing well,
I've installed laravel/horizon locally everything worked like a charm.<br>
I followed up the same instructions to deploy it on my staging server but it didn't work as expected.<br>
All of the routes return correct data with statusCode 404, which make the views show the loading icon

#### Screen shot
Response contains expected data with not found http code status
<img width="1473" alt="404 httpCodeStatus" src="https://user-images.githubusercontent.com/32602971/55553193-73119400-56d7-11e9-98f7-91ed516d3773.png">

<br>
All of the views stuck at loading
<img width="1425" alt="Loading" src="https://user-images.githubusercontent.com/32602971/55551572-12805800-56d3-11e9-9dd2-2f5c76ebdec7.png">

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by elhajouji5** [comment]
@driesvints Thanks for your reply, when I try to install the last version of Horizon with laravel 5.5 I get this error
<img width="2048" alt="Screen Shot 2019-04-04 at 16 20 49" src="https://user-images.githubusercontent.com/32602971/55567583-e1654f00-56f5-11e9-99b8-1bcfd6cf185c.png">

**Comment by driesvints** [comment]
We don't support 5.5 anymore. Please upgrade to 5.8

**Comment by elhajouji5** [comment]
Thanks for the help you provided, I'll upgrade to 5.8 ASAP

**Comment by Edofre** [comment]
@driesvints 

Quick question, does this mean that Horizon ^1.2 (& all official packages) for Laravel 5.5.* will get security updates till August 30th, 2020?

Thanks in advance.

**Comment by driesvints** [comment]
@Edofre no. Only the latest release.
