### ISSUE TITLE
Call to undefined method Illuminate\Queue\RedisQueue::readyNow()

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#568]
- Horizon Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.3
- Database Driver & Version: redis

### Description:
Getting this error on horizon - Call to undefined method Illuminate\Queue\RedisQueue::readyNow()
No stats, queues etc. nothing is displayed and same error is thrown for every API call.

**Comment by xyrintech** [comment]
This problem occurs when the code simply pulled on previous laravel version. 
However if we setup the new code without pulling the code on previous one then this is good. 
I believe the issue has only been at configuration side.

**Comment by xyrintech** [comment]
Noted a very strange behaviour, the same occurs again when I restarted the droplet is restarted.

**Comment by driesvints** [comment]
> This problem occurs when the code simply pulled on previous laravel version.

What do you mean by this? 

Do you properly restart horizon after a deploy?

**Comment by xyrintech** [comment]
I mean restarted the server.

**Comment by xyrintech** [comment]
Horizon log says that queues are processing but nothing shows up on horizon dashboard

**Comment by xyrintech** [comment]
> Do you properly restart horizon after a deploy?

I am using supervisor and restarted supervisor and also did php artisan queue:restart
But the same issue. The jobs in the background are executing fine but nothing shows up on dashboard.

**Comment by xyrintech** [comment]
> What do you mean by this?

I mean when simply pulling the files from git. 

but as I mean later messages the issue is still there.

**Comment by xyrintech** [comment]
```
[2019-04-08 03:48:22] local.ERROR: Call to undefined method Illuminate\Queue\RedisQueue::readyNow() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Queue\\RedisQueue::readyNow() at /var/www/html/laravel/vendor/laravel/horizon/src/AutoScaler.php:80)
[stacktrace]
#0 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1141): Laravel\\Horizon\\AutoScaler->Laravel\\Horizon\\{closure}(Object(Laravel\\Horizon\\ProcessPool), 'default')
#1 /var/www/html/laravel/vendor/laravel/horizon/src/AutoScaler.php(83): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#2 /var/www/html/laravel/vendor/laravel/horizon/src/AutoScaler.php(49): Laravel\\Horizon\\AutoScaler->timeToClearPerQueue(Object(Laravel\\Horizon\\Supervisor), Object(Illuminate\\Support\\Collection))
#3 /var/www/html/laravel/vendor/laravel/horizon/src/Supervisor.php(343): Laravel\\Horizon\\AutoScaler->scale(Object(Laravel\\Horizon\\Supervisor))
#4 /var/www/html/laravel/vendor/laravel/horizon/src/Supervisor.php(300): Laravel\\Horizon\\Supervisor->autoScale()
#5 /var/www/html/laravel/vendor/laravel/horizon/src/Supervisor.php(267): Laravel\\Horizon\\Supervisor->loop()
#6 /var/www/html/laravel/vendor/laravel/horizon/src/Console/SupervisorCommand.php(92): Laravel\\Horizon\\Supervisor->monitor()
#7 /var/www/html/laravel/vendor/laravel/horizon/src/Console/SupervisorCommand.php(67): Laravel\\Horizon\\Console\\SupervisorCommand->start(Object(Laravel\\Horizon\\Supervisor))
#8 [internal function]: Laravel\\Horizon\\Console\\SupervisorCommand->handle(Object(Laravel\\Horizon\\SupervisorFactory))
#9 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /var/www/html/laravel/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/html/laravel/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/html/laravel/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SupervisorCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/html/laravel/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/html/laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by xyrintech** [comment]
Though I tried but if you still insist then I can try again

**Comment by xyrintech** [comment]
There is definitely an issue with this - Call to undefined method Illuminate\Queue\RedisQueue::readyNow()
I mean the same code works and when I restart the supervisor after like few hours then this stopped working.

**Comment by xyrintech** [comment]
I have been observing this from last 2 days.

I have been getting a very strange issue. When I deploy code and start horizon first time, this works completely fine but the time I restart the horizon (supervisor stop and start) then the I get the issue on Horizon Stats, Recent Jobs etc. everywhere.

Call to undefined method Illuminate\Queue\RedisQueue::readyNow() {"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Call to undefined method Illuminate\Queue\RedisQueue::readyNow() at /var/www/html/laravel/vendor/laravel/horizon/src/AutoScaler.php:80)

Now, not sure why its happening, is this something I committing a mistake or something wrong with Horizon?

**Comment by driesvints** [comment]
@xyrintech can you please try a few support channels first?

**Comment by anyb1s** [comment]
@xyrintech did you resolve your issue? I am experiencing it as well (the strange thing is that it is only on production).

Cannot reproduce it locally though. For some reason, it doesn't attach the Redis connector to the queue manager.

Horizon Version: 4.1
Laravel Version: 7.3
PHP Version: 7.4.4

**Comment by thewasta** [comment]
### Environment:
```
Larvel version: 6.x
Php version: 7.3
```

I have the same issue did anyone resolve it?
I first installed php extension `ext-amqp`
My steps:
install
```
$ composer require avto-dev/amqp-rabbit-manager "^2.0"
$ composer require avto-dev/amqp-rabbit-laravel-queue "^2.0"
$ php artisan vendor:publish --provider='AvtoDev\AmqpRabbitManager\ServiceProvider'
```
Configure `./config/rabbitmq.php` and `./config/queue.php`
and run command `php artisan rabbit:setup` now if I use `php artisan queue:work` my jobs works, but if I use `php artisan horizon` I have the issue.

```
Call to undefined method AvtoDev\AmqpRabbitLaravelQueue\Queue::readyNow() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method AvtoDev\\AmqpRabbitLaravelQueue\\Queue::readyNow() at /var/www/vendor/laravel/horizon/src/AutoScaler.php:80)
```
