### ISSUE TITLE
Is it possible to enhance Horizon to work with Beanstalkd queues server?

### ISSUE THREAD

**Issue by OleksandrVladymyrov** [laravel/horizon#569]
Hi,
First of all, thank you for the great package.

Is it possible to enhance Horizon to work with Beanstalkd queues server?
Maybe you use some features which don't support by Beanstalkd.

Thank you in advance.

**Comment by bonzai** [comment]
#100

**Comment by OleksandrVladymyrov** [comment]
1.5 years have passed. Plans could change.

**Comment by driesvints** [comment]
We don't have any plans to move beyond Redis atm.

**Comment by OleksandrVladymyrov** [comment]
@driesvints Did you use any specific features that  Beanstalkd don't support.

**Comment by driesvints** [comment]
@OleksandrVladymyrov I don't know too much about Beanstalkd to answer that question.

**Comment by OleksandrVladymyrov** [comment]
@driesvints Maybe someone another can answer my question.

**Comment by vovakovalchukk** [comment]
@driesvints hey man, any chance smth changed with Beanstalkd ? :)
