### ISSUE TITLE
Runtime shows 1554712872.58s

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#571]
- Horizon Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.3
- Redis Driver & Version: "predis/predis": "^1.1" and Redis server v=5.0.3
- Database Driver & Version: Postgresql 11

### Description:
Getting runtime as 1554712872.58s (huge numbers)

**Comment by driesvints** [comment]
Please provide a screenshot of the problem.

**Comment by xyrintech** [comment]
![Screenshot 2019-04-08 at 4 38 41 PM](https://user-images.githubusercontent.com/7784136/55719827-d0318080-5a1c-11e9-81d6-8cc77a7038fc.png)
Attached

**Comment by driesvints** [comment]
Can you provide the payloads of the requests made with the Horizon API to retrieve the data? Use the network tab in your console to do this.

**Comment by xyrintech** [comment]
There seems to be many issues with 3.1 version horizon. I have been using 1.4 before and never had any issues but since I have upgraded to 3.1 there are many issues.

**Comment by xyrintech** [comment]
<link>/horizon/api/jobs/failed?starting_at=0

**Comment by xyrintech** [comment]
Is that you need or need headers too?

**Comment by driesvints** [comment]
I need the payload from the preview tab.

**Comment by xyrintech** [comment]
` {"jobs":[{"id":"Vzv5r0Z8Pfwz7d0KoPVykd3KyIsRMTJZ","connection":"redis","queue":"low","name":"App\\Jobs\\ImportAdvertisingKeywordReport","status":"failed","payload":{"website_id":2,"timeout":1800,"id":"Vzv5r0Z8Pfwz7d0KoPVykd3KyIsRMTJZ","data":{"command":"O:39:\"App\\Jobs\\ImportAdvertisingKeywordReport\":12:{s:13:\"\u0000*\u0000website_id\";i:2;s:12:\"\u0000*\u0000report_id\";i:43423;s:13:\"\u0000*\u0000identifier\";s:30:\"ImportAdvertisingKeywordReport\";s:9:\"\u0000*\u0000status\";N;s:7:\"timeout\";i:1800;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:3:\"low\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\ImportAdvertisingKeywordReport"},"displayName":"App\\Jobs\\ImportAdvertisingKeywordReport","timeoutAt":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"attempts":2},"exception":"Illuminate\\Queue\\MaxAttemptsExceededException: App\\Jobs\\ImportAdvertisingKeywordReport has been attempted too many times or run too long. The job may have previously timed out. in \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php:401\nStack trace:\n#0 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(321): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1)\n#1 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))\n#2 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))\n#3 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'low', Object(Illuminate\\Queue\\WorkerOptions))\n#4 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'low')\n#5 \/var\/www\/html\/laravel\/vendor\/laravel\/horizon\/src\/Console\/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()\n#6 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()\n#7 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(32): call_user_func_array(Array, Array)\n#8 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#9 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))\n#10 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)\n#11 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(183): Illuminate\\Container\\Container->call(Array)\n#12 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Command\/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#13 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#14 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/var\/www\/html\/laravel\/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 {main}","failed_at":"1554721616.471","completed_at":null,"retried_by":[],"reserved_at":null,"index":0},{"id":"LxEEZWWQbILg5G8LnKqDFIn9FrT5XySb","connection":"redis","queue":"low","name":"App\\Jobs\\ImportAdvertisingKeywordReport","status":"failed","payload":{"website_id":4,"timeout":1800,"id":"LxEEZWWQbILg5G8LnKqDFIn9FrT5XySb","data":{"command":"O:39:\"App\\Jobs\\ImportAdvertisingKeywordReport\":12:{s:13:\"\u0000*\u0000website_id\";i:4;s:12:\"\u0000*\u0000report_id\";i:5912;s:13:\"\u0000*\u0000identifier\";s:30:\"ImportAdvertisingKeywordReport\";s:9:\"\u0000*\u0000status\";N;s:7:\"timeout\";i:1800;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:3:\"low\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\ImportAdvertisingKeywordReport"},"displayName":"App\\Jobs\\ImportAdvertisingKeywordReport","timeoutAt":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"attempts":2},"exception":"Illuminate\\Queue\\MaxAttemptsExceededException: App\\Jobs\\ImportAdvertisingKeywordReport has been attempted too many times or run too long. The job may have previously timed out. in \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php:401\nStack trace:\n#0 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(321): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1)\n#1 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))\n#2 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))\n#3 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'low', Object(Illuminate\\Queue\\WorkerOptions))\n#4 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'low')\n#5 \/var\/www\/html\/laravel\/vendor\/laravel\/horizon\/src\/Console\/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()\n#6 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()\n#7 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(32): call_user_func_array(Array, Array)\n#8 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#9 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))\n#10 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)\n#11 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(183): Illuminate\\Container\\Container->call(Array)\n#12 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Command\/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#13 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#14 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/var\/www\/html\/laravel\/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 {main}","failed_at":"1554721616.4577","completed_at":null,"retried_by":[],"reserved_at":null,"index":1},{"id":"121F8CwuYHSEzRyVdVlZMvhsqA4JlzzX","connection":"redis","queue":"low","name":"App\\Jobs\\ImportAdvertisingKeywordReport","status":"failed","payload":{"website_id":1,"timeout":1800,"id":"121F8CwuYHSEzRyVdVlZMvhsqA4JlzzX","data":{"command":"O:39:\"App\\Jobs\\ImportAdvertisingKeywordReport\":12:{s:13:\"\u0000*\u0000website_id\";i:1;s:12:\"\u0000*\u0000report_id\";i:41851;s:13:\"\u0000*\u0000identifier\";s:30:\"ImportAdvertisingKeywordReport\";s:9:\"\u0000*\u0000status\";N;s:7:\"timeout\";i:1800;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:3:\"low\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\ImportAdvertisingKeywordReport"},"displayName":"App\\Jobs\\ImportAdvertisingKeywordReport","timeoutAt":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"attempts":2},"exception":"Illuminate\\Queue\\MaxAttemptsExceededException: App\\Jobs\\ImportAdvertisingKeywordReport has been attempted too many times or run too long. The job may have previously timed out. in \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php:401\nStack trace:\n#0 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(321): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), 1)\n#1 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))\n#2 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))\n#3 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'low', Object(Illuminate\\Queue\\WorkerOptions))\n#4 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'low')\n#5 \/var\/www\/html\/laravel\/vendor\/laravel\/horizon\/src\/Console\/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()\n#6 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()\n#7 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(32): call_user_func_array(Array, Array)\n#8 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#9 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))\n#10 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)\n#11 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(183): Illuminate\\Container\\Container->call(Array)\n#12 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Command\/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#13 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#14 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/var\/www\/html\/laravel\/vendor\/symfony\/console\/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/var\/www\/html\/laravel\/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 {main}","failed_at":"1554721616.4584","completed_at":null,"retried_by":[],"reserved_at":null,"index":2}],"total":3}`

**Comment by xyrintech** [comment]
Hope this helps now.

**Comment by driesvints** [comment]
`reserved_at` seems to be empty everywhere. We'll need to figure out why this is.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by picbenoit** [comment]
Hello,

I reproduced the problem. My environement setting :

- PHP 7.3

- Laravel 5.8

- Horizon 3.2

![image](https://user-images.githubusercontent.com/22802680/75161238-c6d80200-571b-11ea-8f3b-50db9fdc70b6.png)

unfortunately it crashes my job with the following error :

`Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\MakeImport has been attempted too many times or run too long. The job may have previously timed out. in /var/www/cinte.consumer-live.com/releases/302/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:601`

Thank you for your help,

Ben.

**Comment by picbenoit** [comment]
Still have this problem for some jobs, is it possible to re-open ?

**Comment by fadlymuhammadf** [comment]
> Hello,
> 
> I reproduced the problem. My environement setting :
> 
> * PHP 7.3
> * Laravel 5.8
> * Horizon 3.2
> 
> ![image](https://user-images.githubusercontent.com/22802680/75161238-c6d80200-571b-11ea-8f3b-50db9fdc70b6.png)
> 
> unfortunately it crashes my job with the following error :
> 
> `Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\MakeImport has been attempted too many times or run too long. The job may have previously timed out. in /var/www/cinte.consumer-live.com/releases/302/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:601`
> 
> To be complete, I have a lot of others jobs (thousands every days) working well.
> 
> Thank you for your help,
> 
> Ben.

please up this issue, i have the same issue right now.
thanks for your help.
