### ISSUE TITLE
Console output not working for jobs

### ISSUE THREAD

**Issue by cg-rsands** [laravel/horizon#572]
- Horizon Version: 1.4
- Laravel Version: 5.8
- PHP Version: 7.3
- Redis Driver & Version: phpredis

### Description:
Previously when using 5.6 it use to output:

Processing:......
Processed:....

However now after upgrading to laravel 5.8 horizon says started, processes the jobs but has no output for the jobs it is processing

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
