### ISSUE TITLE
Any change in notification needs to horizon restart

### ISSUE THREAD

**Issue by HPWebdeveloper** [laravel/horizon#573]
Hello,

- Horizon Version: ^2.2
- Laravel Version: 5.7.*
- PHP Version: 7.1.25
- Redis Driver & Version: predis/phpredis 4.0.6
- Database Driver & Version: mysql 5.7.21 Homebrew

### Description: 
In local development environment any change in email notification class is not affected until I stop the horizon and restart it again by :
php artisan horizon

If this is not a horizon issue and this is my problem the same as https://github.com/laravel/horizon/issues/433, and since  `queue:listen`  does not work for me, could you please let me know how I can run always the latest code, and not the snapshot of code when using horizon?

Thank you so much in advance,
Best Regards,

### Steps To Reproduce:

- php artisan make:notification InvoicePaid
- implements ShouldQueue
- then: php artisan horizon
- then trigger then InvoicePaid notification
- In public function toMail($notifiable) add a new line
```
   ->line('One of your invoices has been paid!')
   ->line(' New line - One of your invoices has been paid!')
```
- again trigger the notification again

You can not see that new line in the email content until stop horizon and restart it.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!

**Comment by mfn** [comment]
@HPWebdeveloper this is currently expected and the trade-off of using Larvels worker vs. another architecture like e.g. https://github.com/resque/php-resque

The trade-off being that Laravels concept has much better performance characteristics as the framework does not need to fork() new workers and doesn't need to boot every time vs. you need to restart horizon.

You could try if something like http://www.expertphp.in/article/nodemon-reload-the-server-on-code-change-automatically works for you though.
