### ISSUE TITLE
Stop Monitoring return 405 method not allow

### ISSUE THREAD

**Issue by melvin-clickprofits** [laravel/horizon#574]
- Horizon Version: 1.3.1
- Laravel Version: 5.6.28
- PHP Version: 7.2.7
- Redis Driver & Version: predis/phpredis 1.1.1

### Description:
I was able to create monitoring tag but not able to delete it.
Clicking stop monitoring tag return 405 method not allowed 

Is there anything I can do to allow ? can't see anything in my laravel that blocks that i don't have any horizon related route in my web routes or api routes

### Steps To Reproduce:
Add monitoring tag and then click stop monitoring 
<img width="1436" alt="Screen Shot 2019-04-16 at 2 51 40 PM" src="https://user-images.githubusercontent.com/30608398/56188581-781bff00-6058-11e9-96bd-5a525aad94e6.png">

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so feel free to reply and we'll try to have a look.

Thanks!
