### ISSUE TITLE
Setting 0 processes results in 1 process

### ISSUE THREAD

**Issue by rjksn** [laravel/horizon#587]
- Horizon Version:v3.1.2
- Laravel Version: v5.8.3
- PHP Version: 7.2 (7.3 in Homestead v7.20.0)
- Redis Driver & Version: predis v1.1.1
- Database Driver & Version: Mysql **5.7+**

# Issue… or "feature"?

Setting horizon processors to 0, doesn't set the processors to 0. It instead starts a processor.

I'm using a three section (internal, inbound, outbound) production queue set up and using queue hierarchy to handle orders of operations. I'm attempting to utilize some spare front end cpu cycles, but the main issue is that the outbound requires a single hierarchical connection across all workers.

# Steps to reproduce

Set any processor to 0. 

# config/horizon.php

        'local' => [
            'none' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple', // or 'false'
                'processes' => 0,
                'tries' => 3,
            ],
        ],

# Actual Settings

Can you image I used tinker and saw 2. 0. 0.?

    'environments' => [
        'production' => [
            'internal' => [
                'connection' => 'redis',
                'queue' => ['urgent', 'default', 'build', 'mutate'],
                'balance' => 'false',
                'processes' => 4 * (int) env('WORKER_QUEUE_ENABLED', false) ?: 2 * (int) env('WEB_QUEUE_ENABLED', false),
                'tries' => 3,
                'memory'=> 512,
            ],
            'egres' => [
                'connection' => 'redis',
                'queue' => ['toplevel', 'secondlevel', 'thirdlevel'],
                'balance' => 'false',
                'processes' => 1 * (int) env('WORKER_QUEUE_ENABLED', false),
                'tries' => 3,
                'timeout' => 300,
                'memory'=> 512,
            ],
            'ingres' => [
                'connection' => 'redis',
                'queue' => ['sync', 'inventory'],
                'balance' => 'false',
                'processes' => 12 * (int) env('WORKER_QUEUE_ENABLED', false),
                'tries' => 3,
                'timeout' => 90,
                'memory'=> 512,
            ],
        ],
        ...

**Comment by AJenbo** [comment]
There will always be at least 1 process per queue. This is by design afaik.

**Comment by driesvints** [comment]
This is indeed by design afaik. Having 0 processes doesn't really makes sense I believe?

**Comment by rjksn** [comment]
> Having 0 processes doesn't really makes sense I believe?

Seems like a less hacky way of having different machines do different tasks than all the alternatives I've seen. Alternatives mainly talk about passing different queues in the env but that doesn't help for anything besides the simplest one "queue chunk" per environment.

Is there an alternative solution I'm not seeing to restrict one queue to one processor across all servers?

**Comment by AJenbo** [comment]
You can run the workers directly, but there is no real way to restrict and application to a single cpu, short of only running one worker.

Maybe a solution would be to have the section of the config be behind and if instead of trying to set the workers to 0 with * 1

**Comment by driesvints** [comment]
> Is there an alternative solution I'm not seeing to restrict one queue to one processor across all servers?

I'm not sure how that would be possible?

**Comment by rjksn** [comment]
> You can run the workers directly, but there is no real way to restrict and application to a single cpu, short of only running one worker.

Great get-er-done fallback, no one will ever find that setup.

> I'm not sure how that would be possible?

I thought of a great way, It's having an environment variable setting one "production" machine to run one process. Even works with common sense, 0=0 not 0=!0. ;)

**Comment by driesvints** [comment]
@rjksn you can just define other environments for each machine?
