### ISSUE TITLE
Route not found 

### ISSUE THREAD

**Issue by Daespinosag** [laravel/horizon#592]
- Horizon Version: 3.1.2
- Laravel Version: 5.8.5
- PHP Version: 7.2.14
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: 

### Description:

Horizon views routes do not work on shared server.
- If I go to **server_route/poject_name/horizon** works. 
- But when I click on "Dashboard" it does not take me to **server_route/poject_name/horizon/Dashboard** if not that it takes me to **server_route/horizon/Dashboard** Which is a mistake.

**Comment by driesvints** [comment]
Did you try setting the path in your config file? https://github.com/laravel/horizon/blob/2289331408d592242a41fbfd58820529c04dc70e/config/horizon.php#L29

**Comment by Daespinosag** [comment]
the backend routes are fine, only the fronted routes do not work.
If I change the parth in the horizon configuration, the backend routes are **left route_project / route_project / horizon.** Which is a mistake.

- Is it possible to configure only the routes of the views?
- Is it a problem with laravel-mix?
-Is it possible to place the base route of the application ?, taking into account that it is a shared server this would be very useful.

**Comment by driesvints** [comment]
Can you post example urls? is `server_route/poject_name/horizon` an url or a file path? It's still unclear what you mean.

**Comment by Daespinosag** [comment]
Hello,

I'm on a shared server that has a domain for many applications.

This domain would be the "server_route or www.specific-domain.test" and each project would be a folder within the "www" (it is an apache server).

There are several projects for which access is given by the "server_route" and the name of the folder in which the project is hosted, for example "poject_name".

- The problem is that the fondtend routes address "server_route / horizon" and not "server_route / project_name / horizon".

![explicacion](https://user-images.githubusercontent.com/20668722/58575094-0c0be980-8207-11e9-9291-9d46dcac45ef.png)

![404](https://user-images.githubusercontent.com/20668722/58574449-99e6d500-8205-11e9-9bfa-a022649beaa7.jpg) 

- The routes in the backend are correct. 

![rutas](https://user-images.githubusercontent.com/20668722/58574640-0bbf1e80-8206-11e9-8456-27ba5c718df4.jpg)

- When I change the path in the "path" of horizon configuration, the backend routes are incorrect.

![image](https://user-images.githubusercontent.com/20668722/58575456-b3891c00-8207-11e9-82a6-b39d74c04def.png)

- I guess the problem is the configuration of the javascript routes but I do not know where to configure the "path" only for the frontend.

- Is it possible to include environment variables (.env) in horizon fronted?

**Comment by driesvints** [comment]
What happens when you change "path" to this:

```php
'path' => 'server_route/poject_name/horizon',
```

**Comment by Daespinosag** [comment]
it does not work because horizon concatenates what is put in "path" or "domain" with "server_path" it renders this: 

server_route /poject_name /horizon/server_route/horizon

**Comment by driesvints** [comment]
It just occurred to me that we don't support running Laravel in a subdirectory. So we can't support Horizon like that either, sorry.

**Comment by saurab1996** [comment]
@Daespinosag 

<pre>
'proxy_path' => env('HORIZON_PROXY_PATH', '')  in config/horizon.php

HORIZON_PROXY_PATH = /sub-directory in .env </pre>
