### ISSUE TITLE
Can't publish views

### ISSUE THREAD

**Issue by arbex10** [laravel/horizon#596]
Sorry if it already been answered before, but I haven't found it.

Is there a way I can publish Horizon views?

Thanks in advance,

**Comment by JayBizzle** [comment]
There are no views to publish

`php artisan vendor:publish --tag=horizon-assets --force` 

...should publish everything you need

**Comment by driesvints** [comment]
Yep, just use the command above or the one from the docs: https://laravel.com/docs/5.8/horizon#upgrading

**Comment by arbex10** [comment]
I already did that. But I am still not able to change the view without going in vendor/laravel/horizon/resources/views/layout.blade.php, and these changes would not be sustained when I update it, correct?

I would like to change things like the logo, favicon, and add a few features in the <body> of the layout.

**Comment by JayBizzle** [comment]
You would need to maintain your own fork to do that I believe

**Comment by arbex10** [comment]
Got it, but wouldn't it be a nice and simple feature to add to the project?

Anyway, thanks a lot, @JayBizzle!

**Comment by arbex10** [comment]
@driesvints yes, I do use version control and that is exactly what I am doing atm. But thanks a lot for the suggestion, anyway. :) and if someday you manage to add this feature, I will be glad to hear.
