### ISSUE TITLE
Can't publish package assets

### ISSUE THREAD

**Issue by ybaruchel** [laravel/horizon#6]
- Laravel Version: 5.4.28
- PHP Version: 7.1.5
- Composer Version: 1.4.1
- Horizon Version: 0.1.0

**Description:**
Can't publish the package assets or the "horizon.php" config file.

**Steps To Reproduce:**
`composer require laravel/horizon`
Then:
`php artisan vendor:publish`

**Result**
1. Composer actually installs the package in the vendor folder and adds it in the 'composer.json' file.
2. The vendor publish only publishes the Laravel framework assets (Notification, Pagination, Mails) but not the horizon assets.

**Comment by MattHans0n** [comment]
Horizon requires Laravel 5.5

**Comment by sudiptpa** [comment]
Yep, look at README

Horizon requires Laravel 5.5, which is currently in beta, and PHP 7.1+. You may use Composer to install Horizon into your Laravel project

**Comment by marianvlad** [comment]
Add ```Laravel\Horizon\HorizonServiceProvider::class``` in providers.

**Comment by ybaruchel** [comment]
Sorry, the problem was that I didn't added the `Laravel\Horizon\HorizonServiceProvider::class` to providers.
