### ISSUE TITLE
Jobs continue to run after failure using a second queue created via horizon config

### ISSUE THREAD

**Issue by oniice** [laravel/horizon#602]
- Horizon Version: 3.2.1
- Laravel Version: 5.8.18
- PHP Version: 7.3.5
- Redis Driver & Version: predis/phpredis 1.1.1

### Description:
Jobs continue to run after failure using a second queue created via horizon config.

I want a separate long running queue for some jobs which run quite a while to be processed on. From my understanding (will happily do a PR to docs if my example is true) I can achieve this by creating another supervisor config, overwrite the `timeout` and name a queue in there?

When running a job on that queue, it is still timing out after ~90 seconds, which is the default from the redis setting in `queue.php`.
I have also tried creating a second redis connection in `queue.php` to see if that stopped the helped, but that doesn't fix it. The timeout issue is fixed though by setting it in `queue.php` - but the job still runs after it triggers failed.

That aside - the main issue that seems to be happening with a second supervisor queue is that a job still seems to keep running and doesn't terminate once the timeout is reached.

Horizon will fire the `Failed` event - I see that in the console and the `failed()` method is called doing what ever it needs to do - but what ever is happening in the `handle()` method will still run.

This **doesn't**  happen if there is only one supervisor config and the queues are in the same setup.

### Steps To Reproduce:

I created a second supervisor config in the `horizon.php` config file like this"

```
// config/horizon.php
'supervisor-2' => [
    'connection' => 'redis',
    'queue' => 'crawl',
    'balance' => 'simple',
    'processes' => 3,
    'tries' => 1,
    'timeout' =>  3600, // timeout after 1 hour
    'retry_after' => 3666 // retry_after after 1 hour
],

An example job that keeps running after the job has failed due to timeout
// SleepyJob.php
...
    public function handle()
    {
        while(true) {
            dump("sleeping...");
            sleep(10);
        }
    }
    public function failed(Exception $exception)
    {
        dump("failed =(");
    }
...
```

I used @themsaid's [blog](https://divinglaravel.com/introduction-to-how-laravel-horizon-works) about horizon to get the config properties.

**Comment by themsaid** [comment]
I've seen multiple queues running with the same configuration you shared without any issues. You'll need to double check your configs and make sure all is right.

Ping me if someone else is having the same issue, but so far you can have two supervisors running each with a different timeout value and it'll run just fine.

**Comment by oniice** [comment]
Hi @themsaid - I think it is a config issue...not knowing what configuration gets precedence for the `retry_after` value.

I maybe doing something completely wrong, but not matter what combination I do - setting a `retry_after` value in the `horizon` config, does not effect the queues retry value. 
Neither it appears does setting a `$retryAfter` value on the job model - it is always the base redis configuration value that is getting used.

Would it be possible to get a clearer explanation of what configuration/properties are used and take priority, so I can try and debug this a bit more?

**Comment by vlauciani** [comment]
> Neither it appears does setting a $retryAfter value on the job model - it is always the base redis configuration value that is getting used.

good question...

**Comment by shawnhind** [comment]
@vlauciani what is laravel-horizon 5.8?  Is there a separate branch for that and not just the normal horizon versions?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
