### ISSUE TITLE
Apache not starting when using horizon in Envoy

### ISSUE THREAD

**Issue by AngyNoT** [laravel/horizon#603]
- Horizon Version: 3.1.1
- Laravel Version: 5.8.14
- PHP Version: 7.2.18
- Redis Driver & Version: predis/predis 1.1.1

### Description:

I'm currently setting up continuous deployment on my server with Docker and using Envoy to trigger the following commands on startup: 
```
php artisan migrate --force
php artisan cache:clear
php artisan view:clear
php artisan config:clear
yarn run production
php artisan horizon
```

After Envoy is done running all these commands, my website shows a "Bad Gateway". 
Checking my logs I noticed that Apache was not starting correctly.

A few tries later, I was able to pinpoint that Horizon was causing it.
After removing the horizon line from my **Envoy.blade.php**, Apache starts correctly and I get these lines in my logs : 
```
[Thu May 30 13:58:22.010000 2019] [mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.25 (Debian) PHP/7.2.18 configured -- resuming normal operations
[Thu May 30 13:58:22.010711 2019] [core:notice] [pid 7] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Do you have any idea if that's an actual bug with Horizon or if I'm doing something wrong there?

Thanks

**Comment by driesvints** [comment]
I don't think this has anything to do with Horizon specifically but rather with your specific setup. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
