### ISSUE TITLE
Two replicas of horizon listen to same queues.

### ISSUE THREAD

**Issue by bagayollow** [laravel/horizon#617]
On GKE, I have two replicas of horizon for consuming queues faster, they listening to the same queues,I found out sometimes a job executed mutiple times at the same time. Is this expected to happen, or did I do something wrong?
The queue driver is redis, I am using redis sentinel service, the servers connected to the master directly by REDIS_HOST=redis-ha-master-svc

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
