### ISSUE TITLE
Failed Closure job causing UI to not show the details

### ISSUE THREAD

**Issue by ragingdave** [laravel/horizon#623]
- Horizon Version: 3.2.3
- Laravel Version: 5.8.24
- PHP Version: 7.2.18
- Redis Driver & Version: predis/phpredis 1.1.1

### Description:
When a failed closure job came up, it just caused the horizon UI on the failed job detail screen to not render properly.

This is the failed job response from the api:

    {
      "id": "38228",
      "connection": "redis",
      "queue": "test",
      "name": "Closure (function () use ($changelog) {\n            $changelog->delete();\n        }:2)",
      "status": "failed",
      "payload": {
        "type": "job",
        "timeout": null,
        "tags": {

        },
        "id": "38228",
        "data": {
          "command": "O:34:\"Illuminate\\Queue\\CallQueuedClosure\":9:{s:7:\"closure\";C:36:\"Illuminate\\Queue\\SerializableClosure\":461:{@E5hj7AjS6HrKKdFSHzO8TjB\/H8FHMgYk73Kf5iiuk2I=.a:5:{s:3:\"use\";a:1:{s:9:\"changelog\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:20:\"App\\Legacy\\Changelog\";s:2:\"id\";s:36:\"20181228\";s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";}}s:8:\"function\";s:74:\"function () use ($changelog) {\n            $changelog->delete();\n        }\";s:5:\"scope\";N;s:4:\"this\";N;s:4:\"self\";s:32:\"0000000037dba8e90000000016eede44\";}}s:23:\"deleteWhenMissingModels\";b:1;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}",
          "commandName": "Illuminate\\Queue\\CallQueuedClosure"
        },
        "displayName": "Closure (function () use ($changelog) {\n            $changelog->delete();\n        }:2)",
        "timeoutAt": null,
        "pushedAt": "1561471160.6005",
        "job": "Illuminate\\Queue\\CallQueuedHandler@call",
        "maxTries": null,
        "telescope_uuid": "8e03d562-a719-4f0a-8efc-38b93fb18ea3",
        "delay": null,
        "attempts": 1
      },
      "exception": "ReflectionException: Class Closure (function () use ($changelog) {\n            $changelog->delete();\n        }:2) does not exist in \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/CallQueuedHandler.php:120\nStack trace:\n#0 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/CallQueuedHandler.php(120): ReflectionClass->__construct('Closure (functi...')\n#1 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/CallQueuedHandler.php(45): Illuminate\\Queue\\CallQueuedHandler->handleModelNotFound(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Database\\Eloquent\\ModelNotFoundException))\n#2 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Jobs\/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)\n#3 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(327): Illuminate\\Queue\\Jobs\\Job->fire()\n#4 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(277): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))\n#5 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Worker.php(118): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))\n#6 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'sysx', Object(Illuminate\\Queue\\WorkerOptions))\n#7 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Queue\/Console\/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'sysx')\n#8 \/var\/www\/html\/project1\/vendor\/laravel\/horizon\/src\/Console\/WorkCommand.php(46): Illuminate\\Queue\\Console\\WorkCommand->handle()\n#9 [internal function]: Laravel\\Horizon\\Console\\WorkCommand->handle()\n#10 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(32): call_user_func_array(Array, Array)\n#11 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()\n#12 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))\n#13 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)\n#14 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(183): Illuminate\\Container\\Container->call(Array)\n#15 \/var\/www\/html\/project1\/vendor\/symfony\/console\/Command\/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#16 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))\n#17 \/var\/www\/html\/project1\/vendor\/symfony\/console\/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/var\/www\/html\/project1\/vendor\/symfony\/console\/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/var\/www\/html\/project1\/vendor\/symfony\/console\/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/var\/www\/html\/project1\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/var\/www\/html\/project1\/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 {main}",
      "failed_at": "1561472685.4882",
      "completed_at": null,
      "retried_by": [

      ],
      "reserved_at": "1561472685.4671",
      "index": 0
    }

and the console error from it:
    {name: "Parse Error", message: "Unknown key type ':' at position 571"}

### Steps To Reproduce:
Have a closure that references a deleted model, see the UI mark it as failed but not be able to determine the issue.

**Comment by driesvints** [comment]
Could you share the job itself?

**Comment by ragingdave** [comment]
the closure was just:

    function () use ($changelog) {
        $changelog->delete();
    }

This was getting dispatched in a chain and if the changelog didn't exist when the job ran the error above would be logged (which is already cryptic saying that Closure doesn't exist) and the UI would fail.

I have since converted this simple closure to just be a simple job class to avoid this by enabling using the deleteWhenMissingModels property which also resolves the issue, but just not getting to that state.

**Comment by devinfd** [comment]
I'm not sure how to help with this issue but I am getting the exact same error on this job: https://github.com/Maatwebsite/Laravel-Excel/blob/3.1/src/Jobs/ReadChunk.php

**Comment by ragingdave** [comment]
@devinfd I don't believe that's the exact same issue, as that job referenced is a full fledged job and not a closure. Additionally, the specific job view for a failed job just displays with a spinner in the closure case whereas your's sounds like it is at least still showing something.

**Comment by devinfd** [comment]
Sorry, it was midnight when I wrote that and couldn't think strait. So no, not the exact same issue/cause but yes the same result. All I get is the loading spinner and the console error:

```js
{name: "Parse Error", message: "Unknown key type ':' at position 56464"}
```

@patrickbrouwers since this is coming from a Laravel-Excel job perhaps you can shed some light?

**Comment by patrickbrouwers** [comment]
@devinfd Hm, haven't seen that issue yet with Horizon. Seems there's something in the payload that is specific for your import that Horizon doesn't like reading.

**Comment by devinfd** [comment]
Yea I agree. Unfortunately Horizon wont display the payload to help me debug the root problem in the job. Thanks anyway!

**Comment by patrickbrouwers** [comment]
Have you checked whats' in the failed_jobs table?

**Comment by pactode** [comment]
I am getting this error as well for a couple of failed jobs. All of them unrelated to Laravel Excel.

**Comment by devinfd** [comment]
@patrickbrouwers You asked a good question. I re-checked the failed_jobs table and soon realized that the serialized data in the payload column was malformed. To keep a long story short, apparently in Laravel v5.2 the payload column was changed from Text to LongText. (https://github.com/laravel/framework/commit/08f27292942aadabeb577557a16832305e4a655a#diff-d66424f36c15b26742f3dff4f86be980). This change was not documented in the upgrade guide and since then I (and perhaps many others) have been storing malformed serialized data. I fixed the column length which allowed me to see the actual ReadChunk error and get that fixed.

However the problem with Horizon not display the exception or payload never resolved. It still only shows the spinner with a Parse Error in the console.

**Comment by IgordeOliveira** [comment]
any update ?

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/horizon/commit/9c3a75a0f3cc1a2d1805f48c8aab49469cb4ab33

Thanks everyone

**Comment by mityukov** [comment]
Was it fixed in 3.x branch as well?

**Comment by ragingdave** [comment]
@mityukov It appears so based on the commit noted cross-referencing the code currently on 3.0 branch:https://github.com/laravel/horizon/blob/3.0/resources/js/screens/failedJobs/job.vue#L111 looks to be the same fix
