### ISSUE TITLE
Horizon should support both queue:listen and queue:work styles

### ISSUE THREAD

**Issue by travisaustin** [laravel/horizon#624]
When running Horizon with jobs that connect to a SOAP server (using `SoapClient`) or connect to AWS S3 using the AWS SDK for PHP, many connections are opened, used, and then left in the `CLOSE_WAIT` TCP state until Horizon is terminated. This is not a limitation of Horizon, but it would be really helpful to run Horizon like the command `queue:listen` does so that `CLOSE_WAIT` connections don't start to pile up. If Horizon job processes could end after each time they ran, any remaining TCP connections would be automatically be released after each job.

As it stands, we have to periodically restart Horizon to keep the number of open connections from hitting the open file maximum for the operating system (which then causes our jobs to fail until we restart Horizon). Restarting Horizon on a timer is a less-than-ideal solution, and I'd really like to run Horizon so that job processes die when complete and are not reused.

If I run the queues using queue:listen instead of using Horizon, the `CLOSE_WAIT` connections don't pile up and I don't have any issues.

I fully understand this is an issue with `SoapClient` and AWS S3 SDK at the core, but is there any possibility Horizon will support this configuration in the future?

Thanks!

**Comment by shawnhind** [comment]
We have the same problem and we restart horizon every 4 hours to get around this problem.

**Comment by driesvints** [comment]
I think if you can implement in a clean and non-breaking way that we're definitely open to a PR here.

**Comment by travisaustin** [comment]
Hey @shawnhind, we submitted a PR with this functionality. Feel free to give it a try!

**Comment by driesvints** [comment]
I'm afraid I'll have to close this because the PR for this was rejected. Please see Taylor's remark here: https://github.com/laravel/horizon/pull/626#issuecomment-507675354

**Comment by travisaustin** [comment]
I'm not sure if it's better to comment here on my issue, or on my PR, so I'm adding a note here to say I argued my position on the PR.

https://github.com/laravel/horizon/pull/626#issuecomment-507758257

**Comment by jes490** [comment]
If someone else needs this --once feature, you can do it like this without changing any vendor code (seems to be working): 

```php
// Add this code in any service provider (HorizonServiceProvider seems most fitting)

use Laravel\Horizon\SystemProcessCounter;
use Laravel\Horizon\WorkerCommandString;
use Illuminate\Queue\Listener;
use App\Console\Commands\HorizonListen;

// Register HorizonListen command (need to pass configured Listener class to it)
$this->app->when(HorizonListen::class)->needs(Listener::class)->give(function ($app) {
     return new Listener(base_path());
});

// Configure Horizon to run queue:listen instead of queue:work
WorkerCommandString::$command = 'exec @php artisan horizon:listen';
SystemProcessCounter::$command = 'horizon:listen';
```

And of course you'll need to create HorizonListen command like this (similar to HorizonWork): 

```php
<?php

namespace App\Console\Commands;

use Illuminate\Queue\Console\ListenCommand as BaseCommand;

class HorizonListen extends BaseCommand
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $signature = 'horizon:listen
                            {connection? : The name of connection}
                            {--delay=0 : The number of seconds to delay failed jobs}
                            {--force : Force the worker to run even in maintenance mode}
                            {--memory=128 : The memory limit in megabytes}
                            {--queue= : The queue to listen on}
                            {--sleep=3 : Number of seconds to sleep when no job is available}
                            {--timeout=60 : The number of seconds a child process can run}
                            {--tries=1 : Number of times to attempt a job before logging it failed}
                            {--supervisor= : The name of the supervisor the worker belongs to}';

    /**
     * Indicates whether the command should be shown in the Artisan command list.
     *
     * @var bool
     */
    protected $hidden = true;

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        if (config('horizon.fast_termination')) {
            ignore_user_abort(true);
        }

        parent::handle();
    }
}
```

Now you will have Horizon running like queue:listen.

**Comment by mattkingshott** [comment]
Fantastic!!! Thanks so much 👍🏻👍🏻

**Comment by mattkingshott** [comment]
Looks like a few additional arguments need to be supported, here's the revised signature:

```php
    protected $signature = 'horizon:listen
                            {connection? : The name of connection}
                            {--name=default : The name of the worker}
                            {--delay=0 : The number of seconds to delay failed jobs (Deprecated)}
                            {--backoff=0 : The number of seconds to wait before retrying a job that encountered an uncaught exception}
                            {--max-time=0 : The maximum number of seconds the worker should run}
                            {--max-jobs=0 : The number of jobs to process before stopping}
                            {--force : Force the worker to run even in maintenance mode}
                            {--memory=128 : The memory limit in megabytes}
                            {--queue= : The queue to listen on}
                            {--sleep=3 : Number of seconds to sleep when no job is available}
                            {--timeout=60 : The number of seconds a child process can run}
                            {--tries=1 : Number of times to attempt a job before logging it failed}
                            {--supervisor= : The name of the supervisor the worker belongs to}';
```

**Comment by jes490** [comment]
Yes, in my case signature was for Laravel 7.0 / Horizon 4.0. For Laravel 8.0 / Horizon 5.0 signature should be as above.

**Comment by Dysha96** [comment]
https://divinglaravel.com/avoiding-memory-leaks-when-running-laravel-queue-workers

**Comment by raimondsL** [comment]
`php artisan horizon:listen` works indeed, but this is as far as you can go. supervisor processes won't work.

**Comment by ahsankhatri** [comment]
Laravel 10 / Horizon 5.0 requires this option under signature as well

```
{--rest=0 : Number of seconds to rest between jobs}
```

**Comment by jason-silver-asics** [comment]
In my case I'm working with an older application that doesn't always clear state so using `queue:listen` is safer in the interim to ensure it's refreshed for each job.

An alternative override would be to keep horizon using `queue:work` and set `maxJobs => 1`.
The problem with that though is the `WorkerProcess` has a cooldown of 1 minute which is really long.
Any idea why it needs to have such a long cooldown?

**Comment by silverjason** [comment]
In my case I'm working with an older application that doesn't always clear state so using `queue:listen` is safer in the interim to ensure it's refreshed for each job.

An alternative workaround would be to keep horizon using `queue:work` and set `maxJobs => 1`.
The problem with that though is the `WorkerProcess.php` has a cooldown of 1 minute which is really long.
Any idea why it needs to have such a long cooldown?
