### ISSUE TITLE
Malformed Response for recent/failed jobs on binary data in payload/exception

### ISSUE THREAD

**Issue by ragingdave** [laravel/horizon#628]
- Horizon Version: 3.2.4
- Laravel Version: 5.8.26
- PHP Version: 7.2.18
- Redis Driver & Version: predis/phpredis 1.1.1

### Description:
If an exception or payload contains binary information, that will cause a Server Error and will cause the failed/recent jobs to not show any of the job information as result. As for the specific case, using any binary field in a model will cause this to happen if the data point by itself is in the payload or if the job has an exception that contains this binary information for example a failed insert containing the binary data in the stacktrace.

### Steps To Reproduce:
Have a job contain binary data or throw an exception containing binary information.

I was going to submit a PR, but was unsure if the solution would be to substitute the chars  on decoding the job information or just using something like JSON_INVALID_UTF8_SUBSTITUTE during json_decodes in the controllers of RecentJobs/FailedJobs.

**Comment by driesvints** [comment]
I think this is somehow related to https://github.com/laravel/framework/issues/28847 if I'm right and it seems to me that this is more of a framework problem than a Horizon problem?

**Comment by ragingdave** [comment]
While that might be something related in terms of UTF-8 handling I don't think that's the issue here.
For reference here is the stacktrace:

    [2019-07-02 02:27:08] production.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":16,"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75)
    [stacktrace]
    #0 /var/www/html/backend/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
    #1 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)
    #2 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(746): Illuminate\\Http\\JsonResponse->__construct(Array)
    #3 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Array)
    #4 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Array)
    #5 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #6 /var/www/html/backend/vendor/laravel/horizon/src/Http/Middleware/Authenticate.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #7 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Horizon\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #8 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #9 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #10 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #11 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #12 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #13 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #14 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #15 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #16 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #17 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #18 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #19 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #20 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #21 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #22 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #23 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #24 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #25 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #26 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #27 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #28 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #29 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #30 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #31 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
    #32 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
    #33 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
    #34 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
    #35 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
    #36 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
    #37 /var/www/html/backend/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #38 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #39 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #40 /var/www/html/backend/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #41 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #42 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #43 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #44 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #45 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #46 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #47 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #48 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #49 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #50 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #51 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #52 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #53 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
    #54 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
    #55 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
    #56 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
    #57 /var/www/html/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
    #58 /var/www/html/backend/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
    #59 {main}
    "}

Based on that, I would think that perhaps it is framework related, but specifically has to do with returning the jobs, and the possible binary characters in the exception stacktrace from a job containing sql that could have binary in it.

**Comment by rocramer** [comment]
In rare cases I am getting the same error. Could you find a workaround?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by rezen** [comment]
I've been running into this issue as well. As a quick test I updated Illuminate\Http\JsonResponse` to have a default options of `JSON_INVALID_UTF8_SUBSTITUT`. To cover the bases, if the horizon controllers returned `JsonResponse` with  `JSON_INVALID_UTF8_SUBSTITUTE` as an option this error wouldn't happen

**Comment by rezen** [comment]
An aside on `JSON_INVALID_UTF8_SUBSTITUTE`, it requires php 7.2+

**Comment by Propaganistas** [comment]
@driesvints This should be reopened as it's still an existing issue. I'm running into it as well.

**Comment by nckrtl** [comment]
Im running into this issue as well, also a mail job with an email attachment like @Propaganistas describes

**Comment by Propaganistas** [comment]
@driesvints Please reopen?

**Comment by nckrtl** [comment]
Workaround for me was to run `FLUSHDB` in redis-cli as removing/clearing the queue didn't work to get rid of the error.

**Comment by rezen** [comment]
My workaround in your app Http Kernel to switch out the router with a `CustomRouter`. The key was in the `CustomRouter` I used `JSON_INVALID_UTF8_SUBSTITUTE`. 

```php
<?php

namespace App\Http;

use App\Customized\CustomRouter;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    public function __construct(Application $app, CustomRouter $router)
    {
        $this->app = $app;
        $this->router = $router;
        $this->app['router'] = $router;
        $this->syncMiddlewareToRouter();
    }
```


```php
<?php

namespace App\Customized;

use \Illuminate\Routing\Router as BaseRouter;
use ArrayObject;
use Illuminate\Contracts\Support\{Arrayable, Jsonable, Responsable};
use Illuminate\Http\{JsonResponse, Response};
use Illuminate\Support\Traits\Macroable;
use JsonSerializable;
use Psr\Http\Message\ResponseInterface as PsrResponseInterface;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

class CustomRouter extends BaseRouter
{
    public static function toResponse($request, $response)
    {
        if ($response instanceof Responsable) {
            $response = $response->toResponse($request);
        }

        if ($response instanceof PsrResponseInterface) {
            $response = (new HttpFoundationFactory)->createResponse($response);
        } elseif ($response instanceof Model && $response->wasRecentlyCreated) {
            $response = new JsonResponse($response, 201);
        } elseif (! $response instanceof SymfonyResponse 
            && ($response instanceof Arrayable 
            || $response instanceof Jsonable 
            || $response instanceof ArrayObject 
            || $response instanceof JsonSerializable 
            || is_array($response))
        ) {
            $response = new JsonResponse($response, $status = 200, $headers = [], $options =  JSON_INVALID_UTF8_SUBSTITUTE);
        } elseif (! $response instanceof SymfonyResponse) {
            $response = new Response($response, 200, ['Content-Type' => 'text/html']);
        }

        if ($response->getStatusCode() === Response::HTTP_NOT_MODIFIED) {
            $response->setNotModified();
        }

        return $response->prepare($request);
    }
}
```

**Comment by cwilby** [comment]
> I've been running into this issue as well. As a quick test I updated `Illuminate\Http\JsonResponse` to have a default options of `JSON_INVALID_UTF8_SUBSTITUTE` and then the issue went away. To cover the bases, if the horizon controllers returned `JsonResponse` with `JSON_INVALID_UTF8_SUBSTITUTE` as an option this error wouldn't happen

Following this advice fixed failed requests to failed-jobs (https://github.com/cwilby/horizon/commit/32e37c0e017531d401e153ca6486a3983fa23567)
