### ISSUE TITLE
Progress information for jobs

### ISSUE THREAD

**Issue by tpetry** [laravel/horizon#630]
The functionality of Horizon is already very good and it is an indispensable part of Laravel Applications.

It would be very awesome to be able to show the current progress of jobs:

1. A queue job must derive from an abstract Horizon job class, so that the job ID in horizon is assigned to the job class. This abstract class will provide some functions to publish progress information like the [job status library](https://github.com/imTigger/laravel-job-status) to some redis structures horizon is in control of.

2. The Horizon dashboard must be updated to display this (optional) provided job status information.

3. it would be absolutely perfect if there was an API for Laravel to load the progress information for a horizon job so that it can be displayed in applications to users. An example would be showing the progress of a large video conversion job, a large import job etc.

**Comment by driesvints** [comment]
Feel free to do a proposal PR if you like but I'm unsure if this will get accepted.

**Comment by driesvints** [comment]
Going to close this for now because we're not going to work on it ourselves. We're still open to prs!
