### ISSUE TITLE
Horizon tries to load resources over HTTP on HTTPS

### ISSUE THREAD

**Issue by darki73** [laravel/horizon#631]
- Horizon Version: 3.2.5
- Laravel Version: 5.8.27
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis 1.1.1
- Database Driver & Version:

### Description:
Even though Horizon url is accessed through the HTTPS, it still tries to load the resources from the HTTP. The rest of application works just fine, Laravel Nova is also working fine. For some reason only Horizon fails to understand that if it is accessed through the HTTPS, then all resources must be loaded through HTTPS.
![Annotation 2019-07-07 161201](https://user-images.githubusercontent.com/1318627/60768942-a3037580-a0d2-11e9-8235-abb2d429c4f8.png)

Just a side note, Nova is loading resources from the relative path when horizon is trying to load resources from the absolute path (including domain name and protocol)

### Steps To Reproduce:

Install Traefik as reverse proxy, create a service with Nginx running on port 80, proxy container port 80 to real domain with valid SSL certificate, here comes that page
![Annotation 2019-07-07 161128](https://user-images.githubusercontent.com/1318627/60768888-fb864300-a0d1-11e9-8460-86a3627a6aa7.png)

**Comment by driesvints** [comment]
Are you behind a load balancer? Have you configured your trusted proxies correctly? https://laravel.com/docs/5.8/requests#configuring-trusted-proxies

**Comment by darki73** [comment]
This is the content of my `TrustProxies.php` middleware, no load balancing, no nothing.
![Annotation 2019-07-08 152541](https://user-images.githubusercontent.com/1318627/60809974-ac551680-a194-11e9-9940-10ffaf9222ff.png)


I (presumably) found a way to actually **Nova**_fy_ Horizon by changing:

**From (styles):**
```
<link href="{{ asset(mix($cssFile, 'vendor/horizon')) }}" rel="stylesheet" type="text/css">
```
**To**
```
<link href="{{ mix($cssFile, 'vendor/horizon') }}" rel="stylesheet" type="text/css">
```

**And (js) from:**
```
<script src="{{ asset(mix('app.js', 'vendor/horizon')) }}"></script>
```
**To:**
```
<script src="{{ mix('app.js', 'vendor/horizon') }}"></script>
```

This is pretty much how it is done in Nova, so from now on Horizon will try to fetch files from relative path rather than absolute

**Comment by driesvints** [comment]
I think you're correct. @themsaid do you also follow this reasoning?

**Comment by darki73** [comment]
I've made a pull request just in case this issue will actually go through
https://github.com/laravel/horizon/pull/635

**Comment by driesvints** [comment]
The PR was closed but I wanna look into this a bit more. Are you behind Cloudflare? Does Horizon properly loads if you disable its HTTPS enforcement?

**Comment by darki73** [comment]
I am just using the Cloudflare as DNS manager, however, none of the applications are under the cloudflare proxy. I am using Traefik as a reverse proxy and Horizon works just fine with the changes i've submitted in a PR.

**Comment by driesvints** [comment]
@darki73 Telescope currently works in exactly the same way as Horizon.

I think it's probably best that in this case you publish the view files and make the modifications yourself. That way you're at least up and running. Like you said, this probably won't work for everyone.

**Comment by od3n** [comment]
my current solution is to add ASSET_URL with https to .env

**Comment by 120dev** [comment]
fix for me : 

Add following string to AppServiceProvider::boot() method
\Illuminate\Support\Facades\URL::forceScheme('https');

**Comment by od3n** [comment]
> `\Illuminate\Support\Facades\URL::forceScheme('https');`

i tried but only works on horizon ^1.4, not ^3.4. 

may i know your horizon version?

**Comment by moyvera** [comment]
FYI
From my side I enabled my trusted proxies... That was it. It got solved.
My app is behind a load balancer (I added the internal network IP from the LB)
I'm using cloudflare, I wasn't having issues until I enabled cloudflare [polish](https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images)

I also tried with enabling for `*` all possible proxies and was still working all my app.

**Comment by LGZ1998** [comment]
This may not be the best practice, but setting .envASSET_URL=/. allows me to access normally

**Comment by slamannalespri** [comment]
Had the same issue and followed the Trusted Policy guideline. If you're on AWS, there's a warning in the following section as it needs a different header: https://laravel.com/docs/6.x/requests#configuring-trusted-proxies. If it's not working, then some headers might not pass properly to Laravel.

**Comment by cbloss** [comment]
> Are you behind a load balancer? Have you configured your trusted proxies correctly? https://laravel.com/docs/5.8/requests#configuring-trusted-proxies

This really saved me. This was my problem. Thanks for that!!
