### ISSUE TITLE
Horizon Terminate command not working properly 

### ISSUE THREAD

**Issue by liuk78** [laravel/horizon#632]
when i run supervisor command to Start a new supervisor and after i run terminate command to suspend horizon, then horizon kills all other process but not process added whit command supervisor.

This is the process before i run horizon:supervisor command, 
where there are the processes related to the supervisor inside the configuration file
![before](https://user-images.githubusercontent.com/52653012/60796314-6b95d700-a16d-11e9-90a9-26472ac38051.JPG)

This is the command thaht i run:
![command_supervisor](https://user-images.githubusercontent.com/52653012/60796417-9d0ea280-a16d-11e9-9c82-7a0a4100f70a.JPG)

This is the process status after command:
![after_command](https://user-images.githubusercontent.com/52653012/60796429-a435b080-a16d-11e9-9377-f829c3fefd77.JPG)

this is the process status after i run horizon:terminate
![after_terminate](https://user-images.githubusercontent.com/52653012/60796451-ad268200-a16d-11e9-8c61-768c85e487c5.JPG)

Why horizon:terminate doesn't kill the process added after my horizon:supervisor command?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
