### ISSUE TITLE
Issue when running php artisan horizon on multiple servers

### ISSUE THREAD

**Issue by matrad** [laravel/horizon#645]
Hello,

I'm running the command ```php artisan horizon``` on three servers - web01, web02 and web03. These names are also the hostnames of the servers.

My config looks like this:

```
    'environments' => [
        'live' => [
            'supervisor-default' => [
                'connection' => 'redis-sentinel',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
            ],
            'supervisor-local' => [
                'connection' => 'redis-sentinel',
                'queue' => [gethostname()],
                'balance' => 'simple',
                'processes' => 1,
                'tries' => 3,
            ],
        ],
    ],
```

It works all fine, but on the horizon-Dashboard sometimes I see the web01, sometimes the web02 and sometimes the web03 processes. It's changing time by time. The requests are balanced on all three servers, so supervisor-local has different configurations per hostname.

The problem is that I need one default-queue running on all servers to have HA, and one queue per server to perform local changes ect.

The only problem is the dashboard, the job-processing works fine.

How can I solve this?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
