### ISSUE TITLE
Allow customisation of options passed to binary PHP when adding a supervisor

### ISSUE THREAD

**Issue by CaelanStewart** [laravel/horizon#649]
Hi,

Since the Process class requires `proc_open` internally, I've had to enable it globally for a PHP version.

However, it would be good if I could configure extra options such as `-d disable_functions=` to the PHP binary.

So then, I can start `php -d "disable_functions=" artisan horizon`, and it can delegate permissions, in effect, to the processes spawned by Horizon.

I tried to:

```
$this->app->when(AddSupervisor::class)
            ->needs(SupervisorOptions::class)
            ->give(CustomSupervisorOptions::class);
```

So then I can override:

```
public function toSupervisorCommand()
{
    return SupervisorCommandString::fromOptions($this);
}
```

And call a custom implementation of the `fromOptions` static method to inject the options passed to the executable.

However, Laravel doesn't swap out the class. So I guess perhaps Laravel doesn't support binding a concrete class to another concrete derived class.

I don't know enough about Laravel's internals, nor have enough time to reverse engineer it effectively, to figure out why.

Or is this unnecessary, and I'm overestimating the potential danger of `proc_open` out of misunderstanding?

Thank you.

**Comment by driesvints** [comment]
Heya, thanks for your suggestion. I don't think we'll ever implement this level of customization into Horizon. If more people would request this then we might be able to work something in. However, if you can send in a PR which implements this in a really easy way then feel free to do so. Thanks.

**Comment by CaelanStewart** [comment]
@driesvints 

This doesn't occur to me to be a high level of customisation.

I mean literally a string config option in `horizon.php`, and that options' content is interpolated into the command string.

Very simple customisation, and a limited customisation at that, too.

Is there a particular technical reason why not? Because it seems that we should not have to enable `proc_open` globally just to run the Horizon process.

**Comment by driesvints** [comment]
@CaelanStewart we're not entirely opposed. I just closed this issue because it's not something we'd focus on. But you're free to send in a PR if you can implement it in a clean way.

**Comment by CaelanStewart** [comment]
@driesvints 

OK, that's fair enough.

Thank you for the prompt response.

**Comment by CaelanStewart** [comment]
@driesvints 

Hi,

I've figured out the error of my ways in my original attempt to override, and I've gotten the PHP arguments interpolated.

If I were to put together a pull request, bringing the changes from `app/Horizon/CustomSupervisorCommandString.php` to the original source file, do you think it would be accepted?

I don't want to put in the time if the way I've gone about it here would be considered inadequate for general usage.

Either way, I thought I've leave how I did it for anybody who happens upon this issue in future.
