### ISSUE TITLE
Can't middleware be used ?

### ISSUE THREAD

**Issue by tintnaingwinn** [laravel/horizon#65]
Is there any way to use middleware for route?

**Comment by themsaid** [comment]
For what purpose?

**Comment by tintnaingwinn** [comment]
For Authentication
```
Route::group(['middleware' => ['auth', 'auth.admin']], function() {
     Horizon::auth(function ($request) {
            return true;
     });
}
```

**Comment by themsaid** [comment]
Just use the `Horizon::auth` method in your service provider and decide using the given request object wether this user should have access to horizon or not:

```php
Horizon::auth(function ($request) {
            return $request->user()->is_admin;
        });
```

**Comment by tintnaingwinn** [comment]
$request->user() always return null
```
Horizon::auth(function ($request) {
            return $request->user(); // Null
        });
```

**Comment by jpmurray** [comment]
I was coming to report this also. I'm successfully logged in, but can't access user from the request object.

From the best of my knowledge, to get auth we need to have sessions enabled (they are in middlewares) and service providers are fired _before_ middlewares, no? Maybe @themsaid can confirm this, we might just be doing something wrong also...

**Comment by themsaid** [comment]
It's fixed now in the latest commit :)

**Comment by jpmurray** [comment]
Thank you @themsaid. Will definitely be checking how you can send logged user to a service provider in the source code now! ;-)

**Comment by themsaid** [comment]
You register a callback, and the Horizon calls it in a special middleware :)

**Comment by tintnaingwinn** [comment]
Thank you @themsaid. 👍

**Comment by gadhiamitul41** [comment]
Can you tell me which service provided to add the code in? 

$request->user() always return null

Horizon::auth(function ($request) {
            return $request->user(); // Null
        });

**Comment by tintnaingwinn** [comment]
@gadhiamitul41 waits stable version. It's fixed in the [useWebMiddleware](https://github.com/laravel/horizon/pull/68/commits/1317f543ba0025b01e3627e8138b0ceb708c6055) commit. You can play with 1.0.x-dev version.

**Comment by ninjaparade** [comment]
This commit https://github.com/laravel/horizon/pull/68/commits/1317f543ba0025b01e3627e8138b0ceb708c6055 does indeed solve the issue of the user being null, just curious what approach people are taking when you're authing is API based?

**Comment by jpmurray** [comment]
Surfing on what @ninjaparade says, it got me thinking: there is no way to redirect somewhere if a user isn't auth'ed, and it just throws an error page... Anyway to show something else?

**Comment by vdotgood** [comment]
@jpmurray While it'd be nice to have a simple `redirect` property in the horizon config (potential pull request) you could just catch this in the `App\Exceptions\Handler`. Drop this into your render method

    if($exception instanceof HttpException){
        if($exception->getStatusCode() == 403 && $request->is('horizon*')) return redirect('/');
    }

**Comment by stephenoldham** [comment]
@jpmurray While it'd be nice to have a simple `redirect` property in the horizon config (potential pull request) you could just catch this in the `App\Exceptions\Handler`. Drop this into your render method

    if($exception instanceof HttpException){
        if($exception->getStatusCode() == 403 && $request->is('horizon*')) return redirect('/');
    }

**Comment by jpmurray** [comment]
@stephenoldham good thinking!

**Comment by neorganic** [comment]
@stephenoldham  How did you defined $exception ??

**Comment by stephenoldham** [comment]
@neorganic You place the snippet of code above into the `render` method of your `App\Exceptions\Handler`

**Comment by lriggle-strib** [comment]
I ended up doing this in my AppServiceProvider:

```php
        Horizon::auth( function () {
            abort_unless( (
                auth()->guard()->user() instanceof User &&
                auth()->guard()->user()->isAdmin()
            ), 404 );

            return true;
        } );
```

I know the auth function produces an abort with a 403 code, but I wanted the horizon interface to stay unknown, not just undisplayed.

**Comment by vesper8** [comment]
I too wish there was a way to wrap the auth inside of a middleware

I want to use the jwt.auth middleware and right now am not sure how to proceed yet

**Comment by francislavoie** [comment]
So this is kinda hilarious. I found out that Horizon has an undocumented feature to solve this.

https://github.com/laravel/horizon/blob/1.0/src/HorizonServiceProvider.php#L54

Horizon does try to grab its list of middlewares from config. This isn't documented anywhere unfortunately.

You can simply add `'middleware' => ['web', 'auth'],` to your `config/horizon.php`.

**Comment by jofomah** [comment]
@francislavoie that works, thanks

**Comment by MajidAlaeinia** [comment]
This may help you.
https://stefanzweifel.io/posts/use-basic-authentication-to-protect-the-laravel-horizon-dashboard/

**Comment by jleonardolemos** [comment]
> So this is kinda hilarious. I found out that Horizon has an undocumented feature to solve this.
> 
> https://github.com/laravel/horizon/blob/1.0/src/HorizonServiceProvider.php#L54
> 
> Horizon does try to grab its list of middlewares from config. This isn't documented anywhere unfortunately.
> 
> You can simply add `'middleware' => ['web', 'auth'],` to your `config/horizon.php`.

This is stil undocumented. It seems way better than `Horizon::auth`. Is there any drawback?

**Comment by Sharifur** [comment]
> So this is kinda hilarious. I found out that Horizon has an undocumented feature to solve this.
> 
> https://github.com/laravel/horizon/blob/1.0/src/HorizonServiceProvider.php#L54
> 
> Horizon does try to grab its list of middlewares from config. This isn't documented anywhere unfortunately.
> 
> You can simply add `'middleware' => ['web', 'auth'],` to your `config/horizon.php`.

it worked but had to make ` protected function authorization(): void
    {
        Horizon::auth(function ($request) {
            return true;
        });
    }` in HorizonServiceProvider
