### ISSUE TITLE
Horizon stops consuming jobs when run with queue:work in supervisord

### ISSUE THREAD

**Issue by hungtt57** [laravel/horizon#650]
- Horizon Version: 1.2
- Laravel Version: 5.6
- PHP Version: 7.2
- Redis Driver & Version: predis
- Database Driver & Version:

### Description:
I run laravel in 2 server,
in each server, i setup supervisor run 2 program: 
  - php artisan queue:work
  - php artisan horizon
![Screenshot from 2019-08-20 11-29-17](https://user-images.githubusercontent.com/13230565/63317649-d118de00-c33d-11e9-8895-08e44ce52a47.png)

Normally, it works. Sometime when server has a lot of jobs,  server stops consuming jobs.
All job is pending, new jobs is pending.
And i must restart supervisord, it works again.
How can i fix that? Can i run queue:work and horizon together in supervisord?

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
