### ISSUE TITLE
Horizon can't be stopped in a distributed scenario

### ISSUE THREAD

**Issue by renanwilliam** [laravel/horizon#654]
- Horizon Version: 2.2.1
- Laravel Version: 5.8.30
- PHP Version: 7.2.15
- Redis Driver & Version: predis/phpredis 5.[02
- Database Driver & Version: MySQL 5.7.23

### Description:
In a distributed scenario, the command `php artisan horizon:terminate` don't finish all supervisor process, only if it runs on the machine that is supervisor is running.

I have a application running in AWS using the 'microservice' model, like image bellow:
![Imgur](https://i.imgur.com/a8Nsn8P.png)

The mains services in infrastructure can be resumed like:
- A Nginx service to serve Larave pages
- A PHP-FPM service to upstream 
- A Horizon service for queues and jobs

Each service have autoscaling policies based on CPU/Memory metrics.

The problem is when I need to deploy a new applications version. Before a deploy starts it is necessary do a soft exit in all Horizon process - to not kill current running process.

Currently we use AWS CodePipeline for that:
![Imgur](https://imgur.com/f8G1Rjt.png)

The only way is setup a manual step, verify how many containers are running Horizon and stop each one manually. When I run php artisan horizon:terminante in any container it is supposed to be send a terminate signal to all workers.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
