### ISSUE TITLE
Recurring Allowed memory size exhausted exception

### ISSUE THREAD

**Issue by devinfd** [laravel/horizon#655]
- Horizon Version: 3.3.1
- Laravel Version: 5.7.28
- PHP Version: 7.2.0-2+ubuntu16.04.1+deb.sury.org+2
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version:

### Description:
For the past 18 hours I have been trying to diagnose a Symfony FatalErrorException, Allowed memory size of 536870912 bytes exhausted that occurs every ~2 minutes. The exception stack has this server arg ```["artisan", "horizon:work", "redis", "--delay=0", "--memory=512", "--queue=report-generation", "--sleep=3", "--timeout=60", "--tries=5", "--supervisor=wrmd-worker-temple-8RYS:supervisor-2"]``` which lead me to Horizon. I can stop the exceptions from happening if I call ```horizon:pause``` but ```horizon:continue``` also continues the exceptions. I also deleted all failed jobs in case one was stuck in the queue but that made no change.

### Steps To Reproduce:
I have no idea why this is happening and therefore don't know how to reproduce it. I am at a loss of ideas

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
