### ISSUE TITLE
php lock

### ISSUE THREAD

**Issue by zoryamba** [laravel/horizon#66]
i have an issue. understand, that it's about my configuration, but i can't get with it.
when running horizon it lock the php, so it can not work on other tasks. tried via both apache and cli.
php interactive shell (php -a) works. but when i want to run some php file - it doesn't
when i terminate the horizon all php task get processed.

im running horizon on my macbook, have apache 2.4 with mpm prefork module installed via home brew. php 7.1. laravel 5.5 upgraded from 5.2.

**Comment by jbrooksuk** [comment]
You need to run Horizon under a process monitor, like Supervisor.

**Comment by zoryamba** [comment]
same behavior... 
in both cases horizon itself works fine. starts 3 processes and handles jobs.

 5613 ??         0:01.76 php ./artisan horizon
 5622 ??         0:02.80 php artisan horizon:supervisor Zorias-MacBook-Pro.local-HEVR:supervisor-1 redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=0 --balance=simple --max-processes=1 --min-processes=1
 5629 ??         0:00.93 php artisan horizon:work redis --delay=0 --memory=128 --queue=default --sleep=3 --timeout=60 --tries=0 --supervisor=Zorias-MacBook-Pro.local-HEVR:supervisor-1

also simple artisan command queue:work works fine

**Comment by zoryamba** [comment]
also i'm using sphp script to switch php versions. installed it by instruction posted [here](https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions) . may it cause problem??

**Comment by themsaid** [comment]
> it lock the php

How does it look PHP? I don't understand your concern.

**Comment by themsaid** [comment]
ping @zoryamba

**Comment by zoryamba** [comment]
when i'm running file with php cli, just like `php filename.php `, it does nothing. just waiting. when i terminate horizon - it starts working.
same behavior i saw when sending two requests from browser with same session id. if session file is locked by one process - another process waits while it gets free.

i figured out that problem occurs when i have failed jobs in horizon. think problem in my failed jobs config. i have no database in my project, just redis. can anyone help me how to configure failed jobs with redis?

**Comment by themsaid** [comment]
You need to have a table in the DB to store failed jobs.

Horizon shouldn't be blocking anything, you need to check your system log files to see what's going on, I can't think of a specific issue. But while running horizon I can do other tasks as needed.

**Comment by zoryamba** [comment]
is it really impossible to configure failed jobs to work with redis?? o_O

**Comment by dpde** [comment]
Have a look here:
https://laravel.com/docs/5.4/queues#dealing-with-failed-jobs

What is the problem with saving them into a database?
Redis is a in memory database. From my point of view, it does not really make a lot of sense to store data you want to keep in redis.

Besides that is redis a key-value storage and the failed jobs table is a bit more complex.

**Comment by tillkruss** [comment]
I know this is off-topic, but I'd also like to see failed jobs stored in Redis 🙂

**Comment by themsaid** [comment]
Going to close this issue since it's getting nowhere, please continue the discussion of the failed jobs thing in the forums :)
