### ISSUE TITLE
Symlinked app in sub-directory breaks Horizon AJAX

### ISSUE THREAD

**Issue by rk** [laravel/horizon#660]
- Horizon Version: 3.3.2
- Laravel Version: 5.8.35
- PHP Version: 7.2.19
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version: MySQL 5.7

### Description:

It appears that installing an app into the subdirectory of a domain will break Horizon. Our routes are all prefixed by `shop/...`, and we set the `APP_URL` config parameter accordingly. 

When `APP_URL=http://mytest.localhost/shop` it appears that:

https://github.com/laravel/horizon/blob/692d3649a9c1bd13a3340ecc10036c1d3b55155b/resources/js/app.js#L26-L30

Will assume that the application is installed at the top-level of the domain. All routes will be registered correctly, but the JS front-end will drop the "/shop/" prefix from all its generated URLs.

I don't know if this is the only area, but it's what I've found so far.

### Steps To Reproduce:

Assuming your environment uses `test.localhost` as your testing domain...

**.env**

    # Add a subdirectory to generated URLs
    APP_URL=http://test.localhost/shop

**Your apache/nginx**

We symlink the `shop` directory to the app's public folder at another location. This is required for our use case.

**Then:**

1. Install horizon
2. Deploy assets
3. Go to: `http://test.localhost/shop/horizon`
   - I see the sidebar layout, no dashboard without clicking "Dashboard".
4. Open the Web Inspector
5. Click "Dashboard" or any of the links
6. Note all the AJAX requests 404 because they go to `/horizon/...` instead of `/shop/horizon/...`

Edit: bullet formatting

**Comment by driesvints** [comment]
We unfortunately don't support installing Laravel in a subdirectory.

**Comment by ultrablue** [comment]
Hi, Dries:

> We unfortunately don't support installing Laravel in a subdirectory.

Did you mean Horizon instead of Laravel?

We're having a similar issue, and I'm going to have to explain the problem to my management and systems teams. Can you tell me what's happening here?

It seems like Horizon's config path value was implemented for just this occasion? Am I missing something. Thanks!

Greg

**Comment by rk** [comment]
@ultrablue From my experience, Laravel has no issues installing and running in a subdirectory. The same app I asked this about has been running in a subdirectory (**happily**) ever since.

This appears to be an issue with Horizon, and an intentionally chosen one. I don't understand it either, but it appears to be a `#wontfix`type issue.

**Comment by matejsvajger** [comment]
@driesvints are you open to a PR that would fix this?

It seems to me Laravel is perfectly capable of resolving the base path (mix, asset, route, ..) when you symlink its' public folder to a custom folder positioned in web servers' public root.

We're running production Laravel apps in "subfolders" for years without any problems.

I'd be happy to contribute a change that would make horizon run there as well.

**Comment by driesvints** [comment]
I don't think we'll be accepting a PR to this, sorry.

**Comment by matejsvajger** [comment]
That's too bad, thanks for the quick reply 'tho! 👍 

For anyone else stumbling upon this, one can always make their over version of `Laravel\Horizon\Http\Controllers\HomeController` in their app, change implementation of index function and bind that in the container to the packages' controller.

**Comment by ahsankhatri** [comment]
To enable functionality in sub-directories, I've devised an approach that eliminates the need to modify the `window.Horizon.path` value directly. Instead, we can achieve the desired effect by overriding `window.Horizon.basePath` within the `public/vendor/horizon/app.js` file.

This can be accomplished by replacing the code `window.Horizon.basePath="/"+window.Horizon.path` with

```js
window.Horizon.basePath=document.location.pathname.replace(new RegExp(window.Horizon.path+'.*$'), '')+window.Horizon.path
```

Please be aware that when migrating to a new Horizon version, it might be necessary to run `php artisan horizon:publish` to apply these changes. However, keep in mind that doing so may result in the loss of this particular tweak.
