### ISSUE TITLE
Horizon is duplicating the asset host due to assets declaration in blade templates

### ISSUE THREAD

**Issue by alexandrecruz** [laravel/horizon#661]
### Description:
According to Laravel docs for [`asset()`](https://laravel.com/docs/5.8/helpers#method-asset), we can use `ASSET_URL` to replace current domain with a custom one for assets (usually when using CDN for example).

Horizon views are declaring assets like this in the blade views:
`<link rel="stylesheet" href="{{ asset(mix('path/to/file.css')) }}" />` which causes issues when using MIX_URL (used by Mix to set host) or ASSET_HOST.

### Steps To Reproduce:

When checking the CLI, here is the output:

```bash
mix('css/app.css')
``` 
-> return https://xxxxx.cloudfront.net/css/app.css?id=9368b37e21a511e47a02

```bash
asset('css/app.css')
```
-> return https://xxxxx.cloudfront.net/css/app.css (no hash from manifest)

```bash
asset(mix('css/app.css'))
```
-> return https://xxxxx.cloudfront.net/https://xxxxx.cloudfront.net/css/app.css?id=9368b37e21a511e47a02

### Additional Details
- Horizon Version: 3.3.2
- Laravel Version: 5.8.34
- PHP Version: 7.1.12

### Discussion

- Should Horizon declare assets in another way?
- Are there any configs on the project-side that should be considered as well? Like Mix config, webpack, anything else? (URL generation is backend only as far as I could test and no JS/post processing is changing it)
- Something else I am missing?

Thanks :)

**Comment by driesvints** [comment]
Can't you set `MIX_HOST` to something empty?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
