### ISSUE TITLE
Failed jobs don't go away after successful retry

### ISSUE THREAD

**Issue by mityukov** [laravel/horizon#668]
- Horizon Version: 3.3.1
- Laravel Version: 5.8.33
- PHP Version: 7.3.8
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version: redis-cli 5.0.5 (not sure how to get version of the Redis RDBM itself) & MySQL 5.7.21

### Description:

After clicking <Retry> on a failed job in horizon UI, the following happened:
- The job was re-run (this time successfully)
- There is a record with "Completed" status in the "Recent Retries" section of the "Failed job details" page

(ok, so far)

The job, however, is not removed from Failed jobs list (althouh, "retry" ison is not longed displayed near successfully retried ones).

Also, the job's still present in the `php artisan queue:failed` output.

Is it expected behavior? I can see there are two options in the config: `horizon.trim.recent_failed` and `horizon.trim.failed`, but to my understanding these options should affect failed (and not successfully retried since then)  jobs only…

**Comment by mityukov** [comment]
Forgot to add: to my understanding, successfully retried job should be either
a). removed from the list of failed jobs
-- or --
b) somehow distinctly marked that "it's not a liability already".

And it definitely should be removed from `php artisan queue:failed`.


P.S.: What is the difference between `horizon.trim.recent_failed` and `horizon.trim.failed` anyway?

**Comment by driesvints** [comment]
I have no idea myself anymore. So much has changed with recent prs. @themsaid any ideas?

**Comment by driesvints** [comment]
okay so the `horizon.trim.recent_failed` is the expiration for the number on the dashboard while the `horizon.trim.failed` is the expiration for the failed jobs tab. 

As in regard of your question: it's indeed normal that failed jobs stay in the list until they've reached their expiry time. This is for reference purposes.

**Comment by dimer47** [comment]
hi @driesvints

I'm not quite clear on the rationale for keeping a retried job for reference.

If the retried job fails again, it will be put back into the failed jobs list, and if it's successful, that's great as we have completed all the necessary jobs. What's the benefit here? Am I missing something? Could you please clarify this for me?

cc @mityukov
