### ISSUE TITLE
how to monitor job system

### ISSUE THREAD

**Issue by wuaier6** [laravel/horizon#67]
Now , I created the new system as  horizon system . but i want to don't change my old system 's code.    in new system  , I operated the command "php artisan horizon".  now  I created a job  in the old system.  but  this job is operated in the new system.  I just want to use the horizon system as a monitor system. Do you have some solutions .

**Comment by themsaid** [comment]
I don't understand what you are saying, what do you mean by the old system?

**Comment by richardkeep** [comment]
I presume, by old system, he means an existing Laravel project.

**Comment by themsaid** [comment]
1. Put app in maintenance mode
2. Let old workers finish all existing jobs
3. Configure horizon and start it
4. Remove maintenance mode

That's what I'd do, you need to make sure your old jobs are finished before moving to horizon.

**Comment by sebestenyb** [comment]
I assume we need to change the existing supervisord config as well, removing the existing workers, and add the horizon one?

**Comment by themsaid** [comment]
@sebestenyb yes.
