### ISSUE TITLE
Installation fails with Laravel 6

### ISSUE THREAD

**Issue by travisbotello** [laravel/horizon#674]
- Horizon Version: 3.3
- Laravel Version: 6.0
- PHP Version: 7.3.9
- Redis Driver & Version: phpredis 5.0.2

### Description:
After running `composer require laravel/horizon` I am receiving the following output:

```
$ composer dump-autoload
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Horizon.php line 100:

  Redis connection [] has not been configured.


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

My redis connection is working as session and cache driver.

### Steps To Reproduce:
Run `composer require laravel/horizon` or either `composer dump-autoload` after you added Horizon.

**Comment by travisbotello** [comment]
My bad...I forgot to manually add `horizon.php` to config folder...sorry

**Comment by martinschenk** [comment]
i have exactly the same error.
I installed redis with

    brew install redis
