### ISSUE TITLE
Unable to insatll on freash Laravel 5.5, 5.6 versions

### ISSUE THREAD

**Issue by davodavodavo3** [laravel/horizon#677]
Hi to all.
I have a problem by installing the Horizon on Laravel.

Using php version `7.1.32`.
Command that is executed `composer require laravel/horizon`

I have tried to install it on fresh Laravel 5.5 and 5.6 but getting 

On version 5.5
` illuminate/queue v6.0.4 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.3 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.2 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.1 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.0 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - Conclusion: remove laravel/framework v5.5.48
    - Conclusion: don't install laravel/framework v5.5.48
    - laravel/horizon v3.3.0 requires illuminate/queue ~5.7.0|~5.8.0|^6.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - laravel/horizon v3.3.1 requires illuminate/queue ~5.7.0|~5.8.0|^6.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - laravel/horizon v3.3.2 requires illuminate/queue ~5.7.0|~5.8.0|^6.0|^7.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
`

On version 5.6
`
- illuminate/queue 7.0.x-dev requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
- illuminate/queue v6.0.4 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
- illuminate/queue v6.0.3 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.2 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.1 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue v6.0.0 requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - illuminate/queue 6.x-dev requires php ^7.2 -> your PHP version (7.1.32) does not satisfy that requirement.
    - Conclusion: remove laravel/framework v5.6.39
    - Conclusion: don't install laravel/framework v5.6.39
    - laravel/horizon v3.3.0 requires illuminate/queue ~5.7.0|~5.8.0|^6.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - laravel/horizon v3.3.1 requires illuminate/queue ~5.7.0|~5.8.0|^6.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - laravel/horizon v3.3.2 requires illuminate/queue ~5.7.0|~5.8.0|^6.0|^7.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, 7.0.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
`

On the same environment Horizon installation on Laravel 5.7 and 5.8 is successful.

So how to install it on 5.5 and 5.6?

**Comment by driesvints** [comment]
We don't support these versions anymore.
