### ISSUE TITLE
Notification: Long Wait Detected - solved

### ISSUE THREAD

**Issue by m-bosch** [laravel/horizon#684]
There is a great feature that notifies when a job need our attention for `Long Wait Detected`.

It would be great there will be also a notification when the `Long Wait Detected` is resolved.

**Comment by driesvints** [comment]
Hmm, that could be cool I guess but it'd involve setting up websockets to display it. Could maybe be done in combination with https://github.com/laravel/horizon/issues/266

**Comment by driesvints** [comment]
Going to close this as we've only received one request for this. Sorry.
