### ISSUE TITLE
Horizon suddenly stoped

### ISSUE THREAD

**Issue by saeedvaziry** [laravel/horizon#685]
- Horizon Version: 3.2
- Laravel Version: 5.7
- PHP Version: 7.2
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: MSSQL

### Description:

Suddenly horizon stopped on production server with this error

    The process "exec ps axo %cpu,%mem,command | grep horizon:work | grep "supervisor=pw-4w7O:supervisor-telegram" | grep -v "exec ps axo"" exceeded the timeout of 60 seconds. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"exec ps axo %cpu,%mem,command | grep horizon:work | grep \"supervisor=pw-4w7O:supervisor-telegram\" | grep -v \"exec ps axo\"\" exceeded the timeout of 60 seconds. at /home/pay/www/vendor/symfony/process/Process.php:1236)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by saeedvaziry** [comment]
This is an unusual error. that's because i opened issue here.
Thanks

**Comment by cerw** [comment]
I am having same issue even that the timeout=900

``` exceeded the timeout of 60 seconds.```
