### ISSUE TITLE
Update icons in UI to differentiate between reserved and pending jobs

### ISSUE THREAD

**Issue by Muffinman** [laravel/horizon#686]
I feel it would be really handy if the UI had different icons to differentiate between reserved and pending jobs. At the moment it's not straight forward to tell which jobs are running and which are waiting.

For longer-running tasks this would be really handy.

**Comment by JayBizzle** [comment]
This would be useful.

Do you think it would require a new icon or just a different colour of the current `pause` icon?

**Comment by driesvints** [comment]
Sounds good. Feel free to PR.

**Comment by Muffinman** [comment]
Blue?
![blue](https://user-images.githubusercontent.com/1319568/66756173-57125a80-ee91-11e9-9021-9665badffba7.gif)

Or Purple?
![purple](https://user-images.githubusercontent.com/1319568/66756174-57aaf100-ee91-11e9-8662-aad6ad401702.gif)

Subjectively I prefer the bootstrap blue, but I know that purple is used in other places where jobs are running (e.g. retying failed jobs.)

**Comment by JayBizzle** [comment]
I like it, where did that animated spinner icon come from?

Blue works for me!

**Comment by JayBizzle** [comment]
Although, perhaps it could stay the same colour as `pending` and use the animation as the differentiator?

**Comment by Muffinman** [comment]
@JayBizzle I took the existing `retry` and `complete` icons and used parts of both. 😄 

I was not sure about using the existing pending colour, as when scanning down lots of jobs it would be nice if they stood out?

Anyone else have thoughts?

**Comment by JayBizzle** [comment]
I guess we need to decide 2 things...

1. What icon to use
2. What colour that icon should be

**Comment by piotrgrabowskielastique** [comment]
> I guess we need to decide 2 things...
> 
> 1. What icon to use
> 2. What colour that icon should be

very difficult question...

**Comment by driesvints** [comment]
PR is merged.
