### ISSUE TITLE
How to configure timeout retry time

### ISSUE THREAD

**Issue by hookover** [laravel/horizon#689]
laravel version: 5.7
php version: 7.3

Log: 
```
[2019-10-15 11:02:26] STA.ERROR: App\Jobs\CallCenter\VoiceToTextJob has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\CallCenter\\VoiceToTextJob has been attempted too many times or run too long. The job may have previously timed out. at /opt/webroot/collect_admin/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:401)

```

I have a mission that takes more than 200 seconds. Jobs in queue may be executed more times. I had try to set the 'retry_after' configure.

I make an interface to trigger the Job and request it once.
From the console log, I found that the job run without stop.

the Job code is: 

```
public function handle()
    {
        dump($this->chainQueue . $this->queue . $this->delay);
        sleep(120);
        return;
}
```
horizon config:
```
 'waits' => [
        'redis:default'       => 60,
        'redis:voice_to_text' => 3600,
        'voice_to_text:voice_to_text' => 3600,
        'voice_to_text' => 3600,  //how can config ?
    ],

 'local' => [
            'supervisor-3' => [
                'connection'    => 'redis', // or 'voice_to_text'
                'queue'         => ['voice_to_text'],
                'balance'       => 'auto',
                'processes'     => 3,
                'tries'         => 0,
                'min-processes' => 1,
                'memory'        => 256,
                'timeout'       => 3600,
            ],
        ],
```

config\queue.php config:
```
'connections' => [
        'redis' => [
            'driver'      => 'redis',
            'connection'  => 'default',
            'queue'       => 'default',
            'retry_after' => 90,
        ],

        'call' => [
            'driver'      => 'redis',
            'connection'  => 'default',
            'queue'       => 'default',
            'retry_after' => 0,
        ],

        'voice_to_text' => [
            'driver'      => 'redis',
            'connection'  => 'default',
            'queue'       => 'default',
            'retry_after' => 0,
        ],
    ],
```
I try to set retry_after time, but it seems not usable.

I just want to let the job execute only once. can u help me to handle it please.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
