### ISSUE TITLE
Call to a member function hmset() on boolean

### ISSUE THREAD

**Issue by popfaker** [laravel/horizon#693]
- Horizon Version: v2.2.2
- Laravel Version: 5.5.x-dev
- PHP Version: 7.2.17
- Redis Driver & Version: phpredis 3.0.6
- Database Driver & Version: mysql 5.7.20

### Description:
Hi,
I use the horizon in a production environment, and it works well.
But yesterday I changed the redis server, and the error log of horizon appeared in `laravel.log`. I am not sure what the impact will be, I want to know why the error occurred and how to fix it.

The redis queue is now working properly
![image](https://user-images.githubusercontent.com/38718383/67365748-c7f9f680-f5a4-11e9-8fd7-3aee042a1ab6.png)

thank you
```
production.ERROR: Call to a member function hmset() on boolean {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function hmset() on boolean at /mnt/www/telrobot-saas/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php:117)
```
### Steps To Reproduce:
Redis server has been changed. The original redis server is built locally, while the current redis is connected through the external network

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by chenjianeng0201** [comment]
@driesvints

**Comment by chenjianeng0201** [comment]
@driesvints hi, i get the same problem on my system, i use laravel 6.0 lts, its first occured on yesterday, but i dont do any change on that time, now its still error
