### ISSUE TITLE
The suspended Job disappeared without execution

### ISSUE THREAD

**Issue by hookover** [laravel/horizon#697]
dev env:
```
php 7.2
laravel 5.7
horizon:2.0
```

code:
```
class TestJob()
{
      private $id;
      public __construct($id, Carbon $delay_at) {
             $this->id = $id;
             $this->delay($delay_at);
      }

      public function handle()
     {
             $staus = $this->doWork($this->id);
             if($status != true) {
                    dispatch(new TestJob($this->id, now()->addDays(1));  // Add a new Job, and delay execution by one day
              }
      }

      private function doWork($id) {
                return false;
      }
}
```
php artison tinker
```
>>>dispatch(new TestJob(1,now()));
```
Horizon Recent Jobs:

|Job|Tags|On|Queued At| Runtime|Status|
|----|---|----|-----------|---------|-------|
|TestJob|id:1,delay_at:19-10-28 14:31:04|test_queue|19-10-28 14:31:04|0.02|success|
|TestJob|id:1,delay_at:19-10-29 14:31:05|test_queue|19-10-28 14:31:05|0.02|pending|

In about two hours, the second piece of data will be lost, and no data about the task can be found in Redis

This question has been bothering me for a long time, please help me

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
