### ISSUE TITLE
Redis operation conflicts with horizon

### ISSUE THREAD

**Issue by tanghang55** [laravel/horizon#699]
In my project, the middleware USES redis operations, (db not equal to 0), and then USES Job::dispatch($log)->onQueue('order '); The state displayed on the horizon page is all pending. I found that redis db 0 has queue related information. You put code on the middleware and let reds initialize it
$this - > rDB = 0;
$this - > rKey = 'test';
$this - > rGet ();
The queue is then used normally. Hope you can avoid this problem in the source code. Now I can only do one more redis query to solve this problem
Thank you, boss!

Thanks!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
