### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by andrepaes** [laravel/horizon#703]
Hello. I've been using laravel horizon at my current project and it's been working fine but without any apparently reason, the horizon dashboard stopped working and only show a blank page, the title, and the favicon.
On chrome console, show it:
![Captura de Tela 2019-11-11 às 16 38 10](https://user-images.githubusercontent.com/12038420/68615425-cf286c00-04a1-11ea-9e38-ade4b147239d.png)
And inside app.js show it:
![Captura de Tela 2019-11-11 às 16 38 51](https://user-images.githubusercontent.com/12038420/68615461-e1a2a580-04a1-11ea-99ab-014997afcb99.png)
I now that some related issues was created but no one offer a solution for this problem.
Can anyone help me?
Thanks in advance@

**Comment by mfn** [comment]
Have you upgraded horizon without publishing the assets, `php artisan horizon:assets`?

**Comment by andrepaes** [comment]
@mfn Interesting, i tried to publish the assets using in other way. This way worked for me. Thanks!
