### ISSUE TITLE
Horizon dashboard 500 error when caching Laravel's config files with php artisan config:cache

### ISSUE THREAD

**Issue by naillizard** [laravel/horizon#705]
- Horizon Version: ^3.4
- Laravel Version: 5.8.*
- PHP Version: 7.3.8-1+ubuntu18.04
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version: mysql 8

Forge server

### Description:
After running ```php artisan route:cache``` causes 500 error on horizon dashboard
```
{
    id: "internal_server_error"
    message: "The server encountered an internal error or misconfiguration and was unable to complete your request."
}
```

### Steps To Reproduce:
installed horizon as per instructions, deployed application to server (we use forge and envoyer.io), these are the deployment hooks.

after composer install:
php artisan config:cache
php artisan route:cache

before activate new release:
php artisan migrate --force
php artisan horizon:terminate

Then, after deployment logging in with the user that has permissions to view horizon's dashboard, I get a 500 error as above.

SSH into the server and running ```php artisan config:clear``` solves the problem.

One more piece of information that could be important:

there are two sites running on the server, a production and staging versions.
I run a daemon for each in forge inside each app directory, each has a different HORIZON_PREFIX so in theory it should work? Any feedback regarding this is also appreciated, should I run only one instance per server? if all applications have the same "queue" naming etc?

Anyone else experienced anything like it?

**Comment by mfn** [comment]
> id: "internal_server_error"
> message: "The server encountered an internal error or misconfiguration and was unable to complete your request."

There has to be some log / more details what this is about. Maybe temporary enable `APP_DEBUG` to get more information.

**Comment by naillizard** [comment]
I’ll investigate this further when I get the chance, probably something wrong with the environment.
