### ISSUE TITLE
Filter incompleted failed jobs

### ISSUE THREAD

**Issue by olivernybroe** [laravel/horizon#707]
After changing to Horizon we had a lot of jobs failing which didn't fail before, so this means our failed jobs table is getting a lot of entries.

We can easily retry them from the UI, however going through 4-5 pages and finding which failed jobs has been retries and which hasn't is pretty tiresome. 

I would be awesome if we could filter away all the failed jobs which has been completed, so we only have a list of the failed jobs we need to handle still.

**Comment by driesvints** [comment]
Feel free to attempt a PR.

**Comment by olivernybroe** [comment]
An easy solution for this could be to create a new set with all incompleted failed jobs and then just get the id's from this set instead. 

However this won't work when searching by tag at the same time as filtering for incomplete only, which for my use case is not a problem. 

Regarding the UI if it's acceptable that you cannot search by tag while filtering. This could be done as simple as just using the tag searching field for filtering to incomplete jobs only.
![image](https://user-images.githubusercontent.com/5870441/69223468-b2fc8d00-0b7b-11ea-8dc8-43c847527f41.png)

**Comment by driesvints** [comment]
Going to close this as we've only received one request for this. We're still open to PRs.
