### ISSUE TITLE
Dashboard Authorization not working

### ISSUE THREAD

**Issue by InvokerMaster** [laravel/horizon#711]
- Horizon Version: 3.4
- Laravel Version: 6.5
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis 5.0.5
- Database Driver & Version: MySQL 5.7.28

### Description:
```
Horizon::auth(function ($request) {
            return app()->environment('local') ||
                   Gate::check('viewHorizon', [$request->user()] ||
                  auth()->user()
            );
});
```
$request->user() is always null. 
I noticed there was similar issue but I can see they are already resolved. but the horizon is newest and seems like this is happening again. Can anyone please look at this?

**Comment by muscle-rhnkyr** [comment]
Try like this :

In HorizoServiceProvider :

    public function boot()

    {
        parent::boot();
        \Horizon::auth(static function ($request) {
            if (auth('admin')->user()->email !== 'xxxx@xxxx.com') { // instead of admin guard - auth('admin') - you use whatever suits you
                throw new UnauthorizedHttpException('Unauthorized');
            }
            return true;
        });
    }

**Comment by driesvints** [comment]
In Horizon 3, it makes use of a Gate method instead: https://laravel.com/docs/6.x/horizon#dashboard-authorization

**Comment by InvokerMaster** [comment]
Well, Gate actually called 

> \Horizon::auth(static function ($request) {
>         if (auth('admin')->user()->email !== 'xxxx@xxxx.com') { // instead of admin guard - auth('admin') - you use whatever suits you
>             throw new UnauthorizedHttpException('Unauthorized');
>         }
>         return true;
>     });

Actually this still returns null for `$request->user();` or `auth()->user()`

And for @driesvints 's comment, The User defined Gate method is also called from authorization before calling the Gate::check().
