### ISSUE TITLE
Remove a job from queue

### ISSUE THREAD

**Issue by mhndev** [laravel/horizon#714]
Isn't it nice to be able to remove a job from a queue by its identifier or by its tags ?
consider I have job which manipulate my main image and create multiple versions of each image (thumb, ... )
when an image is replaced and uploaded again, I need to be able to remove older job.
This is how I think it should be :
when dispatching a job we can give it and identifier or some tags or ...,
and there is a builtin laravel functionality which helps us remove the job .

for example 
```php
Job::removeById($id);
```
or
```php
Job::removeByTag($tag);
```

**Comment by driesvints** [comment]
Jobs already have an id or tag so I believe this technically would indeed be possible. The jobs in Laravel have a `delete` method which can be called.

**Comment by mhndev** [comment]
Hi @driesvints,
can you please show me how can I delete a job?
I know that a job is a record in the broker, which can be redis, database (mysql) , ...
and I know somehow I can delete that data using underlying connection to the broker.
but I don't think that's the best way to do so.

**Comment by driesvints** [comment]
It has a `delete` method.

**Comment by driesvints** [comment]
Going to close this as we've only received one request for this. We're still open to PRs.

**Comment by ziming** [comment]
Adding my request too. It will be nice to cancel a job or multiple jobs via the horizon UI

**Comment by BlueBayPhil** [comment]
Adding my request to this too. Surprised its not a feature to be honest.

**Comment by mennorenkens** [comment]
This would be convenient! :)

**Comment by dimitribocquet** [comment]
That will be nice!

**Comment by erickneverson** [comment]
+1

**Comment by robbanl** [comment]
+1

**Comment by wdda** [comment]
Hi! I spent half a day looking for an opportunity to remove a job from Laravel + Redis + Horizon.

I have accessed any queue data, but I have not been able to successfully delete the queue.


```
//Photo model

public function deleteQueues()
{
    $queueItems = Redis::connection()->lrange('queues:test', 0, -1);

    foreach ($queueItems as $key => $queueItem) {
        $decodedItem = json_decode($queueItem, true);
        $jobId = $decodedItem['id'];

        $data = (array)unserialize($decodedItem['data']['command']);

        if ($data['photoId'] == $this->id) {
            //???
        }
    }
}
```

It is strange that there is an easy way to delete only for failed jobs.

**Comment by noatudor** [comment]
I've spent an hour on this issue and came up with the following solution: You can use the ZREM command from Redis to remove the pending jobs from Laravel Horizon. Here's how you can implement it:

Redis::connection('horizon')->command('ZREM', ['laravel_horizon:pending_jobs', 'job-id']);

**Comment by rinkla3024** [comment]
In the Failed Jobs, there is a retry button. Could we add a Cancel button on the pending jobs screen?

**Comment by beaubus** [comment]
+1

**Comment by iMatheusPaula** [comment]
+1

**Comment by CodyPChristian** [comment]
+1 we could really use this! Other great options would be: 'move to end of queue', 'hold' (basically gets skipped over until hold or pause is removed), 'delay until x'

**Comment by iamrangoo** [comment]
+1

**Comment by highlandmegseegmiller** [comment]
@driesvints can we re-open this enhancement request?
