### ISSUE TITLE
Horizon error in Queue::pushRaw with rabbitmq

### ISSUE THREAD

**Issue by johnabil** [laravel/horizon#717]
- Horizon Version: 3.3
- Laravel Version: 6.2
- PHP Version: 7.2
- RabbitMQ Driver & Version: vladimir-yuldashev/laravel-queue-rabbitmq 9.1
- Database Driver & Version : pqsql 

### Description:
I am using RabbitMQ to make microservices connect with each through the queue, not through https so each service push some data to queue to another service and vice versa on of the microservices is Laravel and I am using Laravel Horizon and it's connected with RabbitMQ and working great and executing jobs in queues but when I try to send data to some queue through using Queue::pushRaw function  just like that `Queue::pushRaw(json_encode($body), $this->queue_name);` 
it gives me this error
`ReflectionException: Class  does not exist in file /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/horizon/src/Tags.php on line 107

#0 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/horizon/src/Tags.php(107): ReflectionClass->__construct('')
#1 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/horizon/src/Tags.php(28): Laravel\Horizon\Tags::modelsFor(Array)
#2 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/horizon/src/JobPayload.php(132): Laravel\Horizon\Tags::for(NULL)
#3 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/horizon/src/JobPayload.php(91): Laravel\Horizon\JobPayload->determineTags(NULL)
#4 /home/mr-fighto/main/work/GBarena-Backend/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(45): Laravel\Horizon\JobPayload->prepare(NULL)
#5 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(258): VladimirYuldashev\LaravelQueueRabbitMQ\Horizon\RabbitMQQueue->pushRaw('{"notifiables":...', 'requests')
#6 /home/mr-fighto/main/work/GBarena-Backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Illuminate\Queue\QueueManager->__call('pushRaw', Array)
#7 /home/mr-fighto/main/work/GBarena-Backend/app/Services/NotificationService.php(30): Illuminate\Support\Facades\Facade::__callStatic('pushRaw', Array)`

**Notice**
this started to happen when I started to use Laravel Horizon before using horizon everything was working just fine.

**Comment by driesvints** [comment]
Horizon only supports Redis at this time.
