### ISSUE TITLE
cache:clear will wipe jobs

### ISSUE THREAD

**Issue by tillkruss** [laravel/horizon#72]
As discussed with @themsaid, the `cache:clear` command calls `FLUSHDB`, which will delete all Horizon data, or other application data stored in Redis.

**Comment by themsaid** [comment]
For now we'll just have to make sure your queues are persisted in a separate Redis connection.

**Comment by tillkruss** [comment]
Or suggest in the docs to use a different Redis connection for the cache.

**Comment by themsaid** [comment]
We'll mention in the docs that it's recommended to use a separate redis connection for queues to avoid issues like this and also make sure other redis clients won't eat all the memory leaving your workers in a broken state.

**Comment by juukie** [comment]
Hi @themsaid, I can't find it in the [Horizon docs](https://laravel.com/docs/5.5/horizon). Does it still need to be added?

**Comment by ArondeParon** [comment]
This seems like a pretty important thing to document. Is this still on the radar?

**Comment by kevindees** [comment]
I put together a little package to handle clearing specific Redis queues. I'd be interested to know if this helps anyone https://github.com/kevindees/laravel-redis-queue
