### ISSUE TITLE
Horizon dashboard says Paused if 1 server is paused

### ISSUE THREAD

**Issue by rudiedirkx** [laravel/horizon#724]
Not a bug report, because the code seems purposeful, but a question. To get the combined Horizon status, the stats controller does:

    protected function currentStatus()
    {
        if (! $masters = app(MasterSupervisorRepository::class)->all()) {
            return 'inactive';
        }

        return collect($masters)->contains(function ($master) {
            return $master->status === 'paused';
        }) ? 'paused' : 'running';
    }

Why is the Horizon dashboard `paused` if there is 1 `paused` master? If there are 8 more masters `running`, why isn't the combined/summary status `running`? Isn't that confusing? Is that a general queue thing?

I can ask on a forum, but then I get guesses. I want to know the actual reason from the actual source. Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rudiedirkx** [comment]
Yeah, that's what I said. So the answer will be from someone who guesses why, not someone who knows why. Thanks.
