### ISSUE TITLE
Downloading lot of large json files for no reason

### ISSUE THREAD

**Issue by spmsupun** [laravel/horizon#725]
- Horizon Version: 2.2.2
- Laravel Version: 5.6.*
- PHP Version: 7.1.3

### Description:
When I go to recent jobs it downloads lot of json files nonstop, and those are very large and it makes my whole server slow.

<img src="https://i.ibb.co/fCtYV8M/Screenshot-from-2019-12-16-14-58-45.png" alt="Screenshot-from-2019-12-16-14-58-45" border="0" />

### Steps To Reproduce:
Go to horizon and recent job the go to dev tool and network tab in the browser

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
