### ISSUE TITLE
Feature: dynamic queue names for batchs of tasks

### ISSUE THREAD

**Issue by 4n70w4** [laravel/horizon#726]
Case: I need to handle batch of tasks, for example, 1 000 pieces. And I need to be able to stop (pause, continue) the batch of tasks and see the progress of the handling. This is most conveniently done through a dynamic queue name. One unique queue name for each batch of tasks.

also https://github.com/laravel/framework/issues/26339

**Comment by driesvints** [comment]
We have no intention atm to support this.
