### ISSUE TITLE
Installation fails with Laravel 6

### ISSUE THREAD

**Issue by pavlik** [laravel/horizon#728]
- Horizon Version: 3.4.4
- Laravel Version: 6.9.0
- PHP Version: 7.3.3
- Redis Driver & Version: phpredis 5.1.1

### Description:
After running `composer require laravel/horizon` I am receiving the following output:

> $ composer dump-autoload
> Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> 
> In Horizon.php line 100:
> 
>   Redis connection [] has not been configured.
> 
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

My redis connection is working as session and cache driver.

### Steps To Reproduce:
Run `composer require laravel/horizon` or either `composer dump-autoload` after you added Horizon (or `php artisan horizon:install`).

### Temporary solution:
I solved the problem like this:
1. Copy `src/vendor/laravel/horizon/config/horizon.php` to `src/config/` folder.
2. Remove Horizon `composer remove laravel/horizon`
3. Clear laravel cache`php artisan config:clear && php artisan cache:clear && php artisan config:cache && composer dump-autoload`
4. Install composer`composer require laravel/horizon`

**Comment by driesvints** [comment]
> My redis connection is working as session and cache driver.

Never use the same redis connection for your session and cache. Cache should always be ready to be flushed completely without affecting any other parts of your app.

> Redis connection [] has not been configured.

This means that your `database.php` config file isn't up to date with the one from the skeleton or your redis connection which you've set in your horizon.php config file isn't defined as a `database.redis` connection.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by pavlik** [comment]
I googled this bug, but can't found solution.
My session & cache uses different redis dbs.
My `database.php` redis section:
```
'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_') . '_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

    ],
```

**Comment by iKlsR** [comment]
@pavlik Thanks, got this too and your temp solution saved me else I'd have been digging thru configs all night.
