### ISSUE TITLE
[Bug] Vue component request increase thrash

### ISSUE THREAD

**Issue by wells** [laravel/horizon#73]
I am currently testing out `^0.1.0` of horizon, and I noticed an issue with the dashboard. After navigating through the routes multiple times, I see an increase the number of api requests. It also appears that these requests from one page continue even after visiting another page with vue-router.

![GIF: Horizon request thrash example](https://media.giphy.com/media/l41JYQIztsszqLvEc/giphy.gif)

I believe the issue lies in how `setInterval()` is being called but not managed in each of the Vue components. Each time a component is `mounted()` a new interval is created.

Here's my thought on a solution:

- Assign `setInterval()` to a data variable on each component, such as `this.interval = setInterval()`
- Call `clearInterval(this.interval)` whenever a component is no longer in use (i.e. destroyed, deactivated, etc)

Here are the unmanaged setInterval() calls:

- [pages/RecentJobs/Jobs.vue#L71-L79](https://github.com/laravel/horizon/blob/master/resources/assets/js/pages/RecentJobs/Jobs.vue#L71-L79)
- [pages/Failed/Job.vue#L36-L38](https://github.com/laravel/horizon/blob/master/resources/assets/js/pages/Failed/Job.vue#L36-L38)
- [pages/Monitoring/Jobs.vue#L78-L86](https://github.com/laravel/horizon/blob/master/resources/assets/js/pages/Monitoring/Jobs.vue#L78-L86)
- [pages/Failed/Index.vue#L118-L126](https://github.com/laravel/horizon/blob/master/resources/assets/js/pages/Failed/Index.vue#L118-L126)
- [pages/Dashboard.vue#L105-L113](https://github.com/laravel/horizon/blob/master/resources/assets/js/pages/Dashboard.vue#L105-L113)

If you'd like a pull request, let me know.

**Comment by themsaid** [comment]
Thank you so much for this :) I've fixed it in a recent commit.
