### ISSUE TITLE
Failed jobs in the past hour is not correct

### ISSUE THREAD

**Issue by juhasev** [laravel/horizon#734]
- Horizon Version: 3.4.1
- Laravel Version: 6.5
- PHP Version: 7.3
- Redis Driver & Version: predis 1.1

### Description:
Dashboard shows 30 failed jobs for the last hour, but looking at failed jobs list the last failed job was over 12 hours ago. Should this boil down to a timezone issue all servers + Redis all set to UTC (AWS MySql, Redis). I am on America/Chicago timezone and Horizon UI displays all times and dates correctly.

Example:
[https://vimeo.com/381497252](https://vimeo.com/381497252)

### Steps To Reproduce:
Produce some failed jobs and wait past 1 hour mark and inspect the dashboard.

**Comment by themsaid** [comment]
Make sure you are running latest Horizon version and re-publish the assets.

**Comment by rickycheers** [comment]
@juhasev I was having the same problem but fixed it by adding this `'recent_failed' => 60,` to the `horizon.php` config file. It should be under the `trim` section.

```
'trim' => [
        'recent' => 60,
        'recent_failed' => 60,
        'failed' => 10080,
        'monitored' => 10080,
    ],
```
