### ISSUE TITLE
Using helpers from `Iluminate/Foundation`

### ISSUE THREAD

**Issue by masterjus** [laravel/horizon#735]
- Horizon Version: 3
- Laravel Version: 6
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis 5.1.1
- Database Driver & Version:

### Description:
Generally, this bug would never happen but I'm using your Horizon as a package for my own package and found that you're using helper functions from `Illuminate/Foundation` but this package not in composer requirements.

Example: https://github.com/laravel/horizon/blob/3.0/src/HorizonServiceProvider.php#L142

### Steps To Reproduce:

Install Horizon in Lumen.

**Comment by driesvints** [comment]
We don't support using Horizon outside the framework, sorry.
