### ISSUE TITLE
Runtime meta data for jobs

### ISSUE THREAD

**Issue by esbenp** [laravel/horizon#746]
Similar: #630 

One thing that would be neat is the possibility to attach meta data to a job during runtime. This could be progress information, logging etc.

Right now the failed job view shows job data and exception stack trace, so my suggestion is to add a third box with this meta data. This would help a lot with debugging failed jobs without having to leave the Horizon UI.

Is this something that would be considered if I created a PR? If so, any does/dont's? Potential pitfalls?

**Comment by driesvints** [comment]
We've already tried this in the past. I can't immediately find the related issue. But it came down to it hogging up excessive memory usage so it's unlikely we'll reconsider this, sorry.
