### ISSUE TITLE
Auto-scaler fluctuates when no job is waiting 

### ISSUE THREAD

**Issue by halaei** [laravel/horizon#750]
Imagine the following supervisor config:
```php
[
    'quque' => ['high', 'med', 'low'],
    'processes' => 10,
    'balance' => 'auto',
],
```
Ideally, we want no job to be waiting in the queues, in other words, readyNow() to be zero for all the queues. Imagine that is achieved at the moment by 6 workers for 'high', 3 for 'med' and 1 for 'low' queue and everything is perfect. Now `Laravel\Horizon\AutoScaler` comes into play and, because no job is waiting, it tends to balance the settings by removing 1 worker from 'high' and adding one to 'low'. However, now 5 workers for 'high' queue is not enough and jobs get accumulated there, while there is actually not much workload in the 'low' queue. In short, auto-scaler hurts here. In the next auto scaling, things go back to normal 6-3-1 arrangement. Next auto-scaling the arrangement will be 5-3-2 again.
This fluctuation goes forever as long as we can ideally have no delay on the queues.

In order to improve the situation, I suggest to minimize the chance of jobs in any queue getting delayed by trying to maximize/increase a mathematical objective function like the following:
```
min(workers(q) - reserved(q) - ready(q) for q in the config['queue'])
```
where `workers(q)` is the current number of processes working on q, `reserved(q)` is the number of jobs in q that are currently being processed, or in other words, the number of busy workers, and `ready(q)` is the number of waiting jobs in q.

**Comment by themsaid** [comment]
I don't seem to understand the situation you are describing. What's wrong with the scaler assigning only 5 workers to the `high` queue if it doesn't need 6?

**Comment by halaei** [comment]
My point is that it may need exactly 6 workers even if no job is waiting. For example when all the workers are busy.
I think removing a worker is bad when everything is actually fine, because:
1. It delays future ready jobs in the 'high' queue.
2. Switching workers from one queue to another takes some extra cpu, which is a minor issue, but it happens frequently.

**Comment by themsaid** [comment]
I still can't picture the problem here. If no job is waiting, why keep 6 processes running?

**Comment by halaei** [comment]
Lets consider this simple case: all the jobs takes exactly 1 second to be processed, and exactly 6 jobs arrives at every given seconds, at every moment the size of the ready queue is exactly 0, but 6 jobs are in reserved queue, being processed. Doesn't it mean we need exactly 6 workers, not 5?

**Comment by themsaid** [comment]
6 jobs are already being processed, 6 workers are already busy. How can we assume the next second we'll still need 6 workers still at all time?

**Comment by halaei** [comment]
That is a question regarding probability theory. I don't recall the formula or the exact terminology. For as much as I can understand from looking at wikipedia, the inter-arrival time of such events tends to generally be of exponential distribution with a constant average/expected value, and the number of jobs arrives at a constant period of time, e.g. a minute, is of Poisson distribution. 

That is, if 1000 jobs arrives at a given minute, chances are high that the number of arrived jobs in the next minute be close to 1000. So we can predict the near future with a good chance just by looking how much jobs are being processed at the moment.

Anyway, I was always hesitant of using the current auto-scaling feature, because I am afraid it doesn't work well for applications that need all the queues to be always empty, unless huge bursts happen. So I just go with one queue per supervisor and assigning a lot more than necessary workers per queue, which is terrible in terms of memory efficiency.

**Comment by driesvints** [comment]
Hey @halaei. Thanks for your input here. I'm going to close this one off as it's not a high priority issue or anything. If you feel anything can be improved to the auto scaler, feel free to send in a PR.
