### ISSUE TITLE
Dashboard: Wrong interval of failed jobs

### ISSUE THREAD

**Issue by LKaemmerling** [laravel/horizon#756]
- Horizon Version: v3.3.2
- Laravel Version: v6.0.1
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:

We have the following trim config:
```php
$horizon = [    
'trim' => [
        'recent' => 5,
        'failed' => 60 * 24,
    ]
];
```
On the Dashboard you see only the following:
<img width="735" alt="Bildschirmfoto 2020-02-06 um 16 10 07" src="https://user-images.githubusercontent.com/4281581/73949997-7aa75800-48fb-11ea-8966-092ec1c4e0b6.png">
But it should be `Failed jobs past 24 hours` instead of `Failed jobs past 5 minutes`
### Steps To Reproduce:
Use a similar trim config like above.

**Comment by themsaid** [comment]
Make sure you have the full configurations in your config file:

```
    'trim' => [
        'recent' => 60,
        'completed' => 1,
        'recent_failed' => 10080,
        'failed' => 10080,
        'monitored' => 10080,
    ],
```

**Comment by LKaemmerling** [comment]
@themsaid the config was stripped to the relevant values. The bug is still present because of a wrong fallback flag. It works like a charm only the UI is wrong

**Comment by themsaid** [comment]
If I have recent_failed set, the UI works fine for me and displays the correct period. What's the value of `trim.recent_failed` in your config file?

**Comment by LKaemmerling** [comment]
It is not set because we recently updated to the latest horizon version. It works like a charm only the UI has the small bug  after the stats endpoint was called. You can see the small fix in the PR.

**Comment by themsaid** [comment]
The recent version of Horizon has it:

https://github.com/laravel/horizon/blob/3.0/config/horizon.php#L98

**Comment by themsaid** [comment]
trimming of "recent" failed jobs is different from trimming of "failed" jobs.
