### ISSUE TITLE
Filter background jobs by custom tags 

### ISSUE THREAD

**Issue by deepakbasnal** [laravel/horizon#758]
I want to search background jobs in laravel horizon usign custom tags. I checked the laravel horizon documentation also, but didn't found any information.

![Horizon - Recent Jobs](https://user-images.githubusercontent.com/32673378/74028888-777e9b80-49d1-11ea-96bf-8f6ace4cbb49.png)

I am not sure if this is possible or I am missing something in documentation

**Comment by themsaid** [comment]
Only failed jobs are searchable.

**Comment by deepakbasnal** [comment]
@themsaid I can't even filter failed jobs

**Comment by indigoram89** [comment]
> Only failed jobs are searchable.

but why is it so?
