### ISSUE TITLE
Filtering of `Recent Jobs` screen

### ISSUE THREAD

**Issue by atymic** [laravel/horizon#759]
I think it would make sense to be able to filter the recent jobs page.
For context, we have a cron that mass queues ~100k jobs into redis.
The issue is that i'd love to see the completed jobs, but since there is so many jobs after it, it would take days to paginate all the way to the completed ones.

I would propose having some kind of filter, to select from:

- All
- Completed
- Pending

Thoughts?
Happy to have a go at a PR.

**Comment by driesvints** [comment]
I'm not sure how easy this is to implement but feel free to try a pr. There have been some performance issues with filtering from previous prs which we ultimately reverted but I believe that related to tagging. If the info is already in redis we might be able to easily implement this.

**Comment by driesvints** [comment]
There's also https://github.com/laravel/horizon/issues/707 for failed jobs so maybe we can tackle that one together.

**Comment by Muffinman** [comment]
I like the idea of this. Also `Reserved` would be another obvious filter to add, so you can see what is actually picked up and running.

Bear in mind that any PR that adds functionality will need to have a very compelling case to be accepted. Most of this type of PRs tend to get a 'do it as a package' response.

**Comment by driesvints** [comment]
Going to close this as we're not gonna work on this ourselves. We're still open to PRs.
