### ISSUE TITLE
horizon config single one redis connection, can prefix be optional?

### ISSUE THREAD

**Issue by RryLee** [laravel/horizon#76]
@themsaid 

[d00d0b](https://github.com/laravel/horizon/commit/d00d0b6c0fec931be909acf6a3a560455ba4a6a7) this repo make horizon use one redis. I think prefix can be optional.

```php
public static function use($connection, $prefix = null)
{
    $config = config("database.redis.{$connection}");

    config(['database.redis.horizon' => array_merge($config, [
        'options' => ['prefix' => $prefix ?: 'horizon:']
    ])]);
}
```

Multiple apps use one redis server in aws,  i think they can use one redis connection shared in  different apps.

**Comment by themsaid** [comment]
There's no harm in forcing the prefix, making it optional doesn't really add a value.
