### ISSUE TITLE
Unable to dispatch job to new redis connection, it falls back to default redis connection

### ISSUE THREAD

**Issue by khatritariq** [laravel/horizon#766]
- Horizon Version: v1.2.9
- Laravel Version: v5.8
- PHP Version: 7.1
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:

Hi,

I am using lumen 5.8 and laravel horizon as well.

I want to dispatch events based on condition, for e.g. if x= 1, then dispatch event to redis_server_1 and if x= 2, dispatch event to redis_server_2

To achieve this, I'm using following code base:

dispatch( (new MyJob( $params ))->onQueue('default')->onConnection('redis1') );

I've defined 'redis' array in config/queue.php and also, defined a new array for 'default1' in config/database.php under redis array, but it doesn't seems to work.

Please advise.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by khatritariq** [comment]
Can you please confirm whether the scenario I have explained is supported even or not ? So that I can upgrade it accordingly

**Comment by khatritariq** [comment]
I've upgraded my application to "laravel/lumen-framework": "v6.3.4" and the result is same.

**Comment by driesvints** [comment]
@khatritariq we don't support any of the first party packages in Lumen: https://lumen.laravel.com/docs/6.x#compatibility
