### ISSUE TITLE
Redis database connection options are overriden

### ISSUE THREAD

**Issue by canvural** [laravel/horizon#777]
- Horizon Version: 3.4.7
- Laravel Version: 6.11.0
- PHP Version: 7.4.1
- Redis Driver & Version: predis 1.1

### Description:

In `Horizon::use` method, when setting the prefix for the connection, all of the options are overridden. Here, https://github.com/laravel/horizon/blob/3.0/src/Horizon.php#L103
Using `array_merge_recursive` instead of `array_merge` would solve the issue.

Is this intentional? I have some options that I'd like to be also included in the `horizon` connection.

**Comment by driesvints** [comment]
This connection is the internal Redis connection for Horizon and isn't really meant to be manipulated afaik. What is it exactly that you want to do?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
