### ISSUE TITLE
Error while installing Horizon on windows

### ISSUE THREAD

**Issue by john5db** [laravel/horizon#78]
Hi,
When i try to install Horizon on  windows dev machine it gives following error 

~~~
Problem 1
    - Installation request for laravel/horizon dev-master -> satisfiable by laravel/horizon[dev-master].
    - laravel/horizon dev-master requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.

~~~
But  pcntl  is not available for windows 

How to install without pcntl.

**Comment by john5db** [comment]
Can we use   pthreads    https://github.com/krakjoe/pthreads

instead of pcntl 

pthreads supports windows ,mac,linux

**Comment by themsaid** [comment]
Sorry no plans for this at the moment :) I suggest that you use something like Laravel Homestead and run a virtual machine where you can use Ubuntu.

**Comment by JapSeyz** [comment]
@john5db The very talented developer of Laragon has ported the extension (more or less, it's still experimental at this point) to windows, you can get it here: https://forum.laragon.org/topic/593/how-to-add-pcntl-extension-windows

**Comment by mtx-z** [comment]
Latest release 1.0.5 have a new windows issue making it impossible to install. 
I successfully fixed the PCNTL issue using @JapSeyz solution (Horizon 1.0.0). 

Now, on 1.0.5, we have the `POSIX PHP extension` missing:

```
  Problem 1
    - Installation request for laravel/horizon v1.0.5 -> satisfiable by laravel/horizon[v1.0.5].
    - laravel/horizon v1.0.5 requires ext-posix * -> the requested PHP extension posix is missing from your system.
```

I'm running PHP 7.1.9.

**Comment by cmosguy** [comment]
@themsaid @mtx-z yup I am stuck here on the posix issue issue as well.  Is there a a strong need for this extension for some reason?

**Comment by chilio** [comment]
@themsaid  you are right, but what if I'm using Homestead already.
This broke my workflow, cause I can't use composer commands directly in IDE anymore.

**Comment by kiwina** [comment]
if you just developing on windows and deploying on linux use --ignore-platform-reqs with your composer command, this will still install horizon you still see the dashboard but its useless on windows.

**Comment by FurrukhJamal** [comment]
So there are still no workarounds with laravel 10 for windows 11?

**Comment by ariefan** [comment]
To run Horizon on Windows 11, the easiest and most recommended method is to utilize Windows Subsystem for Linux (WSL). Assuming you're working with Laravel 11, follow these straightforward steps:

1. Open PowerShell or Windows Command Prompt as an administrator.
2. Execute the following command to install WSL, the easiest and most reliable method:
`wsl --install`
3. Follow the prompts to set up your Linux username and password, then restart your machine.
4. Navigate to your project folder in Windows PowerShell and access the Ubuntu terminal in WSL with the command:
`wsl -d Ubuntu`
5. Install PHP 8.3 and the necessary dependencies for Horizon by running:
```
sudo add-apt-repository ppa:ondrej/php 
sudo apt update
sudo apt-get install redis
sudo apt-get install zip php8.3 php8.3-cli php8.3-{bz2,curl,mbstring,intl,xml,dom,zip,redis}
```
6. Finally, install and run Horizon using Composer and Artisan commands:
```
composer require laravel/horizon
php artisan horizon:install
php artisan horizon
```

**Comment by Geovanek** [comment]
If you use Herd, add this to composer.json
```json
"config": {
      "platform": {
            "ext-pcntl": "8.4",
            "ext-posix": "8.4"
        }
}
```

**Comment by parthjani7** [comment]
> If you use Herd, add this to composer.json
> 
> "config": {
>       "platform": {
>             "ext-pcntl": "8.4",
>             "ext-posix": "8.4"
>         }
> }

This works after removing composer.lock and running `composer install`. Thanks @Geovanek
