### ISSUE TITLE
Retry icon keeps spinning even with errors

### ISSUE THREAD

**Issue by LasseRafn** [laravel/horizon#781]
- Horizon Version: 3.7.0
- Laravel Version: 6.14
- PHP Version: 7.4
- Redis Driver & Version: PhpRedis
- Database Driver & Version: MySQL 8.0

### Description:

The loading/retrying spinner in failed jobs shows a active (loading / actively retrying ?) state even if the retry request fails. Maybe it should show just a simple `alert` or stop the spinning animation.

Disregard the CSRF error (unsure where it comes from but it is unrelated to what I'm reporting)

Video: https://www.dropbox.com/s/o9gcxvdkbysrl7u/horizon-example.mp4?raw=1

**Comment by driesvints** [comment]
Is the problem also happening with v3.7.2?

**Comment by LasseRafn** [comment]
Did not realize there was an update, sorry! However still happens in v3.7.2 yes

**Comment by driesvints** [comment]
Appreciating PRs for this.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/horizon/commit/df7adc1ddacbfed64a1a8dbca6e9cd1b55bbb480
