### ISSUE TITLE
Can you restart from a class?

### ISSUE THREAD

**Issue by futurewebsites** [laravel/horizon#784]
Hi LaraPeeps,

I have an API which requires oAuth2 on initial connection it has to be human authorised by clicking a button on the vendors website, this then hits a call back url with an access token - the token must be refreshed via a scheduled job every 30 mins in order to stay authorised. 

If I queue the api pushes the first token is held in memory I guess and I receive an unauthorised exception. 

so I need to restart horizon in either my controller or event so the refreshed token is used for authentication? 

I have tried Artisan::call('horizon'); 

I hope that makes sense?

**Comment by mfn** [comment]
> If I queue the api pushes the first token is held in memory I guess and I receive an unauthorised exception.
> 
> so I need to restart horizon in either my controller or event so the refreshed token is used for authentication?

The way I understand is:
- you need to implement your user story
- once you have the initial token enqueue a job with that token
- _then_ enqueue the follow-up jobs

Usually you need the _current_ access token (short lived) and a separate refresh_token (long lived) to get a new (short lived) access token, so I'm accustomed to just store them in the database anyway.

Does that make sense for your use case?

**Comment by themsaid** [comment]
Please ask on the forums, this repo is for bug reporting only. You can use https://laracasts.com/discuss or https://laravel.io/forum which are forums with a very large community of developers helping each other.
