### ISSUE TITLE
Store Horizon data in MySQL similar to Telescope

### ISSUE THREAD

**Issue by wwwroth** [laravel/horizon#785]
Hi!

I'm curious why Horizon stores it's data for the dashboard in files/cache instead of in the database like Telescope does. I've noticed when I deploy on Azure and swap slots, the cache/temp files are cleared and data is lost even though it's set in the config to persist for six hours.

Is this intentional for some reason? Would you accept a PR that would generate migrations and store data in MySQL instead?

Thanks,

**Comment by driesvints** [comment]
Please see https://github.com/laravel/horizon/issues/421

We might reconsider in the future.

**Comment by wwwroth** [comment]
I may not have explained myself well enough. I don't mean actually supporting the `QUEUE_CONNECTION=database` driver, I mean storing the data for reporting within a database so it persists even after clearing cache, redeploying, etc.

Then, you can have a truncate command scheduled (like Telescope) to clear out data after N hours/days/etc.

Looking into it more, this data is stored within Redis itself. Maybe also store it in a DB table so it persists even when Redis is reinstalled?

**Comment by driesvints** [comment]
Ah I see. I believe this would require quite a daunting overhaul of internals at first sight so I don't think this is something we're gonna do anytime soon, sorry.

**Comment by michael-ferioli** [comment]
Old thread, but I totally agree with this idea.  I want to be able to report on horizon performance over time.

**Comment by driesvints** [comment]
Coming back on this after so many years, I believe the main reason for Redis is just its fast distritbution/throughput. When you have a high number of queue jobs it's much more powerful to handle such data flows than a MySQL database. So I don't think we'll ever consider a different storage which could be a blocker for people eventually.

For the connection itself you can always choose a different more longer lived one than the default: https://github.com/laravel/horizon/blob/5.x/config/horizon.php#L44

**Comment by wwwroth** [comment]
I don't believe it's as much of migrating away from Redis but storing the statistics viewed in the dashboards in MySQL. I understand the decision to use Redis and completely agree but if stats were in MySQL they would persist and be stateless and would not be "wiped" on redeployments.

**Comment by driesvints** [comment]
@wwwroth that's why I point to a different redis connection in the config. Separating this one into a persistent redis store that's separate from your cache etc won't allow it to be wiped on deployment.
