### ISSUE TITLE
Conclusion: remove laravel/framework v6.9.0

### ISSUE THREAD

**Issue by rainbowhat** [laravel/horizon#786]
- Horizon Version: Latest
- Laravel Version: 6.9
- PHP Version: 7.3.8
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: Postgress 11

composer require laravel/horizon

Problem 1
    - Conclusion: remove laravel/framework v6.9.0
    - Conclusion: don't install laravel/framework v6.9.0
    - laravel/horizon 4.x-dev requires illuminate/support ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4].
    - laravel/horizon v4.0.0 requires illuminate/support ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4].
    - Can only install one of: laravel/framework[7.x-dev, v6.9.0].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.9.0
    - don't install illuminate/support v7.0.0|don't install laravel/framework v6.9.0
    - don't install illuminate/support v7.0.1|don't install laravel/framework v6.9.0
    - don't install illuminate/support v7.0.2|don't install laravel/framework v6.9.0
    - don't install illuminate/support v7.0.3|don't install laravel/framework v6.9.0
    - don't install illuminate/support v7.0.4|don't install laravel/framework v6.9.0
    - Installation request for laravel/framework (locked at v6.9.0, required as ^6.2) -> satisfiable by laravel/framework[v6.9.0].
    - Installation request for laravel/horizon ^4.0 -> satisfiable by laravel/horizon[4.x-dev, v4.0.0].

**Comment by Felo-Z** [comment]
I have the same question

**Comment by vesper8** [comment]
probably because Horizon 4 requires Laravel 7?

**Comment by driesvints** [comment]
Horizon 4 indeed requires Laravel 7. Please see the upgrade guide: https://github.com/laravel/horizon/blob/4.x/UPGRADE.md

**Comment by vesper8** [comment]
@driesvints Does Horizon 4 have an actual real dependency on Laravel 7? I ask because if not I will just fork it and re-enable Laravel 6 support since I would really like to have Horizon's 4 new features but am being held back by multiple other dependencies that have yet (and will probably take weeks) to support Laravel 7

**Comment by driesvints** [comment]
@vesper8 yes: https://github.com/laravel/horizon/blob/4.x/composer.json#L18

> I ask because if not I will just fork it and re-enable Laravel 6 support

You can't do that. It's backwards incompatible with Symfony 4
