### ISSUE TITLE
Recent Jobs are not displaying - problem with Vue component

### ISSUE THREAD

**Issue by Neilbircumshaw** [laravel/horizon#788]
Bug has been implemented in v 3.7.0

Reason for bug - A new component was made called "job-row" to slim down the index component (https://github.com/laravel/horizon/blob/v3.7.0/resources/js/screens/recentJobs/index.vue) and imported at the top `import JobRow from './job-row';` however the import for Jquery was removed. '$' now has no reference in this component.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by tomgrohl** [comment]
Hey

This problem looks to be introduced in 3.7.0 and still happens in 3.7.2.

Horizon 3.7.2 is the latest version for Laravel 6.

**Comment by tcdsantos** [comment]
Hi!

I am having this same problem: Recent Jobs not displaying.

With previous setup (Laravel 6.8 + Horizon 3.3) everything was working well. 
Then, I decided to upgrade Laravel to the new version (Laravel 7.1.3) and i also upgraded Horizon to the latest version (4.0.1) and i got 2 problems with Horizon:

1) When i open the route `/horizon`, firefox is giving me one error in the console:
`Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://www.<mydomain.com>/vendor/horizon/app.js?id=f19116ddea43222f35b2
Source Map URL: popper.js.map`

2) Recent Jobs page opens empty. 

All other pages are being correctly opened. Dashboard shows correct status, jobs past hour, number of processes, everything seems to be ok.

Is anyone else having the same problem?

Thank you!

**Comment by killgt** [comment]
Same problem with the latest version, there is no 'completed_jobs' key on redis, trying to figure out why...

**Comment by tcdsantos** [comment]
My problem got resolved after the upgrade to the latest version.

Two days ago, when v4.0.2 was released, i installed it, republished the assets and suddenly it started working with no issues.
