### ISSUE TITLE
Add 'Pending' or 'Completed' Jobs 'empty' screen

### ISSUE THREAD

**Issue by richardkeep** [laravel/horizon#790]
It would be nice, like in the `Failed Jobs` page, to show a message that there are no `Pending` or `Completed` jobs, rather than showing a blank screen. 

![Screenshot from 2020-03-09 12-51-40](https://user-images.githubusercontent.com/3874381/76201965-28f93280-6205-11ea-92fe-0efff132406c.png)
![Screenshot from 2020-03-09 12-51-18](https://user-images.githubusercontent.com/3874381/76201976-2c8cb980-6205-11ea-8f6c-392224c96d4c.png)

**Comment by themsaid** [comment]
Check your browser console, seems like there's an error in your app.

**Comment by richardkeep** [comment]
My bad, I hadn't re-published the Horizon's asset
