### ISSUE TITLE
empty prefix is impossible

### ISSUE THREAD

**Issue by feistiny** [laravel/horizon#791]
queue name is shared with others, if I install horizon, then I must prefix the queue name with something or default `horizon:`, which make me stop.
consider the php null coalescing operator `??`
change
```php
        config(['database.redis.horizon' => array_merge($config, [
            'options' => ['prefix' => config('horizon.prefix') ?: 'horizon:'],
        ])]);
```
to
```php
        config(['database.redis.horizon' => array_merge($config, [
            'options' => ['prefix' => config('horizon.prefix') ?? 'horizon:'],
        ])]);
```
to allow empty prefix

in .env
use default prefix
```
HORIZON_PREFIX=null 
```
use empty prefix
```
HORIZON_PREFIX=empty 
```

**Comment by browner12** [comment]
Do you specifically **need** an empty Horizon prefix? Wouldn't it be easier to just add a prefix string?

**Comment by feistiny** [comment]
Before using horizon, the queue name was in laravel's default format `queues:default`, after using horizon , all the programs not only laravel communicating based on the same queue name should add a prefix `horizon:queues:default`, it's better to keep it unchanged in my situation, since I cannot do it on my own.

**Comment by feistiny** [comment]
This is really not a big problem, I can wait to all the programs to be upgraded so that the queue name can be changed together by all, or fork and change.

**Comment by feistiny** [comment]
I find that just change the queue connection of horizon to exact a different name than horizon works.
Just not use the `database.redis.horizon`.
