### ISSUE TITLE
Cannot view failed jobs if payload doesn't have tags property

### ISSUE THREAD

**Issue by gio00** [laravel/horizon#792]
- Horizon Version: v4.0.1
- Laravel Version: v7.1.0
- PHP Version: 7.4
- Redis Driver & Version: predis v1.1.1
- Database Driver & Version:

### Description:
There is a wrong check of the variable tags inside the payload. If there is no property tags the page crash for accessing property length of undefined.

Check `tags` and not `tags.length` in the v-if fix the issue: https://github.com/laravel/horizon/blob/e86b16eab6b1acba1cddd6bf3801fc951c98ef06/resources/js/screens/failedJobs/index.vue#L230

### Steps To Reproduce:
I'm not sure, I was just testing horizon and i couldn't see the failed jobs.

**Comment by themsaid** [comment]
Updated in a latest commit. Will be available with the next release.
