### ISSUE TITLE
Can't install horizon to fresh Laravel v6.18.1  project

### ISSUE THREAD

**Issue by n588E** [laravel/horizon#797]
- Horizon Version: ^4.0
- Laravel Version: 6.18.1
- PHP Version: 7.3
- Redis Driver & Version: predis/phpredis ^1.1
- Database Driver & Version:

### Description:
Can't install horizon on fresh project.

Error output:

vagrant@homestead:~/code/new-project$ composer require laravel/horizon
Using version ^4.0 for laravel/horizon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.18.1
    - Conclusion: don't install laravel/framework v6.18.1
    - laravel/horizon 4.x-dev requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3].
    - laravel/horizon v4.0.0 requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3].
    - laravel/horizon v4.0.1 requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3].
    - don't install illuminate/queue 7.x-dev|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.0|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.1|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.2|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.3|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.4|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.5|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.6|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.7|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.0.8|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.1.0|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.1.1|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.1.2|don't install laravel/framework v6.18.1
    - don't install illuminate/queue v7.1.3|don't install laravel/framework v6.18.1
    - Installation request for laravel/framework (locked at v6.18.1, required as ^6.2) -> satisfiable by laravel/framework[v6.18.1].
    - Installation request for laravel/horizon ^4.0 -> satisfiable by laravel/horizon[4.x-dev, v4.0.0, v4.0.1].

Installation failed, reverting ./composer.json to its original content.

### Steps To Reproduce:

composer create-project --prefer-dist laravel/laravel blog "6.*"

composer require laravel/horizon

**Comment by waltersteven** [comment]
@n588E Got the same problem. Horizon 4.0 requires illuminate/contracts, /queue and /support in ^7.0.  I did not want to upgrade so I solved it installing Horizon 3.7.2 which is compatible with Laravel 6:

 `composer require laravel/horizon:3.7.2`

**Comment by driesvints** [comment]
Horizon 4 only supports Laravel 7.

**Comment by josepcrespo** [comment]
The same happended to me. It is not supposed that Composer is capable of handling all this kind of issues by himself? Why does not Composer solves this version dependency by himself? If there is a previous compatible version why can not Composer, at least, suggest to install a previous version?

**Comment by homeoftheunits** [comment]
I have the same Problem, but with Laravel 7:

```
- Conclusion: don't install laravel/horizon v4.3.0
    - Conclusion: remove cakephp/chronos 1.3.0
    - Installation request for laravel/horizon ^4.3 -> satisfiable by laravel/horizon[4.x-dev, v4.3.0].
    - Conclusion: don't install cakephp/chronos 1.3.0
    - laravel/horizon 4.x-dev requires cakephp/chronos ^2.0 -> satisfiable by cakephp/chronos[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - Can only install one of: cakephp/chronos[2.0.0, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.1, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.2, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.3, 1.3.0].
    - Installation request for cakephp/chronos (locked at 1.3.0) -> satisfiable by cakephp/chronos[1.3.0].
```

**Comment by driesvints** [comment]
@homeoftheunits try `composer update --with-dependencies`

**Comment by wwwroth** [comment]
@driesvints having this issue as well on 7.4.5/7.11
```
☁  ***-***-*** [development] ⚡ composer require laravel/horizon
Using version ^4.3 for laravel/horizon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/horizon v4.3.2
    - Conclusion: don't install laravel/horizon v4.3.1
    - Conclusion: don't install laravel/horizon v4.3.0
    - Conclusion: remove cakephp/chronos 1.3.0
    - Installation request for laravel/horizon ^4.3 -> satisfiable by laravel/horizon[4.x-dev, v4.3.0, v4.3.1, v4.3.2].
    - Conclusion: don't install cakephp/chronos 1.3.0
    - laravel/horizon 4.x-dev requires cakephp/chronos ^2.0 -> satisfiable by cakephp/chronos[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - Can only install one of: cakephp/chronos[2.0.0, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.1, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.2, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.3, 1.3.0].
    - Can only install one of: cakephp/chronos[2.0.4, 1.3.0].
    - Installation request for cakephp/chronos (locked at 1.3.0) -> satisfiable by cakephp/chronos[1.3.0].


Installation failed, reverting ./composer.json to its original content.
☁  ***-***-*** [development] ⚡ php artisan --version
Laravel Framework 7.11.0
☁  ***-***-*** [development] ⚡ php -v
PHP 7.4.5 (cli) (built: Apr 23 2020 02:25:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
☁  ***-***-*** [development] ⚡
```

**Comment by wwwroth** [comment]
I got it to work by adding the line directly to composer.json, then running `composer update --with-dependencies`.

**Comment by vedmant** [comment]
This all is caused by moving to different Laravel versioning like 6, 7, 8. I think that was a bad decision, I started to have lots of dependencies issues now with Laravel.

**Comment by raf187** [comment]
> composer update --with-dependencies

thx that fix my problem   👌🏽
