### ISSUE TITLE
Pending Jobs and Completed Jobs

### ISSUE THREAD

**Issue by serderovsh** [laravel/horizon#798]
- Horizon Version: 4.0
- Laravel Version: 7.0.6
- PHP Version: 7.3.2

### Description:

Good afternoon, check out these sections. They are not workers

- horizon/jobs/pending
- horizon/jobs/completed

requests in these sections are not executed

**Comment by serderovsh** [comment]
![2020-03-15_14-43-41](https://user-images.githubusercontent.com/24723913/76700728-7d9c2200-66cb-11ea-9548-6bb55a1282b4.png)

**Comment by tcdsantos** [comment]
I have this same problem but with "Recent Jobs".
In my project, recent jobs' vue component is not being displayed.
Other views are ok: dashboard, monitoring, metrics and failed jobs.

**Comment by backstageel** [comment]
@serderovsh after de upgrade you need to republish the assets with:

`php artisan horizon:publish`

**Comment by driesvints** [comment]
Did you read the upgrade guide and run the above command? https://github.com/laravel/horizon/blob/4.x/UPGRADE.md

**Comment by tcdsantos** [comment]
In my case, i followed the upgrade guide and i did the recommended republish of the assets. I have repeated this action 4~5 times, removed all the old assets from the server, cleared the browser's cache, republished it again and the problem persists. I can't figure out why is it happening...

Not only this view ("Recent Jobs") is not being displayed but also it is being displayed an error in the firefox console related with poppers's source map:

```
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://www.<my_domain>.com/vendor/horizon/app.js?id=f19116ddea43222f35b2
Source Map URL: popper.js.map
```

Previously it was working well with laravel 6.8 + horizon 3.3. After the upgrade do Laravel 7 + horizon 4 this problem has started.

@serderovsh Did you find a solution?

Thank you.

**Comment by driesvints** [comment]
Since most of this works fine for people I believe there is something really specific to your app that's causing this.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by ajnozari** [comment]
So I don't mean to re-open this unnecessarily but I am seeing this EXACT behavior.  It works fine locally, but when we publish on our staging server it fails to use the newly published (and committed) vendor files.

**Comment by levis012** [comment]
My project is the same this issue.
Nobody help ?

**Comment by ajnozari** [comment]
So we solved it after a deep clearing of all the coaches and views.

**Comment by jdavidbakr** [comment]
I've noticed that when there is a large amount of jobs in pending or complete, the list tends to not pull.  I'm guessing it's exceeding some sort of limit, no idea what it is or if it can be changed, but that's been my experience.

**Comment by codex-corp** [comment]
same here, I did all of suggestions above and still empty.

**Comment by darkostanimirovic** [comment]
We had the same problem. Ran the publish command a bunch of times, didn't help.

For those who might be having the same issue: It looks like **browser was caching the old JS**. The "Recent Jobs" link was there even though in the source file for routes.vue it wasn't. In the end, hard reload and cache purge + PHP restart helped it.

(But now "Completed" jobs is empty even though there's a lot of jobs coming into Pending and they're being completed. So the upgrade for us was/is not as simple as "run php artisan horizon:publish")

**Comment by Morgunov-Vitaly** [comment]
+

**Comment by DriverCat** [comment]
Maybe it would be helpful for someone. In my case I have a main app and a microservice, both uses one Redis instance. 
Main app writes job info through Horizon into Redis and microservice reads it and executes. 
Horizon has this config variable:
```
'prefix' => env(
        'HORIZON_PREFIX',
        Str::slug(env('APP_NAME', 'laravel'), '_').'_horizon:'
    ),
```
If your main app and microservice have different app names, there will be different variables inside Redis (and microservice would get empty data). The workaround is to use same ENV variable ```HORIZON_PREFIX``` on both apps.
