### ISSUE TITLE
Cannot Install On L6.18

### ISSUE THREAD

**Issue by prezire** [laravel/horizon#800]
Tried issuing a command: composer require laravel/horizon

But I got these errors instead.

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: remove laravel/framework v6.18.1
    - Conclusion: don't install laravel/framework v6.18.1
    - Conclusion: don't install laravel/framework v6.18.0
    - laravel/horizon 4.x-dev requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3].
    - laravel/horizon v4.0.1 requires illuminate/queue ^7.0 -> satisfiable by illuminate/queue[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3].
    - don't install illuminate/queue 7.x-dev|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.0|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.1|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.2|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.3|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.4|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.5|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.6|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.7|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.0.8|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.1.0|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.1.1|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.1.2|don't install laravel/framework 6.x-dev
    - don't install illuminate/queue v7.1.3|don't install laravel/framework 6.x-dev
    - Installation request for laravel/framework ^6.18 -> satisfiable by laravel/framework[6.x-dev, v6.18.0, v6.18.1].
    - Installation request for laravel/horizon ^4.0.1 -> satisfiable by laravel/horizon[4.x-dev, v4.0.1].

**Comment by mfn** [comment]
For Laravel 6 you need Horizon ^3.0
