### ISSUE TITLE
php artisan horizon:purge not killing any orphaned processes

### ISSUE THREAD

**Issue by Ganganation** [laravel/horizon#804]
- Horizon Version: v4.0.2
- Laravel Version: v7.2.0
- PHP Version: PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS)
- Redis Driver & Version: phpredis
- Database Driver & Version: MySQL 8.0.19

### Description:
Whenever I run `php artisan horizon:purge` none of the roque processes is killed:
`php artisan horizon:purge
Observed Orphan: 2074
Observed Orphan: 2075
Observed Orphan: 2076
Observed Orphan: 2272
Observed Orphan: 2273
Observed Orphan: 2274
Observed Orphan: 2275
Observed Orphan: 2276
Observed Orphan: 2277
Observed Orphan: 2280
Observed Orphan: 2281
Observed Orphan: 2282
Observed Orphan: 2283
Observed Orphan: 2284
Observed Orphan: 2285
Observed Orphan: 2286`

This is a fairly new installation of a DigitalOcean server using Forge.

### Steps To Reproduce:
1. Start supervisor (using the server > daemon tool in Forge)
2. Terminate horizon `php artisan horizon:terminate`
3. Restart supervisor `sudo service supervisor reload`
4. Run `php artisan horizon:purge`

I am also not able to kill horizon with ctrl+c whenever I simply run `php artisan horizon`. So this might also be server/Forge/DigitalOcean related. If so you think so, please close this bug :)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
