### ISSUE TITLE
Javascript error on metric detail page 

### ISSUE THREAD

**Issue by wwwroth** [laravel/horizon#805]
- Horizon Version: ^4.0
- Laravel Version: ^7.0
- PHP Version: 7.3.11
- Redis Driver & Version: Redis server v. 3.2.6

### Description:
When accessing a metric detail page, I see a Javascript error in the console `can't assign to property "time" on "<": not an object`

<img width="1440" alt="Screen Shot 2020-03-23 at 5 20 14 PM" src="https://user-images.githubusercontent.com/3310210/77364817-6395bb80-6d2b-11ea-86c5-23f443c22b97.png">

<img width="895" alt="Screen Shot 2020-03-23 at 5 19 42 PM" src="https://user-images.githubusercontent.com/3310210/77364823-6690ac00-6d2b-11ea-8da5-ece19dddfab3.png">

**Comment by driesvints** [comment]
Have you run `php artisan horizon:publish`?

https://laravel.com/docs/7.x/horizon#upgrading-horizon

**Comment by wwwroth** [comment]
Yes, I'm running that command on each deployment and getting a successful response.

```
Copied Directory [/vendor/laravel/horizon/public] To [/public/vendor/horizon]
Publishing complete.
```

**Comment by wwwroth** [comment]
@themsaid let me know if you need any more information. Would love to get these metrics running :)

**Comment by driesvints** [comment]
@wwwroth a pr to fix the bug is the only thing I can think of.

**Comment by themsaid** [comment]
I'm unable to replicate the issue. Wonder if anyone else is having the same issue.

**Comment by wfeller** [comment]
The metrics page doesn't work for me either, but I don't seem to have the same error.

It's a fresh Laravel project and I get this error when using Safari (no problem on Firefox apparently!).

![image](https://user-images.githubusercontent.com/21337627/78694585-2e799380-78fd-11ea-95f3-67e02267e0d1.png)

**Comment by driesvints** [comment]
I don't get any errors on the metrics page and running several apps in production without any problems on the latest version.

**Comment by roberto0arruda** [comment]
I have the same problem, when reading the source, I noticed that the parameter received by the route /metrics/jobs/{id} is id, but received in the controller as show($slug).

In another analysis, I saw that the problem was fixed in the commit: https://github.com/laravel/horizon/commit/48229555075d3f46d782d77794705c60c9c7b379

Released only on horizon v5,
I use: 
- Horizon Version: ^4.0
- Laravel Version: ^7.0

Could you generate a release for horizon v4 containing the same fix?
