### ISSUE TITLE
Ramsey Uuid v4 support

### ISSUE THREAD

**Issue by klarworks** [laravel/horizon#806]
- Horizon Version: 4.x
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version:

### Description:
Problem 1
    - Installation request for ramsey/uuid ^4.0 -> satisfiable by ramsey/uuid[4.0.0, 4.0.0-alpha1, 4.0.0-alpha2, 4.0.0-alpha3, 4.0.0-alpha4, 4.0.0-alpha5, 4.0.0-beta1, 4.0.0-beta2, 4.x-dev].
    - laravel/horizon v4.1.0 requires ramsey/uuid ^3.5 -> satisfiable by ramsey/uuid[3.x-dev].
    - laravel/horizon v4.1.0 requires ramsey/uuid ^3.5 -> satisfiable by ramsey/uuid[3.x-dev].
    - laravel/horizon v4.1.0 requires ramsey/uuid ^3.5 -> satisfiable by ramsey/uuid[3.x-dev].
    - Conclusion: don't install ramsey/uuid 3.x-dev
    - Installation request for laravel/horizon (locked at v4.1.0, required as ^4.1) -> satisfiable by laravel/horizon[v4.1.0].

### Steps To Reproduce:
composer require laravel/horizon

```
    "require": {
        "php": "^7.2.5",
        "ext-pdo": "*",
        "aws/aws-sdk-php": "^3.133",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/nova": "^3.1",
        "laravel/scout": "^8.0",
        "laravel/telescope": "^3.2",
        "laravel/tinker": "^2.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "maatwebsite/excel": "^3.1",
        "maatwebsite/laravel-nova-excel": "^1.2",
        "mll-lab/laravel-graphql-playground": "^2.1",
        "predis/predis": "^1.1"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
```

**Comment by driesvints** [comment]
We still need to update Horizon to work with the new ramsey/uuid library. In the meantime you can require ramsey/uuid:^3.7 directly.
