### ISSUE TITLE
Hope horizon can support lumen

### ISSUE THREAD

**Issue by huangdijia** [laravel/horizon#808]
Some light weight project, I choose lumen, I want to manage jobs with horizon, because it very nice and smart。

**Comment by driesvints** [comment]
No plans for this

**Comment by Rasoul-Karimi** [comment]
how is now? 
No plans for this??? support lumen?!

**Comment by Rasoul-Karimi** [comment]
> No plans for this

how is now?
No plans for this??? support lumen?!
