### ISSUE TITLE
Can't view job details if its has tags

### ISSUE THREAD

**Issue by halah-m** [laravel/horizon#816]
- Horizon Version: v4.2.0
- Laravel Version: v7.4.0
- PHP Version: 7.3

### Description:
if the job have tags the detail page keeps loading, if I click a failed job the page keep loading forever, also when I add any tag to my job
Screen Shot 2020-04-02 at 2 50 10 AM
<img width="1202" alt="Screen Shot 2020-04-02 at 2 49 27 AM" src="https://user-images.githubusercontent.com/29860327/78197073-fbfb1100-748c-11ea-8777-6018c95a25af.png">

Thank you.

**Comment by themsaid** [comment]
Make sure you publish the assets after upgrading.
