### ISSUE TITLE
same failed job reflush some times,the new job has been 

### ISSUE THREAD

**Issue by MonkWang** [laravel/horizon#817]
- Horizon Version: 4.2.0
- Laravel Version: 7.0
- PHP Version: 7.4
- Redis Driver & Version: phpredis 5.0.8
- Database Driver & Version: mysql 5.7.29

### Description:

failed-jobs：if one failed-job has been clicked 3 times reflush button,  the failed-job still faild, then new job has added 3 same job,in the end，the same job are repeated。usually the same failed-job, whether do how many times faild，the new job still is one,
### Steps To Reproduce:
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
//use Illuminate\Support\Facades\Redis;

class RedisJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        for($i=0;$i<10;$i++){
            Redis::set('user:id:'.$i, $i);
        }
    }
}

**Comment by themsaid** [comment]
I don't understand the issue. Can you please elaborate with some screenshots?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
