### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by rikiless** [laravel/horizon#818]
- Horizon Version: 4.2.0
- Laravel Version: 7.4.0
- PHP Version: 7.3.8

### Description:

Activating Night mode of Horizon interface not working.
I think it's stopped working in Laravel <=  7.0 in both cases (existing project & new project).

### Steps To Reproduce:

1.

```
laravel new laravel7
cd laravel7
composer require laravel/horizon
php artisan horizon:install
```

2. Uncomment HorizonServiceProvider.php:24
```php
// Horizon::night();
```

3. Visit http://laravel7.test/horizon/dashboard

<img width="1552" alt="Screenshot 2020-04-02 at 13 45 59" src="https://user-images.githubusercontent.com/589851/78245760-51b0d700-74e8-11ea-91fa-55445dfabd7e.png">

**Comment by driesvints** [comment]
Seems that https://github.com/laravel/horizon/pull/795 broke the way `Horizon::night()` works.

**Comment by driesvints** [comment]
Will be fixed in the next release on Tuesday. Thanks for reporting.
