### ISSUE TITLE
Support worker with multiple queues

### ISSUE THREAD

**Issue by dbpolito** [laravel/horizon#82]
If you have a worker that has multiple queues, like: `high,default` several places doesn't work, like `Current Workload > Jobs` and `Current Workload > Wait`.

Nothing is broken, but it simply doesn't load data properly.

**Comment by themsaid** [comment]
Works for me, you can see I have a supervisor that serves from two queues.

<img width="871" alt="screen shot 2017-08-11 at 12 52 14 pm" src="https://user-images.githubusercontent.com/4332182/29210400-bb6041ca-7e93-11e7-9b19-780aa5341fdc.png">

**Comment by dbpolito** [comment]
Here is what i have:

![image](https://user-images.githubusercontent.com/347400/29214867-2fd46230-7e7f-11e7-82e7-6accda55feb2.png)

and the config:

````
            'default' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'off',
                'processes' => 1,
                'tries' => 1,
            ],
            'blockets__blockets_images' => [
                'connection' => 'redis',
                'queue' => ['blockets', 'blockets_images'],
                'balance' => 'off',
                'processes' => 2,
                'timeout' => 600,
                'tries' => 1,
            ],
````

**Comment by themsaid** [comment]
Thanks, a fix was submitted.
