### ISSUE TITLE
Problem with cakephp/chronos

### ISSUE THREAD

**Issue by sojeda** [laravel/horizon#823]
- Horizon Version: ^4.0
- Laravel Version: 7.5.2
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:
I use "cakephp/chronos": "^2.0" on my project. When i try to install horizon:

 - laravel/horizon 4.x-dev requires cakephp/chronos ^1.0 -> satisfiable by cakephp/chronos[1.3.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7,
1.2.8, 1.x-dev].

### Steps To Reproduce:

composer require cakephp/chronos

composer require laravel/horizon

**Comment by driesvints** [comment]
I'll mark this as an enhancement since nothing is really broken here.

**Comment by mfn** [comment]
Would be awesome if Horizon wouldn't depend on Chronos when Laravel itself already depends on Carbon 😄

**Comment by mfn** [comment]
Wooo! https://github.com/laravel/horizon/pull/826

**Comment by Octet83** [comment]
I'm trying to install Horizon but I've an issue related to cakephp/chronos. I do not use it anywhere but when I try to install Horizon with composer I get the following error : 

> Problem 1
>     - Conclusion: don't install laravel/horizon v4.3.0
>     - Conclusion: remove cakephp/chronos 1.3.0
>     - Installation request for laravel/horizon ^4.3 -> satisfiable by laravel/horizon[4.x-dev, v4.3.0].
>     - Conclusion: don't install cakephp/chronos 1.3.0
>     - laravel/horizon 4.x-dev requires cakephp/chronos ^2.0 -> satisfiable by cakephp/chronos[2.0.0, 2.0.1, 2.0.2, 2.0.3].
>     - Can only install one of: cakephp/chronos[2.0.0, 1.3.0].
>     - Can only install one of: cakephp/chronos[2.0.1, 1.3.0].
>     - Can only install one of: cakephp/chronos[2.0.2, 1.3.0].
>     - Can only install one of: cakephp/chronos[2.0.3, 1.3.0].
>     - Installation request for cakephp/chronos (locked at 1.3.0) -> satisfiable by cakephp/chronos[1.3.0].

**Comment by driesvints** [comment]
@Octet83 try `composer update --with-dependencies`
