### ISSUE TITLE
Unable to upgrade to 4.3.0, chronos package version conflict with Laravel Nova

### ISSUE THREAD

**Issue by tanthammar** [laravel/horizon#828]
Trying to upgrade to v4.3.0 but Composer complains that Laravel Nova v3.4.0 requires cakephp/chronos ^1.0

**Comment by ilvalerione** [comment]
Same issue here. I had to force horizon to `4.2.1` version to avoid composer error during update.

**Comment by driesvints** [comment]
Already fixed on Nova's side: https://github.com/laravel/nova/pull/876
