### ISSUE TITLE
Status as "Inactive" when running horizon on a different container

### ISSUE THREAD

**Issue by mrbenosborne** [laravel/horizon#835]
I am running a Kubernetes cluster with the following (trimmed):

- Deployment One = Laravel application running
- Deployment Two = Laravel Horizon running

I access the horizon dashboard through "Deployment One" but it shows the status of inactive, most likely due to that horizon is not running on the same container, but the queue workers are running on "Deployment Two".

Is there anyway to get the status to show correctly when running separately?

![image](https://user-images.githubusercontent.com/7268075/80570624-0d372f00-89f3-11ea-891b-fa15349ca15f.png)

**Comment by themsaid** [comment]
It's inactive because no master processes are active.

**Comment by mrbenosborne** [comment]
But they are, just not on the same container as the horizon dashboard.

**Comment by themsaid** [comment]
It doesn't have to be on the same container. But must be on the same redis connection.

**Comment by mrbenosborne** [comment]
Hmmmm, it is using the same Redis connection, let me double check.

**Comment by mrbenosborne** [comment]
> Hmmmm, it is using the same Redis connection, let me double check.

It is using the same Redis connection because jobs are being processed.... :/

**Comment by themsaid** [comment]
Something is broken somewhere in your setup. Horizon is unable to read any Masters running in the redis instance. Are you sure you're on the latest Horizon version?

**Comment by mrbenosborne** [comment]
> Something is broken somewhere in your setup. Horizon is unable to read any Masters running in the redis instance. Are you sure you're on the latest Horizon version?

Ok I will take a deeper look, thanks for your help on this, I installed Horizon yesterday, the version is 4.3.

**Comment by themsaid** [comment]
@mrbenosborne what was it?

**Comment by mrbenosborne** [comment]
I can't seem to fix it, I have horizon using the same connection as the queue, see below:

## queue.php
```php
'connections' => [
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 600,
            'block_for' => null,
        ],
],
```

## horizon.php
```php
    'environments' => [
        'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default,email,scout'],
                'balance' => 'auto',
                'processes' => 10,
                'tries' => 3,
                'timeout' => 570,
            ],
        ],

        'local' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default,email,scout'],
                'balance' => 'auto',
                'processes' => 3,
                'tries' => 3,
            ],
        ],
    ],
```

**Comment by plakhin** [comment]
Same, on both local and production environments.

Laravel version: 8.10.0
Horizon version: 5.2.1

Horizon config:
```
    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default', 'media'],
            'balance' => 'auto',
            'maxProcesses' => 1,
            'tries' => 3,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-1' => [
                'maxProcesses' => 5,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
            ],
        ],

        'local' => [
            'supervisor-1' => [
                'maxProcesses' => 3,
            ],
        ],
    ],
```

Queue config:
```
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            'block_for' => null,
        ],
```

Database config:
```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],
```

**Comment by msassa** [comment]
I have the same problem with Horizon 5 ... any way to fix this?

**Comment by boka18** [comment]
I have the same issue!

**Comment by alexanderkraemer** [comment]
Could we reopen this issue?
I have the same problem!

**Comment by alexanderkraemer** [comment]
@mrbenosborne Did you find any solution to this problem?

**Comment by mrbenosborne** [comment]
@alexanderkraemer Hey! I remember this being an issue that I created somehow and fixed it but for the life of me I cannot remember what it was!

Let me have a think and come back to you, I'm sure i'll remember what it was.

**Comment by alexanderkraemer** [comment]
@mrbenosborne Thanks!

**Comment by mrbenosborne** [comment]
Perhaps a few things to check: 

1. Under config/database.php, at the bottom the redis connection settings, are they all correct? Not pointing to a localhost redis server or something?
2. Check environment variables, most importantly Redis environment variables?
3. Are your environments setup correctly, according to your APP_ENV? https://laravel.com/docs/8.x/horizon#configuration

**Comment by r14ull** [comment]
I fixed this by making sure my env 'APP_NAME' where the same on both environments

**Comment by alexanderkraemer** [comment]
Unfortunately that did not solve it :/

**Comment by paul-a-byford** [comment]
have you started horizon with the artisan command `php artisan horizon` ?

https://laravel.com/docs/8.x/horizon#running-horizon

**Comment by dimsav** [comment]
I got this error after moving my redis server to a new machine. What fixed it for me was to manually restart the daemon running `php artisan horizon`. 

For some reason (probably because the config was updated), running `horizon:terminate` was not enough.

**Comment by wrabit** [comment]
Using `php artisan horizon` is fine, but when I switched to `artisan horizon:work --queue=queue1,queue2` the dashboard displays 'inactive' yet jobs are still processed.

Is there a way to get the dashboard to work correct when using the `horizon:work` command?

**Comment by wrabit** [comment]
To confirm why I think this issue is not resolved. When you want to offload the queues to run on separate worker instances you will run `php artisan horizon:work --queue=[queue_name]` from the instance. By running `php artisan horizon` on the main app machine (where you see dashboard) does make the 'inactive' - 'active' but will also start processing jobs which you do not want in this case.

**Comment by okedialf** [comment]
@mrbenosborne , @wrabit @dimsav, @alexanderkraemer @r14ull , @boka18 , @msassa incase you hadn't solved this, it's caused by a datetime difference on the different containers or server environments. To solve it, I synced the date time using an ntp service.  Figured it out by taking a peek at how horizon works here vendor/laravel/horizon/src/Repositories/RedisMasterSupervisorRepository.php

**Comment by ricventu** [comment]
same issue here

**Comment by adampatterson** [comment]
I'm not using containers but am running 3 app servers, a worker, and a shared cache. 

When I load `/horizon` it said that it was inactive. When I logged into the worker and ran `php artisan horizon:status`: **Horizon is inactive.**

When I ran `php artisan horizon:supervisors`: **No supervisors are running.**

At least in Forge the Damon reported that the horizon was running.

My deployments all include `$FORGE_PHP artisan horizon:terminate` but the only thing that brought everything back up was to run `php artisan horizon`. 

Is there an issue between the supervisor task and horizon properly reporting its status?

**Comment by cdwieber** [comment]
The comment above about ensuring `APP_NAME` was identical across servers is what fixed it for me. However, `php artisan horizon:terminate` wasn't enough to bring it back up in the dashboard; I had to go into Forge and restart the supervisor daemon completely. After that, everything came back up in the dashboard as expected.

**Comment by motters** [comment]
Ended up here from google so thought i'd add my solution. I was running `php artisan horizon:work` instead of `php artisan horizon` . Maybe it'll save someone 10 minutes.

**Comment by adampatterson** [comment]
I figured I'd also post my solution, I am using Forge and my worker was unable to communicate with other other servers because I had to setup a network in Forge.

**Comment by rvanbaalen** [comment]
What turned out to be the solution to this? Im running a standalone worker server and my web servers keep reporting that Horizon is inactive, while it's actually executing jobs.

**Comment by llstarscreamll** [comment]
I encountered a mismatch with the cakephp/chronos package, which is utilized by laravel/horizon (4.3.5). When Laravel workers attempt to initiate, an error is logged, as shown below:

```
[2025-03-19 22:42:01] production.ERROR: Since 2.4 - addSecond() is deprecated. Use addSeconds() instead. {"exception":"[object] (ErrorException(code: 0): Since 2.4 - addSecond() is deprecated. Use addSeconds() instead. at ./vendor/cakephp/chronos/src/Traits/ModifierTrait.php:863)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 ./vendor/cakephp/chronos/src/Traits/ModifierTrait.php(863): trigger_error()
#2 ...
"}
```

To resolve this error, I set version 2.3.3 of cakephp/chronos in my composer.json file, as illustrated below:

```json
{
    "require": {
        "laravel/horizon": "^4",
        "cakephp/chronos": "2.3.3",
    }
}
```

Following this modification, I executed `composer update`.
