### ISSUE TITLE
route prefix not applied on horizon routes

### ISSUE THREAD

**Issue by beaumind** [laravel/horizon#837]
- Horizon Version: 4.3.2
- Laravel Version: 7.8.1
- PHP Version: 7.4.5
- Redis Driver & Version: predis/phpredis 1.1.1
- Database Driver & Version: mysql version 8

'horizon' prefix is not apply on generated routes, so there are route conflicts with main routes. the generated routes are like '/api/workload' without 'horizon' prefix, that causes 403 errors on site main pages.

Steps To Reproduce:
run composer require laravel:horizon and that's it. it breaks the site on production

**Comment by alireza-h** [comment]
I have the same issue. it is ok on local env, but doesn't work on prodcution.

**Comment by miladh06** [comment]
> * Horizon Version: 4.3.2
> * Laravel Version: 7.8.1
> * PHP Version: 7.4.5
> * Redis Driver & Version: predis/phpredis 1.1.1
> * Database Driver & Version: mysql version 8
> 
> 'horizon' prefix is not apply on generated routes, so there are route conflicts with main routes. the generated routes are like '/api/workload' without 'horizon' prefix, that causes 403 errors on site main pages.
> 
> Steps To Reproduce:
> run composer require laravel:horizon and that's it. it breaks the site on production

Me Too

**Comment by driesvints** [comment]
Horizon just works fine for me on several apps in production. Please give very specific steps to reproduce.

**Comment by beaumind** [comment]
@driesvints as I mentioned I just ran  'composer require laravel:horizon' on production and when new cached routes generates, horizon routes was without any prefix

**Comment by driesvints** [comment]
<img width="1798" alt="Screenshot 2020-05-04 at 12 05 44" src="https://user-images.githubusercontent.com/594614/80955431-9ab5bd00-8dff-11ea-92e4-ac976caf5b88.png">

Working fine for me with a custom prefix and route caching enabled.

**Comment by beaumind** [comment]
my problem is only on production, it's working properly on local. 
here is generate cache route example:
`    'horizon.index' => 
    array (
      'methods' => 
      array (
        0 => 'GET',
        1 => 'HEAD',
      ),
      'uri' => '{view?}',
      'action' => 
      array (
        'domain' => NULL,
        'middleware' => 'web',
        'uses' => 'Laravel\\Horizon\\Http\\Controllers\\HomeController@index',
        'controller' => 'Laravel\\Horizon\\Http\\Controllers\\HomeController@index',
        'namespace' => 'Laravel\\Horizon\\Http\\Controllers',
        'prefix' => NULL,
        'where' => 
        array (
        ),
        'as' => 'horizon.index',
      ),
      'fallback' => false,
      'defaults' => 
      array (
      ),
      'wheres' => 
      array (
        'view' => '(.*)',
      ),
      'bindingFields' => 
      array (
      ),
    ),`

**Comment by obrunsmann** [comment]
@beaumind have you found a solution? Experiencing same issue with the route registered on root level :/

```
GET|HEAD | {view?}                                                                                    | Laravel\Horizon\Http\Controllers\HomeController@index
```
