### ISSUE TITLE
[Proposal] Only display allowed properties of the payload for failed jobs insight

### ISSUE THREAD

**Issue by lkmadushan** [laravel/horizon#84]
Sometimes we want hide sensitive information from logs because of security reasons.

In the current situation when queue jobs failed it displays all the properties of the object in failed jobs insight.

Ex:

```
User
- id
- name
- email
```

Above example user object has `name` and `email` property, but when queue job failed we only want to display `id` and `name`. We want to ignore `email` when log payload

**Comment by themsaid** [comment]
You should limit access to Horizon dashboard to only people who need to see it, Horizon displays the details of a failed job for debugging reasons, there's no way we can configure what to show and what not to show, we just unserialize the job and display its data.

**Comment by rolfdenhartog** [comment]
Hi @themsaid! I was wondering if it's now possible to hide sensible data?
