### ISSUE TITLE
"Delayed until" on the Job detail screen is incorrect when a DateTime object is passed with TimeZoneType != 3

### ISSUE THREAD

**Issue by mattyh88** [laravel/horizon#845]
- Horizon Version: 3.7.2
- Laravel Version: 6.14.0
- PHP Version: 7.4.2
- Redis Driver & Version: phpredis 6.0.1
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.27

### Description:
The "delayed until" label on the Job detail screen is incorrect when a DateTime object is passed to Job's delay() method, with timezone_type != 3 (e.g. timezone_type: 1 & timezone: "+02:00")
The good thing is, that the job is executed at the correct time. So it's just the label that's incorrect. 

Probably it's because MomentJS is used to display the delayed_until label and it's tz() method is only accepting strings like 'Europe/Brussels', instead of "+02:00"? 

### Steps To Reproduce:
    $dateTime = Carbon::parse("2020-05-28T10:00:00+02:00");

    MyJob::dispatch()
            ->delay($dateTime);

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by mattyh88** [comment]
Fair enough .. I'll test this a bit later. 

In the mean time, I saw that new commits have been done on the v3 branch. Would it be possible to release a 3.7.3 tag? As this will fix the delayed_until timezone issue on the index screen. Thanks :) (Please see commit: https://github.com/laravel/horizon/commit/bee4f2396a46cb4b181c4ba8565f346a3df6db34)

**Comment by driesvints** [comment]
3.x isn't maintained anymore. Please upgrade to 4.x
