### ISSUE TITLE
Horizon don't work when .env files have the same environment and don't have .example in file name

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/horizon#846]
- Horizon Version: 4.3.3
- Laravel Version: 7.13.0
- PHP Version: 7.3.18
- Redis Driver & Version: predis/phpredis 5.0.9 / 6.0.4 & 1.1.1
- Database Driver & Version:

### Description:
When `.env` file and at least one more `.env` file without `example` extension have set up the same `APP_ENV`, then horizon only start but don't processed jobs
and
int that scenario are forced HTTPS to use in web horizon dashboard.
Example of files and content:
1. `.env` have `APP_ENV=dev`
2. `.env.dev` have `APP_ENV=dev`.
Sollution: on second file add extension `.example`. Then we have:
1. `.env` have `APP_ENV=dev`
2. `.env.dev.example` have `APP_ENV=dev`.
and everything working as expected.

### Steps To Reproduce:
1. Create files `.env` and `.env.xxx` where `xxx` can be anything expect `example`.
2. Fill up these files with the same `APP_ENV`, for example `local`, `production`, `something`.
3. Fire up horizon with `php artisan horizon`.

In previous version of Laravel and Horizon, I don't have that issue.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
