### ISSUE TITLE
Delayed job not executing until another job is dispatched behind it

### ISSUE THREAD

**Issue by mstralka** [laravel/horizon#848]
- Horizon Version: 4.3.3
- Laravel Version: 7.15.0
- PHP Version: 7.4.6
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version: MySQL 5.7.30

### Description:

There appears to be a problem with how Horizon manages delayed jobs.

I dispatched a job with a 60-second delay like this:

~~~php
dispatch(new VerifyDomain($domainName))->delay(now()->addSeconds(60));
~~~

I see the job appear in Horizon on the Pending Jobs screen like this
![image](https://user-images.githubusercontent.com/439680/84279624-3b388480-ab04-11ea-87b8-0d1372b58954.png)

Even though the delay was only 60 seconds and the job should have executed at `14:16:00 UTC`, it is now `14:22 UTC` on the server and the job has not executed. Horizon is managing several queues on this server but there are no other pending jobs that would cause this specific job to be delayed longer than expected.

That job is not be processed until I push another `VerifyDomain` job to the same queue - but then that new one is delayed indefinitely until another job.

Thank you
Mark

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mstralka** [comment]
In case this helps anyone else, the problem appeared to be having `sleep` set to `0` in `horizon.php`. I changed it to `2` (seconds) and this weird delay issue went away.
