### ISSUE TITLE
Job metric broken

### ISSUE THREAD

**Issue by Propaganistas** [laravel/horizon#849]
- Horizon Version: 4.3.3
- Laravel Version: 7.15.0
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis 5.2
- Database Driver & Version: MySQL 5.7

### Description:

I'm on a fresh install of Laravel and Horizon.
When navigating to the Job metric page the loading indicator keeps spinning for eternity while the console shows a peculiar error:

![Schermafbeelding 2020-06-11 om 17 59 01](https://user-images.githubusercontent.com/6680176/84409455-bb96dc80-ac0d-11ea-9d7e-69b37b1bc4f4.png)

Upon inspecting the actual response of the page's XHR request I see the page's HTML instead of some API json response.

### Steps To Reproduce:

1. Freshly installing Laravel and Horizon
2. Publish Horizon assets + schedule horizon snapshots every five minutes
2. Create some random job (like in the screenshot above a job that updates a date in the DB)
3. Use the scheduler to queue the job every minute
4. Wait..

**Comment by driesvints** [comment]
Works fine for me. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Propaganistas** [comment]
Hi @driesvints 

I managed to track down the issue. I'm hosting my apps on Azure, and noticed that backward slashes in the job class (that's part of the URL) are being converted to forward slashed. Hence Laravel handles this as a completely different (but missing) route instead of the route with a parameter:

![Schermafbeelding 2020-06-12 om 16 56 08](https://user-images.githubusercontent.com/6680176/84516145-aaada000-accd-11ea-9209-65344ab04121.png)

![Schermafbeelding 2020-06-12 om 16 48 23](https://user-images.githubusercontent.com/6680176/84516031-85209680-accd-11ea-992a-bd1216bc266d.png)

Surprisingly, that conversion seems to be "correct behavior". Backslashes are not amongst the characters allowed in a HTTP or HTTPS URL (as per [RFC 1738](http://www.rfc-editor.org/rfc/rfc1738.txt)), therefore they should be escaped. Note that the RFC explicitly mentions backslash as an unsafe character:

> Other characters are unsafe because gateways and other transport agents are known to sometimes modify such characters. These characters are "{", "}", "|", "\", "^", "~", "[", "]", and "`".
> All unsafe characters must always be encoded within a URL.

So I think the solution to this bug is: explicitly encode backslash URLs when building the api URL...

**Comment by driesvints** [comment]
Hmm, the url seems properly encoded for me so not sure why it's not for you.

**Comment by Propaganistas** [comment]
Yeah, i can see the url is indeed properly encoded upon request, but the actual received URL by the application is transformed; all backward slashes, encoded or not, are becoming forward ones.

I'm thinking in the direction of Azure's internal load balancer. Unfortunately that's completely out of reach.

Any chance to, let's say, convert the request signature to a GET parameter so the slashes can never be seen as route segments? Or apply Some serialization logic in the class string... Just thinking out loud?
