### ISSUE TITLE
Horizon cached on Zenkins

### ISSUE THREAD

**Issue by tienluckyfor** [laravel/horizon#850]
- Horizon Version: ^3.4
- Laravel Version: 5.8
- PHP Version: 7.1
- Redis Driver & Version: predis/phpredis ^1.1
- Database Driver & Version: PostgresQL 11.5

### Description:
<img width="1440" alt="Screen Shot 2020-06-16 at 13 07 04" src="https://user-images.githubusercontent.com/62745044/84737548-573f9880-afd2-11ea-9be7-956d83196986.png">

My server run on Zenkins and I was re-build. 
Although I change queen name but in Horizon dashboard until call old jobs.
P/s: New last name is : _tmp_17
Old name is : _tmp_13

### Steps To Reproduce:
As I thought maybe horizon have cached.
So what should I do in this situation, that make my app doesn't work properly.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
