### ISSUE TITLE
Queue load presented as a stacked graph

### ISSUE THREAD

**Issue by andrei-livadariu** [laravel/horizon#852]
In my Horizon projects I often ask myself the following question:
How often does it happen that jobs pile up, and how long does it take for the pile to be processed?

I think the current metrics, Throughput and Runtime, don't provide insight into this matter, so I'd like to propose one more metric.

For lack of a better term, I'm calling this "Queue Load", and I think it should be presented as a stacked graph. Using my amazing artistic skills I have produced a crude mockup of how it would look:

![queue-load](https://user-images.githubusercontent.com/1064610/85000622-57b76b00-b15b-11ea-9e1a-fc17250a761a.png)

The point is that you can see the jobs as they come in advance through the various states. This graph can be generated both per job and per queue, just like the current metrics.

Depending on your use case, a healthy queue would look like the following:

- For a constant stream of jobs, the yellow and green areas should advance diagonally and parallel to each other
- For a burst workload, you should see large patches of yellow every now and then, which are then eaten up by the green areas

If something is wrong with the queues, it's easy to notice. Jobs piling up would flood the graph in yellow, while a burst failures would lead to a red spike.

I haven't contributed to the project before, but if this feature gets some support and constructive criticism, I might make a PR for it.

**Comment by driesvints** [comment]
Gonna leave this to @themsaid to see what his thoughts are on this.

**Comment by themsaid** [comment]
looks good to me. You may want to send a PR to show how you'll manage to store the stats for the graph. Remember, storing too much stats may eat the server memory.

**Comment by mfn** [comment]
I would love to get such insights.

How is "Completed" to be understood, at what point this is vanish/decrease? Or never? So the graph as a whole always goes up? Sorry, maybe dump question and I just missed something 😅

**Comment by andrei-livadariu** [comment]
@mfn You make a good point. The way I see it, this metric would look at the jobs that are currently in the system, which are bound by the trimming configuration. So as successful jobs get trimmed, the graph would go down.

I haven't started implementing this, so I haven't figured the specifics yet.

**Comment by driesvints** [comment]
Going to close this as we won't be working on this ourselves. We're still open to PRs.
