### ISSUE TITLE
Recent jobs tab disappeared/not displaying

### ISSUE THREAD

**Issue by jfoliveira** [laravel/horizon#854]
- Horizon Version: 4.3.3
- Laravel Version: 7.16.1
- PHP Version: 7.2.21
- Redis Driver & Version: phpredis #.#.#
- Database Driver & Version:

### Description:
Just upgraded from `Horizon 3.7 + Laravel 6` to `Horizon 4.3.3 + Laravel 7` and can no longer see the `Recent Jobs` tab. See image below:

![image](https://user-images.githubusercontent.com/1943318/85043953-5f7b0d80-b163-11ea-910d-706366c531a5.png)

Any advice on how to bring/enable the recent jobs tab back so I can see my failing, pending and successful jobs on the same view?
Any `config/horizon.php` setting that I should turn on after upgrade to Horizon 4?

The `Recent jobs` page it's a really useful view for our team to watch not only failed/incoming jobs, but also have a quick visual feedback (`green` vs `red` icons) of how jobs are finishing, and also to watch if some successful job it's taking longer than usual.

Looking at the Release notes there is no mention of removal of `Recent Jobs` screen, just found mentions to  [a separate screen for completed jobs](https://github.com/laravel/horizon/releases/tag/v4.0.0)

### Steps To Reproduce:
Just access the dashboard running Laravel 7 + Horizon 4.3.3

**Comment by driesvints** [comment]
Did you read the upgrade notes and republished the assets? https://github.com/laravel/horizon/blob/4.x/UPGRADE.md

**Comment by driesvints** [comment]
Ah actually, recent jobs has been split up in pending and completed jobs. So it's no longer available in one view.

**Comment by jfoliveira** [comment]
Ooohh. :-(
That was definitely a very useful view to me and my team.
Are PRs to bring the `Recent jobs` view back welcome?
Or you just don't plan on keeping a consolidated view?

**Comment by driesvints** [comment]
No, it wasn't practical to aggregate the data in a single view. The same data is available in separate tabs now.
