### ISSUE TITLE
Failed job list is empty but response is not empty

### ISSUE THREAD

**Issue by mvaliolahi** [laravel/horizon#855]
- Horizon Version: 3.2
- Laravel Version: 5.8
- PHP Version: 7.3.8
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version: MySQL 5.7

#### The horizon failed job section does not show anything, but Browser inspect network to show the response.

Also, filter response is like: 

{"jobs":[],"total":0}

I have no idea about reproducing it! to debug.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
