### ISSUE TITLE
Tags won't display if there are duplicate values

### ISSUE THREAD

**Issue by immanolo** [laravel/horizon#856]
- Horizon Version: 3.2
- Laravel Version: 5.7.28
- PHP Version: 7.2.24
- Redis Driver & Version: predis/phpredis 1.1.1
- Database Driver & Version: N/A

### Description:
I've discovered that if the job has duplicate value for its tags it won't display on horizon recent jobs or failed jobs.
As I investigate the issue the job has tags based on the horizon API but it is in JSON/Object format so it will surely not show in the front since the expected value of tags must be an array.
To be sure that this not only happening in our project I analyze how horizon determines tags for each job and I found out that when the horizon determines tags for each job it removes duplicate values by using [unique](https://laravel.com/docs/7.x/collections#method-unique)() in collected data for tags and because of it if there are duplicate values it returns an associative array and before it sets the value of job payload it will perform json_encode and it will cause the tags to be object/JSON.

> more info: https://www.php.net/manual/en/function.json-encode.php

### Steps To Reproduce:
1. In your job put tags manually by creating tags() method and set the value of it with a duplicate.
```PHP
    /**
     * Returns job tags
     *
     * @return array
     */
    public function tags()
    {
        return [
            'Tag1',
            'Tag1',
            'Tag2'
        ];
    }
```
2. Dispatch your job and monitor it on the horizon.
![image](https://user-images.githubusercontent.com/53388751/85377443-ac981e80-b56b-11ea-9768-9ec4fd51414a.png)
![image](https://user-images.githubusercontent.com/53388751/85377513-ca658380-b56b-11ea-83a8-95ad788963a2.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by immanolo** [comment]
Hi @driesvints,

I've updated the issue, the problem still persists.

Thanks!

**Comment by driesvints** [comment]
Hey @immanolo. Tags need to be unqiue.

**Comment by immanolo** [comment]
Got it @driesvints thanks!
