### ISSUE TITLE
a timed out job won't retry

### ISSUE THREAD

**Issue by chenghung** [laravel/horizon#858]
- Horizon Version: 4.3.3
- Laravel Version: 7.6.2
- PHP Version: 7.3.18
- Redis Driver & Version: predis/phpredis 1.1.1
- Database Driver & Version: MySQL

### Description:

If job execution timed out, this job is returned to pending jobs list, but it won't be retried again.

### Steps To Reproduce:

1. create a simple job that sleep more than 3s, make job always be timed out and killed.
2. defined $timeout = 3
3. defined $tried = 2

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
