### ISSUE TITLE
"Delayed" tag doesn't show up for Closure jobs

### ISSUE THREAD

**Issue by shalvah** [laravel/horizon#859]
- Horizon Version: 4.3.3
- Laravel Version: 7.17.2
- PHP Version: 7.4.2
- Redis Driver & Version: phpredis 5.2.2
- Database Driver & Version: SQLite 3.22.0

### Description:
The "Delayed" tag is shown for Job classes but not for Job Closures

### Steps To Reproduce:
In my code, I dispatch a Closure Job and a Class job,both delayed.
   ```php

        dispatch(new SendNewsletter)->delay(now()->addMinutes(3))
        dispatch(function () {
        })->delay(now()->addMinutes(7)); 
  ```

Only the class is marked as "Delayed" in the Horizon UI.

![image](https://user-images.githubusercontent.com/14361073/86521804-40f86000-be4d-11ea-8b9d-fde4eb0397f6.png)

**Comment by driesvints** [comment]
The JS library that's used in Horizon can't unserialize closure payloads. We'd be happy for any prs that helps implement this.

**Comment by Cannonb4ll** [comment]
I was responsible for adding the delayed label. Ill see if I can work on a enhancement for closures tomorrow.

**Comment by Cannonb4ll** [comment]
Just tried for an hour to see if a fix was possible. @driesvints is indeed correct, the library is unable to unserialize the closures for some reason.

I've looked for other libraries and tested them:

https://github.com/naholyr/js-php-unserialize & https://locutus.io/php/var/unserialize/

Sadly, no go.

**Comment by driesvints** [comment]
Going to close this as we believe this isn't possible. If anyone has a solution feel free to PR.
