### ISSUE TITLE
Job preview is broken

### ISSUE THREAD

**Issue by kamui545** [laravel/horizon#871]
- Horizon Version: 4.3.3
- Laravel Version: 7.24.0
- PHP Version: 7.4.9

### Description:

The job preview is broken on some cases, I don't really know why but `phpunserialize` and `prettyPrintJob` seem to be the cause. The parsing silently fails for some payload and you are stuck with the loading screen, fetching indefinitely the job even though the request succeed and JSON is valid.

Related issues:

- https://github.com/laravel/horizon/issues/620
- https://github.com/laravel/horizon/issues/815

### Steps To Reproduce:

```bash
git clone https://github.com/kamui545/horizon-test.git
cd horizon-test
npm install

node test.js #fail
php test.php #success
```

You can see that `phpunserialize` from the node package used by Horizon failed to parse `payload.data.command` in `error.json`, PHP parsed it just fine. Last release was more than 6 years ago, can't we just use `json_encode` and `json_decode` instead?

**Comment by driesvints** [comment]
Yes this is indeed problematic it seems. I'm not really sure is json_encode is a good solution here though.

**Comment by themsaid** [comment]
You'll need to share the errors in the console when this happens.

**Comment by kamui545** [comment]
> You'll need to share the errors in the console when this happens.

Sadly, as I stated, it fails silently, there are no errors in the console.

Just browse a non-existing job `/horizon/failed/0123456`, and you will see what I am experiencing:

Horizon will try loading over and over again `/horizon/api/jobs/failed/0123456` (which respond 200 ?!). No errors, no feedbacks, nothing.

In my case however, the job does exist, but the parsing of the payload has issues.
I made a SQL dump with a record that should allow you to reproduce the issue, please let me know.

[failed_jobs.sql.zip](https://github.com/laravel/horizon/files/5118679/failed_jobs.sql.zip)

**Comment by driesvints** [comment]
@kamui545 @themsaid has patched this: https://github.com/laravel/horizon/commit/57903edbf845e3d401a9d188199d89f2ed203ff1

Will release tomorrow.

**Comment by kamui545** [comment]
@driesvints Hi, could please re-open the issue?

I just tried with the new release and the issue is still there (I did re-publish the assets).
I don't think adding a try / catch would be enough to fix that issue since there is no exceptions logged in the console.

**Comment by themsaid** [comment]
How about you attempt to fix it since you are the only person who can replicate the issue? Feel free to open a Pull Request, will be happy to review it and provide assistance if you can show us what you think will help deal with your special case.

**Comment by kamui545** [comment]
> How about you attempt to fix it since you are the only person who can replicate the issue?

After reworking my environment I finally managed to build horizon.
I had some issues with NPM somehow, which is why I could not go further in my debugging.

So, it appears there is nothing logged by VueJS because of the "production" build, but the error is there and the try/catch indeed does the trick.

However, it was not applied to every components, only recent-jobs. I will submit a PR after checking further.

**Comment by kamui545** [comment]
PR open https://github.com/laravel/horizon/pull/880
