### ISSUE TITLE
Delayed Jobs

### ISSUE THREAD

**Issue by jhemmmm** [laravel/horizon#882]
- Horizon Version: v4.3.3
- Laravel Version: v7.25.0
- PHP Version: 7.4.8
- Redis Driver & Version: redis 3.2.12

### Description:
There is seem to be a little problem on my delayed jobs. I don't know why but I am receiving delayed jobs for too long. It says delayed for 2 hours while I did not dispatch that job for 2 hours. 
![image](https://user-images.githubusercontent.com/14343151/92192041-bd341180-ee97-11ea-92ff-9cff101f9211.png)
![image](https://user-images.githubusercontent.com/14343151/92192081-d046e180-ee97-11ea-8f39-c87e018bbb47.png)

### Steps To Reproduce:
Create a simple job.
```
ProcessDrive::dispatch(0)->delay(now()->addMinutes(15));

class ProcessDrive implements ShouldQueue
{

handle:
$retry = 0;
$retry++;

$found = ($available == 0) ? 15 : 31; 
if($retry <= 5)
ProcessDrive::dispatch($retry)->delay(now()->addMinutes($found));
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
