### ISSUE TITLE
Setting min/max per queue instead of Horizon instance

### ISSUE THREAD

**Issue by likeadeckofcards** [laravel/horizon#883]
I recently came across the the minProcesses/maxProcesses. This feature would be useful for a project that I am working on but unless I am reading this wrong it appears to be set for the Horizon instance and not configurable per queue instance. Is this something that could be added so a specific queue can be scaled within the parameters defined?

Example:
queues: orders, default, imports
Normally orders has the bulk of the processing but when running an import the import queue can get a large backlog that has a rate limit on it to prevent overloading an API. This backlog takes up the majority of the processes meaning the orders queue processes drops down to 1 process unless the total number of jobs on the orders queue is high enough to get more processes allocated.

**Comment by themsaid** [comment]
If you're using auto balancing this shouldn't make any difference. The balancer will assign a number of workers to each queue depending on how busy it is.
