### ISSUE TITLE
getting Illuminate\Queue\MaxAttemptsExceededException in laravel jobs

### ISSUE THREAD

**Issue by jigarhalani** [laravel/horizon#886]
- Horizon Version: ^4.0
- Laravel Version: ^7.11
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis ^1.1
- Database Driver & Version: MySQL & 8

### Description:
I have one job which will take 1 hour to run, I already created job-based on laravel documentation, here is my job file.

```
<?php


namespace App\Modules\Csv\Jobs;

use App\Jobs\Job;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use League\Csv\Reader;
use Phone;

/**
 * A single excel import job, which can be pushed on to a queue
 */
class UploadCsvDataInTable extends Job implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels, Dispatchable,Queueable;

    public $timeout = 172800;
    /**
     * The excel to import
     *
     * @var App\BulkUpload
     */
    protected $csvUpload;

    /**
     * Create a new job instance.
     *
     * @param App\FeedImport
     *
     * @return void
     */
    public function __construct(CsvUpload $csvUpload)
    {
        $this->csvUpload = $csvUpload;
    }

    public function handle()
    {

        app(CsvUploadService::class)->uploadCsv($this->csvUpload);

    }
}
```

here is code for how I am calling that job.

`UploadCsvDataInTable::dispatch($csvUpload)->onConnection('redis')->onQueue('low');`

here is my configuration for queue & horizon

```
// horizon.php
 'production' => [
            'supervisor-1' => [
                'connection' => 'redis',
                'queue'      => ['high', 'default', 'low'],
                'balance'    => 'simple',
                'processes'  => 6,
                'tries'      => 3,
            ],
 ],

  //queue.php

  'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'),
            'retry_after' => 90,
            'block_for' => null,
        ],
```

also I am using QUEUE_CONNECTION=sync

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
