### ISSUE TITLE
UI bug: Jobs and Queues metrics not accessible

### ISSUE THREAD

**Issue by opiy-org** [laravel/horizon#887]
- Horizon Version: 4.3.5
- Laravel Version: 7.28.0
- PHP Version: 7.4.3
- Redis Driver & Version: predis 1.1.4
- Database Driver & Version: postgres 10

### Description:
In user interface can't view job or queue metrics.

### Steps To Reproduce:
1. open horizon UI
2. go to "metrics" page
3. open tab "Jobs" (same for tab  "Queues")
4. click on any job
5. new page not opened
6. got js error:
`app.js?id=a2e36b7a4f248973b22b:2 Uncaught (in promise) TypeError: Cannot create property 'time' on string '<'`

Error caused by ajax call to api route:
.. api/metrics/jobs/{job**SLug**}

In _vendor/laravel/horizon/routes/web.php_ there are two wrong routes:
` Route::get('/metrics/jobs/{id}', 'JobMetricsController@show')->name('horizon.jobs-metrics.show');`
and
` Route::get('/metrics/queues/{id}', 'QueueMetricsController@show')->name('horizon.queues-metrics.show');`
It uses {**id**} route param.

But in controllers, we can see "**slug**" param: 
_vendor/laravel/horizon/src/Http/Controllers/JobMetricsController.php_:
`  /**
     * Get metrics for a given job.
     *
     * @param  string  $slug
     * @return \Illuminate\Support\Collection
     */
    public function show($slug)`

**Comment by driesvints** [comment]
Works just fine for me. Think you might need to publish your assets (see updating Horizon in docs).

**Comment by luizeof** [comment]
Same Here

**Comment by driesvints** [comment]
I tried the exact steps to reproduce from the above and couldn't re-create it which means there's something missing here. If anyone can push a test repo from a fresh Laravel install and provide steps on setting the environment I can take another look. Please commit your changes separately from the skeleton.
