### ISSUE TITLE
5.0 upgrade guide

### ISSUE THREAD

**Issue by Eldair** [laravel/horizon#889]
Hello,

Unsure if this is the right place for this but there are multiple changes which are unclear:
Is `max_processes` a replacement for `processes` config, or is it only for auto balance option and `processes` should still be used for simple balancing?
Is `max_time` a replacement for `timeout` config?

**Comment by driesvints** [comment]
I'll investigate with @themsaid

**Comment by themsaid** [comment]
`max_processes` has been there since before Horizon 5. It's used when auto balancing.

`max_time` is a newly added feature to Laravel 8.

**Comment by Eldair** [comment]
So, if balancing is simple then processes config is still ok?
Also, is max_time a replacement for the previous timeout (job fails after if it is not completed before max_time expires)?

**Comment by hxnk** [comment]
@Eldair: `timeout` defines how long a job may run, `maxTime` is about how long a worker should run. Checkout https://laravel.com/docs/8.x/queues#running-the-queue-worker:

> The --max-time option may be used to instruct the worker to process jobs for the given number of seconds and then exit. This option may be useful when combined with Supervisor so that your workers are automatically restarted after processing jobs for a given amount of time:

```
// Process jobs for one hour and then exit...
php artisan queue:work --max-time=3600
```
