### ISSUE TITLE
minProcesses has no effect with balance=auto

### ISSUE THREAD

**Issue by robj** [laravel/horizon#897]
- Horizon Version: 5.0
- Laravel Version: 8.0
- PHP Version: 7.4

### Description:

with minProcesses=1  & balance=auto:

workers per queue will still scale down to 0

Jobs will be assigned to a queue that has been scaled down to 0 for very long periods (eg. >10mins) before a worker is finally assigned to the queue. It is important to us to have at least 1 worker always assigned to priority queues to prevent delays.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by robj** [comment]
I don't think rapidly closing all Issues reported to a project with templates makes for a good project ;)

**Comment by driesvints** [comment]
@robj can you please try a support channel first? Happy help you out if you've confirmed that this is a bug.

**Comment by robj** [comment]
@driesvints - Looking at closed tickets, I am the second person to report a similar issue in 48hrs. If you left Issues open instead of 'OCD Inbox Zeroing' then that would have been more visible.

**Comment by driesvints** [comment]
@robj I just tried this and as I suspected this worked just fine for me. I'm suspecting there's something else at fault for causing this to fail for you but that's probably best to be figured out as a support request through one of the links above.

I closed this because I don't have the time to provide support for every single issue. There's about a hundred issues a day that I handle and if I had to tackle each of them myself personally I wouldn't be able to keep up. We have a large community ready to help you out on our support channels. If at some point, you are absolutely sure you've pinpointed a bug then you're free to post a thorough issue with the details on how to recreate it.

In general I want to ask you to be a little bit more considerate for project maintainers the next time you post an issue.

```php
    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'minProcesses' => 1,
            'maxProcesses' => 5,
            'tries' => 1,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-1' => [
                'maxProcesses' => 10,
                'balanceMaxShift' => 1,
                'balanceCooldown' => 3,
            ],
        ],

        'local' => [
            'supervisor-1' => [
                'maxProcesses' => 3,
            ],
        ],
    ],
```

![Screenshot 2020-09-25 at 11 25 52](https://user-images.githubusercontent.com/594614/94250794-fa814180-ff21-11ea-8931-355279756aa7.png)

![Screenshot 2020-09-25 at 11 25 59](https://user-images.githubusercontent.com/594614/94250802-fc4b0500-ff21-11ea-9150-709efd922cb3.png)

**Comment by robj** [comment]
@driesvints - noted thank you

I have many queues, In my case it looks like
Queue 1, 4 Jobs pending, 0 processes (stuck at 0 for a looong time)
Queue 2, 500,000 jobs pending, 80 processes

which made me think perhaps there could be some kind of rounding error with the math used to assign # of processes to each queue

**Comment by rocramer** [comment]
After upgrading to L8 and Horizon 5 I had similar problems. I had supervisor processes with three queues assigned. After the upgrade horizon didn't assign a process to one of my queues which leads to lots of pending jobs. I had to tweak the Horizon config to get it working again.

**Comment by robj** [comment]
@rocramer - what was your tweak? 

- as a temp fix I'm deploying with 2 horizon configs, 1 node set to use balance=simple (ensuring every queue has 1 worker), and the rest of node's (20 or so) deployed with balance=auto

cc @rustik666

**Comment by gabrielboliveira** [comment]
> After upgrading to L8 and Horizon 5 I had similar problems. I had supervisor processes with three queues assigned. After the upgrade horizon didn't assign a process to one of my queues which leads to lots of pending jobs. I had to tweak the Horizon config to get it working again.

I just experienced this same problem. I discovered that if you have `minProcesses` with a number that will be higher than maxProcesses, it will break the balancing. Let me explain:

I had this:

```
'default' => [
    'connection' => 'redis',
    'queue' => ['email', 'default'],
    'balance' => 'auto',
    'minProcesses' => 3,
    'maxProcesses' => 5,
],
```

I saw that it always started with 3 and 2 processes on queue email and default. Then I added a new queue, but kept the same min and max processes.

```
'default' => [
    'connection' => 'redis',
    'queue' => ['email', 'default', 'new-queue'],
    'balance' => 'auto',
    'minProcesses' => 3,
    'maxProcesses' => 5,
],
```

Then, Horizon started with 3 processes for queue `default` and 3 for queue `new-queue`, and never balanced to queue `email`, stuck at 0 processes for ever.

When I decreased the `minProcesses` to 1, it started with 1 process for each queue, thus processing the jobs pending on queue `email` and scaling properly.

So, if you have a number of queues * minProcesses that is higher than maxProcesses, it will not balance properly. This worked:

```
'default' => [
    'connection' => 'redis',
    'queue' => ['email', 'default', 'new-queue'],
    'balance' => 'auto',
    'minProcesses' => 1,
    'maxProcesses' => 5,
],
```

**Comment by robj** [comment]
Hi @gabrielboliveira , It is frowned upon to discuss Issues here cc @driesvints

**Comment by ferdinandfrank** [comment]
I can confirm the same issue on our projects.
This is our config:
```
'prod'  => [
    'supervisor-1' => [
        'connection'      => 'redis',
        'queue'           => ['webhook', 'high', 'low', 'system_function'],
        'balance'         => 'auto',
        'maxProcesses'    => 24,
        'minProcesses'    => 3,
        'balanceMaxShift' => 3,
        'balanceCooldown' => 2,
        'tries'           => 1,
        'timeout'         => 300,
    ],
],
```

So according to the docs `minProcesses` should ensure a min amount of processes for each queue which seems to work fine when all queues have a low or moderate workload:
![image](https://user-images.githubusercontent.com/19409640/141078258-9e75f939-9ad6-4133-bfb2-3caa61e46370.png)

However, when one queue needs to process a lot of jobs over a longer period of time (`system_function` in our case), it receives all processes from other busy queues (`low` in our case) which leads to the `low` queue to not process any job even though it should always have the configured amount of `minProcesses`.
![image](https://user-images.githubusercontent.com/19409640/141078522-a31f33ca-2e2a-464b-be6b-47e84286c441.png)

**Comment by taylorotwell** [comment]
Should be fixed by https://github.com/laravel/horizon/issues/897
