### ISSUE TITLE
Issue with laravel 8 Command

### ISSUE THREAD

**Issue by BryanMootoosamy** [laravel/horizon#898]
- Horizon Version: 5.1
- Laravel Version: 8.6.0
- PHP Version: 7.4.10

### Description:
When lanching a console command or making a composer dump-autoload when a command exists, I get this error

Symfony\Component\ErrorHandler\Error\FatalError 

  Type of Laravel\Horizon\Console\ClearCommand::$signature must be string (as in class Illuminate\Console\Command)
In class ClearCommand, signature type is missing on the property

### Steps To Reproduce:
Create a command and trying to use it

**Comment by paras-malhotra** [comment]
@BryanMootoosamy can you please paste the entire error with stack trace? I'm unable to reproduce this on a fresh Laravel installation with Horizon v5.1.

**Comment by driesvints** [comment]
I can't reproduce this either.
