### ISSUE TITLE
Large job payloads result in huge data transfers on job overview screens

### ISSUE THREAD

**Issue by devfrey** [laravel/horizon#901]
- Horizon Version: 4.3.5
- Laravel Version: 7.28.1
- PHP Version: 7.3
- Redis Driver & Version: predis/predis 1.1.6
- Database Driver & Version: MariaDB

### Description:
I have an application with large job payloads. Unfortunately, all overview pages with a list of jobs (pending, completed, and failed) also seem to load the `payload` attribute when querying all jobs. This results in API responses of ±25MB, which take longer to complete than the refresh interval (5 seconds), causing a huge build up of pending requests that slow down the server and the client.

![Schermafbeelding 2020-10-01 om 12 00 13](https://user-images.githubusercontent.com/1571879/94795490-ac66b500-03dd-11eb-90a5-885db11d80ff.png)

Could we remove the `payload` attribute from `/horizon/api/monitoring/*` responses? It doesn't seem to be used anywhere on the page. When clicking a job to view its details, a new request is made that contains the payload (as expected, because it's used on the page).

### Steps To Reproduce:
Dispatch a set of jobs with large payloads (several hundreds of KBs or even a megabyte) and inspect the network traffic using the browser console.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by devfrey** [comment]
@driesvints I'm a bit disappointed you didn't take the time to go over my issue and rushed to close it. I was under the impression Horizon 4.x is still supported, because there still is bug fix support for Laravel 7.

Anyways, I tried this with a fresh install of Laravel 8.7.1 with Horizon 5.2.0 and the issue is still present. Would you please take another look at it?

**Comment by paras-malhotra** [comment]
@devfrey the reason payload is getting returned is because the job hash stores all the data (including job name, connection, queue, status, payload, etc.) and the controller is returning the entire hash data. Payload isn't expected to be huge typically (serialisation and storage of large payloads on high frequency jobs is very expensive) and that's why it seems to be specific to your use case.

A workaround that might work (not 100% sure) is that you could add this to your `AppServiceProvider`:
```php
$this->app->resolving(\Laravel\Horizon\Contracts\JobRepository::class, function ($repo, $app) {
    $repo->keys = array_diff($repo->keys, ['payload']);
});
```

This should stop fetching the payload on all your job screens (index and detail).

**Comment by driesvints** [comment]
> I'm a bit disappointed you didn't take the time to go over my issue and rushed to close it.

You can't expect us to provide support for every single older version of a package out there. We have [a support policy](https://laravel.com/docs/8.x/releases#support-policy) in place which clearly states we don't provide support or bug fixes for older versions. 

It's also clearly indicated before you open an issue to check if your version is supported:

![Screenshot 2020-10-01 at 13 25 37](https://user-images.githubusercontent.com/594614/94803566-c6a69000-03e9-11eb-9167-958966ceaea8.png)

In any case from the looks of it the large payloads are, in my opinion, more of a design flaw in the app at hand. This is also open source software so if you feel like anything can improved here you're free to send in a PR. Thanks.

If you want to figure out ways to reduce the payload of your jobs I suggest you try a support channel as this isn't a Horizon problem.

**Comment by devfrey** [comment]
Apart from what I could do to reduce the payloads in my application (which btw is not intentional, it's due to the way `SerializesModels` works), the point still stands that Horizon loads information that is not used on the page. Maybe this should be seen as a performance improvement, rather than a bug fix.

I'd be happy to send in a PR if you're open to improve what I described. Please let me know.

**Comment by driesvints** [comment]
If they aren't used on the page then I think we can remove the payload yeah.
