### ISSUE TITLE
No jobs showing in failed jobs within the week

### ISSUE THREAD

**Issue by antonioribeiro** [laravel/horizon#904]
- Horizon Version: v4.3.5
- Laravel Version: v7.28.3
- PHP Version: 7.4.7
- Redis Driver & Version: predis/phpredis v1.1.6
- Database Driver & Version: MariaDB for Azure

### Description:

I have 1 job failed in the last week, but no jobs in the list of jobs. `Job Trimming Times` is the default one:

``` php
'failed' => 10080,
```

![image](https://user-images.githubusercontent.com/3182864/94904183-3a54a580-049b-11eb-9d99-44b6d638d824.png)

![image](https://user-images.githubusercontent.com/3182864/94904203-404a8680-049b-11eb-9458-4b6f9b18d523.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
