### ISSUE TITLE
Job type is unclear (`trim` in config)

### ISSUE THREAD

**Issue by Namoshek** [laravel/horizon#920]
- Horizon Version: latest

### Description:
Some time ago, the `trim` option in the config has been extended with additional job types and also the UI has received an update splitting _Recent Jobs_ into _Pending Jobs_ and _Completed Jobs_.

https://github.com/laravel/horizon/blob/5495ee80ab1b4e5e346d3c0f1fab671f18956e2b/config/horizon.php#L90-L108

Unfortunately, neither the configuration file nor the documentation contains an explanation for these types. Confusing to me is especially the difference between `recent` and `completed` as well as `recent_failed` and `failed`. What I figured out using the method of elimination:
- `recent`: all jobs are inserted when pushed to the queue
- `pending`: new jobs and jobs released back onto the queue during processing
- `completed`: successfully finished and deleted jobs
- `recent_failed`: the failed jobs of which the count is shown on the dashboard
- `failed`: the failed jobs which are displayed on the _Failed Jobs_ page
- `monitored`: jobs of which a tag is actively monitored

It seems that `failed` and `recent_failed` have a slightly different use case, where `failed` can be mutated by the user (e.g. by deleting failed jobs using `php artisan queue:forget`) while `recent_failed` is purely used to display the count on the dashboard.

Since this is only a guess, I would welcome a clearification of someone with a bit more background knowledge. An explanation, what impact each of the `trim` options have, would be welcomed as well. For me totally unclear at this point: when and how are the actual jobs deleted from Redis (i.e. when is memory freed)? The sorted sets given by `trim` are only reference sets, as far as I understood.

_PS: it might be helpful to enable the Discussions feature for this and other first-party package repositories as well._

**Comment by driesvints** [comment]
If you want to change something feel free to send in a PR 👍 

After evaluation of the discussions feature on laravel/framework we decided to not be rolling it out on other repos.

**Comment by Namoshek** [comment]
I would like to change it, but first I need to understand it. That's what I'm seeking help with.

**Comment by Stetzon** [comment]
There was a section in the 7.x Laravel documentation for Job Trimming touching on the `trim` option; however, this was removed in the 8.x documentation offering no explanation for these new options
