### ISSUE TITLE
Exponential Backoff Strategy: Pass Array To Backoff Config

### ISSUE THREAD

**Issue by MannikJ** [laravel/horizon#925]
As stated [here](https://divinglaravel.com/features-and-changes-coming-to-laravel-8-queue-system) the backoff parameter of the queue system now also excepts an array to define different delays between the retries. 

I tried to configure another supervisor like below and wondered why horizon didn't launch the supervisor-2 worker, before I found that the backoff configuration was causing this. 

```php
'local' => [
    'supervisor-1' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 3,
        'tries' => 1,
    ],
    'supervisor-2' => [
        'connection' => 'redis',
        'queue' => ['webhooks'],
        'balance' => 'simple',
        'processes' => 3,
        'tries' => 5,
        'backoff' => [
            60, // 1 minute
            300, // 5 minutes
            3600, // an hour
            21600, // 6 hours
            86400, // 24 hours
        ],
    ]
],
```

So will this be supported in the future, or is there any other way to specify a default exponential backoff strategy for a group of jobs/queues?

**Comment by driesvints** [comment]
Hey @MannikJ. You can define it as a string:

```php
'local' => [
    'supervisor-1' => [
        'connection' => 'redis',
        'queue' => ['default'],
        'balance' => 'simple',
        'processes' => 3,
        'tries' => 1,
    ],
    'supervisor-2' => [
        'connection' => 'redis',
        'queue' => ['webhooks'],
        'balance' => 'simple',
        'processes' => 3,
        'tries' => 5,
        'backoff' => '60,300,3600,21600,86400',
    ]
],
```

We can maybe look into translating the array into a string under the hood. If you want you can send in a PR for that 👍

**Comment by driesvints** [comment]
Looks like Mohamed was super fast on this one :)

**Comment by MannikJ** [comment]
Haha, "super fast" feels like an underestimate. Thank you!
