### ISSUE TITLE
Metric interval sometimes 10 minutes

### ISSUE THREAD

**Issue by electronick86** [laravel/horizon#931]
- Horizon Version: 4.3.5
- Laravel Version: 7.29.3
- PHP Version: 7.4.12
- Redis Driver & Version: redis version 5.3.2 
- Database Driver & Version: 5.7.26

### Description:

Hi. 
As I can't solve this issue, I want to share it with you. 

<img width="1133" alt="Horizon_-_Metrics" src="https://user-images.githubusercontent.com/8201501/100084861-9ad4e300-2e4b-11eb-8d52-20743da58bb5.png">

my `kernel.php` file contains `$schedule->command('horizon:snapshot')->everyFiveMinutes();`. However my metrics graphs show a value sometimes with 5 and sometimes with 10 minutes interval. 

Can you help me to undestand what's going wrong? 

The same effect is seen on environment with and without load (=jobs to process).

Thanks for your help.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by electronick86** [comment]
Hello @driesvints ,

Thanks for your answer. 

I have another mailcoach instance running laravel v8.15.0 and horizon v5.4.0 and the graphs are exactly the same : 

<img width="1152" alt="Horizon_-_Metrics" src="https://user-images.githubusercontent.com/8201501/100089628-48e38b80-2e52-11eb-8a93-e9718e87d83c.png">

I see values at 11:30, 11:40, 11:45, 11:50, 12:00, 12:10, 12:20, 12:25, 12:35.

Do you see any way to investigate this?

**Comment by driesvints** [comment]
Hey @electronick86, 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
