### ISSUE TITLE
min/maxProcesses inconsistance

### ISSUE THREAD

**Issue by danijelk** [laravel/horizon#933]
So we are trying to configure our pods to use 50 processes per pod between 3 queues. But they should be able to balance between themselves.

so with conf
```

    'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => \App\Helper\HorizonHelpers::getQueue(),
            'balance' => 'simple',
            'processes' => 1,
            'tries' => 1,

            'balanceMaxShift' => 5,
            'balanceCooldown' => 3,
            'minProcesses' => env('HORIZON_WORKERS_MIN', count(\App\Helper\HorizonHelpers::$queues)),
            'maxProcesses' => env('HORIZON_WORKERS', 20),
        ],
    ],

    'environments' => [
        'production' => [
            'supervisor-1' => [
                'balance' => 'auto',
                'max-jobs' => '10000',
                'timeout' => 1130, // see queue retry_after
                'memory' => 256,
            ],
        ],
    ];
];
```

We expect if we set minProcesses to 50 and maxProcesses 50 that it will always have '50' processes available, but instead we got this scenario where the processes flee our most valuable 'realtime' queue which has first priority as per order, and it has 60 processes?

![Screen Shot 2020-11-25 at 11 00 53](https://user-images.githubusercontent.com/580753/100220273-6595c700-2f17-11eb-8b70-ea969bbe3277.png)

This is what it looks like with minProcesses 3, maxProcesses 50, as we can see it's now 40 instead of the maxProcess
![Screen Shot 2020-11-25 at 12 05 06](https://user-images.githubusercontent.com/580753/100220310-71818900-2f17-11eb-8fe4-714c7983db5d.png)

Our issue is that a pod is idle too much and the time it takes to start processes vs the k8s hpa telling deployment to start more pods isn't great giving us jumps in performance and execution.

Any tips to a better config?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
