### ISSUE TITLE
Snapshot miss lock time to time

### ISSUE THREAD

**Issue by glamorous** [laravel/horizon#935]
- Horizon Version: 5.x
- Laravel Version: 8.x
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis #.#.#

### Description:
Because the cache-lock for metrics is exact 5minutes or 300s you can have cases when cron is running slow/fast, he can't obtain the lock and misses the snapshot for that timing.

### Steps To Reproduce:
Having  fast or slow environment.

Problem lays here:

```
/**
     * Execute the console command.
     *
     * @param  \Laravel\Horizon\Lock  $lock
     * @param  \Laravel\Horizon\Contracts\MetricsRepository  $metrics
     * @return void
     */
    public function handle(Lock $lock, MetricsRepository $metrics)
    {
        if ($lock->get('metrics:snapshot', 300)) {
            $metrics->snapshot();

            $this->info('Metrics snapshot stored successfully.');
        }
```

Proposal is to have this a couple of seconds lower or make it configurable so people can choose to have shapshots every 2 minutes for example.

**Comment by driesvints** [comment]
Sure, feel free to send in a PR.
