### ISSUE TITLE
Horizon-Supervisor not recovering from failover gracefully. 

### ISSUE THREAD

**Issue by m1stermanager** [laravel/horizon#938]
- Horizon Version: v5.2.1
- Laravel Version: v8.9.0
- PHP Version: 7.3.23
- Redis Driver & Version: phpredis 5.1.1
- Database Driver & Version: mysql 8.0.17

### Description:
Our redis cluster had a failover, which caused the following exception in the logs (trimming to the parts that feel the most relevant but can provide full logs if needed) 

[2020-11-25 09:51:49] production.ERROR: Connection closed {"exception":"[object] (RedisException(code: 0): Connection closed at /var/app/current/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:406)

[previous exception] [object] (RedisException(code: 0): read error on connection to tls://master.prod-redis-tls.lgyn36.use2.cache.amazonaws.com:6379 at /var/app/current/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:406)

[previous exception] [object] (RedisException(code: 0): READONLY You can't write against a read only replica. at /var/app/current/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php:406)

The next log that we receive is:
[2020-11-25 09:51:50] production.ERROR: NOAUTH Authentication required. {"exception":"[object] (RedisException(code: 0): NOAUTH Authentication required. at /var/app/current/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:116)

The NOAUTH log then repeats every second.... I had to manually intervene by manually killing some supervisor and horizon related PIDs and then restarting the supervisord process, at which point everything was totally fine.

During the time that this was happening the environment was completely stable.... the horizon dashboard displayed as being down, but the "completed jobs" section was still being populated and no jobs actually failed. It looks like the horizon-supervisor was the only thing experiencing a non-graceful recovery. 

### Steps To Reproduce:
Run horizon w/ a multi-node redis instance, trigger a failover while horizon is running.

**Comment by driesvints** [comment]
Have you already tried upgrading to the latest versions of the framework and Horizon to see if the problem has been fixed since?

**Comment by driesvints** [comment]
Also: can you upgrade to the latest phpredis driver version?

**Comment by driesvints** [comment]
I think this is because you're running an old phpredis version. We've seen other issues with NOAUTH popping up which were solved in a newer phpredis version. Please upgrade, thanks.

**Comment by m1stermanager** [comment]
awesome. Will check that out. thanks a ton

**Comment by graemlourens** [comment]
@m1stermanager just for the record: we had the same issue with short unavailability of redis, and it was solved in phpredis 5.2.2 (see https://github.com/laravel/horizon/issues/744)
