### ISSUE TITLE
Seems like "memory" param for workers is ignore

### ISSUE THREAD

**Issue by paintmeyellow** [laravel/horizon#940]
- Horizon Version: 5.6.0
- Laravel Version: 8.17.0
- PHP Version: 7.4.12
- Redis Driver & Version: predis 1.1.6
- Database Driver & Version: mysql 5.7

### Description:
It seems like "memory" param for workers is ignore.
```
'defaults' => [
        'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'maxProcesses' => 1,
            'memory' => 128,
            'tries' => 1,
            'nice' => 0,
        ],
    ],
```

### Steps To Reproduce:
I tried to check it with log function called inside job:
```
private function print_mem(): string
    {
        $mem_usage = round(memory_get_usage() / 1024);
        $mem_peak = round(memory_get_peak_usage() / 1024);
        return "The script is now using: {$mem_usage} KB. Peak usage: {$mem_peak} KB";
    }
```
And it reached 1.5G
![image](https://user-images.githubusercontent.com/24860764/100783334-740c4300-342f-11eb-8383-60441a96924e.png)

Does it work correctly or I misunderstood something?

**Comment by driesvints** [comment]
Going to let @taylorotwell review this one.

**Comment by taylorotwell** [comment]
My very basic test of Laravel's memory check in the Illuminate queue worker does indicate it will exit if the memory usage is above the specified amount:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/463230/101368561-e84e4880-386c-11eb-9b4f-8a32f2b7e6a5.png">

**Comment by taylorotwell** [comment]
memory_get_usage() / 1024 / 1024 ... you are missing an extra 1024... your job is only using 1.5mb.

**Comment by paintmeyellow** [comment]
> memory_get_usage() / 1024 / 1024 ... you are missing an extra 1024... your job is only using 1.5mb.

It says "Returns the memory amount in bytes."
1 Megabyte = 1048576 Bytes

My example show results in KB's, not in MB's
1562987 KB / 1024 = 1526 MB = 1.5G
Am I wrong?

**Comment by driesvints** [comment]
@paintmeyellow yes you are: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Worker.php#L672

**Comment by paintmeyellow** [comment]
> @paintmeyellow yes you are: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Worker.php#L672

It cannot be using only 1.5MB.
Since I've just started a queue, it is already using 32.5MB
![image](https://user-images.githubusercontent.com/24860764/101381718-eb7f1e00-38d8-11eb-992b-cfe493fa3e07.png)
![image](https://user-images.githubusercontent.com/24860764/101381754-f5a11c80-38d8-11eb-92b9-1fb1911a9ee1.png)

Okay, maybe I wrong, but where?
Now I am using this function inside my job. It show result in MB's.
![image](https://user-images.githubusercontent.com/24860764/101381993-40bb2f80-38d9-11eb-81eb-44a12d4dd0b0.png)
And then got this
![image](https://user-images.githubusercontent.com/24860764/101382978-639a1380-38da-11eb-859d-b9a817a0f467.png)
1535MB = 1.5G

**Comment by paintmeyellow** [comment]
The thing is when job is not working, it checks the memory.
But as soon as job run, it's stop to check memory limit.
Try this one:
![image](https://user-images.githubusercontent.com/24860764/101386643-474ca580-38df-11eb-809c-aef714eadfa2.png)

Cause I've got this
![image](https://user-images.githubusercontent.com/24860764/101386899-95fa3f80-38df-11eb-857d-5cc68965d813.png)
