### ISSUE TITLE
"supervisor-1" always spawned when default supervisor for an environment renamed

### ISSUE THREAD

**Issue by daniel-g-wood** [laravel/horizon#943]
- Horizon Version: 5.6.0
- Laravel Version: 8.17.2
- PHP Version: 7.4.3
- Redis Driver & Version: phpredis 5.0.7
- Database Driver & Version: MySQL 8.0.22

### Description:
When the supervisor workers are renamed in the config `horizon.php` to something other than `supervisor-1`, the `supervisor-1` worker always appears.

### Steps To Reproduce:
1. Create a new Laravel 8 app.
2. Create a test database.
3. Install/publish assets etc.
4. Run migrations.
5. Rename the supervisor worker for the specified environment e.g. local, and supply config values (leaving the `defaults` array):
```
'local' => [
            'supervisor-local' => [
                'maxProcesses' => 3,
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'auto',
            ],
        ],
```
6. Run `php artisan horizon & php artisan serve`
7. Despite only having one supervisor worker defined for the `local` environment, the `supervisor-1` worker still appears:
```
+---------------------------------------+-------+---------+-------------------+-----------+
| Name                                  | PID   | Status  | Workers           | Balancing |
+---------------------------------------+-------+---------+-------------------+-----------+
| desktop-hqjefvf-wu1L:supervisor-local | 14670 | running | redis:default (1) | auto      |
| desktop-hqjefvf-wu1L:supervisor-1     | 14669 | running | redis:default (1) | auto      |
+---------------------------------------+-------+---------+-------------------+-----------+
```

The only way of removing this is by supplying an empty `defaults` array, i.e.:
```
    'defaults' => [],
```

This may be related to PR #869.

**Comment by driesvints** [comment]
This is the expected behavior. It merges the defaults, not overwrites them. If it overwrote them the defaults would be useless. You'll need to clear the defaults like you did.
