### ISSUE TITLE
Horizon picking up the old configurations even after purge

### ISSUE THREAD

**Issue by setkyar** [laravel/horizon#946]
- Horizon Version: ^5.3
- Laravel Version: 8.11.2
- PHP Version: 7.4.6
- Redis Driver & Version: predis/phpredis ^1.1

### Description:

I am trying to dynamically switch the mailgun configuration at runtime. I watch [themsaid's youtube about Multitenancy in Laravel: Updating configuration at runtime](https://www.youtube.com/watch?v=Ibd8stzF1KQ) and try to do for the mail. And horizon is keep using the old configurations.

### Steps To Reproduce:

Create `local` environment in Horizon like the following

```
'local' => [
    'supervisor-1' => [
    'connection' => 'redis',
    'queue' => ['mail'],
    'balance' => 'simple',
    'processes' => 1,
    'tries' => 1,
]
```

Create `SimpleMail` class inside the `App\Mail` like the following

```
<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Support\Facades\Mail;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class SimpleMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($enable)
    {
        if($enable) {
            config([
                'services.mailgun.domain' => '', //set new mailgun domain
                'services.mailgun.secret' => '' // set new mailgun secret
            ]);

            Mail::purge('mailgun');
        }
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('simple-mail');
    }
}
```

And your `simple-mail.blade.php` will be something like the following

```
Hello Horizon
```

And from your route create a simple route like the following

```
Route::get('mail-testing', function() {
    $isEnable = request('is_enable') ?? false;

    Mail::to('hello@youremail.com')
        ->send(
            (new SimpleMail($isEnable))->onQueue('testing')
        );
});
```
And you try to request from the browser to newly created route `localhost:8000/mail-testing` and `localhost:8000/mail-testing?is_enable=true`. After that, if you go check the email mailed-by domain. It will always be the default value. Unless you set two different queue and use the different queue name.

![image](https://user-images.githubusercontent.com/4435358/101760816-c58c9000-3b09-11eb-8346-96a4a2a3b81c.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by graemlourens** [comment]
@setkyar have you tried to reproduce this outside of queues/horizon?
For example just make an artisan console command, or controller, whatever is easier for you, where in a loop you are first running sending the mail with the parameter true, and then with false.

This will simulate what happens in horizon most of the times (or generally a queue worker) as the framework is only booted once. If its still happening there you're already a step further, knowing it has nothing to do with horizon, but with either your code or laravel framework, which will narrow it down for you. (I suspect it has nothing to do with horizon).
