### ISSUE TITLE
Dispatching multiple jobs within transaction (after_commit=true) leads to tags (for all jobs) of last pushed job

### ISSUE THREAD

**Issue by graemlourens** [laravel/horizon#950]
- Horizon Version: 5.6.3
- Laravel Version: 8.19.0
- PHP Version: 7.4.12
- Redis Driver & Version: phpredis 5.3.2

### Description:
We are using the queue config option 'after_commit' set to true, in order that all jobs that are dispatched within transactions, are pushed after the transaction commits.

We use horizon tags, and saw lately that the tags did not match up with what the actual job.
After some digging we found out that when having after_commit set to true, the tags that are generated are taken from the previous job that was pushed to queue, not the actual one that i being pushed.

We followed this down the rabbits hole to `RedisQueue.php` in the method `pushRaw`. When after_commit is set to true, `$this->lastPushed` that is used to 'prepare' the job (extract tags etc) contains the last job that was pushed instead of the actual one that is being prepared.

### Steps To Reproduce:

1) Create 2 different jobs with each either manually tagging or passing a model as a constructor value
2) Set after_commit to true in your queue config.
3) Dispatch both jobs within a transaction:

```
        DB::transaction(function() {
            dispatch(new JobA());
            dispatch(new JobB());
        });
```

If you set a breakpoint in `RedisQueue.php` on the first line of `pushRaw` you will see that in both cases `$this->lastPushed` is equals to the JobB job instance, and therefore is passed along to the `prepare` method which will falsely determine the tags (and other things)

The tags that are determined (before being pushed to queue, and put into payload) will be those of JobB also for JobA.

I have tried to identify where this issue is coming from but can currently can not pinpoint it exactly nor propose a solution.

Hope this will make immediate sense to @themsaid

Kind regards, Graem

**Comment by driesvints** [comment]
Thanks for the report @graemlourens. Mohamed has sent in a PR here: https://github.com/laravel/horizon/pull/951

**Comment by graemlourens** [comment]
Fantastic, thank you for the swift fixing! I'll check the fix out in a couple of hours to confirm our logs are showing the correct tags.

**Comment by graemlourens** [comment]
I can confirm the fix works as intended. Tags are not correctly assigned to the correct jobs. Thx again!
