### ISSUE TITLE
Duplicate UUID key entries for failed jobs

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/horizon#953]
- Horizon Version: 5.1.0
- Laravel Version: 8.6.0
- PHP Version: 7.4.13
- Redis Driver & Version: predis 5.3.2
- Database Driver & Version: MySQL 8.0.21

### Description:

I swapped to the UUID for failed jobs, but now I am quite often I am getting duplicate key entries for failed jobs. I am running several separate workers that use one main redis server if that makes any difference.

`Illuminate\Database\QueryException SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'cfce569e-e2a1-4105-b16d-3860d59abcca' for key 'failed_jobs.failed_jobs_uuid_unique' (SQL: insert into `failed_jobs` (`uuid`, `connection`, `queue`, `payload`, `exception`, `failed_at`) values ...`

Config should be OK:

```
Psy Shell v0.10.4 (PHP 7.4.13 — cli) by Justin Hileman
>>> config('queue.failed');
=> [
     "driver" => "database-uuids",
     "database" => "mysql",
     "table" => "failed_jobs",
   ]
>>> 
```

**Comment by paras-malhotra** [comment]
@lasselehtinen is your `retry_after` set to be greater than your queue timeout (default: 60 seconds)? See https://laravel.com/docs/8.x/queues#worker-timeouts

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
