### ISSUE TITLE
undefined method Laravel\Horizon\RedisQueue::enqueueUsing()

### ISSUE THREAD

**Issue by ameth97** [laravel/horizon#955]
- Horizon Version: 5.6.4
- Laravel Version: 8.12.0
- PHP Version: 7.4.1
- Redis Driver & Version: predis 1.1.0

### Description:
vendor/laravel/horizon/src/RedisQueue.php:45 in push method
The method undefined method Laravel\Horizon\RedisQueue::enqueueUsing() does not exist.
This should check if the method exists first. It's not an issue in 5.6.3 version.

**Comment by driesvints** [comment]
Update your Laravel framework version.
