### ISSUE TITLE
MySQL Locks with horizon's persistent db connections

### ISSUE THREAD

**Issue by jhoopes** [laravel/horizon#956]
- Horizon Version: 3.7.2
- Laravel Version: 6.20.7
- PHP Version: 7.4.13
- Redis Driver & Version: php-redis
- Database Driver & Version: AWS Aurora with mysql 5.7 dialect (but this occurs on RDS instances of MySQL for 5.7 and 8)

### Description:
Hello,

I've been trying to determine how to fix an issue that we've been having lately. 

* We have 2 supervisors in the horizon.php configuration that each run different queues in the queue configuration
* We have a decent amount of load on our application that's around 300-500+ requests per minute and generate about 1-2000 jobs per hour during peak times.

We have had a good amount of jobs processing through our queues in the past to offload front end processing, but we started getting a lot of locks within MySQL being unable to fully finish a transaction and then a job trying to pick up a record and saying the model doesn't exist among other issues.

From there we tried to push more of the processing back into the main request / response lifecycle to help keep things moving there, but locks are still persisting even on the front end from queue worker's db connections.  And digging into MySQL, both with upgrading the amount of resources it has to what is very likely overkill  (going from just a simpler MySQL RDS instance to AWS Aurora), and doing some monitoring of queries it seems the culprit seems to be Horizon's queue workers not releasing the database connection or fully closing the statement / thread of a transaction.  

The locking and blocking threads in MySQL are always a horizon queue worker's thread id that shows the SQL being run as "Stmt/close" and the connection from our queue server and not our application servers.  Some further steps taken is that simply running `horizon:terminate` which kills the current queue workers and tells supervisor to restart horizon automatically fixes the locks placed by the database connections from the queue workers because the database connections are then fully closed and reopened on a new job run.

Is there a configuration item or something that I'm missing here, I've tried both increasing and decreasing the lock timeouts and wait times within MySQL but they don't correct for this problem?  Or to me it seems like a bug that laravel/horizon isn't closing the database connection and leaving it persistently open or in a state on MySQL that doesn't clear out the row locks it keeps from the job it ran.

**Comment by paras-malhotra** [comment]
Horizon doesn't store anything in mysql. Jobs, metrics, supervisor data, etc. are all stored in Redis, nothing in the DB. A `horizon:terminate` fixing the locks could also mean that your jobs are creating these database connections?

**Comment by jhoopes** [comment]
Hi @paras-malhotra. thanks for replying.  Yep.  I get where you're coming from that things are stored in redis for horizon itself, so thinking about it, maybe this issue in this repo is the wrong place to put it.  But the jobs are creating database connections by just querying for models.    I also know that queue workers are long running php processes that likely are then just never closing the connection after using it.  Is your suggestion to add a line like: `\DB::disconnect('mysql')` at the end of a job's class?  

Is that common for people to do as I haven't really seen that in documentation or other places.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
