### ISSUE TITLE
Horizon duplicate supervisor process

### ISSUE THREAD

**Issue by LashchenkoViktor** [laravel/horizon#957]
- Horizon Version: 5.6.1
- Laravel Version: 8.16.1
- PHP Version: 7.3.0
- Redis Driver & Version: predis/predis 1.1.6
- Database Driver & Version: AWS Serverless

### Description:
Hi, seems like that horizon duplicate supervisors process from time to time. After deployment, I have 1 supervisor process, 1 horizon process, and 3 workers always. Here is a screenshot:
![Screenshot from 2021-01-12 14-47-51](https://user-images.githubusercontent.com/30956182/104316740-96d94f00-54e5-11eb-9c5b-1fd446600130.png)
Also my configuration file for this set up:
![Screenshot from 2021-01-12 14-42-16](https://user-images.githubusercontent.com/30956182/104316811-b3758700-54e5-11eb-86b8-fcff7730cec9.png)
I run PHP artisan horizon in my supervisor file:
`
[program:horizon]
process_name=%(program_name)s
command=php /var/www/html/artisan horizon
autostart=true
autorestart=true
user=apache
redirect_stderr=true
stdout_logfile=/var/www/html/log/horizon.log
stopwaitsecs=3600
`

But, from time to time with different time intervals, my supervisor process duplicates and get up more worker processes. Here is the screenshot:
![Screenshot from 2021-01-12 14-40-02](https://user-images.githubusercontent.com/30956182/104317095-1ebf5900-54e6-11eb-8bed-d4e4b1a4893d.png)
And a screenshot from horizon dashboard:
![Screenshot from 2021-01-12 14-40-22](https://user-images.githubusercontent.com/30956182/104317122-2c74de80-54e6-11eb-9343-53448b8c0013.png)
We can see that on one server we have 1 supervisor process, with 3 workers, but on another two we have two supervisors. Also, duplicate the supervisors' processes does not appear in the "active supervisors section". We can understand that something's wrong only from the "Current Workload" section by the number of workers, or go to the server and check the process list.

So, I do not know how I can fix it. I expect to see 1 supervisor and 3 worker process, but see two supervisors and 6 workers from time to time.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by LashchenkoViktor** [comment]
hi, @driesvints. Can you help me please thing figuring out this issue? I will provide all additional data if u need

**Comment by mfn** [comment]
@LashchenkoViktor FTR, never seen this problem running on a regular (non-aws non-fancy cloud) server

The timestampts are very next to each other what I see from your second screenshot.

Is there anything in the `/var/www/html/log/horizon.log`?

**Comment by LashchenkoViktor** [comment]
@mfn yes, I see the log like that.
```
[2021-01-12 16:35:02][8e8b2cfe-1f0c-4288-9386-75a3b97e9081] Processing: NameEvent
[2021-01-12 16:35:02][8e8b2cfe-1f0c-4288-9386-75a3b97e9081] Processed:  NameEvent
```
And sometimes "Horizon started successfully." But part of this has called deployments because in deploying I restarting the supervisor

**Comment by LashchenkoViktor** [comment]
@mfn any idea?

**Comment by mfn** [comment]
> And sometimes "Horizon started successfully."

Does this and the start time always match the deployments?

**Comment by LashchenkoViktor** [comment]
@mfn I do know what you mean. But if artisan horizon will run twice, I would have seen two ran processes in the process manager.

**Comment by mfn** [comment]
Something prevented the new invocation to not "see" the old one. Though the name visible in `htop` gives away it's the same server / ip / etc.

Maybe a redis issue? Wrong instance or something? 🤷‍♀️ Out of ideas…

**Comment by LashchenkoViktor** [comment]
> Something prevented the new invocation to not "see" the old one. Though the name visible in `htop` gives away it's the same server / ip / etc.
> 
> Maybe a redis issue? Wrong instance or something?  Out of ideas…

yep, fully agree with you.
Also if I for example will try to run `php artisan horizon:terminate` I got terminate only one supervisor with its workers. Another one will not be affected.

**Comment by LashchenkoViktor** [comment]
`sh-4.2$ php artisan horizon:supervisors
+---------------------------------------------------------+------+---------+-----------------------------------+-----------+
| Name                                                    | PID  | Status  | Workers                           | Balancing |
+---------------------------------------------------------+------+---------+-----------------------------------+-----------+
| ip-10-0-10-77eu-west-1computeinternal-tuv0:supervisor-1 | 4393 | running | redis:default (2), redis:high (1) | simple    |
| ip-10-0-10-77eu-west-1computeinternal-NhVy:supervisor-1 | 5264 | running | redis:default (2), redis:high (1) | simple    |
+---------------------------------------------------------+------+---------+-----------------------------------+-----------+
sh-4.2$ php artisan horizon:list
+--------------------------------------------+------+--------------+---------+
| Name                                       | PID  | Supervisors  | Status  |
+--------------------------------------------+------+--------------+---------+
| ip-10-0-10-77eu-west-1computeinternal-tuv0 | 4376 | supervisor-1 | running |
+--------------------------------------------+------+--------------+---------+`

Also that. I have not idea...

**Comment by LashchenkoViktor** [comment]
hi, @driesvints that's like a bug. Can you please reopen the issue? 
I would be happy to assist detect the reason.
Hope this will make immediate sense.
Kind regards, Viktor

**Comment by driesvints** [comment]
@LashchenkoViktor can you please try a few support channels like I asked?

**Comment by LashchenkoViktor** [comment]
> @LashchenkoViktor can you please try a few support channels like I asked?

sure, I have posted on laracast already
https://laracasts.com/discuss/channels/laravel/horizon-duplicate-supervisor-process
now will try on discord also, thanks

**Comment by LashchenkoViktor** [comment]
@mfn Does this and the start time always match the deployments?
I have investigated horizon.log and detect that log `Horizon started successfully.` had arisen without deployment.
But in doing I still see only one process for `php artisan horizon` command...

**Comment by LashchenkoViktor** [comment]
> > And sometimes "Horizon started successfully."
> 
> Does this and the start time always match the deployments?

I have investigated horizon.log and detect that log `Horizon started successfully.` had arisen without deployment.
But in doing I still see only one process for `php artisan horizon` command...

**Comment by LashchenkoViktor** [comment]
hi @driesvints I have found a solution for this issue. 
To greater understanding a few words about how my deploying are working. 
Steps of deployment: 
1. Stop the application. On this step, I run `service supervisord stop`. So, this command will stop the Horizon process.
2. Some steps for deploying...
3. Start the application.  On this step, I run `service supervisord start`. So, this command will start the Horizon process.
Insofar as I run stop and start supervisord commands, I guess that Horizon should work normally in so doing. But as it turns out, after investigation 'Supervisor activity log' that's not exactly true.
That is the screenshot of when I start the supervisor.
![image (11)](https://user-images.githubusercontent.com/30956182/105521056-19cb8800-5ce4-11eb-8a42-b84f5b8f127a.png)
We can see that supervisor spawned 'horizon' and waiting from horizon _some response_.., but not getting it.
This been going on for 1 hour. Why one hour? Because `stopwaitsecs=3600` as indicated in Laravel doc., and as a result in my supervisor config file. After this time supervisor killed the horizon process and run another one instead of current one, but this process will return _some response_ to the supervisor. We can see it on the next screenshot:
![image (12)](https://user-images.githubusercontent.com/30956182/105521868-29979c00-5ce5-11eb-8110-d4e0c863f929.png)
pay no attention to the time on screenshots.. For more fast testing I have set `stopwaitsecs` to 300 sec.
So, after restarting Horizon by Supervisor, we have the situation when horiozon:supervisor process is duplicated, and one from these has no managing by Horizon. 
As a solution for this issue, I have added `php artisan horiozn:terminate` to the third step on deployment. But for me, it just seems weird. The current flow:

- Supervisor spawned horizon
- `php artisan horizon:terminate` terminated horizon
- Supervisor spawned the horizon. 

Why we should terminate the horizon after first starting? As for me, it seems like a bug.

@taylorotwell @themsaid @mfn  and all who can understand this logic, please, cant you look at this message and help me? Thanks.

**Comment by driesvints** [comment]
https://laravel.com/docs/8.x/horizon#supervisor-configuration

Is it related to this? (Just throwing ideas at this)

<img width="763" alt="Screenshot 2021-01-25 at 13 32 33" src="https://user-images.githubusercontent.com/594614/105706404-c9397200-5f11-11eb-82b6-0713439e465e.png">

**Comment by LashchenkoViktor** [comment]
> https://laravel.com/docs/8.x/horizon#supervisor-configuration
> 
> Is it related to this? (Just throwing ideas at this)
> 
> <img alt="Screenshot 2021-01-25 at 13 32 33" width="763" src="https://user-images.githubusercontent.com/594614/105706404-c9397200-5f11-11eb-82b6-0713439e465e.png">

yes, but it is not the main reason. 
The main reason that is `service supervisord start` does not receive a true response from the horizon process (You can see it on screenshots above). And after `stopwaitsecs` time, the supervisor restart the horizon process thus losing my `horizon:supervisor` process. And after that a have two `horizon:supervisor` processes. 
In my opinion, It can be related to https://github.com/laravel/horizon/issues/663. In particular related to listening `pcntl` signals.

**Comment by driesvints** [comment]
I'm out of ideas myself sorry. Since this is the only report we've gotten about this I'm going to leave this one be. Appreciating a PR or any help with this if anyone wants to put in the effort to investigate this.
