### ISSUE TITLE
Error RedisQueue::enqueueUsing() after updating horizon 

### ISSUE THREAD

**Issue by rizkynich** [laravel/horizon#962]
- Horizon Version: 5.6
- Laravel Version: 8.0
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis 1.1
- Database Driver & Version:

### Description:
i got error : Call to undefined method Laravel\Horizon\RedisQueue::enqueueUsing()

### Steps To Reproduce:
i got the error after update horizon

**Comment by driesvints** [comment]
Try updating to the latest Laravel 8.x version.

**Comment by liusongsen** [comment]
亲测，直接上代码吧，  "laravel/framework": "8.*",
        "laravel/horizon": "^5.6", 升价到8.*就可以了，很奇怪，手动调整成8.1（laravel/framework）就不行
