### ISSUE TITLE
No fallback font defined for Google webfont

### ISSUE THREAD

**Issue by John5** [laravel/horizon#963]
Horizon uses a Google webfont but does not specify a fallback (Arial, sans-serif). Our server sends CSP headers that don't allow connecting to Google's servers. So we see an ugly "Times New Roman" default font and the following error in the browser console:

Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css?family=Nunito (“style-src”).

I strongly suggest to specify a fallback font more similar to the Nunito font. On top of that you can also include the font in the assets so it is served from the same server and will continue to work regardless of Google and have the benefit of not leaking data to a third party.

**Comment by driesvints** [comment]
Feel free to PR something, thanks 👍
