### ISSUE TITLE
    the time taken for a failed job in batch section  is not correct

### ISSUE THREAD

**Issue by chaokang-refundlabs** [laravel/horizon#974]
- Horizon Version: 5.6.1
- Laravel Version: 8.18.1
- PHP Version: 7.4.9
- Redis Driver & Version: predis/phpredis 4.0.9
- Database Driver & Version:pgsql psql (PostgreSQL) 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
### Description:
    the time taken for a failed job in batch section  is not correct like the image below

### Steps To Reproduce:
  it is not always show up 

<img width="1680" alt="Screen Shot 2021-02-26 at 11 22 42" src="https://user-images.githubusercontent.com/56284586/109251263-1f0d7c80-7826-11eb-9ac9-1af82ea5748d.png">

**Comment by driesvints** [comment]
Please provide the exact steps to reproduce this.

**Comment by chaokang-refundlabs** [comment]
sorry i tried a few times , it is not reproduceable, you can close this issue if necessary .
