### ISSUE TITLE
Can't Understand laravel jobs behavior in horizon

### ISSUE THREAD

**Issue by bilalswiftsolutions** [laravel/horizon#975]
I am dispatching about 25000 jobs in loop . But when i disptach them my database mysql cpu utilization reaches 100 %. And 20% of jobs get complete and rest of them just disappeared . Those jobs are not failed but also not completed . I don't know if its because of redis drvier or because of my mysql cpu cunsumption.

Please guide someone

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by graemlourens** [comment]
@bilalswiftsolutions could you please fill in the ticket template so we know what versions of what you are using? this is crucial to being able to help & identify issues.

One hint that i can already give: when dispatching 25'000 jobs, not only is redis filling queues with 25k entries, but every successfully processed job is logged / archived by horizon. In case your redis instance has only small amount of memory assigned, you'll hit the issue of 'key eviction' where redis kicks out keys to get enough space to store new things. (https://redis.io/topics/lru-cache)

This happened to us, and we had to 1) greatly increase redis memory when dispatching up to 1 million jobs, and 2) reduce the amount of time horizon remembers successfully processed jobs (you can configure that).

Hope that helps

**Comment by bilalswiftsolutions** [comment]
@graemlourens  thanks for the reply it was helpful. I know thats not your job but still i am asking you can you please tell me taht how i can solve the issue of 100% mysql cpu utlilization . Becauase every job is having 20,30  database queries

**Comment by graemlourens** [comment]
@bilalswiftsolutions this has nothing to do with horizon anymore but with the content of your job, so i'll pull out of this discussion now. Happy my comment helped. Good luck!
