### ISSUE TITLE
Horizon API

### ISSUE THREAD

**Issue by browner12** [laravel/horizon#977]
Is the Horizon internal API considered part of the "public contract"? Or in other words, is it closed to change without a major version bump?

The reason I ask is in our own internal dashboard I make a call to `/horizon/api/stats` to fetch the status of Horizon and display it on our dashboard. Since I'm on this dashboard all the time, it's nice to have there, so I can see if Horizon is up.

If it's not considered that way, would we be open to make an endpoint that is?

**Comment by driesvints** [comment]
Heya. No we don't consider that as part of the public contract. I don't think we'll consider adding an endpoint that is, sorry.
