### ISSUE TITLE
[Request] Option to change the route prefix

### ISSUE THREAD

**Issue by fletch3555** [laravel/horizon#98]
Is there a way to change the route prefix? I'm looking to make this a standalone app, so it would be nice to have it served from the root instead of `/horizon`.

**Comment by taylorotwell** [comment]
Route::redirect('/', '/horizon');

**Comment by fletch3555** [comment]
That's not the same... It's what I'm currently doing as a workaround.  I think it's perfectly reasonable to desire the base path of a package to be changed.

**Comment by activeRobert** [comment]
Not sure this is what you're looking for either, but I added this in my routes file. It works, but it looks like it still uses a "horizon" prefix. I am running this as a standalone app as well, so your request would be nice. 

`
Route::get('/', function () {
    return view('horizon::app');
});
`

**Comment by browner12** [comment]
all done guys, will be customizable in the next release. 😃

**Comment by justinwilson-apollidon** [comment]
@browner12 When will that be released? I'm also looking for a customizable solution, though I'm looking to customize the route and the views as well.

**Comment by browner12** [comment]
there's no specific timeline on releases. whenever they get around to it.

**Comment by emotality** [comment]
Was this feature added? 😊  @browner12

**Comment by browner12** [comment]
https://github.com/laravel/horizon/pull/200
