### ISSUE TITLE
Queues with 0 processes

### ISSUE THREAD

**Issue by eelco-4free** [laravel/horizon#981]
Version:
Laravel 8.0
Horizon 5.0
phpredis as client

Very often, we have queues with 0 processes. We see this in the dashboard, and we see this when I run `app(Laravel\Horizon\Repositories\RedisSupervisorRepository::class)->all();` on the server. This leads to queues with thousands of unprocessed jobs. Sometimes the queues will get some processes again after a few hours, sometimes our memory just completely fills up because the processes wont start at all. The processes are started correctly, but over time the processes disappear.

I have attached some screenshots. I have started a topic at Laracast before but without response. We don't know whats the issue and don't know how to solve this. In the screenshots, I have removed the queue names to prevent some sensitive data becoming public.

<img width="649" alt="Schermafbeelding 2021-03-10 om 12 44 18" src="https://user-images.githubusercontent.com/28431012/110625521-d350c080-819f-11eb-90b6-916b5f92074b.png">

<img width="651" alt="Schermafbeelding 2021-03-10 om 12 44 25 kopie" src="https://user-images.githubusercontent.com/28431012/110625516-d21f9380-819f-11eb-931b-9a8e3f4350da.png">

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by eelco-4free** [comment]
I posted to Laracasts 2 months ago:
https://laracasts.com/discuss/channels/laravel/horizon-starting-too-many-or-0-processes-per-queue

I believe this is a bug, because a queue should never have 0 processes?

**Comment by m-lotze** [comment]
We had the same problem for the last 2 days with one queue, where 60 jobs where pending but the queue had 0 processes. The problem seemed to be a job that queued emails on the same queue. After changing the queue for the job to a different one it seems to be resolved. 

but in general it would be nice to have some kind of monitoring for this circumstance. horizon should send a notification if there is a queue with a lot of pending jobs and 0 processes for a certain time.

**Comment by jcsoriano** [comment]
I am also experiencing this:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/5937317/171612910-3d351de6-d4ba-46bf-bfa6-faf6f4449055.png">

Were you able to find a solution for this @eelco-weblog ?
