### ISSUE TITLE
Process count is one behind.

### ISSUE THREAD

**Issue by sazo** [laravel/horizon#982]
- Horizon Version: v5.6.5
- Laravel Version: v8.22.1
- PHP Version: 7.4
- Redis Driver & Version: phpredis 
- Database Driver & Version: MySQL

### Description:
Amount of processes shown in horizon dashboard is 1 behind when running a long-running job. It seems like its only updating process count when a new job is entering processing state.  

### Steps To Reproduce:

1. Create a supervisor with maxProcesses=3
2. Create a long running job
3. Queue 3 long running jobs
4. Look at the horizon dashboard and see process count is only 2 (correct is 3)

```
// horizon.php
'environments' => [
        'local' => [
            'supervisor-1'      => [
                'maxProcesses' => 3,
                'balance'      => 'auto'
            ]
        ],
    ],
```

```
// Test Command
class RunBench extends Command
{

    protected $signature = 'run:bench {amount}';
    protected $description = 'Queue jobs';

    public function handle()
    {
        for ($i = 0; $i < $this->argument('amount'); $i++){
            RunJob::dispatch();
        }

        return 0;
    }
}
```

```
// Long Running Job
class RunJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle() : void
    {
        // Works for 20 sec
        for ($i = 0; $i < 20000; $i++){
            usleep(1000);
        }
    }
}
```

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command.

```bash
laravel new horizon-issue-982 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by sazo** [comment]
Hallo, 

Sorry for the delay, busy week - https://github.com/sazo/horizon-issue-982

To reproduce problem:

1. Run `chmod -R 777 storage/`
2. Run `docker-compose up -d app`
3. Run `docker-compose run --rm artisan test:job`
4. Go to `http://localhost/horizon`
5. See process count only is 2 even with 3 is processing
6. `docker top horizon-issue-982_worker_1` to see 3 running php process 

Config:

```
QUEUE_CONNECTION=redis
REDIS_HOST=redis
```

Hope it makes sense :)

**Comment by driesvints** [comment]
@sazo you don't seem to have used the command I displayed above. All commits are squashed. Please use the command I shared above to create the repo.

**Comment by shivampawstickee** [comment]
I'm running into this same issue. 4 processes showing on the dashboard, 5 processes actually running
