### ISSUE TITLE
2 Horizon instances on same Redis cluster targetting eachother's application

### ISSUE THREAD

**Issue by Propaganistas** [laravel/horizon#983]
- Horizon Version: 5.7.1
- Laravel Version: 8.32.1
- PHP Version: 7.4.16
- Redis Driver & Version: phpredis 5.3.3
- Database Driver & Version: MySQL 8

### Description:

I have been encountering a really weird issue that is going on for months now. I'll try to detail as much as context as possible.

I have:
* 2 Docker web environments
* 1 managed Redis instance (Azure)
* 1 managed MySQL instance (Azure)

Each Docker environment hosts a distinct Laravel application.
Each application connects with its own credentials to SQL and hence can only access its own database.
The credentials for the Redis server are shared.
Each application has Horizon up and running on Redis, overwatched by Supervisor.

Application 1 has the following entries in `.env` : `REDIS_DB=0` and `REDIS_CACHE_DB=1`
Application 2 has the following entries in `.env` : `REDIS_DB=2` and `REDIS_CACHE_DB=3`

Application 1 has multiple Horizon queues: `transactional`, `batch`, `default`
Application 2 has just one Horizon queue: `default`

Once in a while the logs of *Application 2* are populated with the following:

```json
"exception": {
    "class": "ErrorException",
    "message": "Trying to access array offset on value of type null",
    "code": 0,
    "file": "/app/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:156",
}
```

Investigation reveals that a Horizon worker of **Application 2** is trying to load configuration of the `transactional` or `batch` queues defined in **Application 1** (!), even though those queues aren't defined anywhere in Application 2.

Does the `REDIS_DB` value somewhere get lost and hence Application 2 connects to the default value (being `0`)?

I've been checking every single configuration detail, every server configuration, but to no avail. I'm out of clues.

**Comment by graemlourens** [comment]
does using different HORIZON_PREFIX values solve the issue? As different redis db's are deprecated in any case, i'd refrain from using it if you don't absolutely have to (either use _prefix or have different redis instances for different applications if possible)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Propaganistas** [comment]
> does using different HORIZON_PREFIX values solve the issue? As different redis db's are deprecated in any case, i'd refrain from using it if you don't absolutely have to (either use _prefix or have different redis instances for different applications if possible)
> 
> If possible paste your configuration of redis & horizon here so we can have a look

Thanks for your reply. I wasn't aware that multiple Redis DBs is a deprecated feature. I've changed the HORIZON_PREFIX as suggested. I'll give it a few days now to see if that works.

**Comment by graemlourens** [comment]
@Propaganistas i have to correct my statement: It is not officially deprecated, but highly discouraged by the authors of redis themselves (https://groups.google.com/d/topic/redis-db/vS5wX8X4Cjg/discussion) and they have been bouncing back and forth between officially deprecating it or not. It is however official that this is not best practise. The overhead of having multiple redis instances vs one with multiple db is marginal.

Hope it works!

**Comment by mfn** [comment]
Just make sure you don't mix your redis cache with others (e.g. horizon, etc.) in case you use it. Otherwise it will flush your horizon or whatever data you have there. That is the one reason why databases are really useful, and hardly anyone runs multiple version just for this, though it would be smarter.

Just sayin' :)

**Comment by driesvints** [comment]
@graemlourens thanks for helping out here 👍

**Comment by Propaganistas** [comment]
It has been 10 days now since I introduced an explicit HORIZON_PREFIX in each application. Good news: the error hasn't been showing up anymore.

Let's hope it remains like this!

Thanks all for your help 👍
