### ISSUE TITLE
v5.7.1 clean install on laravel8, dashboard doesn't display -- only huge icons

### ISSUE THREAD

**Issue by huna02** [laravel/horizon#985]
- Horizon Version: 5.7.1
- Laravel Version: 8.32.1
- Jetstream Version: 2.2.3 (Livewire install)
- PHP Version: 7.4.16
- Redis Driver & Version: 5.3.3
- Database Driver & Version: redis 6.2.0

### Description:

after install + setup, on nav to the exposed uri, `/horizon`, I don't see the dashboard.

I only see several huge icons:

https://imgur.com/a/mVkk9J4

### Steps To Reproduce:

install laravel8
install jetstream
install horizon

enable/verify redis use for default/cache/queue/session

nav to the exposed uri, `/horizon`

**Comment by mfn** [comment]
One _possible_ issue: I've seen this when running behind a revere proxy and Horizon cannot correctly determine its own URL.

I think https://medium.com/weekly-webtips/laravel-and-cors-behind-a-reverse-proxy-b737566bdd96 details quite nicely: use Fideloper trusted proxies and set the config `proxies` appropriately.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by huna02** [comment]
> Can you first please try one of the support channels below? 

you mean like

https://discord.com/channels/297040613688475649/491412519123157002/819944186719633458

?
