### ISSUE TITLE
Delayed jobs issue when minProcesses are 0

### ISSUE THREAD

**Issue by code2prog** [laravel/horizon#987]
- Horizon Version: 5.7.1
- Laravel Version: 8.32.1
- PHP Version: 7.4.16
- Redis Driver & Version: predis/predis 1.1.6
- Database Driver & Version:

### Description:
When the queue has minProcesses set to 0 and a new delayed task is added to it, the task is never executed. The number of workers is not increased.

### Steps To Reproduce:
Create worker with minProcesses set to 0. Add to it new delayed job.

**Comment by code2prog** [comment]
```
'supervisor-1' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'memory' => 256,
            'timeout' => 60,
            'minProcesses' => 0,
            'maxProcesses' => 8,
            'tries' => 1,
            'nice' => 0,
        ],
```
Once a delayed task is added to the queue it is never executed. It is always stuck in Pending.
Changing maxProcesses to 1 makes everything work correctly.
The problem only occurs with delayed jobs

**Comment by themsaid** [comment]
Why are you setting minProcesses to 0? Now you don't have any workers to migrate the delayed jobs and process them. Min should be 1

**Comment by code2prog** [comment]
> Why are you setting minProcesses to 0? Now you don't have any workers to migrate the delayed jobs and process them. Min should be 1

I think it is worth adding this information to the documentation :)

**Comment by driesvints** [comment]
Feel free to send a PR 👍
