### ISSUE TITLE
403 Response on any route in production

### ISSUE THREAD

**Issue by myckhel** [laravel/horizon#993]
- Horizon Version: 5.7
- Laravel Version: ^8.18
- PHP Version: ^8
- Redis Driver & Version: predis/phpredis ^1.1

### Description:
I have a project in production with the domain pointed to the laravel root directory instead of the project/public directory.
this domain root could not be changed because the url is already hardcoded in mobile project as `domain.com/public/api`.
recently i have decided to use horizon for the queue management.
after testing on development and the test server, all worked fine until i deployed on the production server.
after the deployment the project started returning 403 on any route
but when i switched the environment from `production` to `local` all routes worked fine again including horizon routes.

now my production project is in `local` environment because i am afraid to switch to `production` environment based on the `403` errors on all routes.

i tried to test on the test server which the domain is properly pointing to the `laravel/public` directory using `production` environment but every thing worked fine.

i am suspecting it has something to do with the domain root.

Please what could have gone wrong?
Please help with this bug.

### Steps To Reproduce:
- create new laravel project
- cp server.php index.php
- create domain pointing to project root
- setup horizon
- set env to environment to `production`
- visit any routes of the project

**Comment by driesvints** [comment]
Unfortunately we don't support running Laravel in a sub directory. Please see: https://laravel.com/docs/8.x#directory-configuration

**Comment by myckhel** [comment]
ZERO JOY 😔 .
no sign of sympathy.
