### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by MickaelTH** [laravel/horizon#997]
- Horizon Version: 5.*
- Laravel Version: ^8.0
- PHP Version: 7.4
- Redis Driver & Version: predis/phpredis ^1.1
- Database Driver & Version: MySQL 8

### Description:

Got this error message randomly (not very helpful I know but that's really what is happening) on my logs:

`Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /home/forge/xxx/releases/20210322152436/vendor/laravel/horizon/src/JobPayload.php:48)`

I deduct this is a connection issue between the server and the Redis (separate servers in different datacenter), but when I try to connect with telnet from the server with horizon daemon to Redis I have no connection issue.

Hoping to see if someone already have this kind of issue.

### Steps To Reproduce:

I tried to reproduce this without success, it is appearing randomly every 2 days or week nothing was done on the instance, same code no change.

The only thing I can think of is that horizon daemon is in different datacenter than the Redis server, and could be a timeout issue - but again no problem at all when using telnel.

Here is a screenshot, it could help to debug:

![Screenshot 2021-03-24 102205](https://user-images.githubusercontent.com/26375917/112250085-6b17d980-8c8b-11eb-9633-25e55ee68949.jpg)

**Comment by graemlourens** [comment]
Hi @MickaelTH  please look at https://github.com/laravel/horizon/issues/924 It has already been discussed there heavily and its the same issue you're having if i am not mistaken.

**Comment by driesvints** [comment]
please see the other issue
